### ISSUE TITLE
Openshift et Heroku

### ISSUE THREAD

**Issue by jeanfrancis** [GladysAssistant/Gladys#1]
Voudrais suggerer des button Openshift et Heroku pour permettre une installation

**Comment by GladysAssistant** [comment]
Je ne comprends pas ce que vous suggérez, pouvez vous détailler s'il vous plaît ? 

Merci

**Comment by jeanfrancis** [comment]
une installation package pour Heroku ( https://devcenter.heroku.com/articles/heroku-button ) et Openshift ( exemple http://voltdb.com/blog/voltdb-%E2%80%93-creating-openshift-cartridge-%E2%80%93-part-1 )

**Comment by Pierre-Gilles** [comment]
Okay I will see if I can do something, but that's very easy to install Gladys, I'm not sure that's necessary.

And if you want more home automation interaction that's probably better to install it on a Raspberry Pi.

**Comment by jeanfrancis** [comment]
Yes was more thinking about those who want to test

**Comment by Pierre-Gilles** [comment]
I'll see in the future if I will implement it.
