### ISSUE TITLE
Node version '0.12.4' -> Bug dans le build.

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#10]
Salut. Je me permet de faire le bugreport en français puisque vous parlez a priori français.
Si on utilise une version de node // npm à jour, il n'est pas possible de build lame de qui Gladys dépend. La nouvelle version de v8 n'est pas compatible avec les instructions demandées par lame.

npm version:

```
{ npm: '2.11.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.4',
  openssl: '1.0.2a',
  uv: '1.5.0',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

Une parte des erreurs sortie lors du npm install:

```
/home/giskard/.node-gyp/0.12.4/deps/v8/include/v8.h:2114:8: note:   candidate expects 2 arguments, 3 provided
../src/node_lame.cc:394:58: erreur: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Integer>, v8::PropertyAttribute)’
       static_cast<PropertyAttribute>(ReadOnly|DontDelete))
```

Ça serait bien de le mettre dans les contraintes de versions du README.

Merci.

**Comment by Pierre-Gilles** [comment]
Tout à fait effectivement, la version préconisée est la 0.10.x ! Je vais l'ajouter au README.

**Comment by Pierre-Gilles** [comment]
C'est bon, README updated.
