### ISSUE TITLE
[philips-hue] Newly bridge paired lamp cannot be used in Gladys

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1006]
This is a first analyse.

On existing hue / Gladys installation, if I add new lamp in hue bridge and in Gladys, I can't use them before restart.

https://community.gladysassistant.com/t/probleme-avec-hue-et-lumiere-bloom

**Comment by Pierre-Gilles** [comment]
@VonOx So the fix is upgrading the philips hue node library?

**Comment by VonOx** [comment]
Nope, just restarting container

**Comment by Pierre-Gilles** [comment]
I don't understand, what was the bug then? Restarting a container is not a solution ^^

It should work all the time, no restart needed

**Comment by VonOx** [comment]
I agree, that's why I opened issue

**Comment by VonOx** [comment]
Opened an issue on lib repo

https://github.com/peter-murray/node-hue-api/issues/197

**Comment by VonOx** [comment]
https://github.com/peter-murray/node-hue-api/blob/4.x/lib/api/Api.js#L154

@Pierre-Gilles in that case we can call resynch function.

[As lib maintainer says to me](https://github.com/peter-murray/node-hue-api/issues/197#issuecomment-870591129), it's an heavy call so what's the plan here ?

* In case of error we resync
or
* On demand via UI button

**Comment by Pierre-Gilles** [comment]
If the error easy to identify ? If yes, on error why not, but the problem is that we really don't want to trigger this multiple time in a row as it's an heavy call! 

Or maybe, when adding a new lamp, could we know if the problem is here?

**Comment by VonOx** [comment]
Yep error is pretty clear in this issue

ApiError: Light with id:12 was not found on this bridge

But i did'nt know how to catch them.

Error is triggered when contrlling the device not when adding them to Gladys

**Comment by Pierre-Gilles** [comment]
> ApiError: Light with id:12 was not found on this bridge

Yes, but this error could also be "normal", for example if the user added a lamp in Gladys, then remove the lamp from Philips Hue. In that case, we will be retrying many time and it won't solve the issue. 

Maybe the best would be to do a combo:

- Message in the UI if the error occured recently ? We can save a flag in the JS code of the Philips Hue integration
- Button in the UI (always displayed) to re-sync the bridge, with a confirmation to warn the user that this is a heavy call

What do you think of that ?

**Comment by VonOx** [comment]
Not stale

**Comment by Pierre-Gilles** [comment]
Not stale
