### ISSUE TITLE
Dev env Install issue

### ISSUE THREAD

**Issue by thebradleysanders** [GladysAssistant/Gladys#1007]
First, are you sure that you found a Gladys bug? Yes

**Describe the bug**
When installing Dev environment the error:
'Cannot find module bottleneck/es5'

**To Reproduce**

1. cd Gladys/server
2. sudo npm install
3. npm run db-migrate:dev
4. sudo npm start

**Expected behavior**
NPM install command to install dependency (bottleneck)

**Your Gladys installation (please complete the following information):**

- Manual installation: [MacOS/Windows/Linux?] Linux

**Desktop (please complete the following information):**

- OS: lubuntu
- Version 18.04

**Additional context**
When installing Dev environment the error:
'Cannot find module bottleneck/es5'

The fix was to run the command 'sudo npm i bottleneck'

**Comment by VonOx** [comment]
Why using sudo to run Gladys and install deps ?

**Comment by thebradleysanders** [comment]
Most likely a bad habit, I will try again without sudo, thank  you.

**Comment by cicoub13** [comment]
And check your node/npm version 😉 (expected node 12 and npm 6)

**Comment by Pierre-Gilles** [comment]
If you need help to setup Gladys, please use the forum => https://community.gladysassistant.com/

We use GitHub for issue tracking, and I don't think it's a Gladys bug here :)
