### ISSUE TITLE
[MQTT] User must know if connected or not

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1016]
Currently, even if mqtt server is configured, we don't know if Gladys is connected ( actually we need to check logs)

**Comment by atrovato** [comment]
Still pending.

**Comment by atrovato** [comment]
What do you think about?

![image](https://user-images.githubusercontent.com/1839717/140823834-af87fd5f-eeb7-4b42-8034-6973c3d466d3.png)

![image](https://user-images.githubusercontent.com/1839717/140823921-47a0badd-1321-4960-b3e8-842126896b12.png)

**Comment by VonOx** [comment]
Yep will do the Job for now.

For future ( when switch to lucide icon will be done ) I think link link-off picto is better to represent connection status
![image](https://user-images.githubusercontent.com/1528694/140980286-70c2e80d-fea7-4170-97e6-e63c0ef9956b.png)

**Comment by Pierre-Gilles** [comment]
@atrovato :  Nice! Maybe you could add a little text Like "Connected" / "Disconnected" so it's really self-explanatory?

**Comment by atrovato** [comment]
There is already a "tooltip" (HTML `title` attr).
I think this "little text" will overload the screen.

In this case, I though about something like (draft):
![image](https://user-images.githubusercontent.com/1839717/141255570-4d62128e-342e-40da-9023-a22141661df7.png)

**Comment by Pierre-Gilles** [comment]
The position is a bit weird, it looks like it's in the menu?

**Comment by atrovato** [comment]
Yes it is in the menu, I agree, it is a bit weird.
Keep thinking about it, I will try some other options.

**Comment by Pierre-Gilles** [comment]
Maybe it could just be displayed in the "setup" screen as an "green" alert?

**Comment by VonOx** [comment]
Something like this ?

![image](https://user-images.githubusercontent.com/1528694/141368087-a08cc8a3-f2a6-40e8-afac-68f40f5c824d.png)

**Comment by Pierre-Gilles** [comment]
At this place yes, but with a normal "alert" :) (The big "Connected" has a weird green)

**Comment by atrovato** [comment]
If this is good for you (go to setup menu), I'll do this (more simple than my first proposal).

**Comment by Pierre-Gilles** [comment]
Yes good for me! Just a simple green alert with a normal text message is fine! (and a warning if not connected)

**Comment by atrovato** [comment]
![image](https://user-images.githubusercontent.com/1839717/141497484-3c5aad02-4056-4f06-ae05-64aaa3494403.png)

Done in PR.
