### ISSUE TITLE
[TAMOSTA] Error 500 MQTT Discover

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1017]
@atrovato I've a tamosta device up and running publishing on MQTT container configured in MQTT Service.

When I try to discover Tamosta device in MQTT 
![image](https://user-images.githubusercontent.com/1528694/102642800-7fb17680-415e-11eb-8fe4-08fd27c69c89.png)

Gladys UI retrun generic error
`Error discovering Tasmota devices.`

Nothing in server logs :/

**Comment by atrovato** [comment]
Ok, you are on v4.0.3 ? I will take a look ASAP.

**Comment by VonOx** [comment]
Yep latest release , just a question, is this service compatible with tamosta sensors?

**Comment by atrovato** [comment]
Yes it should. But I develop it based on Tasmota v8 documentation, now it is v9, I may miss some new sensors.
For more, only Gladys compatible sensors are done.
But you can make any request to update service if yours is missing.

**Comment by VonOx** [comment]
I will check

FYI, http discover sayed that my device is not managed.
( SR04P ultrasonic sensor)

Is error 500 normal in that case?

**Comment by atrovato** [comment]
That's weird, I don't have to error... maybe due to Tasmota device and ultrasonic sensor...
Sure you don't have any logs on back side?

**Comment by VonOx** [comment]
Yes for sure, my first check is to verify logs

**Comment by VonOx** [comment]
Service not started ( Explain error 500 )

**Comment by Pierre-Gilles** [comment]
@atrovato I had some serious issue too with the task we wrote to avoid the service from starting (when we had the Bluetooth bug), now I agree with you maybe we should remove this...

**Comment by Pierre-Gilles** [comment]
I was using MQTT and nothing was working, at the end I realized the service was not started because of the task to avoid crash at startup. I think this thing of service "started", "stopped" is not working properly + not explicit enough in the UI

**Comment by atrovato** [comment]
I created a new issue https://github.com/GladysAssistant/Gladys/issues/1021

**Comment by Pierre-Gilles** [comment]
Thanks! +1
