### ISSUE TITLE
Typing command results in 500 error

### ISSUE THREAD

**Issue by danships** [GladysAssistant/Gladys#102]
I use Gladys 3.2.0 in English. When I type a command, 'hello' for example, a 500 error is returned. The logs show the following:

```
0|gladys   | Brain : Classified alarm;set-alarm
0|gladys   | Sending 500 ("Server Error") response:
0|gladys   |  Error: alarm.command is not a function
0|gladys   |     at /srv/http/webapps/gladys/node_modules/gladys/api/core/brain/brain.classify.js:43:39
```

Full error log: http://pastebin.com/gw8jgGNY

**Comment by Pierre-Gilles** [comment]
Hi ! 

Sorry for that, all command are not working yet.. This v3 of Gladys is a brand new version and everything is not fully implemented :) 

I'll answer a more complete answer on your other issue
