### ISSUE TITLE
[Philips-HUE] Device state not updated when swithching ON/OFF outside Gladys

### ISSUE THREAD

**Issue by PhilippeMA** [GladysAssistant/Gladys#1030]
First, are you sure that you found a Gladys bug? i think, yes. Before switching from beta to lastest stable version of Gladys, this feature worked.

**Describe the bug**
When i switch on or off from android's philips hue app, status update is not applied on Gladys.

**Your Gladys installation (please complete the following information):** 
Manual installation on Raspberry PI (https://gladysassistant.com/en/docs/installation/docker)

**Desktop (please complete the following information):**
- OS: Raspbian
- Browser : firefox

**Comment by VonOx** [comment]
Hi @PhilippeMA , I have tested right now and poll is working. 

Poll frequency is every minutes.

**Comment by Pierre-Gilles** [comment]
I close this, if you feel this is a real bug @PhilippeMA feel free to open it again :)
