### ISSUE TITLE
[Docs] Xiaomi home dev mode

### ISSUE THREAD

**Issue by vdeville** [GladysAssistant/Gladys#1035]
Hello,

Today i try to configure mi home bridge using the tutorial https://gladysassistant.com/fr/docs/integrations/xiaomi/ but the app changed and not find button to enable dev mode. Do you have idea to update the docs ?

Thanks

**Comment by VonOx** [comment]
Hi @MyTheValentinus 

I saw on comments in french article that you need to click in bottom several time on white zone ( no text ) , can you test that  ( I'dont have bridge to test )

![image](https://user-images.githubusercontent.com/1528694/104136851-0b52a780-5399-11eb-8dfd-79a848dcd81c.png)

**Comment by vdeville** [comment]
Hello,
Ok you need the GW, i had not understand this;

Thanks
