### ISSUE TITLE
[CI] Discussion about Docker and CI

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1037]
I open this issue to talk about CI 
Goal is to optimize/improve the way we build docker images.

I've already tested a lot before open this issue.

Today a full build take 1H 
![image](https://user-images.githubusercontent.com/1528694/104133780-06d0c380-5386-11eb-9998-8e83e5cbceeb.png)

Why is this so long ?
* Repeated build of the same dependencies ( OZW )
* Installation of the same npm packages again and again
* Our dockerfile is not cache efficient
--------------------------------

## Layers caching

First problem I encountered is circleci. For using layers caching we must pay for it ( I don't really understand why to be honest ).
Fir that reason, all tests and implementation will be done on Github Workflows.

### Open Zwave

To avoid building openzwave from source there is some simple solution => Multi Stage build

We take compiled binary from an already builded openzwave image. We are lucky because openzwave build their own and we can get real version tag ( not commit like today )

So OZW can now be added in your image like this:

```
# OpenZwave version 1.6.1520 
FROM chrisns/openzwave:alpine-1.6.1520 as ozw

# Just copy conf and binaries
COPY --from=ozw /usr/local/include/openzwave /usr/local/include/openzwave
COPY --from=ozw /openzwave/libopenzwave.so* /lib/
COPY --from=ozw /openzwave/config /usr/local/etc/openzwave
```
And voilà , OZW in our images without building it ( Several minutes saved here 😃 )

### node_modules

Also named by me "the tricky part" ( a lot of fail 😅 )

Even in active project like Gladys, npm deps doesn't change so much, why node_modules is not cached by docker when building ?

Simple answer, because we run npm install on the whole base code ! Cache is invalidated on each build.

Simple solution is to copy only package.json and lock file and run npm install on it, that way cache will work if no modification is commited , cache will be used by docker

After implementation, I'm able to build docker images in only 5 minutes ( for all platforms ) with change in codebase ( server and/or front )

![image](https://user-images.githubusercontent.com/1528694/104136102-6afa8400-5394-11eb-8b9f-858f184085c9.png)

----------------------------------------

There is some work to do but I need feedback from @GladysAssistant/core to know if I continue on this way or not.

PS: DockerFile for testing => https://github.com/VonOx/GLADYS_CI/blob/master/docker/Dockerfile.buildx
~~STEP 2 is not easy to maintain I know that 😉 .~~

**Comment by Pierre-Gilles** [comment]
Great topic, and great investigation! 👏 

I'm all in for both topics! It'll definitely makes build faster 😃

**Comment by cicoub13** [comment]
Great news 💪 
About Open Zwave and layers, I think you have the good approach.

node_modules seems tricky yes
Some interesting article about it : https://www.freecodecamp.org/news/speed-up-node-re-builds-leveraging-docker-multi-stage-builds-and-save-money-65189a4ab115/

**Comment by VonOx** [comment]
Yes this is tricky because in Gladys each service have their own package.

But I found a solution 😃 

Full build with test and no cache take 1H15
Cached build + test take 17 minutes

![image](https://user-images.githubusercontent.com/1528694/104243853-8aabae00-5461-11eb-80cc-58218f09661e.png)

Docker stage ( only building image ) 2 minutes, I can't do better

![image](https://user-images.githubusercontent.com/1528694/104243958-bb8be300-5461-11eb-8897-2341c7a620e2.png)

Now I need to test generated images.
PR incomming

**Comment by Pierre-Gilles** [comment]
It looks very very nice ! Quick question: could you explain a little bit more STEP 2 of the Docker multi-stage build, and how it's the same/different that what we were doing previously ?

This is STEP 2: 

```
# STEP 2
# Prepare server package*.json files
FROM node:12-alpine as json-files
COPY ./server /json-files/server
WORKDIR /json-files/server/
RUN find . -type f \! -name "package*.json" -exec rm -r {} \;
COPY ./server/cli /json-files/server/cli
COPY ./server/utils /json-files/server/utils
```

From what I read, you copy the whole `server` folder, and then you delete everything except package*.json. 

Then, you copy that later to run npm install and cache the results if the package.json did not change.

How do you merge the file tree with node_modules installed, and Gladys server later? Is the final result exactly the same as previously? 

Thanks for the amazing work here it looks amazing!

**Comment by VonOx** [comment]
> From what I read, you copy the whole `server` folder, and then you delete everything except package*.json.
> 
> Then, you copy that later to run npm install and cache the results if the package.json did not change.

You are right, I copy all and then delete all but package*.json


> How do you merge the file tree with node_modules installed, and Gladys server later? Is the final result exactly the same as previously?

This is the last part of DockerFile => https://github.com/GladysAssistant/Gladys/blob/a08ab0ec8cc09017fd8be936e2d6be5764911fa6/docker/Dockerfile.buildx#L48

Here I copy all files, this is normally the only layer not cached ( because somebody commit modifications )
That way, build is fast because this is the last step/layer

**Comment by Pierre-Gilles** [comment]
Correct me if I'm wrong, but docker layer caching works on each command, so why does the caching works here if you COPY then delete all files on 2 separate commands ?

**Comment by VonOx** [comment]
You are right again, but because we make theses commands ( copy & delete ) in separate stage ( multistage build ) we are caching the result of the stage.

2 or more command in separate stage has the same result because the only thing we need is the whole structure with only package*.json files. That's why we are fast.

**Comment by Pierre-Gilles** [comment]
Got it, nice!
