### ISSUE TITLE
Scene : "Continuer seulement si" avec un capteur de présence

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1038]
**Describe the bug**
J'ai créé une (ma première !) scene dans laquelle je voulais recevoir une notification en cas de mouvement dans la pièce.
Pour limiter le nombre de message envoyé, j'ai voulu mettre en place : 
* "Continuer seulement si"
* La dernière valeur = mouvement non détecté

Mais les seules valeurs qui peuvent être utilisées sont numérique et ne semble pas correspondre au joli ON/OFF du début.

![image](https://user-images.githubusercontent.com/14235706/104211920-8f09a400-542c-11eb-8d9f-927c8e76c989.png)

Dans la scene, les valeurs proposées ne permettent pas de reproduire le ON/OFF : 
![image](https://user-images.githubusercontent.com/14235706/104212024-ab0d4580-542c-11eb-8b68-f5f93d150f20.png)

**To Reproduce**

1. Créer une nouvelle scene
3. Choisir un détecteur de mouvement
4. Condition : si du mouvement est détecté
5. Action : Envoyer un message
6. Sauf si : derniere valeur est différente de 1

**Expected behavior**
Lorsqu'un mouvement est détecté, un message est envoyé.
Tant que le mouvement n'est pas arrêté, plus aucun message n'est envoyé.

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation: Raspberry Pi 4 4Go + Image Officielle

**Additional context**
Image docker utilisée : zigbee2mqtt (de @r6n0).

**Comment by Pierre-Gilles** [comment]
Effectivement, il n'y a pas vraiment d'intelligence dans la box "continuer seulement si" qui affiche un champs libre quel que soit la variable injecté, c'est vrai qu'on pourrait améliorer ça!

Pour ton scénario en revanche, je ne comprend pas ce que tu veux faire. On en parle sur le forum? (GitHub on utilise ça pour le dev uniquement, pas le support)

**Comment by LM1LC3N7** [comment]
En fait le bug que je soulève c'est qu'on ne peut pas utiliser les capteurs de type on / off dans cette partie. 
Seulement ceux qui renvoient des chiffres (lumière, température, etc)

**Comment by Pierre-Gilles** [comment]
Tout valeur d'état d'un device dans Gladys est un chiffre, la box "changement d'état de l'appareil" a juste été plus travaillé, et affiche un picker ON/OFF quand il faut, mais derrière ça reste des chiffres.

On = 1 et Off = 0 :) 

Mais effectivement je suis d'accord c'est pas facile à comprendre et ça mériterait qu'on améliore ça. 

J'ai créé une issue GitHub: 

https://github.com/GladysAssistant/Gladys/issues/1043

**Comment by LM1LC3N7** [comment]
Merci pour la confirmation. C'est ce que je suspectais mais je ne pensais pas que c'était fonctionnel justement "a cause" du ON/OFF plus travaillé.
Parfait donc, ce n'est pas un bug 😄
