### ISSUE TITLE
Display Multilevel device feature controller for more than just dimmer values

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1042]
We should evaluate all device feature that need a multilevel range controller and add it here: 

https://github.com/GladysAssistant/Gladys/blob/master/front/src/components/boxs/device-in-room/DeviceRow.jsx#L42

**Comment by atrovato** [comment]
@Pierre-Gilles do you remember for what kind of device features?
We already add some more.

**Comment by Pierre-Gilles** [comment]
I don't remember honestly, let's close this and if someone ask let's open new issues 👍
