### ISSUE TITLE
Bog on create House in FR

### ISSUE THREAD

**Issue by Terdious** [GladysAssistant/Gladys#1055]
First, are you sure that you found a Gladys bug?

If you are not sure, you can come discuss with us on [Gladys Community](http://community.gladysassistant.com/) 🙂

**Describe the bug**
When creating a house with a name that is too long, the default returned by the UI is not the correct one :
![image](https://user-images.githubusercontent.com/35010958/106350937-e89d1a00-62d8-11eb-8757-1f52a294bcb9.png)

This should read: "Erreur de validation : Le nom de votre maison est trop long"
The EN version is good: "House name should be between 1 and 40 characters" :
![image](https://user-images.githubusercontent.com/35010958/106350995-652ff880-62d9-11eb-8ae9-cb7770bc5e36.png)

**Comment by VonOx** [comment]
Good catch @Terdious 😉

**Comment by Terdious** [comment]
Ok, I started to watch. There are actually 2 errors. In the file /front/src/actions/house.js - Line 230 we have:
```
} else if (status === 422 && url.includes ('/ room /')) {
  store.setState ({
  houseUpdateStatus: {
      [house.id]: RequestStatus.RoomValidationError
  }
});
```
while this error normally deals with the house error. So we should have:
`} else if (status === 422 && url.includes ('/ house')) {`
and line 233:
`[house.id]: RequestStatus.HouseValidationError`
So this error is not handled in the front / src / components / house / EditHouse.jsx file and does not exist in fr.json and en.json.
