### ISSUE TITLE
Have a larger view of the camera when you click on the box.

### ISSUE THREAD

**Issue by tlse-vins** [GladysAssistant/Gladys#1059]
102 / 5000
Have a larger view of the camera when you click on the box in a pop-up window or other.

**Comment by Pierre-Gilles** [comment]
We use github for bugtracking only, as this is a feature request (that is present on the forum as well), i'm closing this: 

https://community.gladysassistant.com/t/afficher-la-camera-en-pleine-ecran-depuis-le-dashboard/6610
