### ISSUE TITLE
[MQTT] Mosquitto 2.0 and Configuration

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1071]
Mosquitto 2.0 need a new option to work ( https://github.com/eclipse/mosquitto/issues/2040 )

`listener 1883`

Related thread in forum => https://community.gladysassistant.com/t/tutoriel-flasher-et-configurer-un-sonoff/4526/57?u=vonox

----------------------------------------------

For newly created configuration no problem ( if we update the shell script ), but for existing configuration there is not check.
All current Gladys running instance with configured MQTT integration can be impacted.

@atrovato FYI

**Comment by atrovato** [comment]
Nice to know. I will try. For more, my MQTT network suddendly dies... not relation with Gladys, I use separated broker for now.

**Comment by VonOx** [comment]
> Nice to know. I will try. For more, my MQTT network suddendly dies... not relation with Gladys, I use separated broker for now.

Me too, may be related to listener option

**Comment by atrovato** [comment]
Ok, `listener 1883` fixes the issue.
In both cases we'll have to update Gladys shell script.

We may add a param to service to check if new option is already set.
Something like `EMBEDDED_MQTT_PORT = 1883`,
at startup, we'll check for this, if Gladys use embedded MQTT and param is not set, we automaticcly update shell script (and set the param).

What do you think?

**Comment by Pierre-Gilles** [comment]
What about finding another MQTT Docker image that just supports environment variables instead of a config file?

Right now, the process seems "flaky", mostly because there are several source of truth (the mosquitto container + the file + Gladys DB) that can be easily out of sync between themselves. 

On top of that, as the DB is no longer the only source of truth, backing up the DB do not backup everything.

**Comment by VonOx** [comment]
Env variable can change too , I think that doesn't solve the problem

Mosquitto problem come from major release 1.X to 2.X. ( Yes breaking change  😟  ) 
Our mistake was to use latest tag.

Right now we need to check at gladys startup conf file for missing options ( like @atrovato  said )
And ensure container use major tag ( [eclipse-mosquitto:2](https://hub.docker.com/layers/eclipse-mosquitto/library/eclipse-mosquitto/2/images/sha256-1ad48db5d7b9a509b60d96367d5a4af8295fab46dc114ce0adb3630aa70d3751?context=explore)

What about that => https://www.npmjs.com/package/aedes ?

**Comment by Pierre-Gilles** [comment]
>Env variable can change too , I think that doesn't solve the problem

It doesn't solve this problem, but improve the overall stability of all this :) 

Agree, for this problem, if we keep the same docker image, we need to update the file at startup with listener 1883. It could just be done in a migration !

**Comment by Pierre-Gilles** [comment]
For Aedes, I don't think it's a short term solution to fix this issue !

**Comment by VonOx** [comment]
> For Aedes, I don't think it's a short term solution to fix this issue !

Yes I agree , just a question. Another topic for another day 😅

**Comment by atrovato** [comment]
@VonOx 
> And ensure container use major tag ( eclipse-mosquitto:2

do you mean we force mosquitto version?

**Comment by VonOx** [comment]
@atrovato yes right, so mosquitto is updated ( bug fix ) and next major release ( v3 or something ) will not break gladys integration

**Comment by atrovato** [comment]
Ok, so I will have to force remove / re-creation of the mosquitto container (only for already configured containers) to force image version to 2 and not latest.

**Comment by atrovato** [comment]
@VonOx @Pierre-Gilles can we close this?

**Comment by snagulap** [comment]
Hello,
In my case it showing address not available
mosquitto version 2.0.18 starting
1705326773: Config loaded from /mosquitto/config/mosquitto.conf.
1705326773: Starting in local only mode. Connections will only be possible from clients running on this machine.
1705326773: Create a configuration file which defines a listener to allow remote access.
1705326773: For more details see https://mosquitto.org/documentation/authentication-methods/
1705326773: Opening ipv4 listen socket on port 1883.
1705326773: Opening ipv6 listen socket on port 1883.
1705326773: Error: Address not available
1705326773: mosquitto version 2.0.18 running

can someone explain how to remove that error?
