### ISSUE TITLE
Remove darksky service from list of running services

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1084]

**Comment by VonOx** [comment]
darksky is only referenced in demo, production image does'nt list darky in service. Are you sure about this issue ?

**Comment by Pierre-Gilles** [comment]
A Gladys Plus user told me that on slack... are you sure it's not the case anymore ?

**Comment by VonOx** [comment]
Have checked in my installation => no darksky service
Searched in the whole repo => only in demo ( and changelog btw)

**Comment by Pierre-Gilles** [comment]
> Have checked in my installation => no darksky service
Searched in the whole repo => only in demo ( and changelog btw)

Yeah but you're looking only at the "current state" of the code. This information is stored in DB, and therefore if no SQL migration was done, is probably still in DB for early users.  

I think this user probably installed Gladys during the beta, and installed all versions since. He probably still have the service in DB :) 

I'm checking with this user first to see in which version of Gladys he is.

**Comment by atrovato** [comment]
@Pierre-Gilles do you remember why you reopened it?

**Comment by Pierre-Gilles** [comment]
Because the issue is not fixed for existing users. But honestly, we can close this. 

It's absolutely not a priority and it doesn't change anything for most users.
