### ISSUE TITLE
Sort Houses and Rooms alphabetically in Room Selector

### ISSUE THREAD

**Issue by cicoub13** [GladysAssistant/Gladys#1087]
**Is your feature request related to a problem? Please describe.**
When a user has a lot of rooms, it could be difficult to select one.

**Describe the solution you'd like**
It would be easier to choose the good room if Houses and Rooms were sorted alphabetically

Target :

<img width="387" alt="Capture d’écran 2021-03-03 à 19 18 00" src="https://user-images.githubusercontent.com/1773153/109852691-5086ad80-7c55-11eb-8918-6e7d5f18cc1b.png">

**Comment by cicoub13** [comment]
There are 2 options :
- sort houses and rooms before put them in store
- update RoomSelector to sort before display

**Comment by Pierre-Gilles** [comment]
Good idea! Let's sort them before putting them in the store :)
