### ISSUE TITLE
Temperature is in F in the chat

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1088]
**Describe the bug**
Gladys display an "F" instead of a "C" in the chat when I ask for a temperature. 
Bug discovered from a Telegram chat but present in the web interface too. 

**To Reproduce**

1. Install Gladys and chose °C for temperature 
2. Ask to Gladys from a chat (web based or telegram) a room temperature 
3. See error 

**Expected behavior**
°C should be use if configured like this. 

**Screenshots**
![Screenshot_20210304-222956__01](https://user-images.githubusercontent.com/14235706/110033298-843b0380-7d39-11eb-8f84-3b23638d8a08.jpg)

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation: RPi 4

**Comment by Pierre-Gilles** [comment]
I think it was fixed in https://github.com/GladysAssistant/Gladys/commit/2c0c3c5d5f41e7620ead51c475dd0a941047f201.

I tried on my side, and it works. I'm closing this, feel free to re-open it if you still see the bug :)
