### ISSUE TITLE
Bluetooth service never deactivate

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#1093]
From forum : https://community.gladysassistant.com/t/probleme-de-recherche-bluetooth/6132/8?u=alextrovato

When deactivate service from configuration page, Bluetooth service is still running.

TODO: check if only this service is impacted, or all services.

**Comment by atrovato** [comment]
Looks like Bluetooth service never reset properties to default value on stop.

**Comment by Pierre-Gilles** [comment]
Should be fixed by https://github.com/GladysAssistant/Gladys/commit/0ae38b9b403adeecc3d4e48658647ceb25e978a4
