### ISSUE TITLE
Gladys as Bluetooth device

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#1096]
To be able to check user presence with Smartphones, use Gladys as a discoverable device.

So the phone will ping Gladys on connect, and Gladys will be able to detect mobile presence.

**Comment by atrovato** [comment]
https://community.gladysassistant.com/t/probleme-de-recherche-bluetooth/6132/5?u=alextrovato

**Comment by atrovato** [comment]
I tried to use https://github.com/abandonware/bleno to use smartphone to connect to Gladys and add presence capability, but I can't connect / keep connected using smartphone wihtout a specifc application on it.

**Comment by Pierre-Gilles** [comment]
I'm indeed closing this as we use Github only for bug-tracking now.

Feature requests are on the forum!
