### ISSUE TITLE
Suggest change terminologi in README.md from "home assistant" to more generic "virtual assistant"

### ISSUE THREAD

**Issue by Hedda** [GladysAssistant/Gladys#1099]
**Is your feature request related to a problem? Please describe.**

Please consider changing the wording/terminology in Gladys's [README.md](https://github.com/GladysAssistant/Gladys/blob/master/README.md) from "home assistant" to the commonly more generic term/words of "[virtual assistant](https://en.wikipedia.org/wiki/Virtual_assistant)". If sounds OK, please also consider changing this wording/terminology on the website and in docs.

Suggest changing Gladys current tag-line description use to the term/words "home assistant":

   * "_Gladys Assistant - A privacy-first, open-source **home** assistant_"

Into an other more commonly used term/words "virtual assistant" to describe the same thing:

   * "_Gladys Assistant - A privacy-first, open-source **virtual** assistant_"

The main reason for this small wording change suggestion is that "Home Assistant" is already used as a product name by the [Home Assistant](https://www.home-assistant.io/) project and this wording can be confusing to new users since Gladys is in the same field of home automation software. In addition, this is somewhat compounded as the [Home Assistant](https://www.home-assistant.io/) project also use the term/words "privacy-first" in their own tag-line:

* "_Home Assistant - Open source home automation that puts local control and **privacy first**._"

For reference, Wikipedia also already list "virtual assistant" https://en.wikipedia.org/wiki/Virtual_assistant as the generic term for this type of product, while it list "Home Assistant" as the specific product/software project: https://en.wikipedia.org/wiki/Home_Assistant

Yes this is only semantics but I think changing this terminology because "Home Assistant" is valid reason enough because it is specifically used by the now worlds most popular open-source home automatic software project. On the other hand "virtual assistant" is not the commonly accepted generic term for describing any virtual assistant, whether or not it features voice input or not. 

True that "Home Assistant" current project name should probably be considered as a poor choice because it is really too generic to be copyrighted, however, that would not stop them from trademarking that name if they wanted to, as copyright and registering a trademark are very different, (just look at "Microsoft" verses "Windows").

At least Home Assistant is so well known today that it has been posted about so much that it can easily prove its notability today:

https://letmegooglethat.com/?q=%22home+assistant%22

**Describe the solution you'd like**

Please consider changing all uses of "home assistant" into "virtual assistant". Maybe also change all docs and other references too?

**Describe alternatives you've considered**

An alternative is to leave it or pic a completely new tag-line description.

**Additional context**

This wording/terminology is currently used on Gladys website and more as well:

![image](https://user-images.githubusercontent.com/6320001/111122269-18913b80-856e-11eb-92cc-e4a5a1a3e0b6.png)

![image](https://user-images.githubusercontent.com/6320001/111120895-3f4e7280-856c-11eb-985c-257c86eee131.png)

**Comment by Pierre-Gilles** [comment]
I don't think we'll change that, Gladys is clearly a product dedicated to home control, it's definitely not a virtual assistant.

**Comment by Hedda** [comment]
> I don't think we'll change that, Gladys is clearly a product dedicated to home control, it's definitely not a virtual assistant.

So maybe change the tag-line to "home automation" or something similar? See -> https://en.wikipedia.org/wiki/Home_automation

Again, the objection is really only against using the wording "home assistant" -> https://en.wikipedia.org/wiki/Home_Assistant


Maybe change it to "smart home" or "smart house" or perhaps add "automation" to the phrase in between those words?

   * "_Gladys Assistant - A privacy-first, open-source **smart home assistant**_"

or 

   * "_Gladys Assistant - A privacy-first, open-source **smart house assistant**_"

or 

   * "_Gladys Assistant - A privacy-first, open-source **home automation assistant**_"

or

   * "_Gladys Assistant - A privacy-first, open-source **smart home automation assistant**_"

or 

   * "_Gladys Assistant - A privacy-first, open-source **smart house automation assistant**_"

Using the wording "home automation", "smart home", or "smart house" would make use of the right generic terminology, or?

**Comment by Hedda** [comment]
FYI, created new issue suggesting change to "smart home...", "smart house...", a"home automation..." or something similar  -> https://github.com/GladysAssistant/Gladys/issues/1100
