### ISSUE TITLE
Create house error when house name is in chinese

### ISSUE THREAD

**Issue by bulolo** [GladysAssistant/Gladys#1110]
![image](https://user-images.githubusercontent.com/10026498/112710091-930c7480-8ef9-11eb-9416-a30b28cee430.png)

![image](https://user-images.githubusercontent.com/10026498/112710099-a4ee1780-8ef9-11eb-8849-70ff0200b539.png)
![image](https://user-images.githubusercontent.com/10026498/112710137-e41c6880-8ef9-11eb-96f9-eae5e5f67a68.png)

i found that if i create a house from /api/v1/house success,and then create room error.
the i save house again,the house name has created. i can't create

somethings else,is there support chinese room name or house name?

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/112710324-2a25fc00-8efb-11eb-9841-c9dc23c1e08c.png)
error from create house and room

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/112710364-7113f180-8efb-11eb-8aef-a6766e07b7fa.png)
delete a house do not real delete my house

**Comment by Pierre-Gilles** [comment]
Hi! 

When you create any entity in Gladys 4, we calculate a "slug" for this entity, and we use this function: https://github.com/GladysAssistant/Gladys/blob/master/server/utils/slugify.js

Honestly this is the first time a chinese user use Gladys so i've never tested :) I think the slugify function we use doesn't work with chinese characters. 

Do you know what's the best practice to slugify chinese text?

**Comment by VonOx** [comment]
I think we have the same problem with Hebrew, Cyrillic and German.

Is there any lib to manage this?

**Comment by atrovato** [comment]
https://www.npmjs.com/package/combined-slugify

**Comment by Pierre-Gilles** [comment]
Last published 5 years ago unfortunately... not sure it's the kind of library we want to use

<img width="419" alt="Screenshot 2021-04-06 at 18 40 52" src="https://user-images.githubusercontent.com/7365207/113699123-c32cf200-9707-11eb-9a91-77e773070044.png">

But I'm sure there are others libraries doing the job :D

**Comment by VonOx** [comment]
There is no issue on github, if it stable and nothing to fix, there is nothing to publish! 🤔

**Comment by bulolo** [comment]
i think it time to support chinese house name 
https://github.com/GladysAssistant/Gladys/pull/1178

**Comment by atrovato** [comment]
Still open.

**Comment by VonOx** [comment]
@Pierre-Gilles limax lib can do the job ( it's maintained )
https://www.npmjs.com/package/limax

Latin - Cyrillic - Chinese - Japanese 👍🏻

**Comment by Pierre-Gilles** [comment]
Why not, but this is not a trivial change, we need to make sure the migration is properly unit tested with many different cases, examples:  

-  "My house" => "my-house"
- "Ma télévision" => "ma-television"
- "Lamp control, living room" => "lamp-control-living-room"
- Lampe control / Living room;" => "lamp-control-living-room"
- "Chinese symbols" => "pinyin equivalent"

More broadly, we need to see if this lib slugify the same way as before for latin sentences. 

Also, right now we use a custom function that is only a few lines long, weighting a few bytes.

Replacing the function by this lib will change the size of the front by this factor: 

<img width="1440" alt="Screenshot 2021-10-22 at 10 40 45" src="https://user-images.githubusercontent.com/7365207/138384720-ad2e1610-1c8b-4ece-b035-c7b5f2451a55.png">

This is not light, so we need to see if the slugify is really needed on the front, and if yes, if there are lighter options.

If not, why not using this lib, but we need to make sure we do the right choice on this, it's not a trivial change :)

**Comment by VonOx** [comment]
Yes I understand

Unfortunately limax is not working in browser... so another solution , a dictionary to extend slugify function to handle all no latin langage ( lib free )
like this => https://github.com/winglechen/node-pinyin/blob/master/pinyin.js#L9

**Comment by Pierre-Gilles** [comment]
Interesting! Why not honestly, but as I said previously I'm not sure this is the top priority...
