### ISSUE TITLE
When Telegram API key is invalid, Gladys keeps retrying infinitely at a very fast pace

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1113]

**Comment by Pierre-Gilles** [comment]
Bug is still present, let's keep this.

**Comment by Pierre-Gilles** [comment]
Still the case

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by atrovato** [comment]
I tried to reproduce it, but I can't, do you have more details?

**Comment by Pierre-Gilles** [comment]
Indeed, I can't reproduce it either. I saw it once on someone instance, but can't reproduce it.

I'm closing this
