### ISSUE TITLE
Color picker is not well displayed on iOS browser

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1115]
<img width="524" alt="Screenshot 2021-04-01 at 15 40 32" src="https://user-images.githubusercontent.com/7365207/113260285-a86e0e00-9300-11eb-9dc3-aac127fba760.png">

**Comment by atrovato** [comment]
Nice, I'll try to fix it using cypress!

**Comment by atrovato** [comment]
But,
> Unsupported Browsers
Many browsers such as Safari and Internet Explorer are not currently supported. Support for more browsers is on our roadmap. You can read an explanation about our future cross browser roadmap here.

https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers

**Comment by atrovato** [comment]
I think it's a question of css `z-index` property here.

**Comment by Pierre-Gilles** [comment]
> Nice, I'll try to fix it using cypress!

> But,

aha 😄

> I think it's a question of css z-index property here.

Yes probably just a question of z-index. Do you have an iOS device to test?

**Comment by atrovato** [comment]
No, so I'm not able to take this point.

**Comment by Pierre-Gilles** [comment]
Sooo I'm currently debugging this on my iPhone connected in USB to my mac to debug safari, and it's a real pain ^^

Z-index is set and is working fine (1060 on the iro color picker):

<img width="1002" alt="Screenshot 2021-04-23 at 13 16 40" src="https://user-images.githubusercontent.com/7365207/115822454-26709100-a437-11eb-80dc-d0e395137543.png">

It seems that when I remove "position: absolute" on the component, it works. But I can't find an option to remove this in the API of the component.

Any idea?

**Comment by Pierre-Gilles** [comment]
If you want to see the bug live, you can use browserstack for free to start a safari emulator in your browser: 

https://www.browserstack.com/guide/how-to-debug-on-iphone

**Comment by atrovato** [comment]
What if you add css class `position-relative` to ColorDeviceFeature.jsx file line 107?

**Comment by atrovato** [comment]
If you "unset" position to absolute value, color picker will be stacked and makes te scrollbar visible.
I'll make some tests.

**Comment by atrovato** [comment]
I can't reproduce it using browerstack "real device cloud".
Tested with iPhone from 12 to 8. Safari and chrome, works well.

What's your setup?

**Comment by Pierre-Gilles** [comment]
iPhone 12 on Safari, real device, but I'm using the touchscreen so it might change something? 

Or maybe browserstack is not using real devices 😄

I'll try the position-relative tomorrow

**Comment by Pierre-Gilles** [comment]
Bug is still present, but I'm completely unable to fix it :/ 

Maybe we should contact the owner of the library ?

**Comment by Pierre-Gilles** [comment]
Still the case

**Comment by Pierre-Gilles** [comment]
Not stale, and I'm not able to fix it.
