### ISSUE TITLE
zigbee2mqtt:5 zigbee2mqtt supported devices cannot add to gladys

### ISSUE THREAD

**Issue by bulolo** [GladysAssistant/Gladys#1118]
my devices TT001ZAV20 has support in zibgee2mqtt ,follow `https://www.zigbee2mqtt.io/devices/TT001ZAV20.html#tuya-tt001zav20`

but,i can't add in gladys, ,and it has recognized,in zigbee2mqtt from 8080 port web

![image](https://user-images.githubusercontent.com/10026498/113477878-b3b76a00-94b7-11eb-9fbd-d37a98436d20.png)
![image](https://user-images.githubusercontent.com/10026498/113477881-b914b480-94b7-11eb-8f36-c3364d2e6cfc.png)
![image](https://user-images.githubusercontent.com/10026498/113477930-2d4f5800-94b8-11eb-9ea0-e08848688508.png)

```
{
  "name": "0x000d6ffffe6eca47",
  "external_id": "zigbee2mqtt:0x000d6ffffe6eca47",
  "model": "TT001ZAV20",
  "features": [
    {
      "category": "battery",
      "type": "integer",
      "unit": "percent",
      "name": "Battery",
      "read_only": true,
      "has_feedback": false,
      "min": 0,
      "max": 100,
      "zigbeeField": "battery",
      "external_id": "zigbee2mqtt:0x000d6ffffe6eca47:battery:integer:battery",
      "selector": "zigbee2mqtt:0x000d6ffffe6eca47:battery:integer:battery"
    }
  ],
  "should_poll": false,
  "service_id": "cd5e56de-fd54-446d-a5a7-2539273349d9",
  "supported": false
}
```

also many of zigbee2mqtt supported device cannot 

`https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html`
```
{
  "name": "0x04cf8cdf3c7d5ce3",
  "external_id": "zigbee2mqtt:0x04cf8cdf3c7d5ce3",
  "model": "WXCJKG13LM",
  "features": [
    {
      "category": "battery",
      "type": "integer",
      "unit": "percent",
      "name": "Battery",
      "read_only": true,
      "has_feedback": false,
      "min": 0,
      "max": 100,
      "zigbeeField": "battery",
      "external_id": "zigbee2mqtt:0x04cf8cdf3c7d5ce3:battery:integer:battery",
      "selector": "zigbee2mqtt:0x04cf8cdf3c7d5ce3:battery:integer:battery"
    }
  ],
  "should_poll": false,
  "service_id": "cd5e56de-fd54-446d-a5a7-2539273349d9",
  "supported": false
}
```

some images: my 5 devices can find in zigbee2mqtt supported,but only one device can add to gladys 
![image](https://user-images.githubusercontent.com/10026498/113478893-4529da80-94be-11eb-8c3b-6e84b0b4cc38.png)

![image](https://user-images.githubusercontent.com/10026498/113478838-f5e3aa00-94bd-11eb-90d4-76ca1c7376cd.png)
![image](https://user-images.githubusercontent.com/10026498/113478865-157ad280-94be-11eb-8672-56822b7f52d2.png)
![image](https://user-images.githubusercontent.com/10026498/113478872-1ca1e080-94be-11eb-9c68-b60dcee5533f.png)

### `my five devices:`

[RH3040](https://www.zigbee2mqtt.io/devices/RH3040.html)    ☑️ only this one can add to gladys

[TT001ZAV20](https://www.zigbee2mqtt.io/devices/TT001ZAV20.html#tuya-tt001zav20)

[SNTZ007](https://www.zigbee2mqtt.io/devices/SNTZ007.html)

[WXCJKG13LM](https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html)

[SN10ZW](https://www.zigbee2mqtt.io/devices/SN10ZW.html)

![image](https://user-images.githubusercontent.com/10026498/113479452-c8006480-94c1-11eb-9d77-36d7051bd2e3.png)

**Comment by VonOx** [comment]
@Pierre-Gilles I reopen this one because only sensors have been added.

@cicoub13 will do a PR for the switch/button ( WXCJKG13LM ) that require more work.

**Comment by bulolo** [comment]
Yes，only WXCJKG13LM can not add in now ，thx 
If there is a new zigbee device that didn't support gladys,how can i support it my self。
go to zigbee2mqtt project or here？
![image](https://user-images.githubusercontent.com/10026498/114262256-929fcd80-9a11-11eb-8637-92e2f9cf5dd8.jpeg)
![image](https://user-images.githubusercontent.com/10026498/114262261-97648180-9a11-11eb-8a4d-43b2f00265ae.jpeg)

**Comment by VonOx** [comment]
@bulolo Gladys repository is the right place.

**Comment by bulolo** [comment]
today,i bought a new zigbee devices ZNLDP12LM and want to try,also support in zigbee2mqtt project.
i found none of other zigbee devices can join in now. only above the 4 devices.i donot why.

like 
https://www.zigbee2mqtt.io/devices/ZNLDP12LM.html. 


and there is no log to find the zigbee2mqtt has join in ,event no message that tell me it a unsuport device on zigbee2mqtt dashboard. it seem any of the zigbee devices now can not join in.

i try this two devices
ZNLDP12LM
WXCJKG13LM

no message tell me unsuport ,no logs on dockers that tell me join in message

**Comment by cicoub13** [comment]
Are you sure your network is in mode `permit_join` = true ?
You can access zigbee2mqtt interface on port 8080 of the Raspberry IP to see if devices are in the network or not. If they are, you lust have WARN logs in Gladys with some information.

**Comment by bulolo** [comment]
> Are you sure your network is in mode `permit_join` = true ?
> You can access zigbee2mqtt interface on port 8080 of the Raspberry IP to see if devices are in the network or not. If they are, you lust have WARN logs in Gladys with some information.

yes,i am sure. i use gladysassistant/gladys:dev this docker.and try to join this two devices
ZNLDP12LM
WXCJKG13LM
no other join message and join log
![image](https://user-images.githubusercontent.com/10026498/114274156-bf72d580-9a4f-11eb-8155-3ff9d226cd23.png)
![image](https://user-images.githubusercontent.com/10026498/114274164-c7327a00-9a4f-11eb-83d6-51f87aebe349.png)
 

none message about 
ZNLDP12LM
WXCJKG13LM 's join message on docker or on port of 8080

**Comment by cicoub13** [comment]
And you see them in tab Devices (under the same UI) ?

**Comment by bulolo** [comment]
> And you see them in tab Devices (under the same UI) ?

![image](https://user-images.githubusercontent.com/10026498/114274347-91da5c00-9a50-11eb-90ac-ce5896120c84.png)
![image](https://user-images.githubusercontent.com/10026498/114274363-9ef74b00-9a50-11eb-83e1-287403438035.png)

this four device is the one support by last merge.  (under the same UI same raspi same docker)  

ZNLDP12LM
WXCJKG13LM  
new devices can not see them in 8080 ande tab devices or tab discover or docker join message or log

**Comment by bulolo** [comment]
befor ,i can see a new device join in here
![image](https://user-images.githubusercontent.com/10026498/114274557-92272700-9a51-11eb-9e89-b6714c911ffc.png)

but now,a new device try to join,no message on here to tell and no log join in

**Comment by cicoub13** [comment]
OK. Devices must first need to be paired to the Zigbee Network (so visible in the 8080 interface) to be able to be added to Gladys. Maybe you can refer to the notice of your devices. And try to restart the `gladys-z2m-zigbee2mqtt` container

https://www.zigbee2mqtt.io/devices/ZNLDP12LM.html#pairing

https://gladysassistant.com/docs/integrations/zigbee2mqtt#add-devices

For your information, WXCJKG13LM is not managed yet by Gladys (complex device).

**Comment by bulolo** [comment]
> OK. Devices must first need to be paired to the Zigbee Network (so visible in the 8080 interface) to be able to be added to Gladys. Maybe you can refer to the notice of your devices. And try to restart the `gladys-z2m-zigbee2mqtt` container
> 
> https://www.zigbee2mqtt.io/devices/ZNLDP12LM.html#pairing
> 
> https://gladysassistant.com/docs/integrations/zigbee2mqtt#add-devices
> 
> For your information, WXCJKG13LM is not managed yet by Gladys (complex device).

yes , before i add a device,i can see a join log and pairing message on `gladys-z2m-zigbee2mqtt` docker,but now there is not message when i try ZNLDP12LM or WXCJKG13LM

i think although WXCJKG13LM is not managed yet by Gladys  ,but it will be see in `gladys-z2m-zigbee2mqtt` docker logs,is this right?

**Comment by cicoub13** [comment]
I'm sorry, but I can't help you more 😞 because the issue is between your device and Zigbee2mqtt. We use this library, but we don't develop it.
Maybe this can help : https://www.zigbee2mqtt.io/information/FAQ.html#no-logging-is-shown-at-all

**Comment by bulolo** [comment]
> I'm sorry, but I can't help you more 😞 because the issue is between your device and Zigbee2mqtt. We use this library, but we don't develop it.
> Maybe this can help : https://www.zigbee2mqtt.io/information/FAQ.html#no-logging-is-shown-at-all

ok thank.

i am a china developer i want to make support by myself.but i don't how to begin.

and i also want to make gladys ui in chinese language ，i find this i18n.
![image](https://user-images.githubusercontent.com/10026498/114275297-930d8800-9a54-11eb-9e21-001f34d4263b.png)
i add a cn i18n ?is that right?

**Comment by cicoub13** [comment]
> but i don't how to begin.

You can clone the project and try to launch it locally 
https://gladysassistant.com/docs/dev/setup-development-environment-mac-linux
https://gladysassistant.com/docs/dev/setup-development-environment-windows
After that, feel free to explore the code of some service (like zigbee2mqtt service).

> i add a cn i18n ?is that right?

Yes, you need to translate every key (from english) and add your language in the `index.js` file (same directory).

Feel free to come in the forum https://community.gladysassistant.com/c/international/development/49

**Comment by bulolo** [comment]
thank you very much. i will make a PR to support Chinese.
and try to support new zigbee devices myself if the device is not supported

**Comment by VonOx** [comment]
Feel free to translate website too it's open source 😉

 https://github.com/GladysAssistant/v4-website

**Comment by bulolo** [comment]
> Feel free to translate website too it's open source 😉
> 
> https://github.com/GladysAssistant/v4-website

ok,i will try 😄

**Comment by bulolo** [comment]
https://github.com/GladysAssistant/Gladys/pull/1178

@VonOx @cicoub13 @Pierre-Gilles
