### ISSUE TITLE
Bluetooth presence scanner enabled even if Bluetooth is disabled

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#1121]
Even if Bluetooth is disabled or unavailable, scanner presence still runs in background once you save configuration.

[detected with Cypress]

**Comment by Pierre-Gilles** [comment]
> [detected with Cypress]

Aha, love that :p

**Comment by atrovato** [comment]
To check if fixed.

**Comment by atrovato** [comment]
Already done.
Scanner is enabled only if Bluetooth is ready (enabled).
