### ISSUE TITLE
SCENE : autofill not working in the select

### ISSUE THREAD

**Issue by guim31** [GladysAssistant/Gladys#1123]
**Describe the bug**
When I create a scene, I use the select boxes to choose triggers and actions.
But when I type `all` the first three letters of `Allumer la lumière `ou `Allumer la prise`, it doesn't give me the option I look for.

**Screenshots**
![image](https://user-images.githubusercontent.com/33096540/113582931-488da500-9629-11eb-8118-96262510cc57.png)

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation, RPi 3B+

**Comment by rob-mccann** [comment]
Looks like this might duplicate #1094

**Comment by VonOx** [comment]
Yes it is, thank you @rob-mccann

**Comment by guim31** [comment]
Damn I might be more careful before posting an issue....! Sorry !

**Comment by VonOx** [comment]
Dont worry @guim31  it's ok
