### ISSUE TITLE
Z-Wave: Handle device "ThermoFloor AS Heatit ZDim"

### ISSUE THREAD

**Issue by jstorgaard** [GladysAssistant/Gladys#1134]
```
{
  "manufacturer": "ThermoFloor AS",
  "manufacturerid": "0x019b",
  "product": "Heatit ZDim",
  "producttype": "0x0003",
  "productid": "0x2200",
  "classes": [
    "37",
    "38",
    "39",
    "50",
    "91",
    "94",
    "112",
    "114",
    "115",
    "134"
  ]
}
```

**Comment by jstorgaard** [comment]
When adding this device I get 3 features. Switch (On/Off), Energy consumption and power consumption.
This is a dimmer, so dim should be added instead of switch. Also no energy or power consumption is shown (No value recorded).

**Comment by cicoub13** [comment]
Hello. I couldn't find this model here : https://www.zigbee2mqtt.io/information/supported_devices.html
Can you link me to the right model ?
