### ISSUE TITLE
Z-Wave: Handle device "ThermoFloor AS Heatit Thermostat TF 056"

### ISSUE THREAD

**Issue by jstorgaard** [GladysAssistant/Gladys#1135]
```
{
  "manufacturer": "ThermoFloor AS",
  "manufacturerid": "0x019b",
  "product": "Heatit Thermostat TF 056",
  "producttype": "0x0003",
  "productid": "0x0202",
  "classes": [
    "37",
    "49",
    "50",
    "64",
    "67",
    "94",
    "112",
    "114",
    "115",
    "134"
  ]
}
```

**Comment by jstorgaard** [comment]
This is a thermostat used for floor heating. Should be able to set mode (Eco/comfort), on/off, temp measurement, temp setpoint and power/energy consumption.

**Comment by cicoub13** [comment]
Hello. I couldn't find this model here : https://www.zigbee2mqtt.io/information/supported_devices.html
Can you link me to the right model ?
