### ISSUE TITLE
"Brain" ne fonctionne pas

### ISSUE THREAD

**Issue by Faust24** [GladysAssistant/Gladys#114]
Après avoir tapé `Ctrl+Espace`, j'ai essayé de tester ce fameux cerveau mais celui-ci renvoie sur une URL qui renvoie une erreur 500 si je tape un mot qui n'est pas un mot clé/verbe (Comme `/brain/classify?q=pouet`).
Sinon cela me renvoie un format `JSON` avec `null` (Comme `/brain/classify?q=allumer`).

Est-ce que cela est mis en place pour le moment ?

Je pose cette question car j'ai l'impression que [le controleur](https://github.com/GladysProject/Gladys/blob/c28e84b40bf0932d7a044f291ce65f80ec33436f/assets/js/app/brain/brain.controller.js#L37-L39) n'est pas encore terminé.

Merci par avance 😃 

(Je suis à la version 3.3.1)

**Comment by Pierre-Gilles** [comment]
> renvoie une erreur 500 si je tape un mot qui n'est pas un mot clé/verbe (Comme /brain/classify?q=pouet).

Lorsqu'aucune commande n'est détectée, la route renvoie une 500 :) C'est pas forcément logique effectivement... Mais c'est le fonctionnement normal

Sinon c'est censé exécuter l'action associé, et pas forcément renvoyer quelques choses, la route n'est pas forcément cohérente en effet ^^

J'ai détaillé assez récemment le fonctionnement du brain ici => http://gladysproject.com/forum/viewtopic.php?f=33&t=6486#p12442

Côté client effectivement il n'y a pour l'instant aucune réponse, le texte est tout simplement classifié, l'action effectué et.. c'est tout :) mais ça fait le travail pour l'instant ! ça sera modifié bien entendu
