### ISSUE TITLE
Add support control Light Brightness and Light Temperature UI

### ISSUE THREAD

**Issue by bulolo** [GladysAssistant/Gladys#1141]
i have a zigbee light that support control on/of 、Brightness、Color Temp
i add it throught zigbee2mqtt,but i can not control it on dashborad,and i can control on zigbee2mqtt port 8080 dashboard
![image](https://user-images.githubusercontent.com/10026498/114276468-4e382000-9a59-11eb-9be2-c746bb7ea4b9.png)
![image](https://user-images.githubusercontent.com/10026498/114276500-6f990c00-9a59-11eb-93e6-5ca5a459a136.png)

**Comment by VonOx** [comment]
Wich model ? Because Color and Brightness is available in Gladys, so there is something wrong on the device configuration

=> Box with Hue devices
![image](https://user-images.githubusercontent.com/1528694/114525232-3d003680-9c46-11eb-8a2a-eacf4a78bd95.png)

**Comment by bulolo** [comment]
https://www.zigbee2mqtt.io/devices/ZNLDP12LM.html

**Comment by bulolo** [comment]
> Wich model ? Because Color and Brightness is available in Gladys, so there is something wrong on the device configuration
> 
> 
> 
> => Box with Hue devices
> 
> ![image](https://user-images.githubusercontent.com/1528694/114525232-3d003680-9c46-11eb-8a2a-eacf4a78bd95.png)
> 
> 

ZNLDP12LM

**Comment by atrovato** [comment]
Related to https://github.com/GladysAssistant/Gladys/issues/915

**Comment by atrovato** [comment]
There is a new "dev/beta" version with a new way to handle Zigbee2Mqtt devices.
You can try it, or wait for the new release.

This will allow you to control brightness and temperature on Zigbee devices.
You will need to delete and re-add device from Zigbee2Mqtt setup panel.

We wait for feedbacks.

**Comment by atrovato** [comment]
@bulolo are this features available now?
