### ISSUE TITLE
【zigbee2mqtt】Unplug USB, gladys-z2m-zigbee2mqtt docker stop

### ISSUE THREAD

**Issue by bulolo** [GladysAssistant/Gladys#1142]
![image](https://user-images.githubusercontent.com/10026498/114276605-e1715580-9a59-11eb-98a2-f77c4d65549b.png)

when i use zigbee2mqtt,
![image](https://user-images.githubusercontent.com/10026498/114276629-0b2a7c80-9a5a-11eb-8afa-266daf428810.png)
and then i Unplug USB 
then Plug in USB .
i found the  gladys-z2m-zigbee2mqtt docker is down and never restart

**Comment by geoffreyp** [comment]
I had the same problem today

**Comment by VonOx** [comment]
This is related to zigbee2mqtt, not gladys.

If you remove your dongle, you need to restart zigbee2mqtt because it crash. Not something we need to handle.

**Comment by Pierre-Gilles** [comment]
> If you remove your dongle, you need to restart zigbee2mqtt because it crash. Not something we need to handle.

So the user can't remove his dongle and put it back ? I think it's our responsibility too, the user using zigbee2mqtt in Gladys is just here to use zigbee devices, he don't know what zigbee2mqtt is and don't know how to restart a container (and we don't want him to mess with containers)

I think it's definitely our job!

**Comment by VonOx** [comment]
OK good luck to handle all third parties crash. I'm not agree this is our job.

He know what zigbee is and what service he activated, user is not an idiot or baby. He can read a message ( the only thing we must do here, I think )

**Comment by Pierre-Gilles** [comment]
> ( the only thing we must do here, I think )

Maybe i didn't understood then, let's imagine I disconnect my Zigbee USB key, and plug it back. 

Is Gladys and zigbee devices still working properly after that ?

I think we start the zigbee2mqtt container with a "restart=always" option, so even if it crashes, it should restart and find the USB key back at some point, no ? 

> user is not an idiot or baby.

The user doesn't know what we are doing under the hood, he's not necessarily a programmer. 

It's gladys job to make sure that the installation of the user works properly in a normal usage. And unplugging the USB key, and plugging it back is a completely normal use case

**Comment by cicoub13** [comment]
I agree that the container must restart automatically (it was the idea with the `--restart always`).

But it's not working. I'm investigating 🤔 

```
today at 22:06  Zigbee2MQTT:error 2021-04-24 20:06:18: Adapter disconnected, stopping
today at 22:06  Zigbee2MQTT:info  2021-04-24 20:06:18: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
today at 22:06  Zigbee2MQTT:info  2021-04-24 20:06:18: Disconnecting from MQTT server
today at 22:06  Zigbee2MQTT:error 2021-04-24 20:06:18: Failed to stop Zigbee2MQTT
today at 22:06  npm ERR! code ELIFECYCLE
today at 22:06  npm ERR! errno 1
today at 22:06  npm ERR! zigbee2mqtt@1.18.2 start: `node index.js`
today at 22:06  npm ERR! Exit status 1
today at 22:06  npm ERR! 
today at 22:06  npm ERR! Failed at the zigbee2mqtt@1.18.2 start script.
today at 22:06  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
today at 22:06  
today at 22:06  npm ERR! A complete log of this run can be found in:
today at 22:06  npm ERR!     /root/.npm/_logs/2021-04-24T20_06_19_781Z-debug.log
```

**Comment by cicoub13** [comment]
Issue created on zigbee2mqtt repository - https://github.com/Koenkk/zigbee2mqtt/issues/7198

I'm testing a fix

**Comment by Pierre-Gilles** [comment]
Agree, nice catch @cicoub13 ! 

Let's see what they say on Zigbee2mqtt repo :)

**Comment by cicoub13** [comment]
OK, they made a fix here https://github.com/Koenkk/zigbee2mqtt/pull/7230 but it's not yet released.
Let's see if it solves the issue once released.

⚠️ If you unplug the key just after starting the container (10 seconds) or if you start without key, Restart policy will not apply.

**Comment by Pierre-Gilles** [comment]
Nice! 🙂 Thanks for reporting!
