### ISSUE TITLE
Build LG TV service

### ISSUE THREAD

**Issue by rob-mccann** [GladysAssistant/Gladys#1144]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set up and link my LGTV to Gladys so I can control it from a dashboard

**Comment by Pierre-Gilles** [comment]
Hey! 

We use GitHub issues for bug tracking, but we use the forum for feature requests.

For now, most of our users are french so all features requests are in the french forum, but I just created a features request in the international forum: 

https://community.gladysassistant.com/c/international/feature-requests/53
