### ISSUE TITLE
[zigbee2mqtt] Change vibration sensor type

### ISSUE THREAD

**Issue by vincentBesseau** [GladysAssistant/Gladys#1149]
First, are you sure that you found a Gladys bug?

See this post : https://community.gladysassistant.com/t/zigbee2mqtt-image-docker-de-test-basee-gladys-v4/5746/362

https://www.zigbee2mqtt.io/devices/DJT11LM.html#xiaomi-djt11lm

**Describe the bug**
When i add my sensor to gladys, this sensor was find but it was create with bad features : 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/33568805/115146946-16cd0300-a059-11eb-9672-eb3a35cf96eb.png">

on port 8080, i can see this sensor expose this  : 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/33568805/115147411-20576a80-a05b-11eb-8cde-6f5ac228b74a.png">

**To Reproduce**
Just add this sensor by service zigbee2mqtt as another sensor

**Expected behavior**
I would like to have the strength and another libelle instead of Clic bouton (perhaps just "Action") 

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation (if yes, which Raspberry Pi ?)
RP3B+

**Comment by cicoub13** [comment]
> I would like to have the strength

I'm afraid it's not possible easily. This kind of feature is not existing in Gladys Core for now.

>another libelle instead of Clic bouton

You can change the feature name in the first screenshot you paste. It's difficult to detect the real device behind the "action" in Zigbee without creating a configuration for each device. We tried to keep the features most generic as possible.

**Comment by vincentBesseau** [comment]
Thx @cicoub13 !
I'm wonder, why this sensor doesn't have these features (found on MQTT) 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/33568805/116007179-bb79b280-a60e-11eb-811a-4c8a091daa6f.png">
?
