### ISSUE TITLE
Zigbee2mqtt: Add device 9CZA-A806ST-Q1A

### ISSUE THREAD

**Issue by geoffreyp** [GladysAssistant/Gladys#1156]
New Zigbee2mqtt device : https://www.zigbee2mqtt.io/devices/9CZA-A806ST-Q1A.html
```
{
  "name": "0x60a423fffe880dc0",
  "external_id": "zigbee2mqtt:0x60a423fffe880dc0",
  "model": "9CZA-A806ST-Q1A",
  "features": [],
  "should_poll": false,
  "service_id": "6f6e2105-42cf-4754-afe1-00a0a4214853",
  "supported": false
}
```

**Comment by geoffreyp** [comment]
The model 9CZA-A806ST-Q1A is a RGB light but Gladys see it as a simple light. 
Is it an update to do in the code of gladys or in my settings ?
screenshot : 

![image](https://user-images.githubusercontent.com/9945579/118183770-c9b33580-b43a-11eb-942c-c9d242058c0a.png)

**Comment by cicoub13** [comment]
Color feature is existing in Gladys Core but not yet implemented in Zigbee2Mqtt service.
I'm working on it 😉
