### ISSUE TITLE
[zigbee2mqtt] change type for XIAOMI MFKZQ01LM

### ISSUE THREAD

**Issue by vincentBesseau** [GladysAssistant/Gladys#1158]
https://community.gladysassistant.com/t/zigbee2mqtt-image-docker-de-test-basee-gladys-v4/5746/370?u=spenceur

**Comment by cicoub13** [comment]
Hello. The Xiaomi Cube is not yet managed in Zigbee2Mqtt because it's a very specific device.
I will work on generic buttons first, and after take the work done on Xiaomi service to integrate the Cube in Zigbee2Mqtt.

**Comment by vincentBesseau** [comment]
I found this on MQTT service : 
<img width="109" alt="image" src="https://user-images.githubusercontent.com/33568805/116007248-20350d00-a60f-11eb-9783-14f9418eac4d.png">


I think it lacks information such as the side whose action has executed

<img width="202" alt="image" src="https://user-images.githubusercontent.com/33568805/116007321-828e0d80-a60f-11eb-94e9-5f8ce6e29f63.png">

**Comment by VonOx** [comment]
For reference => https://www.zigbee2mqtt.io/devices/MFKZQ01LM.html

**Comment by VonOx** [comment]
not stale

**Comment by vincentBesseau** [comment]
not stale
