### ISSUE TITLE
Troubles while removing scene trigger 

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#1163]
According to report: https://community.gladysassistant.com/t/releve-de-bugs-divers/6271

On scene page,
1. add a trigger
2. add another (different) trigger
3. remove 1st trigger
4. data mixing

![scene-remove-trigger](https://user-images.githubusercontent.com/1839717/115754520-8f56fb00-a39c-11eb-8492-8e9b45ff7347.gif)

**Comment by Pierre-Gilles** [comment]
I tried to fix it in https://github.com/GladysAssistant/Gladys/pull/1165

It seems to fix it, but I'm not sure it's completely fix. I had to upgrade preact as well (#dangerous).

What do you think about that?

**Comment by atrovato** [comment]
@Pierre-Gilles and what about https://github.com/GladysAssistant/Gladys/pull/1168 ?

**Comment by Pierre-Gilles** [comment]
Oh you're maybe right. I thought it was only a "key" in list problem, but maybe you're right it's not related 

I'm testing that tomorrow
