### ISSUE TITLE
Troubles with feature selection on scene

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#1164]
According to report: https://community.gladysassistant.com/t/releve-de-bugs-divers/6271

On scene page, with feature selector,
if I have multiple features with same type, I can't differenciate it.

![image](https://user-images.githubusercontent.com/1839717/115755036-2d4ac580-a39d-11eb-8a84-261a55ffa999.png)

**Comment by Pierre-Gilles** [comment]
This topic is currently discussed at several place on the forum.

I'm closing this issue as there is no actionable thing to do with it
