### ISSUE TITLE
Slider control in dashboard doesn't work very well on touchscreen devices

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1167]
Tested on Safari iOS but I guess it's the same on Android, the slider doesn't work very well on touchscreen:

<img width="592" alt="Screenshot 2021-04-23 at 17 24 24" src="https://user-images.githubusercontent.com/7365207/115850751-c7bc0f00-a458-11eb-993a-7cc728b048ef.png">

It's hard to use :D

**Comment by vincentBesseau** [comment]
It s same on Android :-D

**Comment by Pierre-Gilles** [comment]
Already fixed
