### ISSUE TITLE
Scrollbar visible in dashboard on Windows

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1206]
## Describe the bug
Scrollbar are visible on the dashboard when movement is detected few seconds ago.

## To Reproduce

1. Add a new widget for movement dection
2. Move in front of you captor
3. The dashboard will create scrollbar because "few seconds ago" is to long to fit in the widget

## Expected behavior
A clean widget without scrollbar.

## Screenshots
![image](https://user-images.githubusercontent.com/14235706/120170640-76dec980-c201-11eb-8cbe-802fc59288ca.png)

## Your Gladys installation

- Raspberry Pi 4B
- Official docker image

**Comment by Pierre-Gilles** [comment]
Already fixed.
