### ISSUE TITLE
Scene: variable in message various bug (deleted when text is removed after the variable and list hides in case of type error).

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1207]
## Describe the bug
I found 2 bugs:

1. (video from start to 15sec) When I try to remove text or spaces **after** a variable, the variable will disappear itself. And text will not be able to be typed. On the video I am try to type something after the variable was deleted and nothing appears.
2. (video from 18 sec to the end) When I write the variable name, if I make mistype a letter, I am forced to deleted the entire variable name until the `{{` character. On a smartphone, it is really a pain to find the correct variable name if openweather API for example (very long JSON object).

## To Reproduce

1. Create a scene and get any value from an API or a device. I used the openweather API : https://api.openweathermap.org/data/2.5/onecall?lat=50&lon=5&lang=fr&exclude=minutely,hourly&appid=TOKEN
2. Try to create a message from the scene with the weather description and mistype one letter in the variable name
3. See, your are forced to delete the whole variable name and write it again

## Expected behavior
The variable selector dropdown could appears again when the error is removed. For example, for a variable `data.daily.0.wheater.0.description`, if I type `data.dailyy`, removing the last `y` should make the dropdown menu appear again.

## Screenshots
https://user-images.githubusercontent.com/14235706/120171914-d2f61d80-c202-11eb-8b60-c7af83cd7c92.mov

## Your Gladys installation
- Raspberry Pi 4B
- OS: Windows 10
- Browser: Firefox Nightly

**Comment by Pierre-Gilles** [comment]
Hey! I just investigated on this! 

Both issues are linked to the lib we use for this: @yaireo/tagify

- For the first one, I managed to fix by upgrading the lib here => https://github.com/GladysAssistant/Gladys/pull/1228
- For the second one, it's not really something we can fix in Gladys, the lib should fix it. There are already some issues on the repo of the library => https://github.com/yairEO/tagify/issues/847
