### ISSUE TITLE
Calendar events created in a different timezone are displayed in the wrong timezone

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1211]
@bertrandda I noticed that events created in a different timezone are displayed in the timezone the event was created, not the timezone of the user watching the calendar

Any idea what could be the cause?

**Comment by bertrandda** [comment]
I replicate the issue, it seems to be during synchronization, timezone is misinterpreted. I'll try to fix that as soon as possible.

**Comment by Pierre-Gilles** [comment]
Ok I see! Thanks for checking 🙂
