### ISSUE TITLE
Cannot use negative values in scenes 

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1222]
**Describe the bug**
As mentionned in the title, in a scene I cannot use negative values (or decimal).
The input does not allow me. 

**To Reproduce**

1. Create a new scene
2. Select a device in trigger
3. Try to trigger if the device value is negative (like temperature of a congelator)
4. See it is impossible to type 

**Expected behavior**
I can use negtive and decimal values. 

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation, last stable. 
**Desktop:**

- OS: Windows 10
- Browser: firefox nightly

**Comment by VonOx** [comment]
FYI copy/paste works

![image](https://user-images.githubusercontent.com/1528694/123616517-a8e64a00-d806-11eb-844b-18c96b977004.png)

I'm trying to find what is going on.

**Comment by Pierre-Gilles** [comment]
I think the validation is faulty, the onType only accept numbers

**Comment by Pierre-Gilles** [comment]
It was a simple bug, I fixed it in https://github.com/GladysAssistant/Gladys/pull/1228
