### ISSUE TITLE
Tasmota: manage IR and RF sensors

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#1234]
According to https://community.gladysassistant.com/t/releve-de-bugs-divers/6271/122?u=alextrovato

Be able to handle IR and RF Tasmota message as sensor first.

**Comment by atrovato** [comment]
Still open.

**Comment by atrovato** [comment]
Not stale.

**Comment by atrovato** [comment]
Still open, not stale...

**Comment by gboulvin** [comment]
By the way, could you add support for RFID ;-) ?
May I help for something ? If you tell me where to look...

**Comment by gboulvin** [comment]
Still open

**Comment by gboulvin** [comment]
Still open

Le mar. 19 juil. 2022 à 13:44, stale[bot] ***@***.***> a
écrit :

**Comment by gboulvin** [comment]
Not stale

Le sam. 17 sept. 2022 à 15:55, stale[bot] ***@***.***> a
écrit :

**Comment by gboulvin** [comment]
Not stale

Le sam. 10 déc. 2022 à 09:18, stale[bot] ***@***.***> a
écrit :

**Comment by VonOx** [comment]
@atrovato did you have an idea for core implementation?

Ir need hex value specific to "feature" right?
https://tasmota.github.io/docs/Codes-for-IR-Remotes/

List is pretty huge 😅, so mapping is not a solution.

**Comment by atrovato** [comment]
My first problem is to detect that the device has an IR or RF module, receiver or emitter.
I didn't see any information on the device statusN about it.

But we can do as in Broadlink, add a parameter with signal value for each button in the device.

**Comment by VonOx** [comment]
I agree, after a lot of search, there is no way to identify a ir/rf feature.

Need to dig a bit more.

**Comment by atrovato** [comment]
I'm asking to our Tasmota expert here -> https://community.gladysassistant.com/t/tuto-rf433-dans-gladys-via-tasmota/7529/11?u=alextrovato
