### ISSUE TITLE
Zigbee2mqtt: Add device TS0601_air_quality_sensor

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1246]
Salut @cicoub13,

J'ai un nouveau capteur de la qualité de l'air, pas encore supporté par Gladys :-)

```
{
  "name": "CapteurQualitéAir",
  "external_id": "zigbee2mqtt:CapteurQualitéAir",
  "model": "TS0601_air_quality_sensor",
  "features": [],
  "should_poll": false,
  "service_id": "13c29ffe-f096-4343-a058-b378a5feeec1",
  "supported": false
}
```

@Pierre-Gilles je ne crois pas que Gladys gère ce genre de feature, on risque d'avoir besoin de toi sur ce sujet : 

![image](https://user-images.githubusercontent.com/14235706/126501977-9d2fdd26-7714-4273-8da5-dd2f2d0eb1b3.png)

Il s'agit d'un [Tuya TS0601](https://www.zigbee2mqtt.io/devices/TS0601_air_quality_sensor.html#tuya-ts0601_air_quality_sensor), que j'ai acheté sur [Aliexpress pour 20€](https://fr.aliexpress.com/item/1005002522369579.html).

**Comment by cicoub13** [comment]
Hello,

These features are already managed in Gladys and in the service Zigbee2Mqtt (let me add the device with this features first) :
- temperature
- humidity

These features are managed by Gladys but not by our Zigbee2Mqtt integration (it will require some development) :
- co2

These features are not managed in Gladys core :
- voc (volatile organic compounds)
- formaldehyd (méthanal ou formaldéhyde ou aldéhyde formique in 🇫🇷)

**Comment by LM1LC3N7** [comment]
Sorry I forget that it is preferable to speak English here 😅 

Thanks @cicoub13 for your work!
