### ISSUE TITLE
Dashboards: Fullscreen bug

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1250]
# Describe the bug
If I use the Firefox button to escape the full screen instead of the Gladys button, some of the screen disappear (menu, profile, etc.).

# To Reproduce

1. Open a dashboard on Firefox
2. Click on Gladys Full screen button
3. Click on Firefox button to escape the full screen
4. See what happens

# Expected behavior
Full screen escape should work with the Firefox or Gladys button the same way.

# Screenshots
https://user-images.githubusercontent.com/14235706/127625181-20add108-3e05-427a-879c-d5c53f10fef3.mov

# Your Gladys installation

- Raspberry Pi installation: Yes
- Gladys Version: Dev

# Desktop

- OS: Windows 10
- Browser: Firefox Nightly

**Comment by Pierre-Gilles** [comment]
Indeed, thanks a lot for testing that! :)
