### ISSUE TITLE
Zigbee2mqtt: Add the battery value to the device RTCGQ11LM

### ISSUE THREAD

**Issue by mikitouf** [GladysAssistant/Gladys#1254]
Hi!

The Aqara human body movement and illuminance sensor RTCGQ11LM have a value "voltage" in Gladys but can we have the value  "battery" like the Aqara temperature  WSDCGQ11LM.

The value ( battery ) is in the state page on  zigbee2mqtt:8080.

It'll be more easier with "battery" value to know when we must change the battery than the voltage

**Comment by cicoub13** [comment]
Hello. The battery feature is auto detected when the device has a "Battery" powersource (like in this image).

<img width="694" alt="Capture d’écran 2021-09-06 à 10 47 02" src="https://user-images.githubusercontent.com/1773153/132188913-26ee1a9b-7ef6-416c-a9f9-282c1e388dfc.png">

Can you try to delete the device and add it again in Gladys (no need to unpair from the Zigbee network) ?

**Comment by mikitouf** [comment]
I delete on gladys ( by the way it's freeze 30s the zigbee2mqtt service, it was like nothing it's on ), and add the battery feature.
Thanks. 

I closed it
