### ISSUE TITLE
Can't create 2 room with the same name in 2 houses

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1263]
It's pretty convenient to name kitchen a kitchen.
If you manage multiple house you have 2 kitchens in 2 houses.

Uniqueness must be managed by house and not instance in some way

![image](https://user-images.githubusercontent.com/1528694/130350661-a25f22e2-aa05-4121-92b3-da6084620fb5.png)

 
* Via Gladys Plus there is no error in UI but ( infinite loading ):
```js
Uncaught (in promise) TypeError: v is undefined
    j house.js:222
    promise callback*o house.js:191
    saveHouse house.js:174
    promise callback*saveHouse/< house.js:174
    saveHouse house.js:17
    action unistore.es.js:1
    saveHouse EditHouseComponent.jsx:30
    saveHouse EditHouseComponent.jsx:26
```

**Comment by atrovato** [comment]
I think the constraint is on generated selector, not really on name.

**Comment by Pierre-Gilles** [comment]
Yes, I wrote a proposal here but haven't got any reply so far: 

https://community.gladysassistant.com/t/proposition-ajouter-un-nombre-aleatoire-a-4-chiffres-a-tous-les-selector-pour-eviter-les-collisions/6617

**Comment by VonOx** [comment]
Not stale

**Comment by Pierre-Gilles** [comment]
Not stale. Will be fixed with random 4 digits in selector
