### ISSUE TITLE
Previous scene name still appear on new scene

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#1267]
**Describe the bug**
If you begin a scene, with a name, then you delete it before you finish it, and then you decide to create a new scene withouth refreshing your brower, the input field Name appears with your previous name, but if you hit the Create button, it says you need a name.

**To Reproduce**
Start creation of a scene, name it, click Create, then Delete it.
Next, start creation of a new scene, you should see your previous name, choose an icon and click on create.
You should get the error.

**Expected behavior**
The previous name should not appear.

**Comment by Pierre-Gilles** [comment]
Nice catch!
