### ISSUE TITLE
Zigbee2mqtt: Update device LED1732G11 / E1524/E1810

### ISSUE THREAD

**Issue by HamendeM** [GladysAssistant/Gladys#1269]
**Is your feature request related to a problem? Please describe.**
As user, I would like to be able to get the status of my lamp when I switch them On / Off using my remote.
And be able to use dimmable functionnalities.

**Describe the solution you'd like**
When I am in the Dashboard, I would like to be able to seen if my lamps are On / Off.
And be able to modify brightness.

**Describe alternatives you've considered**
N/A

**Additional context**
--- Remote ---
{"dateCode":"20190401","description":"TRADFRI remote control","friendly_name":"0x5c0272fffe28cb84","hardwareVersion":1,"ieeeAddr":"0x5c0272fffe28cb84","lastSeen":1630152802881,"manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"E1524/E1810","modelID":"TRADFRI remote control","networkAddress":2912,"powerSource":"Battery","softwareBuildID":"2.3.014","type":"EndDevice","vendor":"IKEA"}

--- Light Bulb ---
{"dateCode":"20200312","description":"TRADFRI LED bulb E27 1000 lumen, dimmable, white spectrum, opal white","friendly_name":"0xccccccfffe9380a0","hardwareVersion":1,"ieeeAddr":"0xccccccfffe9380a0","lastSeen":1630152807716,"manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"LED1732G11","modelID":"TRADFRI bulb E27 WS opal 1000lm","networkAddress":49184,"powerSource":"Mains (single phase)","softwareBuildID":"2.0.029","type":"Router","vendor":"IKEA"}

**Comment by atrovato** [comment]
We now only miss https://www.zigbee2mqtt.io/devices/E1524_E1810.html which is a button device.

**Comment by atrovato** [comment]
I think we are done with this (according to code).

**Comment by Pierre-Gilles** [comment]
In that case I'm closing the issue. Feel free to reopen it if it's not the case :)
