### ISSUE TITLE
[FRONT] Box device in room is showing switch even if feature is not displayed

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1274]
![image](https://user-images.githubusercontent.com/1528694/132089148-9f1e79d4-33a2-4701-8e67-d264941a1718.png)
![image](https://user-images.githubusercontent.com/1528694/135810301-11e138be-1f01-4415-a4f2-2678c784a907.png)

**Comment by Pierre-Gilles** [comment]
https://community.gladysassistant.com/t/editer-le-type-de-feature-des-devices-philips-hue/5806/32?u=pierre-gilles

**Comment by VonOx** [comment]
not stale

**Comment by atrovato** [comment]
I got it recently, I may take it.

**Comment by Pierre-Gilles** [comment]
Not stale
