### ISSUE TITLE
Question: https ?

### ISSUE THREAD

**Issue by nlhomme** [GladysAssistant/Gladys#13]
Tout d'abord, bravo pour Gladys, je sens que je vais abandonner le monde extérieur par ta faute :)
Ensuite, comment sécuriser la connexion à Gladys via https (si on veut y accéder depuis l'extérieur par exemple)

Cordialement

**Comment by ghost** [comment]
Hello

Je pense que le mieux c'est de te faire une connexion openvpn

Cneqt mieux pour accéder a ces service maison 

Je te conseil aussi de t'installer humhub 

J'ai toujours pas réussi a l'installer

**Comment by Pierre-Gilles** [comment]
Pour avoir du https il faut un certificat SSL, sur un Raspberry Pi c'est possible ( voir : http://sirarsalih.com/2014/05/31/setting-up-a-node-server-and-securing-it-with-ssl-on-raspberrypi/ )
Mais il faudra faire des modifs dans Gladys.

**Comment by nlhomme** [comment]
j'ai forké Gladys, de sorte à bosser sur l'implémentation du https de mon côté. Je sais que ce n'est pas très dur, je reviens vers toi si j'ai du nouveau (si je fait ça pendants les cours, j'en connais qui ne vont pas apprécier) ;)

**Comment by nlhomme** [comment]
Bon, ça a l'air un peu plus complexe que je pensais... je connais pas trop sails.js... Je pensais qu'il suffirait de modifier le fichier local.js, mais j'ai des erreurs qui s'affichent ensuite...

**Comment by Pierre-Gilles** [comment]
Pour faire du SSL après quelques recherche il vaut mieux ne pas toucher au code Node.js, juste placer un nginx devant ! 

Plus d'infos : http://blog.risingstack.com/operating-node-in-production/

**Comment by nlhomme** [comment]
ça m'a l'air un peu tordu, mais ça mérite d'être étudié... J'ai surtout peur au niveau des perfs sur le raspberry B... Je garde l'article sous le coude, merci!
