### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by YassineKardid** [GladysAssistant/Gladys#1301]
Hello, I made some changes on database, please how can i generate the migration files ?

**Comment by Pierre-Gilles** [comment]
Hey!

You need to use sequelize-cli: https://github.com/sequelize/cli

Example:

```
 sequelize migration:generate --name add-table-test
```

Then you need to modify the up: () migration. 

If you want to talk with us faster, we are mainly on the forum: https://community.gladysassistant.com/

**Comment by VonOx** [comment]
I'm closing this issue because answered. @YassineKardid feel free to reopen if needed.
