### ISSUE TITLE
Implement RelativeCI new github action

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1303]
https://github.com/relative-ci/agent-action

Documentation: https://relative-ci.com/documentation/setup/agent/github-action/#workflows-triggered-by-forked-repositories-beta
Example: https://github.com/relative-ci/example-github-action-fork-pull-request

**Comment by Pierre-Gilles** [comment]
Still need to do that

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by atrovato** [comment]
Not stale.

**Comment by VonOx** [comment]
@atrovato @Pierre-Gilles I'm currently testing action

Does any of you can make a fake PR on https://github.com/VonOx/gh-test-ci ?
