### ISSUE TITLE
[MAPS] Zoom level is reset at every refresh

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1305]
Not really a bug but every refresh in maps view reset the zoom level

<img width="450" alt="maps" src="https://user-images.githubusercontent.com/1528694/134632109-3a7445c4-2abf-4561-8241-a57a9e2c3df8.gif" />

If you need to check something outside default zoom you can't ( or you need to be very fast :-D )

**Comment by Pierre-Gilles** [comment]
It's definitely a bug, not nice! 

Thanks for reporting :)

**Comment by VonOx** [comment]
Not stale

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by atrovato** [comment]
I'm not able to reproduce it, do you?

**Comment by VonOx** [comment]
I will re check this issue, I think this is when marker position is updated.

**Comment by VonOx** [comment]
@atrovato I have reproduced, this occurs only when user location is updated
