### ISSUE TITLE
When temperature is 0°C in a room, the UI is not displaying the temperature correctly

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1310]
<img width="454" alt="Screenshot 2021-10-04 at 13 57 12" src="https://user-images.githubusercontent.com/7365207/135801096-fb17097d-09a9-44d4-8121-5b15f596cfc3.png">

**Comment by atrovato** [comment]
This is because will live in countries where it's always 20°C :p
