### ISSUE TITLE
[FRONT] can't rename a Scene

### ISSUE THREAD

**Issue by mmbarki** [GladysAssistant/Gladys#1318]
can't edit the scene's name, the click on the name causes an error.
I suspect this line:
https://github.com/GladysAssistant/Gladys/blob/c14e042d6f614c059cc4b142ea7ef8bd833d7e3d/front/src/routes/scene/edit-scene/EditScenePage.jsx#L25
`<form onSubmit={this.saveScene}>`
should be
`<form onSubmit={props.saveScene}>`

**Comment by Pierre-Gilles** [comment]
You're right, it's a bug! I have the same and I can reproduce.
 
We did some changes recently and it broke it ^^

If you want to submit a PR to fix this, you're welcome 🙂
