### ISSUE TITLE
Z-Wave: Handle device "FIBARO System FGRGBW442 RGBW Controller 2"

### ISSUE THREAD

**Issue by Checconio** [GladysAssistant/Gladys#1319]
Bonjour,

Il ne détecte pas les réelles fonctionnalités RGBW et ON/OFF

Merci

```
{
  "manufacturer": "FIBARO System",
  "manufacturerid": "0x010f",
  "product": "FGRGBW442 RGBW Controller 2",
  "producttype": "0x0902",
  "productid": "0x1000",
  "classes": [
    "38",
    "39",
    "49",
    "50",
    "51",
    "91",
    "94",
    "112",
    "113",
    "114",
    "115",
    "117",
    "134",
    "152"
  ]
}
```

**Comment by Pierre-Gilles** [comment]
Salut! 

On est entrain de travailler sur une migration de Open-Zwave a ZwaveJS pour pouvoir justement gérer mieux certains appareils, merci de ton retour!

Tu peux suivre l'avancement du développement sur le forum: 

https://community.gladysassistant.com/t/v4-integration-z-wave/6057/34
