### ISSUE TITLE
Zigbee2mqtt: Add device BRT-100-TRV

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1320]
```
{
  "name": "RadiateurSalon",
  "external_id": "zigbee2mqtt:RadiateurSalon",
  "model": "BRT-100-TRV",
  "features": [
    {
      "category": "battery",
      "type": "integer",
      "unit": "percent",
      "name": "Battery",
      "read_only": true,
      "has_feedback": false,
      "min": 0,
      "max": 100,
      "zigbeeField": "battery",
      "external_id": "zigbee2mqtt:RadiateurSalon:battery:integer:battery",
      "selector": "zigbee2mqtt:RadiateurSalon:battery:integer:battery"
    }
  ],
  "should_poll": false,
  "service_id": "13c29ffe-f096-4343-a058-b378a5feeec1",
  "supported": false
}
```

![Screenshot_20211013-074643__01__01](https://user-images.githubusercontent.com/14235706/137074538-2b16ce61-419a-43cd-bdac-90ff63e5b823.jpg)

![Screenshot_20211013-074652](https://user-images.githubusercontent.com/14235706/137074546-8b512489-78f6-4604-a45c-64017071afcd.jpg)

![Screenshot_20211013-074704](https://user-images.githubusercontent.com/14235706/137074543-24c09081-ad64-4933-a981-d2b4e8b99ea3.jpg)

![Screenshot_20211013-074716](https://user-images.githubusercontent.com/14235706/137074541-75d3568a-8109-4bbc-ac65-f999286e9135.jpg)

![Screenshot_20211013-074708](https://user-images.githubusercontent.com/14235706/137074542-e66beafe-a9e3-444a-a422-c23c228c0b70.jpg)

@Pierre-Gilles Gladys can use all of these features already or a lot of dev will be required ?

**Comment by Pierre-Gilles** [comment]
It's a debate, It just depends how well we want to integrate this with Gladys :) 

Gladys 4 doesn't handle heating systems right now, but if the goal is just to do some On/off in Gladys, it could be easy. 

Can you create a post on the forum:

- describe the device and what it does exactly
- describe what are you needs

**Comment by atrovato** [comment]
Hi @LM1LC3N7 ,
your device should now partially managed with Gladys 4.7.x.
Can you check:
1. Gladys has been well updated?
2. your device has some features/can be added?

The heating system is not handle yet, but you can be able to switch it on/off.

Thank you.
