### ISSUE TITLE
After editing a dashboard name, the dropdown list is not updated

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1323]
Description: When editing an existing dashboard, the dropdown list is not updated with the new name. A page refresh is needed for that.

![image](https://user-images.githubusercontent.com/14235706/137123957-28d33dfa-8b9f-436f-8ad9-7a619d34b015.png)

Procedure: 
1. Create a new dashboard
2. Reload the page
3. Edit the dashboard name and do not refresh the page
4. See the dropdown menu, the old dashboard name is still shown.

**Comment by Pierre-Gilles** [comment]
Thanks for the report!

**Comment by Pierre-Gilles** [comment]
Still the case
