### ISSUE TITLE
New Integration for KNX and KNX devices support

### ISSUE THREAD

**Issue by moustic999** [GladysAssistant/Gladys#1324]
KNX support could be a great feature to add.

There are any flavors of KNX support, first is via KNXNet/IP which is itself splitted into 2 parts : Multicast and Tunneling.
others is via a TP-UART / serial or usb device.

For the KNXNet/IP support there ais a node.js library already existing : https://www.npmjs.com/package/knx

this support could be added quite easily,

Most complex part is that there is no auto-discovery of the devices. So either a import of etsProject can be implemented or to give a possibility to create devices manually via gui or via rest api ? 

 
I would be pleased to participate to the Development but I don't know where to begin and how I can do.

**Comment by Pierre-Gilles** [comment]
Hello @moustic999, 

We use Github for bug tracking only, can you create a feature request in our forum: 

https://community.gladysassistant.com/c/francais/feature-requests/43

(Also, you can write in french on the forum :) )

> I would be pleased to participate to the Development but I don't know where to begin and how I can do.

You're more than welcome, let's talk about this on the forum!
