### ISSUE TITLE
Zigbee2mqtt: Add device LED2002G5

### ISSUE THREAD

**Issue by jojolll** [GladysAssistant/Gladys#1325]
Hello ! En cours de migration vers Gladys V4, je tente l'intégration ZigBee. Ca part mal, première lampe refuse déjà de se connecter lol ! 

```
{
  "name": "Lampe bureau JL",
  "external_id": "zigbee2mqtt:Lampe bureau JL",
  "model": "LED2002G5",
  "features": [],
  "should_poll": false,
  "service_id": "8e387c9f-a22e-4cba-bf82-2857d769b495",
  "supported": false
}
```

J'ai du mal à comprendre le  `"supported": false` étant donné qu'elle est absolument bien supportée par Z2M : 
![image](https://user-images.githubusercontent.com/26553241/137216357-6b1bef18-29e6-4ce5-945c-31d572cc0831.png)

Est-ce un problème côté Gladys ? Ou alors, il faut que tous les périphériques soient ajoutés à la main à Gladys en // à Z2M ?

**Comment by LM1LC3N7** [comment]
En effet pour le moment chaque périphérique doit-être explicitement accepté par Gladys, pour faire correspondre les possibilités de l'équipement et les features internes de Gladys. 
Mais un gros travail est fait en ce moment pour automatiser tout ça et ne plus être bloqué si le périphérique est supporté par Z2M.
Je t'invite a faire un tour sur le forum a ce propos !

**Comment by atrovato** [comment]
Hi @jojolll ,
ce "gros" travail est maintenant disponible avec Gladys 4.7.x.
Peux-tu:
1. vérifier que Gladys est bien à jour ?
2. que ton appareil est maintenant disponible et contrôlable ?

Merci :)
