### ISSUE TITLE
[BUG] Affichage de la présence "dans quelques secondes"

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1328]
Salut,

Lorsque mon device de présence reçoit dans Gladys un nouvel événement, l'affichage sur le dashboard est incorrect : 
* A réception : "dans quelques secondes"
* Après quelques secondes : "il y a quelques secondes"

![image](https://user-images.githubusercontent.com/14235706/137600493-9fa6210e-1fbf-406b-b10f-abb3f97f0b31.png)

**Comment by Pierre-Gilles** [comment]
Yes you're not the first one to report this, it can happen that your laptop/mobile and you Gladys server are not time synchronized, so your laptop thinks the event happened in the future 

In that case, we'll need to "fake" the time reported to avoid this kind of display

**Comment by LM1LC3N7** [comment]
My Gladys can see the future, that's the v5.0 😆

Yeah, maybe a defaut message is that case should be "few seconds ago" even if the datetime correspond to a future time?

**Comment by Pierre-Gilles** [comment]
We'll put a fake time, as this translation is generated and translated in every language possible.

**Comment by Pierre-Gilles** [comment]
Still the case

**Comment by Pierre-Gilles** [comment]
Still the case

**Comment by VonOx** [comment]
Still the case

https://community.gladysassistant.com/t/fonctionnalite-presence-avec-mqtt/7143?u=vonox

**Comment by Pierre-Gilles** [comment]
Yes, it's normal because this bugfix is not in production yet.
