### ISSUE TITLE
Zigbee2mqtt: Add device ZBMINI

### ISSUE THREAD

**Issue by Jac34** [GladysAssistant/Gladys#1330]
```
{
  "name": "0x84fd27fffe8d3798",
  "external_id": "zigbee2mqtt:0x84fd27fffe8d3798",
  "model": "ZBMINI",
  "features": [],
  "should_poll": false,
  "service_id": "bdc6451f-f72b-4f71-a820-9a2a270601cd",
  "supported": false
}
```

**Comment by Jac34** [comment]
Bonjour, je souhaite l'intégration du Sonoff ZB mini dans gladys v4

**Comment by atrovato** [comment]
Bonjour @Jac34 ,
depuis la dernière version de Gladys 4.7.x, 
cet appareil devrait être intégré.

Peux-tu vérifier :
1. que Gladys est bien à jour ?
2. que ton appareil est bien pris en charge ?

Merci :)
