### ISSUE TITLE
Scene condition: Schedule from 10pm to 4am not working

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1331]
When I want to add a time condition like "execute between 10pm and 4am every day" it did not work on certain conditions.

* From 10pm to 11:55pm ✅
* From 12am to 5am ✅
* From 10pm to 5am ❌

**Comment by Pierre-Gilles** [comment]
It's not a bug, this condition is an "AND" condition, not "OR" 

The condition "After 10PM" and "Before 5AM" is always wrong (it's impossible to have a time that is at the same time before 5AM and after 10PM)

What you want is a way to have a "OR" condition I think, and it's a new feature :) 

Also, maybe we could explain a bit better how this condition works, thanks for reporting :)

**Comment by Pierre-Gilles** [comment]
Possible solutions: 

- maybe add a special warning when firstHour > secondHour
- OR switch to a "OR" when firstHour > secondHour

**Comment by LM1LC3N7** [comment]
I like both solutions but the second one is more transparent.

**Comment by Pierre-Gilles** [comment]
Still the case
