### ISSUE TITLE
Zigbee2mqtt: Add device HG06338

### ISSUE THREAD

**Issue by Tolkyen** [GladysAssistant/Gladys#1333]
```
{
  "name": "0xbc33acfffe6ec3e2",
  "external_id": "zigbee2mqtt:0xbc33acfffe6ec3e2",
  "model": "HG06338",
  "features": [],
  "should_poll": false,
  "service_id": "c2e22497-dfb0-4b92-a11c-981b663f1ad2",
  "supported": false
}
```

**Comment by Tolkyen** [comment]
Bonjour,

ce serait pour l'intégration du Bloc multiprise 
[341808_BE_FR.pdf](https://github.com/GladysAssistant/Gladys/files/7368666/341808_BE_FR.pdf)
(https://stesbintegrationprod.blob.core.windows.net/bsionlyarticlemanuals/bsiarticlemanual/341808/341808_BE_FR.pdf)

**Comment by atrovato** [comment]
On travaille sur une gestion plus complète des périphériques. Doucement mais surement.

**Comment by Pierre-Gilles** [comment]
Pour ce genre d'appareil, il y a un travail supplémentaire à faire, ajouter la gestion du split de device pour qu'une prise multiprise puisse être: 

- Repartie dans plusieurs pièces différentes
- Fonctionne avec les assistants vocaux (Google Home/Alexa)
- Puisse être bien différencié sur le dashboard et les scènes

Cf: https://community.gladysassistant.com/t/affichage-des-noms-des-fonctionnalites-au-lieu-du-nom-des-devices-pour-certaines-integrations/6594/24?u=pierre-gilles

**Comment by atrovato** [comment]
Pour information, je viens de simuler cet appareil dans la version zigbee2mqtt en cours de test, les 3 switchs sont bien detectés.

@Pierre-Gilles ici on est sur une simple multiprise, par sûr qu'il soit important de gérer le multi-pièces ici.

**Comment by Pierre-Gilles** [comment]
@atrovato Plusieurs raisons de faire le split device à mon avis :

- Plus facile d'identifier chaque prise dans Gladys (car on affiche le nom du device et pas le nom de la feature a pas mal d'endroits, et cela par choix, cf le débat qu'on a eu sur le forum). 
- Même si c'est une simple multi-prise, ça t'empêche pas d'avoir quelque chose de branché qui est dans le salon techniquement, et dans la cuisine pour une autre lampe branchée sur la prise
- Si le device est pas splitté, l'appareil ne sera pas géré dans Google Home/Alexa, car Google Home ne gère qu'une seule feature "on/off" par device. On en a parlé sur le forum, les autres constructeurs/box domotique font aussi du split de device pour ce cas là.

**Comment by atrovato** [comment]
@Tolkyen 
mise à part la partie supplémentaire sur la gestion / split du device évoquée par @Pierre-Gilles ,
cette appareil devrait maintenant fonctionner avec la version de Gladys 4.7.x.

Peux-tu vérifier que ton Gladys est bien à jour ? Et que l'appareil est prise en charge ?

Merci :)

**Comment by Tolkyen** [comment]
Bonjour,

L'appareil est bien pris en compte. Par contre, lorsque l'on essaie
d'allumer une prise en particulier, seule la première est activée quelque
soit la prise sélectionnée. Par contre sous zigbee2mqtt, ça marche nickel.

**Comment by atrovato** [comment]
Merci pour le retour, je crois avoir une piste de correctif.

Peux-tu me dire si Gladys change l'état des autres prises lorsque tu allumes/éteints depuis zigbee2mqtt ?
Tu actionnes en dehors de Gladys, et tu vérifies l'état dans Gladys.

Merci.

**Comment by Tolkyen** [comment]
Je confirme que les changements d'états dans Zigbee2mqtt sont bien 
reportés dans Gladys

Le 27/11/2021 à 13:21, Alexandre Trovato a écrit :

**Comment by Tolkyen** [comment]
Hello,

Comment puis-je aider pour faire avancer la prise en charge de ce device
dans Gladys ?

**Comment by atrovato** [comment]
Il me semble que nous avions validé ce device avec une image docker de test.
Depuis la modification est en PR, donc en attente de revue afin d'être intégrée dans Gladys.
#1383

**Comment by Tolkyen** [comment]
Bonjour,

un retour sur la version 4.8 de Gladys concernant ce périphérique. Au niveau de l'interface, les boutons de chaque prise peut être activé de façon indépendante. Par contre, quelque soit le bouton activé, c'est toujours la première prise qui est actionnée.

**Comment by atrovato** [comment]
Oui en effet, ça n'a pas été intégré dans la 4.8.0, le problème était plus complexe que ça, et touchait plusieurs autre type d'appareils.
Un correctif est en cours de validation sur l'image docker `atrovato/gladys:zigbee2mqtt`, toujours sur la même PR https://github.com/GladysAssistant/Gladys/pull/1383

**Comment by Tolkyen** [comment]
Bonjour, 

un mot pour dire que la prise en charge de la multiprise fonctionne correctement depuis la version 4.8.4.
Merci pour tous
