### ISSUE TITLE
Zigbee2mqtt: Add device TS0012

### ISSUE THREAD

**Issue by Jac34** [GladysAssistant/Gladys#1339]
```
{
  "name": "0x60a423fffeb04b09",
  "external_id": "zigbee2mqtt:0x60a423fffeb04b09",
  "model": "TS0012",
  "features": [],
  "should_poll": false,
  "service_id": "d58469fe-54cd-4127-8c45-1826b588dcc6",
  "supported": false
}
```

**Comment by Jac34** [comment]
Bonjour,
J'ai acheté le modèle AVATTO – interrupteur de lumière intelligent sans fil Tuya Zigbee, avec/sans neutre, commande à 2 voies
pensant pouvoir l'intégrer dans Gladys V4 sous Zigbee2mqtt, malheureusement il n'est pas vu comme fonctionnel dans Gladys.
Merci !! si cela est possible de le gérer.

**Comment by Pierre-Gilles** [comment]
Pour information on a une PR en cours qui va permettre de contrôler presque n'importe quel appareil Zigbee2mqtt en détectant automatiquement les fonctionnalités présentes :) 

https://github.com/GladysAssistant/Gladys/pull/1302

**Comment by Pierre-Gilles** [comment]
I think this is already fixed by this PR: https://github.com/GladysAssistant/Gladys/pull/1302 that we already merged (not deployed yet, soon) :) 

Now we don't need anymore to declare device individually, they are automatically detected by Gladys 😎

@atrovato Do you confirm the PR integrated this device ?

**Comment by atrovato** [comment]
I feel quite confident with this, but I prefer to get more feedbacks on it.

**Comment by atrovato** [comment]
Bonjour @Jac34 ,
depuis toute récente version de Gladys 4.7.x
cet appareil devrait être pris en charge.

Peux-tu vérifier que ton instance de Gladys est bien à jour ? Et que ton appareil fonctionne ?

Merci :)
