### ISSUE TITLE
Zigbee2Mqtt - Add option keep_history when adding device

### ISSUE THREAD

**Issue by cicoub13** [GladysAssistant/Gladys#1344]
**Is your feature request related to a problem? Please describe.**
When adding a device in ZIgbee2Mqtt integration, add the option to "Don't keep history". Some devices are verbose about state (one state every 10 seconds) and it can fill the database very quickly.

By default, the option is set to true.

**Additional context**
https://community.gladysassistant.com/t/help-probleme-avec-lagregation/6630/28

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by cicoub13** [comment]
Not stale

**Comment by VonOx** [comment]
@cicoub13 is latest release fix this issue ?

**Comment by cicoub13** [comment]
Yes
