### ISSUE TITLE
[FRONT] Topics ordering on dashboard

### ISSUE THREAD

**Issue by zeppmg** [GladysAssistant/Gladys#1345]
**Describe the bug**
I'm unsure of the way the topics are displayed within a dashboard block ; it seems quite random.

**To Reproduce**
Block configuration : 
![configuration affichage capteurs](https://user-images.githubusercontent.com/57366230/139968029-3105e345-c12b-4b51-9f56-f4bfae7cc1f8.png)

Display : 
![affichage capteurs](https://user-images.githubusercontent.com/57366230/139968038-faeec009-df1b-41c1-9d5f-c2a351ec99ff.png)

**Expected behavior**
Topics ordering should be at least homogen, in case we can't chose it by ourselves.

**Your Gladys installation (please complete the following information):**
Raspberry Pi 3 with Gladys image, up to date.

**Comment by Pierre-Gilles** [comment]
Not stale
