### ISSUE TITLE
[FRONT] No unit for voltage topics

### ISSUE THREAD

**Issue by zeppmg** [GladysAssistant/Gladys#1346]
**Describe the bug**
Voltage measurements are shown without unit on dashboard.
![affichage capteurs](https://user-images.githubusercontent.com/57366230/139968228-5e808c3b-7848-4974-99fc-d4c17289f640.png)

**Expected behavior**
Units (V) should be displayed.

**Your Gladys installation (please complete the following information):**
Raspberry Pi 3 with Gladys image, up to date.

**Comment by atrovato** [comment]
Hi,
from which integration/service is your service from?

On my side, I have units for tamosta device:
![image](https://user-images.githubusercontent.com/1839717/143136179-a84fa37e-2305-46d7-8cc8-4c3b2d84ac0d.png)

**Comment by zeppmg** [comment]
The values come from a  bluetooth temperature sensor, through mqtt integration.
Anyway I can't see any voltage measurement in your screenshot 😉

**Comment by Pierre-Gilles** [comment]
@atrovato Indeed I guess there is no way to select the "Volt" unit in the MQTT integration (like we do for the temperature)

**Comment by zeppmg** [comment]
In fact there's an "average voltage" topic in the mqtt integration, but it seems not to be displayed with the appropriate unit.
![Screenshot_20211126-212026](https://user-images.githubusercontent.com/57366230/143626874-f11ee7e0-e2c8-4ce2-924f-873fb8c8e008.png)

**Comment by atrovato** [comment]
There is a mapping file for units,
but I think we can be more prcise.
Here a screenshot with missing units (I open à PR too)

![image](https://user-images.githubusercontent.com/1839717/143673276-d7b1a0df-c475-4ae8-9ac4-4534361540b9.png)

**Comment by Pierre-Gilles** [comment]
Merged in #1382
