### ISSUE TITLE
Zigbee2mqtt: Add device WRS-R02

### ISSUE THREAD

**Issue by sy-per** [GladysAssistant/Gladys#1347]
```
{
  "name": "0x54ef441000066335",
  "external_id": "zigbee2mqtt:0x54ef441000066335",
  "model": "WRS-R02",
  "features": [
    {
      "category": "battery",
      "type": "integer",
      "unit": "percent",
      "name": "Battery",
      "read_only": true,
      "has_feedback": false,
      "min": 0,
      "max": 100,
      "zigbeeField": "battery",
      "external_id": "zigbee2mqtt:0x54ef441000066335:battery:integer:battery",
      "selector": "zigbee2mqtt:0x54ef441000066335:battery:integer:battery"
    }
  ],
  "should_poll": false,
  "service_id": "15b0283c-7e91-4129-a1d1-ca7256a8b26a",
  "supported": false
}
```

**Comment by Pierre-Gilles** [comment]
I think this is already fixed by this PR: https://github.com/GladysAssistant/Gladys/pull/1302 that we already merged (not deployed yet, soon) :) 

Now we don't need anymore to declare device individually, they are automatically detected by Gladys 😎

@atrovato Do you confirm the PR integrated this device ?

**Comment by atrovato** [comment]
I feel quite confident with this, but I prefer to get more feedbacks on it.

But this device allow many button states, not all are managed:
`button_1_hold, button_1_release, button_1_single, button_1_double, button_1_triple, button_2_hold, button_2_release, button_2_single, button_2_double, button_2_triple, button_3_hold, button_3_release, button_3_single, button_3_double, button_3_triple, toggle_1`
