### ISSUE TITLE
Gladys Plus: Subscribe email not responsive at all

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1370]
The subscribe email received by Gladys Plus is not showing well (see scrollbar next to my arrow):

![image](https://user-images.githubusercontent.com/14235706/141998002-d057d867-8754-4d80-9552-08c8adfd4348.png)

**Comment by Pierre-Gilles** [comment]
Thanks for your feedback!

Which email client are you using? 

On my side, all emails are responsive, example on my phone right now: 

![IMG_39D5665F5467-1](https://user-images.githubusercontent.com/7365207/142879816-d47a288a-1e3f-4fb9-a2f6-b37b597e3953.jpeg)
