### ISSUE TITLE
Gladys Plus: Print 2FA enrollment code

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1371]
When creating an account on Gladys Plus, a 2FA enrollment is needed (great 👍).

I am using the application "Authy", which allow to synchronize the Android app and Windows app. In order to use my Windows App, usually websites shows the 2FA enrollment code that I can copy and paste.

For now, I need a camera to initialize the 2FA App.

![image](https://user-images.githubusercontent.com/14235706/141998841-f72d70c2-b23a-408d-aa88-95b1069f9829.png)

**Comment by VonOx** [comment]
There is already an issur in plus repository
https://github.com/GladysAssistant/gladys-gateway/issues/92

**Comment by LM1LC3N7** [comment]
Thanks, I am closing this one.
