### ISSUE TITLE
Zigbee2mqtt: Add device SP-EUC01

### ISSUE THREAD

**Issue by lesaintsgeosmois** [GladysAssistant/Gladys#1372]
```
{
  "name": "0x54ef44100028dccf",
  "external_id": "zigbee2mqtt:0x54ef44100028dccf",
  "model": "SP-EUC01",
  "features": [],
  "should_poll": false,
  "service_id": "5ee7d930-1f56-4fc3-ac79-2e81c0a30883",
  "supported": false
}
```

**Comment by atrovato** [comment]
This should be managed with Gladys v4.6.0, currently in test mode, but I prefer to get more feedbacks on it once new version is released.

**Comment by lesaintsgeosmois** [comment]
can i do anything to help you test ?

i am in V4.6

**Comment by atrovato** [comment]
Nice, so Zigbee2mqtt discover page doesn't recognize your device as a plug with switch features?

**Comment by lesaintsgeosmois** [comment]
zigbee2mqtt detect my device , and the button on/off is operationnal, 
gladys say not supported
![aqua](https://user-images.githubusercontent.com/94477818/142254724-a737a278-c1aa-4237-957c-62cd4ed99672.jpg)

power and energy is N/A
![aquara2](https://user-images.githubusercontent.com/94477818/142255048-85ac53d3-2995-48ef-8a5e-3c8622f521e4.jpg)

**Comment by atrovato** [comment]
Hummm....
Are you sure are using Gladys v4.6.0 dev version?
Can you screenshot the Gladys zigbee2mqtt discover page please?

You should not have the "scan" button on this page, this point ensure you are using the latest zigbee2mqtt discover mode.

**Comment by lesaintsgeosmois** [comment]
you are right, indeed this is not the dev version of gladys 4.
![zig](https://user-images.githubusercontent.com/94477818/142260944-1cf6e99a-7cb1-4c7e-8aab-1e08a6d79255.jpg)
6

you need the dev version for testing ?

**Comment by atrovato** [comment]
The new process for discover is on current dev version, which is currently tested by community, and we are waiting for feedbacks to promote it as next release.

2 options:
 - be patient
 - become a beta tester ;) 

I didn't find any topic on community forum about it, it looks like it is not officially in test (or I just didn't search with good words).

**Comment by atrovato** [comment]
I think I lie, there is not link with 4.6.0, it is only dev version.

**Comment by VonOx** [comment]
Yep there is no build for 4.6.0

Autodiscover feature is on gladys:dev tag ( docker)

**Comment by lesaintsgeosmois** [comment]
ok il have installed the dev version.
the sensor is detected 
il have add button and temperature on the dashboard. it s ok

as same as zigbee2mqtt, power and energy stay to N/A

**Comment by Pierre-Gilles** [comment]
Nice ! @atrovato I think I'm going to merge your PR with the "Update" button and then we can release all that (given the feedbacks, it seems to be working well)

**Comment by atrovato** [comment]
@Pierre-Gilles an unexpected behavior has been detected and mentionned on the forum according to the "new discovry process", and will be fixed with the "update" button.
A new (personal) docker is generated to test it.

**Comment by atrovato** [comment]
Hi @lesaintsgeosmois ,
your device should now managed with Gladys 4.7.x.

Can you check:
1. Gladys has been well updated?
2. your device is well detected?

Thank you.
