### ISSUE TITLE
Poll don't stop even if you set should_poll to false

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#1373]
**Describe the bug**
If I set a device with should_poll to true with a given poll_frequency, and then I decide to update it with should_poll to false, the polling don't stop until you restart Gladys (or service maybe?)

**Expected behavior**
I would expect the poll stop once you update the device with should_poll = false

**Comment by Pierre-Gilles** [comment]
Indeed, it seems the code doesn't remove the device from the poll list if the should_poll switch to false

cf: https://github.com/GladysAssistant/Gladys/blob/master/server/lib/device/device.create.js#L156

**Comment by Pierre-Gilles** [comment]
Not stale
