### ISSUE TITLE
Openwrt support

### ISSUE THREAD

**Issue by ANARHIST1984** [GladysAssistant/Gladys#1377]
Its possible to install GladysAssistant on Openwrt router?
Router CPU 880mhz x2
512Mb RAM

Node and npm work fine. 
But when I try to install GladysAssistant server part, I have this
npm http fetch GET 200 https://registry.npmjs.org/@gladysassistant/gladys-gateway-js/-/gladys-gateway-js-3.5.0.tgz 19419ms
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/dayjs-3f33bdbe/locale/be.js'
npm http fetch GET 200 https://registry.npmjs.org/chai/-/chai-4.2.0.tgz 27716ms
npm http fetch GET 200 https://registry.npmjs.org/p-locate/-/p-locate-5.0.0.tgz 17331ms
npm http fetch GET 200 https://registry.npmjs.org/locate-path/-/locate-path-6.0.0.tgz 17368ms
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/dayjs-3f33bdbe/locale/bg.js'
npm http fetch GET 200 https://registry.npmjs.org/find-up/-/find-up-5.0.0.tgz 18309ms
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/dayjs-3f33bdbe/locale/bi.js'
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/chai-2d4d0079/CODE_OF_CONDUCT.md'
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/chai-2d4d0079/CODEOWNERS'
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/dayjs-3f33bdbe/locale/bm.js'
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/chai-2d4d0079/CONTRIBUTING.md'
npm WARN tar ENOENT: no such file or directory, open '/root/v4.6.0/server/node_modules/.staging/zlibjs-cb1aada2/bin/inflate_stream.min.js'
npm http fetch GET 200 https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz 18301ms

As far as I understand, it is necessary to build an application on big brother. 
But my knowledge is limited and I can't do it.
In the future expect add Gladys Assistant on Openwrt?

**Comment by ANARHIST1984** [comment]
router have Mips CPU MT7621

**Comment by Pierre-Gilles** [comment]
Hey! So far we don't support distribution outside of the Docker image we distribute (https://gladysassistant.com/docs/installation/docker)

I don't think we want to support that kind of device in the future (880mhz CPU & 512mb in RAM seems super light...)

But if you manage to make it work, let us know 😄 

We use Github issues for bug tracking, if you want to talk about this, we have a forum: https://community.gladysassistant.com/c/international/45

Thanks for your feedback!
