### ISSUE TITLE
The Zigbee2mqtt service should be able to be restored from a backup

### ISSUE THREAD

**Issue by cicoub13** [GladysAssistant/Gladys#1378]
**Is your feature request related to a problem? Please describe.**
When you restore a Backup on a new instance, you need to reconfigure your Zigbee network.

**Describe the solution you'd like**

We should save the network key `network_key`, Zigbee channel `channel` or panID `pan_id` in database as Service values and be sure the **configuration.yaml** is initialized with these values.

**Additional context**

Documentation here could help : https://www.zigbee2mqtt.io/guide/faq/#how-do-i-move-my-zigbee2mqtt-instance-to-a-different-environment

**Comment by Pierre-Gilles** [comment]
Is it related to Gladys Plus or is it a todo in the Zigbee2mqtt integration? :)

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by LM1LC3N7** [comment]
This issue is important as recreating a zigbee network if forcing the user to re-pair all its devices. I have at least 2 devices per room, it will take some time to do this.

**Comment by Pierre-Gilles** [comment]
I agree, but I think the issue title is misleading, it's not related at all to Gladys plus, it's a pure Zigbee2mqtt service development

**Comment by LM1LC3N7** [comment]
Because the service should store secrets and configuration into gladys DB and replicate it into the file setting at startup / restore?
If yes, we have to think about people trying to update their zigbee2mqtt settings manually on the file, how do we update these data on Gladys (as there is no advanced config in the web ui)?

**Comment by cicoub13** [comment]
We should save the network key `network_key`, Zigbee channel `channel` or panID `pan_id` in database as Service values and be sure the **configuration.yaml** is initialized with these values.
In case of Backup restore, the **configuration.yaml** will be created with the same values, and it doesn't require repairing.

https://www.zigbee2mqtt.io/guide/faq/#requires-repairing

**Comment by Pierre-Gilles** [comment]
Agree! :)

**Comment by atrovato** [comment]
@cicoub13 @Pierre-Gilles 
Why don't we create the z2m container with `network_key` / `channel` / `pan_id` hardcoded values?

https://www.zigbee2mqtt.io/guide/configuration/zigbee-network.html#network-config

**Comment by Pierre-Gilles** [comment]
@atrovato the network_key should be uniquely generated on the user side, because it's used for security (it's like an encryption key) ! 

If we hardcode the value, it means all Gladys users use the same key, and can be hacked easily :) 

We need to generate & save somewhere in Gladys DB those variables, so Gladys can restart the container with the proper keys in can the user restore Gladys somewhere else

**Comment by VonOx** [comment]
For reference => https://www.zigbee2mqtt.io/guide/faq/#how-do-i-move-my-zigbee2mqtt-instance-to-a-different-environment

**Comment by atrovato** [comment]
I think we should, on z2m container creation:
1. if no params in BD, store the network key (`network_key`), Zigbee channel (`channel`) or panID (`pan_id`) from `configuration.yaml` to Gladys DB (after container creation)
2. if params in DB, write values on `configuration.yaml` and restart container

**Comment by atrovato** [comment]
Personal PR: https://github.com/atrovato/Gladys/pull/47
Test docker image : `atrovato/gladys:zigbee2mqtt`

**Comment by atrovato** [comment]
I get some feedbacks from testers, a new build has been generated.

**Comment by atrovato** [comment]
PR is pending, validated by the community.

**Comment by ghost** [comment]
Soo... what's happening here? :D

**Comment by atrovato** [comment]
Feature has been validated by the community.
We are now checking and reviewing the code.

**Comment by atrovato** [comment]
PR still pending!
