### ISSUE TITLE
Configuration: add a folder in Gladys installation to store service specific files (e.g. logs, configuration...)

### ISSUE THREAD

**Issue by rpochet** [GladysAssistant/Gladys#1390]
**Is your feature request related to a problem? Please describe.**
In the context of the ZWave service development, I would like to store zwavejs log files and network backup file in a folder available from server hosting docker gladys image, e.g. /var/lib/gladysassistant/services/zwavejs/). Currently, folder is within node_modules folder and could be deleted during docker image update.

**Describe the solution you'd like**
Add a config inside Gladys/server/config/config.js:
<env>.servicesFolder: (service) => `./gladys-services/${service}`,
production.servicesFolder: (service) => `${process.env.SERVICES_FOLDER || '/var/lib/gladysassistant/services'}/${service}`,

**Describe alternatives you've considered**
Use serviceId instead of service name.

**Additional context**
Network backup file could be used to debug issues, migration...

**Comment by Pierre-Gilles** [comment]
@rpochet We already do this for some integration like Zigbee2mqtt !

Why not use a folder like /var/lib/gladysassistant/zwave ?

**Comment by rpochet** [comment]
Indeed, why not /var/lib/gladysassistant/zwave... Just to confirm the feasibility and side-effect (e.g. backup). Is serviceId vs name a better solution?

**Comment by Pierre-Gilles** [comment]
"name" is a better option! I definitely recommend `/var/lib/gladysassistant/zwave` ! 

I would recommend using this folder as something that is not critical if deleted (not present on a new installation)

For important data, use the database.

Here if it's just logs/network files, I guess when using the DB on a new installation, ZwaveJs can just re-create those files right?

**Comment by rpochet** [comment]
OK for /var/lib/gladysassistant/zwave.

Ps: yes, a new installation can just re-create those files (network start-up is a very heavy slow process and requires to wake-up sleeping devices, so network file is very useful). Is "/var/lib/gladysassistant" part of the backup ?

**Comment by Pierre-Gilles** [comment]
No, in Gladys backups we just backup the database file. 

All services should re-create files created in /var/lib/gladysassistant at startup if not present :)

**Comment by rpochet** [comment]
Currently, network file is stored inside folder server/services/zwave/node_modules. I suppose this folder is recreated in each release, so network file should be recreate. Not having network file in backup, could have impact on user experience. This should be tested in real life

**Comment by Pierre-Gilles** [comment]
Ok so it's even worse now! 

I guess it's ok (and even, could be beneficial) if the network file is re-created when you restore to a new instance (not something people do every day). At least you don't bring potential bugs to a new instance, if it's something that don't store critical data

It definitely should be tested!

**Comment by atrovato** [comment]
@rpochet I would suggest to split this feature out of your ZWave feature.
To review it easily, and to not mix features in PRs.
