### ISSUE TITLE
Settings > Tasks: print only the last 100 elements (too slow)

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1397]
On Gladys Plus and my local Gladys instance, the "tasks" menu is very slow as there is way to elements. On Gladys Plus they never loads (too long). On my local instance, I need to wait 10 seconds at least.

A potential solution could be to load only the last 100 elements and to use a pagination at the bottom.

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by Pierre-Gilles** [comment]
Fixed in https://github.com/GladysAssistant/Gladys/pull/1453
