### ISSUE TITLE
[Gladys Plus] Backup job should show status

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1398]
**Is your feature request related to a problem? Please describe.**
On Gladys Plus, when starting a new backup by clicking on the button, there is no message regarding the current status of the backup job.

**Describe the solution you'd like**
* A message for "Exporting database"
* Another for "Compressing database"
* Another again for "uploading backup to Gladys plus", with a percentage

As my personnal database is almost 2Gb, it is something that is good to know as it takes a long time.

**Describe alternatives you've considered**
* At least a persistent message showing the backup is currently running, even after a refresh of the webpage.

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by Terdious** [comment]
Not stale

**Comment by Pierre-Gilles** [comment]
Done in Gladys Assistant v4.8.6 

https://github.com/GladysAssistant/Gladys/releases/tag/v4.8.6
