### ISSUE TITLE
Birthdate bug on registration

### ISSUE THREAD

**Issue by Lesterpig** [GladysAssistant/Gladys#14]
Cannot register myself using the form (birthdate bug):

```
 [{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid","model":"User","invalidAttributes":{"birthdate":[{"rule":"date","message":"`undefined` should be a date (instead of \"01/01/01\", which is a string)"}]}}] 
```

**Comment by Pierre-Gilles** [comment]
The date should be in the "DD/MM/YYYY" format! 

If you are on chrome there is a datetime picker box which should appear.

But you are right, the message is ugly for the user, I add this to my bug list, thx for your feedback :)

**Comment by Lesterpig** [comment]
Thx for the quick reply :-)
Even with this format, it did not work using Firefox (and no date picker).
Fixed the bug by modifying the session controler,  but not really pleasant ;(

Btw, good work! Still need a lot more, I will probably contribute in the next weeks!

**Comment by Pierre-Gilles** [comment]
Hum.. Some people have troubles too with email validation, that's very weird maybe sails validator isn't working well... I'm going to investigate :)

Great ! If you want to contribute, there are two ways : 
- If you want to implement a new functionality, create a Gladys module ( check the website for how to build a module )
- If you want to simply correct something, or improve the Gladys core, just make a pull request :)

**Comment by ghost** [comment]
même probléme avec la date de naissance impossble de passer l'enregistrement utilisateur :

J'utlise firefox pas de chrome; comment je passe ce formulaire d'inscrption ?

j'ai essayer ces format ça passe pas : 

01012001
01/01/2001

ça passe pas  ????

**Comment by Lesterpig** [comment]
Si besoin, je pourrai proposer un fix prochainement !

**Comment by Pierre-Gilles** [comment]
Petite question, l'interface que tu as es en anglais ou français ? 

Est-ce que tu pourrais tester en utilisant un format de date anglais ? ( YYYY-MM-DD ). Je soupçonne sails de s'adapter à la langue.

**Comment by ghost** [comment]
Effectivement ça fonctionne avec la date à l'anglais sous fifrefox

**Comment by Pierre-Gilles** [comment]
Très bien, du coup ça n'est pas un bug alors, juste que sails.js s'adapte à la langue de l'utilisateur pour demander la langue dans le bon format :) Il faudrait juste le préciser à l'utilisateur, mais ça me rassure ça n'est pas un bug.

**Comment by Molkobain** [comment]
I'm reopening that question as I think we should do something more userfriendly. That is IMO a huge blocker when people want to try the application. Not having information about how to create a simple account might let people think that the software is not easy to use;

Are you saying, that the date format in the registration page is YYYY-MM-DD when the browser locale is set to en-EN and that it become DD/MM/YYYY when it is set to fr-FR ?

If so, I propose to create a new parameter in the config/locales/*.json, named "birthday-pattern". We should set its values to "YYYY-MM-DD" for en.json, "JJ/MM/AAAA" for fr.json (and appropriate variations for the others).
Finally we could update the registration form by adding a placeholder attribute to the birthdate input.

What do you think, should I do it and propose a PR ?

**Comment by Pierre-Gilles** [comment]
I definitely agree with you ! That's what I was planning to do but with all the little things I have to fix everywhere, I didn't do it.. 

Don't hesitate to propose a PR :) 

Thanks for proposing !

**Comment by Molkobain** [comment]
Cool, I'll do it tomorrow then.
