### ISSUE TITLE
MQTT: Add the publication Topic sensor if the option "Is it a sensor?" is disabled

### ISSUE THREAD

**Issue by pioueo** [GladysAssistant/Gladys#1401]
When adding an MQTT device, when is the option "is this a sensor?" is disabled, only the Gladys order subscription topic is visible.
It would be nice to also see the publication topic of the sensor.

**Comment by Pierre-Gilles** [comment]
Not stale

**Comment by Pierre-Gilles** [comment]
Fixed in https://github.com/GladysAssistant/Gladys/pull/1449
