### ISSUE TITLE
Zigbee2mqtt: Add device E1746

### ISSUE THREAD

**Issue by Ericboust** [GladysAssistant/Gladys#1402]
```
{
  "name": "0x5c0272fffe6d678b",
  "model": "E1746",
  "external_id": "zigbee2mqtt:0x5c0272fffe6d678b",
  "features": [],
  "should_poll": false,
  "service_id": "7713f5c2-a65c-4d25-9bae-16ca69d3764f"
}
```

**Comment by Ericboust** [comment]
Il s'agit d'un repeater Zigbee IKEA voir [https://www.zigbee2mqtt.io/devices/E1746.html](url) et Gladys m'a gentiment demandé de vous communiquer le problème!
_L'appareil n'est pas encore géré, veuillez nous contacter pour nous aider à le connecter dans Gladys !_

**Comment by Pierre-Gilles** [comment]
Tu es en quelle version de Gladys ? "Paramètres" => "Systèmes" dans l'interface ?

**Comment by Ericboust** [comment]
Bonjour Pierre-Gilles,

Version v4.7.1.
Watchtower fait son boulot je pense.

C’est pas trop grave car c’est un repeater et je ne dois pas vraiment le contrôler mais Gladys m’a demandé de communiquer le bug.

Eric

Envoyé de mon iPhone

**Comment by Pierre-Gilles** [comment]
Merci pour ton retour alors, tu es bien dans la dernière version de Gladys ! :) 

Ce n'est pas un bug, juste que le périphérique n'est pas géré. 

Je laisse l'issue pour les développeurs de cette intégration.

**Comment by atrovato** [comment]
Ce device n'a qu'une seule feature `link_quality`.
https://www.zigbee2mqtt.io/devices/E1746.html

Une PR est prête pour intégrer cette feature dans le service zigbee2mqtt, mais nous n'avons pas de UI pour cela.
La reflexion nous avais mené a "devoir" changer de librairie d'icones.
https://community.gladysassistant.com/t/nouvelle-feature-signal-strength-ou-etat-de-la-connexion/6165/55
