### ISSUE TITLE
Why not to use zigbee-herdsman?

### ISSUE THREAD

**Issue by yaneony** [GladysAssistant/Gladys#1403]
I just wonder why not to use well established solution for ZigBee which is also used by home assistant integration?

https://github.com/koenkk/zigbee-herdsman

It has good API and already has wide range of devices.

**Comment by LM1LC3N7** [comment]
Hello,

Thank you for sharing, on my side I was not aware of this project.
Do you know the coverage difference with Z2M on the compatibility, dev speed and device support?

**Comment by yaneony** [comment]
I don't know the difference, but it's used by https://github.com/Koenkk/zigbee2mqtt and devices are listed here https://www.zigbee2mqtt.io/supported-devices/

**Comment by cicoub13** [comment]
We are using **zigbee2mqtt** container (and so library) to discuss with Zigbee devices and transform messages in MQTT.
This tool is based on **zigbee-herdsman** and has the same compatibility devices list.
https://github.com/GladysAssistant/Gladys/blob/master/server/services/zigbee2mqtt/docker/gladys-z2m-zigbee2mqtt-container.json
https://github.com/GladysAssistant/Gladys/blob/master/server/services/zigbee2mqtt/lib/installZ2mContainer.js

<img width="544" alt="CleanShot 2022-01-08 at 13 07 49@2x" src="https://user-images.githubusercontent.com/1773153/148643578-67d7bae8-9e98-48b6-b0f0-64a2a94c1341.png">

But some transformation needs to be done in the device object and message object to align with the Gladys Core abstract model (device/feature/value).
