### ISSUE TITLE
Erreur  User with telegram_user_id “xxxxxxxxxxx” not found

### ISSUE THREAD

**Issue by MazShaka** [GladysAssistant/Gladys#1414]
La synchronisation entre Gladys et Telegram ne se fait pas.
Vérification des logs: `docker logs gladys`
Message : User with telegram_user_id "xxxxxxxxxx" not found
Vérification de l'ID dans Telegram via `@userinfobot`
Vérification dans : `/var/lib/gladysassistant/gladys-production.db` de la table “t_user”
 L'ID “telegram_user_id” est différente de l'userinfobot.
 Elle 2 caractères ont été ajouté '.0'  ('xxxxxxxxxx.0') qui semble être ajouter lors du hand shake entre le bot et Telegram.

Echange détaillé dans le post [https://community.gladysassistant.com/t/echange-telegram-impossible/6769](url)

Merci

**Comment by Pierre-Gilles** [comment]
Hi! Sorry I didn't tell you, we speak exclusively in english on the Github.

I created an EN issue here: https://github.com/GladysAssistant/Gladys/issues/1413
