### ISSUE TITLE
Download link broken on website

### ISSUE THREAD

**Issue by alscheuring** [GladysAssistant/Gladys#1415]
This page:
https://gladysassistant.com/docs

Has this link:
https://gladysassistant.com/download/latest

which fails and ends up here:
https://download-latest.gladysassistant.workers.dev/

**Comment by Pierre-Gilles** [comment]
Interesting, is it still not working on your side?

It works fine for me.. 

What kind of error do you get?

**Comment by Pierre-Gilles** [comment]
Are you sure it was not a network issue on your side?

<img width="1161" alt="Screenshot 2022-01-17 at 09 54 24" src="https://user-images.githubusercontent.com/7365207/149738175-da5e314f-39c0-4ddd-9ebd-77313e604725.png">

I have no errors showing up

**Comment by atrovato** [comment]
Works fine on my side too...

**Comment by Pierre-Gilles** [comment]
No reply so closing this.
