### ISSUE TITLE
Tasmota: in "light" configuration, control the switch with the "chat" command 

### ISSUE THREAD

**Issue by pioueo** [GladysAssistant/Gladys#1422]
The command by the chat of the switching on and off of the light of a room has no effect on the Tasmota device configured in light 

![](https://gladys-assistant-community.b-cdn.net/uploads/default/original/2X/7/7ad84d2ee58a744b8be97d4a1b072945339cf056.png)

**Comment by atrovato** [comment]
You may have a little more information?
Is your tasmota device setup as a light?
Is this device working from dashboard actions?
