### ISSUE TITLE
Zigbee2mqtt: Add device S520567

### ISSUE THREAD

**Issue by svgaman** [GladysAssistant/Gladys#1424]
```
{
  "name": "voletbureau",
  "model": "S520567",
  "external_id": "zigbee2mqtt:voletbureau",
  "features": [],
  "should_poll": false,
  "service_id": "0ed5174f-c72b-4896-bea1-55949ec1509e"
}
```

**Comment by svgaman** [comment]
https://www.zigbee2mqtt.io/devices/S520567.html

**Comment by atrovato** [comment]
Still in discussion https://community.gladysassistant.com/t/gestion-des-volets-roulants/5693

**Comment by atrovato** [comment]
Still in discussion https://community.gladysassistant.com/t/gestion-des-volets-roulants/5693
