### ISSUE TITLE
Support for non-usb zigbee2mqtt adapters

### ISSUE THREAD

**Issue by Gibson-Ayden** [GladysAssistant/Gladys#1432]
**Is your feature request related to a problem? Please describe.**
When trying to setup my raspi hat Gladys is unable to use the serial device, even tho it has it as an option, its not selectable and will still ask you for a USB device

**Describe the solution you'd like**
Add the ability to use other adapters outside of strictly usb

![image](https://user-images.githubusercontent.com/77173178/153735411-06ad0c7f-5ead-4a55-879b-697979cc6b88.png)

**Comment by Pierre-Gilles** [comment]
Is your USB dongle compatible with Zigbee2mqtt?

**Comment by Gibson-Ayden** [comment]
I have the dongle found here https://shop.codm.de/automation/zigbee/33/zigbee-cc2652p2-raspberry-pi-module but it is of note its not USB and functions over Serial via the GPIO pins on the pi, its listed under the pi hat section here https://www.zigbee2mqtt.io/guide/adapters/#recommended as a supported device

**Comment by Gibson-Ayden** [comment]
I figured out the issue, I had an instance of Zigbee2Mqtt in the background, however I believe that setup should be more verbose about whether it can attach or not, if its in use etc

**Comment by Pierre-Gilles** [comment]
Ok, closing this issue then :)
