### ISSUE TITLE
[Feature Request] Add Voice with Coqui STT and TTS

### ISSUE THREAD

**Issue by JRMeyer** [GladysAssistant/Gladys#1433]
Hi there 👋 

Glad to see a cool project like Gladys is actively maintained! It seems currently there's no voice feature enabled, and I think @coqui-ai could be a nice option.

Gladys seems to be mostly written in JavaScript, so Coqui Speech-to-Text should work nicely:)

https://stt.readthedocs.io/en/latest/NodeJS-API.html 

There's also Text-to-Speech from Coqui (python-based) <https://github.com/coqui-ai/tts>

**Comment by Pierre-Gilles** [comment]
Hey 👋

Which languages are supported by Coqui ?

**Comment by JRMeyer** [comment]
salut @Pierre-Gilles -- the short answer is: "lots of languages"

You can see all STT languages here <https://coqui.ai/models>

and for TTS, the list is:

```
English
French
German
Spanish
Japanese
Dutch
Ukrainian
Mandarin Chinese
```
