### ISSUE TITLE
Zigbee2mqtt: Add device QS-Zigbee-C01

### ISSUE THREAD

**Issue by Ragnulf67** [GladysAssistant/Gladys#1436]
```
{
  "name": "0x847127fffe056627",
  "model": "QS-Zigbee-C01",
  "external_id": "zigbee2mqtt:0x847127fffe056627",
  "features": [],
  "should_poll": false,
  "service_id": "87266639-a6a3-454a-a04b-5bba938c27ec"
}
```

**Comment by Ragnulf67** [comment]
Hello, I Simply click on Button un Gladys to report QS-Zigbee-C01, who is a zigbee sonoff curtain module

**Comment by atrovato** [comment]
Gladys doesn't handle curtains for now (neither enum value - for moving actuator).
But it is somewhere in the pipe.

**Comment by Ragnulf67** [comment]
Ok merci du retour, je vais attendre que ça ce fasse :)
Très bon boulot, bravo à toute l'équipe.
