### ISSUE TITLE
See and use only the 10 first variables of "get device value" from a block in "send a message"

### ISSUE THREAD

**Issue by mikitouf** [GladysAssistant/Gladys#1437]
Hello 

When we use the variable in " send a message" we can see and use only the 10 first variables of "get device value" from a block ( X )
even if we write X.11 after {{
Futhermore if we use a second block of "get device value" we can't see it easily. We must write the number of the block to see the device

[link of the post in gladys community](https://community.gladysassistant.com/t/bug-scenes-recuperation-variable-limitee-a-10-donnees-sur-un-bloc-lors-de-lutilisation-dans-laction-envoyer-un-message/6971)

**Comment by Pierre-Gilles** [comment]
I'm able to reproduce, it's a parameter in the library we are using ! 

Fixing in : https://github.com/GladysAssistant/Gladys/pull/1438
