### ISSUE TITLE
Sonoff Zigbee2mqtt show up but cannot configured in docker version

### ISSUE THREAD

**Issue by help-14** [GladysAssistant/Gladys#1439]
**Describe the bug**
Hi, I'm using Gladys docker version in a Debian VM. I have passthrough Sonoff usb and it is show up on Gladys Zigbee2mqtt USB dongle Settings but it is still show "Gladys is not attached to any Zigbee2mqtt USB Dongle."

**Screenshots**
![image](https://user-images.githubusercontent.com/574357/154783737-4b797de8-40bc-4ac5-9e0c-c668cc1f8e08.png)
![image](https://user-images.githubusercontent.com/574357/154783745-40e18ac2-de81-438c-a962-530846f73105.png)
![image](https://user-images.githubusercontent.com/574357/154783787-c7abcd63-021b-4cbd-a185-7108ca31dc3c.png)

**Your Gladys installation (please complete the following information):**
- Docker / Debian

**Comment by help-14** [comment]
Okay for some reason Ubuntu 18 worked and not Ubuntu 21 or Debian 11.
But after enabled it throw some error and no mqtt image show up, no scan button.
No container for mqtt and zigbee2mqtt created

![image](https://user-images.githubusercontent.com/574357/154789699-0f926c82-875d-4036-a1fb-7d2ab316c56c.png)
![image](https://user-images.githubusercontent.com/574357/154787856-765b2844-b7f9-460b-a00a-fae6ba9f0638.png)
![image](https://user-images.githubusercontent.com/574357/154787877-7c502d33-f6ee-413e-b880-d1f4e6aa5502.png)

**Comment by Pierre-Gilles** [comment]
We currently only support Debian 10 and below, and Ubuntu 20.04 and below. 

Debian 11 and Ubuntu 21 are not supported because of a change on cgroups that affects code related to Docker inside Gladys.

We are working on developing support for those system :)

**Comment by help-14** [comment]
Hi @Pierre-Gilles .
Glad to know, but even in ubuntu 18 after press enable zigbee2mqtt my docker is still not have mqtt and zigbee container created. Any idea about it ?

**Comment by Pierre-Gilles** [comment]
Can you come on the forum and give us more details about what you are doing ? https://community.gladysassistant.com/c/international/configuration/46

We use Github only for bug tracking, we don't do support here.

I'm closing this issue :)
