### ISSUE TITLE
Update Scenario

### ISSUE THREAD

**Issue by geoffreyp** [GladysAssistant/Gladys#144]
To change action or a trigger in a scenario we need to delete it and create a new scenario, it will be great to update our scenario in the next release.

**Comment by geoffreyp** [comment]
I'm trying to work on this feature even if I am not an expert on sails and Angular ;)

**Comment by Lyreo** [comment]
+1 It could be really helpful and a feature to check all conditions with more details and not only "House ==1 and User ==1" as well.

**Comment by chatondearu** [comment]
Updating a scenario is the must have,  and if we can clone and update it can better ! :p

**Comment by Pierre-Gilles** [comment]
Added in last version of Gladys !
