### ISSUE TITLE
Z-Wave: Handle device "FIBARO System FGBS222 Smart Implant"

### ISSUE THREAD

**Issue by reivaxm** [GladysAssistant/Gladys#1441]
Hello,
Je suis en train de faire des tests de capteur dans Gladys basé sur du zwave et des smart implant de chez fibaro
J'en ai un qui a détecter un capteur

```
{
  "manufacturer": "FIBARO System",
  "manufacturerid": "0x010f",
  "product": "FGBS222 Smart Implant",
  "producttype": "0x0502",
  "productid": "0x1000",
  "classes": [
    "32",
    "48",
    "94",
    "112",
    "114",
    "115",
    "134"
  ]
}
```

L'autre qui ne detect aucun capteur

```
{
  "manufacturer": "FIBARO System",
  "manufacturerid": "0x010f",
  "product": "FGBS222 Smart Implant",
  "producttype": "0x0502",
  "productid": "0x1000",
  "classes": [
    "32",
    "112",
    "114"
  ]
}
```

Une idée du pourquoi ?

En tout cas superbe travail !
PS: j'utilise la carte Razberry v2 (https://www.planete-domotique.com/carte-d-extension-razberry2-v2-pour-raspberry-pi-version-europeenne-z-wave-me.html) ça marche dans Gladys mais il faut désactiver le bluetooth dans le fichier de boot sinon il y a un conflit pour l'accès à la carte

**Comment by Pierre-Gilles** [comment]
Salut @reivaxm ! Ces appareils ne doivent pas être géré par Gladys. Il faut développer la compatibilité.

Actuellement il y a le projet de quitter Open-Zwave (cette librairie est deprecated), pour passer à ZWaveJS (la nouvelle librairie moderne), donc je ne pense pas que la compatibilité pourra être développé sur l'intégration actuelle, mais pourra l'être sur la nouvelle.

Il y a une PR en cours ici : https://github.com/GladysAssistant/Gladys/pull/1342

SI tu veux venir en parler, le mieux est de venir sur le forum : https://community.gladysassistant.com/, c'est là bas qu'on échange. 

A très vite !
