### ISSUE TITLE
Z-Wave: Handle device "Everspring AD142 Plug-in Dimmer Module"

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#1489]
```
{
  "manufacturer": "Everspring",
  "manufacturerid": "0x0060",
  "product": "AD142 Plug-in Dimmer Module",
  "producttype": "0x0003",
  "productid": "0x0001",
  "classes": [
    "38",
    "39",
    "114",
    "115",
    "117",
    "134"
  ]
}
```

La prise n'est pas reconnue.

**Comment by atrovato** [comment]
Waiting for zwave "new age" docker image.

**Comment by atrovato** [comment]
Still waiting for new implentation of ZWave service.

**Comment by Pierre-Gilles** [comment]
Do we really need this issue? Current integration is going to be removed, and new integration will have nothing to do with the current one :)

**Comment by atrovato** [comment]
That was my first try on ZWave. I'm ok to close it, and wait for the new integration.
