### ISSUE TITLE
Cron Alarm not scheduled at startup of gladys

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#149]
Hello,

I've made test with cron alarm and when creating an alarm while gladys is up,it works fine.
But when you restart Gladys, previous cron alarm seems to be ignored.

When Gladys is up and I create an alarm, I see in the log the line "Scheduled alarm <name>, with id <id>".
While at startup, I don't see that log and alarm does not works.

**Comment by Pierre-Gilles** [comment]
completely right, thx for the feedback I'm on it :)
