### ISSUE TITLE
[FRONT] - On chart dashboard box, loading spinner when new value arrives is displayed too often

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1490]
![image](https://user-images.githubusercontent.com/1528694/160564127-4fea6f2c-7dc4-4619-90ca-32ed0242ddd9.png)

https://community.gladysassistant.com/t/graph-bug-refresh/7108

**Comment by atrovato** [comment]
What do you think about something like

![progress_bar](https://user-images.githubusercontent.com/1839717/166555219-a09c4a0b-d6b7-4dd0-9a5d-dfe5d40b23b2.gif)

instead of the big loading circle?

---

CSS:
```
.progress-bar {
  height: 4px;
  background-color: rgba(5, 114, 206, 0.2);
  width: 100%;
  overflow: hidden;
}

.progress-bar-value {
  width: 100%;
  height: 100%;
  background-color: rgb(5, 114, 206);
  animation: indeterminateAnimation 1s infinite linear;
  transform-origin: 0% 50%;
}

@keyframes indeterminateAnimation {
  0% {
    transform:  translateX(0) scaleX(0);
  }
  40% {
    transform:  translateX(0) scaleX(0.4);
  }
  100% {
    transform:  translateX(100%) scaleX(0.5);
  }
}
```

HTML added in box card element:
```
<div class="progress-bar">
    <div class="progress-bar-value"></div>
</div>
```

**Comment by atrovato** [comment]
@VonOx

**Comment by VonOx** [comment]
Yes it's better, less annoying and we keep informing that something happening.

**Comment by VonOx** [comment]
Not stale

**Comment by VonOx** [comment]
@atrovato tested your PR ( chromium 103.0.5060.134 ) 

![image](https://user-images.githubusercontent.com/1528694/182122165-6590f6cf-e427-4f68-961b-018ca31b5a0e.png)

Loader is fine except its persistant, even when no new value there is like a shadow at box bottom. A bit weird 

![image](https://user-images.githubusercontent.com/1528694/182122499-7136c806-bbd5-4ea4-bbec-11e037c55bbd.png)

**Comment by atrovato** [comment]
The blue background is problem. Thank you for your feedbacks.

**Comment by atrovato** [comment]
I pushed the transparent background, tell me if it's better. Thank you.
