### ISSUE TITLE
Cant change linux login password.

### ISSUE THREAD

**Issue by nielsnl68** [GladysAssistant/Gladys#1493]
First, are you sure that you found a Gladys bug?
Yes, with other distro's you can change your password.

**Describe the bug**
Cannot log in with default  username/password
When you do you are asked to change the password, but while doing that you get the errors: 
```
passwd: Authentication token manipulation error
passwd: password unchanged
```
and you need to login again.

**To Reproduce**
Just try to login via ssh or via a connected display/keyboard and enter the login details
after that you are requested to change the password (as it is mandatory)
Enter a new password and hit 'enter'.
And there you have it.

**Expected behavior**
That i can use my own pi as i want to by logging and install what ever i want, or change gladys to my own needs.
- Raspberry Pi installation (if yes, which Raspberry Pi ?)
RPi 3B+

- Manual installation: [MacOS/Windows/Linux?]
I just your distro

**Comment by Pierre-Gilles** [comment]
Thanks for your feedback! 

I tag @VonOx here who is working on the Gladys Raspberry Pi OS image :)

**Comment by VonOx** [comment]
Hi @nielsnl68 

Sorry for late reply.
That's seems to be a generic filesystem mount problem, can you try flash gladys image again?

**Comment by nielsnl68** [comment]
i have switched to an other HA
