### ISSUE TITLE
[Scene] Bad variable management when one variable id contains another id variable

### ISSUE THREAD

**Issue by cicoub13** [GladysAssistant/Gladys#1503]
**Describe the bug**
When you use the variable system in Scene (for example Send a message), if there are two variables with almost the same id, it creates an error.

For example, if you have these 2 variables:
-` 1. 1. data.main.temp`
-` 1. 1. data.main.temp_min`
 
And you fill text with "Hello {{ 1. 1. data.main.temp_min }}", the system will first replace `1. 1. data.main.temp` by a variable (and will let the `_min`) and so it's not the expected variable

**To Reproduce**
Create a scene where you fetch in HTTP `https://api.openweathermap.org/data/2.5/weather?lat=44.842680&lon=-0.586846&appid=KEY&lang=FR&units=metric`

**Screenshots**

![image](https://user-images.githubusercontent.com/1773153/163526315-f8bc55c2-2eae-42d1-a396-37e987275a28.png)
![image](https://user-images.githubusercontent.com/1773153/163526326-5c7321d1-9edb-46fa-86df-57e218aa4bf8.png)

**Your Gladys installation (please complete the following information):**

- Raspberry Pi 4 installation + SSD

**Comment by PhilippeMA** [comment]
Bonjour,

Je suis intéressé par ce correctif. S'il y a besoin d'aide pour faire des tests, je peux aider.

Philippe
