### ISSUE TITLE
Any ETA on Tuya integration?

### ISSUE THREAD

**Issue by ahmadalibaloch** [GladysAssistant/Gladys#1507]
Tuya devices are quite diverse and easily accessible from stores. I'd like to see integration with Tuya cloud platform.

**Comment by atrovato** [comment]
Work is in progress, please be patient ;)

**Comment by Pierre-Gilles** [comment]
I'm closing this as we don't use Github issues for feature requests (only for issues) :) 

Please use our forums for feature requests, we have a voting system on them :)

- [Our forum in french](https://community.gladysassistant.com/)
- [New: our forum in english](https://en-community.gladysassistant.com/)
