### ISSUE TITLE
Zigbee2MQTT: modify type of Aqara door & window contact sensor

### ISSUE THREAD

**Issue by William-De71** [GladysAssistant/Gladys#1512]
modification du type température du capteur d'ouverture de porte, pour ne pas être pris en compte dans la fonction température de la pièce

![image](https://user-images.githubusercontent.com/11477113/165932727-4dd7cfec-76a1-47b6-bd62-8a5464f06d6e.png)

https://community.gladysassistant.com/t/bug-widget-temperature-de-la-piece/6593/7

**Comment by atrovato** [comment]
De mon point de vue, le capteur XIAOMI MCCGQ11LM possède un capteur de température (voir https://github.com/Koenkk/zigbee2mqtt/issues/4680) qui n'est pas la température du matériel, mais bien la température de l'air.

**Comment by William-De71** [comment]
le problème c'est que j'ai plusieurs capteurs de ce type et aucun ne retourne une température correcte

**Comment by atrovato** [comment]
Il semblerait que tu puisses calibrer les capteurs depuis z2m selon https://www.zigbee2mqtt.io/devices/MCCGQ11LM.html

**Comment by William-De71** [comment]
ok je vais essayer

**Comment by William-De71** [comment]
La calibration fonctionne mais j'ai filtré pour ne plus envoyer la température du coup.
Je ferme l'issue

**Comment by alessandrowayne** [comment]
Hello, my Aqara sensors display temperature in Homekit using Z2Mqtt, but I want to hide this feature. How can I do it?

**Comment by William-De71** [comment]
Hello, You can set a filter in zigbee2mqtt interface.
Go to the setting of your sensor and add temperature in the filter attributes
![image](https://user-images.githubusercontent.com/11477113/168166433-d32b0d72-e409-4f17-b163-719e640c8a57.png)

**Comment by alessandrowayne** [comment]
Thanks for answering me! 
I did it, and in fact the MQTT Server does not update that value.
But in the Home App, they appears like another accessory. This influences the average temperature in the room
![a65a5d05-0e41-4367-925d-3e66c9665856](https://user-images.githubusercontent.com/105395603/168167887-e94a8767-2ebc-41e5-92ae-0e7599357e99.jpg)

**Comment by William-De71** [comment]
I'm sorry I don't know how is working your Home App, I can't help you anymore.

But maybe can you calibrate the temperature value to avoid your average problem?
In the settings (specific) you can add offset to the temperature value.
![image](https://user-images.githubusercontent.com/11477113/168169106-7c8f015e-c42d-4331-b2c0-a68025dbdd50.png)

**Comment by alessandrowayne** [comment]
It's the Apple Home App, don't know why it exposes this like another accessory. 
Spent 10hours in 2 days to find a solution, but can't find it.
