### ISSUE TITLE
Weather box: refresh data when user comes back to the current screen and left for more than 30 minutes

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1564]
If I leave one Gladys tab open for 1 night, when I come back, data is from the day before.

Could be nice to have an automatic refresh when I come back.

https://community.gladysassistant.com/t/live-youtube-lundi-20-juin-2022-a-20h30-pour-le-lancement-de-gladys-assistant-4-9/7377/18?u=pierre-gilles

**Comment by atrovato** [comment]
> Could be nice to have an automatic refresh when I come back.

Or maybe automatic refresh based on timer, every hours?

**Comment by Pierre-Gilles** [comment]
@atrovato It's already the case, but when a tab isn't used (computer in sleep mode), setInterval is disabled as well, so the user will only see the updated data XX minutes later after coming back

That's why we need another case: when coming back on the tab, check when was last refresh. If last refresh was before update interval, then refresh data

**Comment by Pierre-Gilles** [comment]
Cf: https://github.com/GladysAssistant/Gladys/blob/master/front/src/components/boxs/weather/WeatherBox.jsx#L222

**Comment by Pierre-Gilles** [comment]
Bug fixed in https://github.com/GladysAssistant/Gladys/releases/tag/v4.14.0
