### ISSUE TITLE
Chart sometimes displays lots of 0.00000 on the y axis

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1565]
![image (1)](https://user-images.githubusercontent.com/7365207/174805682-4b2ef41c-c489-42cc-8dc9-6595de1bd4ba.png)

https://community.gladysassistant.com/t/live-youtube-lundi-20-juin-2022-a-20h30-pour-le-lancement-de-gladys-assistant-4-9/7377/18?u=pierre-gilles

**Comment by Ericboust** [comment]
Hi,
I still have the problem in some cases.  I believe it's when i change the time frame from the standard "last 24U" to "last hour".  after that, the format with the 8 zero remain even if i come back to 24U. But it's strange that i have this only with one graph!  for this one, i remark that the value for the y axis remain high.  For the other one's the value for the Y axis in the  "last hour" format change to 0 to high value.
![24 u](https://user-images.githubusercontent.com/29695717/204590647-87f4da09-4427-4101-b827-8a9f01483a55.png)
![1 u](https://user-images.githubusercontent.com/29695717/204590741-b4b19611-11aa-4daf-afe1-d45902d74287.png)

**Comment by Pierre-Gilles** [comment]
Thanks for the feedback, it might be an error with the library we are using, but it's a bit hard to fix it because I'm unable to reproduce the bug :/ Random bug are hard :D

**Comment by Pierre-Gilles** [comment]
For reference, the lib we are using is https://github.com/apexcharts/apexcharts.js

It has 212 open issues currently

**Comment by atrovato** [comment]
@Pierre-Gilles I think I reproduce it with demo data:

![image](https://user-images.githubusercontent.com/1839717/211073010-0925b3c3-8996-459e-9fe3-c148c644fb06.png)

I change a value to add decimal numbers (33 to 33.1100008 - demo.js line #2942).

It looks like the lib arranges axis to decimal value.

**Comment by atrovato** [comment]
According to open issues, I found these one:
 - https://github.com/apexcharts/apexcharts.js/issues/10
 - https://github.com/apexcharts/apexcharts.js/issues/779

There is many available options to limit decimals according to the documentation: https://apexcharts.com/docs/options/yaxis/ 

If I set `decimalsInFloat: 2` we will always see `.00` suffix, even if values have no decimal, and this will be the maximum of visible decimals.
In case of "precise values" for a device (between 0.000 and 0.003), we won't be able to see details:

I divide values by 1.000:
![image](https://user-images.githubusercontent.com/1839717/211077995-5a1ecefc-e573-4e2f-a4ed-98415c246931.png)

Without decimal option:
![image](https://user-images.githubusercontent.com/1839717/211078152-89642882-c8a7-44be-8ad5-e5a89f5f6036.png)

We don't manage all cases for now, and chart library upgrade don't fix the problem.

**Comment by Pierre-Gilles** [comment]
Thanks for investigating! So nothing to do on our side right?

**Comment by Pierre-Gilles** [comment]
Fixed by Gladys 4.45.0
