### ISSUE TITLE
Updating device in integration override customized values

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1573]
If you have Feature Name customized and you update the device, all customized value are override.

Before updating we need to check if current value ( like feature name ) is edited.

For devices with many feature this is very useful

**Comment by atrovato** [comment]
I'm on it, I will keep:
 - on features: name
 - on device: name, room
I don't think about any other, but let me know if I miss any.

**Comment by atrovato** [comment]
@VonOx did you try it?
I am generating an up-to-date image with this feature: `atrovato/gladys:merge-devices` (wait for 2 hours until now to get generated!)
