### ISSUE TITLE
Module volet roulant Schneider

### ISSUE THREAD

**Issue by VASNIER** [GladysAssistant/Gladys#1574]

**Comment by atrovato** [comment]
Bon j'avoue que la description n'est pas très complète.
On parle de zigbee2mqtt ?

**Comment by VASNIER** [comment]
Oui, sorry, il s’agit bien de zigbee2mqtt, avec le d’ongle USB SONOFF
Zigbee 3.0.
Merci

**Comment by VASNIER** [comment]
Il s’agit du device en PJ.
Encore merci pour ton aide. J’ai 5 modules à raccorder et à appairer.
Gérard

Le dim. 24 juil. 2022 à 14:59, Gérard VASNIER ***@***.***> a
écrit :

**Comment by VASNIER** [comment]
Sorry, j’ai oublié la pièce pièce jointe, la voilà

Le lun. 25 juil. 2022 à 16:00, Gérard VASNIER ***@***.***> a
écrit :

> Il s’agit du device en PJ.
> Encore merci pour ton aide. J’ai 5 modules à raccorder et à appairer.
> Gérard
>
> Le dim. 24 juil. 2022 à 14:59, Gérard VASNIER ***@***.***> a
> écrit :
>
>> Oui, sorry, il s’agit bien de zigbee2mqtt, avec le d’ongle USB SONOFF
>> Zigbee 3.0.
>> Merci
>>
>>
>> Le dim. 24 juil. 2022 à 14:50, Alexandre Trovato <

**Comment by atrovato** [comment]
En attente de fusion sur la branche master.

**Comment by VASNIER** [comment]
Bonjour Alexandre
C’est à dire ?

**Comment by atrovato** [comment]
L'intégration des "cover" (volet / rideau) est développée, en attente de revue et d'intégration sur la version officielle de Gladys.
La fonctionnalité a été validée par @VonOx (si je ne me trompe pas).

**Comment by VASNIER** [comment]
Ok, merci pour ton retour
As-tu une idée du délai pour l’Intégration z2mqtt dans Gladys plus?

**Comment by atrovato** [comment]
Non aucune, mais on peut demander à @Pierre-Gilles de jeter un œil à #1577 ;)

**Comment by VASNIER** [comment]
Super
Merci
Bon WE

**Comment by VonOx** [comment]
Je ferme cette issue en doublon avec #1541
