### ISSUE TITLE
Use of decimals in the "continue only if" block

### ISSUE THREAD

**Issue by vincentBesseau** [GladysAssistant/Gladys#1585]
This issue is related in this post :
https://community.gladysassistant.com/t/bloc-continuer-seulement-si-a-decimal/7471/3?u=spenceur

**Comment by vincentBesseau** [comment]
🤔

**Comment by Tolkyen** [comment]
🙏

**Comment by vincentBesseau** [comment]
@Pierre-Gilles why this issue is stale ?

**Comment by VonOx** [comment]
@vincentBesseau This is a automatic behavior if no activities, dont worry
