### ISSUE TITLE
Zigbee2mqtt: Add device QS-Zigbee-C03

### ISSUE THREAD

**Issue by Herbinchristophe** [GladysAssistant/Gladys#1588]
```
{
  "name": "0xa4c1389ec8829e30",
  "model": "QS-Zigbee-C03",
  "external_id": "zigbee2mqtt:0xa4c1389ec8829e30",
  "features": [],
  "should_poll": false,
  "service_id": "7f13241f-c428-4cca-b714-d0974ede0f84"
}
```

**Comment by Pierre-Gilles** [comment]
Is this a device to control shutters/curtains? If so, I guess it might be handled by this PR: https://github.com/GladysAssistant/Gladys/pull/1577

cc @atrovato

**Comment by atrovato** [comment]
This device is a cover, but with a "moving" feature (acting state OPEN / CLOSE or STOP) that can be used as feedback on the device... but this will be a "big" change on the integration code.

To explain, it provides 1 feature to act, and 1 feature to get state. 2 different z2m features for 1 Gladys device.
