### ISSUE TITLE
Redémarrage permanent de Gladys

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#159]
Bonjour,

J'ai suivi toute la procédure d'installation de Gladys, et j'ai pu accéder à son interface.
Or au bout de 2 minutes, l'interface devient inaccessible et je suis obligé de redémarrer la raspberry pi.

Auriez vous une solution à ce problème ?
Merci beaucoup

**Comment by Pierre-Gilles** [comment]
Bonjour,

Tu as quoi dans les logs ? 

lance : `pm2 logs gladys`

**Comment by ghost** [comment]
Bonjour, 

Merci de ta réponse, voilà le résultat

`[TAILING] Tailing last 10 lines for [gladys] process (change the value with --lines option)
/home/pi/.pm2/logs/gladys-out-0.log last 10 lines:
0|gladys   |  ____---___--___---___--___---___--___-__
0|gladys   |
0|gladys   | Server lifted in `/home/pi/gladys/node_modules/gladys`
0|gladys   | To see your app, visit http://localhost:8080
0|gladys   | To shut down Sails, press <CTRL> + C at any time.
0|gladys   |
0|gladys   |
0|gladys   | Gladys brain loaded with success !
0|gladys   | New version of Gladys available : 3.4.2
0|gladys   | New User connected : Vincent

/home/pi/.pm2/logs/gladys-error-0.log last 10 lines:
0|gladys   | User 1 subscribed to room everybody
0|gladys   | User 1 subscribed to his own room
0|gladys   | User 1 subscribed to room everybody
0|gladys   | User 1 subscribed to his own room
0|gladys   | User 1 subscribed to room everybody
0|gladys   | User 1 subscribed to his own room
0|gladys   | User 1 subscribed to room everybody
0|gladys   | User 1 subscribed to his own room
0|gladys   | User 1 subscribed to room everybody
0|gladys   | User 1 subscribed to his own room

[STREAMING] Now streaming realtime logs for [gladys] process
`

**Comment by Pierre-Gilles** [comment]
Tout m'a l'air bon ! Quand tu dis l'interface devient inaccessible, tu as une erreur 502 ? Gladys a crashé ? Qu'a tu comme indication ? Je n'ai jamais entendu ce problème.

Tu as quoi comme raspberry pi ?

**Comment by ghost** [comment]
Non j'ai une erreur d'accès du serveur... J'ai une rpi 3

![image](https://cloud.githubusercontent.com/assets/25695212/23723600/1826d30c-044a-11e7-885e-f9558005dcdc.png)

**Comment by Pierre-Gilles** [comment]
ah, c'est plus un problème de DNS en fait. Au lieu d'utiliser gladys.local, utilise l'IP du raspberry pi directement ( `ifconfig` sur le rasp )

**Comment by ghost** [comment]
Yes ! Ca marche ! Merci de ton aide, il faut bien utiliser l'ip de la pi ! A+

**Comment by Pierre-Gilles** [comment]
Top !
