### ISSUE TITLE
Gladys do not parse Tasmota SENSOR message correctly

### ISSUE THREAD

**Issue by barbudor** [GladysAssistant/Gladys#1590]
**Describe the bug**
hello 
I'm coming from Tasmota developer team as user @titou4307  as reported us that the DS18x20 temperature sensor is not reported in Gladys (https://github.com/arendst/Tasmota/discussions/16304#discussioncomment-3464385)

Tasmota is publishing on `tele/nameofdevice/SENSOR` the following payload:
```json
{"Time":"2022-08-24T19:09:29","DS18B20":{"Id":"3C6404577D30","Temperature":23.5},"ESP32":{"Temperature":46.1},"TempUnit":"C"}
```

I've looked at the code briefly and I feel that Gladys has 2 issues:
- It only looks for temperature provided by DHT11 and AM2301 and not from DS18B20
https://github.com/GladysAssistant/Gladys/blob/ce2142054d10b0006128242a4e0c84297dfafd8c/server/services/tasmota/lib/features/temperature.js#L9
- It seems that it expect the JSON for SENSOR to have a `StatusSNS` key which is wrong. The SENSOR message is exactly as abobe. `StatusSNS` is included on the response of `Status 8` and `Status 10`commands
https://github.com/GladysAssistant/Gladys/blob/ce2142054d10b0006128242a4e0c84297dfafd8c/server/services/tasmota/lib/mqtt/tasmota.mqtt.handleMessage.js#L17-L19

**To Reproduce**

1. Install Tasmota on an ESP device and configure it to work in Gladys & MQTT environment
2. Configure a DS18x20 in Tasmota

**Expected behavior**
As Tasmota is properly reporting the SENSOR message with a temperature sensor, the temperature should be reported in Gladys whatever is the sensor used.

**Screenshots**

**Your Gladys installation (please complete the following information):**

@titou4307please describe your Gladys installation

**Desktop (please complete the following information):**

**Additional context**

**Comment by titou4307** [comment]
Here the copy screen of the Tasmota : 

![Sans titre 1](https://user-images.githubusercontent.com/56826797/186506567-27df2517-0f70-4db3-9ca8-89b3b657172b.png)

My config is : 

Hardware : Pi4 8Go raspi os 64bit
Software : raspi os 64bit with docker and portainer

The solution home assistant is Gladys Assistant under a container docker
For to integrate MQTT péripherals it use mosquito MQTT Eclipse installed by Gladys directly (it create a new container (the broker)

I'm trying to connect a sonoff TH Origin THR320 with sensor DS18x20 
I have flashed this sonoff with tasmota with the online tools tasmota 

So after this the tasmota THR320 will communicate to Gladys (discover and the relay) but the sensor DS18x20 not appears....

In the client MQTT Explorer the message come into the broker but it seems not to Gladys...

**Comment by titou4307** [comment]
Just for confirm I have another container with Home Assistant
I have add the MQTT broker of Gladys

Just for the fun I have add another sensor DS18x20 at my Sonoff Tasmota (possible after reading doc of tasmota...)

Here the result : 

![Sans titre 2](https://user-images.githubusercontent.com/56826797/186530366-dbfed0ae-885d-4eae-ad7e-cad4e01c8c7d.png)

It confirm the diagnostic this is Gladys bug

**Comment by Pierre-Gilles** [comment]
Hi, thanks for your report! This has been fixed in https://github.com/GladysAssistant/Gladys/pull/1570, and I just merged it to master!

It should go live in the next version of Gladys :)
