### ISSUE TITLE
Z2M - No scan button on fresh install

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1592]
https://community.gladysassistant.com/t/config-mqtt-freebox-delta/6657/8?u=vonox
https://en-community.gladysassistant.com/t/scanning-for-new-devices-with-zigbee2mqtt/46?u=vonox

This is a big issue for new users, on fresh install, after z2m setup, no scan button. This obviously prevent adding new devices to Gladys.

EDIT: seems there is no button from https://github.com/GladysAssistant/Gladys/pull/1302 😄 We need to update documentation

**Comment by Pierre-Gilles** [comment]
Yes documentation needs to be updated! 

Closing this issue in favor of https://github.com/GladysAssistant/v4-website/issues/140
