### ISSUE TITLE
HTTP (POST) call bug when using a device last value

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1605]
Hello all!

When using the "HTTP Call Request" with a Body, the last value used it not parsed correctly and all brackets are sent with the request.

![image](https://user-images.githubusercontent.com/14235706/191924128-2534cfdc-ff3d-4e54-b671-340cb727ed2d.png)

When trying to execute the request (here the bug is visible) : 

![image](https://user-images.githubusercontent.com/14235706/191924173-596c71d2-80c3-4e98-a750-afedbee17de9.png)

The bug is that the value sent by Gladys contains `{{` and `.lastvalue`.

**Comment by LM1LC3N7** [comment]
Steps to reproduce:

1. Create a new scene
2. Step 1 : nothing. Step 2 : new HTTP Request
3. HTTP Request type `POST` with the following content

```
  {
    "expr": [
      "(18+19)/ 2"
    ],
    "precision": 3
  }
```

This involves an error **on saving** the scene and **on the result** so I can't use the API answer.

![image](https://user-images.githubusercontent.com/14235706/191938601-6117515a-aa78-45fa-b656-414f45dc9264.png)

**Comment by Pierre-Gilles** [comment]
OK I understood what was going on.

We were not parsing correctly arrays in response, object were fine.

I wrote a fix, and I tried it's perfectly usable, even with arrays.

In the meantime, you can switch to the string version of the Math.js API, this should be working fine:

<img width="678" alt="Screenshot 2022-09-29 at 16 53 18" src="https://user-images.githubusercontent.com/7365207/193001574-c8224c76-5137-4b81-8b17-16553f66aad8.png">

**Comment by LM1LC3N7** [comment]
Great to read!

Also, the red star should not be present next to "Headers", as this is not mandatory.

**Comment by Pierre-Gilles** [comment]
Indeed, I removed the red star on headers!
