### ISSUE TITLE
Device filtering kept on tab change but keyword not displayed

### ISSUE THREAD

**Issue by rpochet** [GladysAssistant/Gladys#1623]
First, are you sure that you found a Gladys bug?

If you are not sure, you can come discuss with us on [Gladys Community](http://community.gladysassistant.com/) 🙂

**Describe the bug**
When doing device filetring on integration screen, if we move tab and go back to device tab, devices are still filtered but search keyword is not displayed

**To Reproduce**

1. Go to device tab e.g. '/dashboard/integration/device/zigbee2mqtt'
2. Set a device filtering keyword, only filtered devices are shown
3. Go to setup tab e.g. '/dashboard/integration/device/zigbee2mqtt/setup'
4. Go back to device tab e.g. '/dashboard/integration/device/zigbee2mqtt'
5. Only filtered devices are shown but filtering keyword is empty

**Expected behavior**
Going back to device tab e.g. '/dashboard/integration/device/zigbee2mqtt' should either 
1. Display all devices
2. Display previously filtered devices with the previously device filtering keyword

**Screenshots**
![image](https://user-images.githubusercontent.com/5940493/196783020-7334205a-fb56-4ccc-b57a-3ea4dbc39dc5.png)
![image](https://user-images.githubusercontent.com/5940493/196783095-23289709-69e7-45bd-9658-c1bc98c3f202.png)
![image](https://user-images.githubusercontent.com/5940493/196783144-78711ee6-50be-4794-9a17-c5c6181efb76.png)
![image](https://user-images.githubusercontent.com/5940493/196783190-d5825537-7257-4b63-99bb-e3da6f92a025.png)

![image](https://user-images.githubusercontent.com/5940493/196783897-25c7e702-06ab-4b8d-bff8-f10d2c582426.png)

**Your Gladys installation (please complete the following information):**

- Intel NUC
- Debian docker

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome, IE
- Version: ???

**Additional context**

**Comment by atrovato** [comment]
I think we have this issue on all integration pages.

**Comment by atrovato** [comment]
The #1598 PR keeps the filter keyword value when we change page.
