### ISSUE TITLE
List of devices don't have a key and sometimes devices are merged when one is deleted

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1640]
<img width="792" alt="Screenshot 2022-11-01 at 18 34 31" src="https://user-images.githubusercontent.com/7365207/199224050-b83c983d-3ed1-4210-ad02-890303a455e6.png">

https://community.gladysassistant.com/t/bug-suppression-device-zigbee/7149/8?u=pierre-gilles

**Comment by atrovato** [comment]
I just see the code, the state is linked to the box, not to the device.
This will be not so simple to do.
We will have to store the "delete state" somewhere in the back, and provide it to front.

**Comment by Pierre-Gilles** [comment]
Mmm I'm not sure we are talking about the same thing

I'm talking about a preact frontend bug, we don't use a key={} attribute, so the component is not re-rendered and it causes some display issue :) 

Very simple bug to fix aha

**Comment by atrovato** [comment]
Ok, so we don't care to display the device after reloading the page, with no warning message?
The user can click on delete again...

**Comment by Pierre-Gilles** [comment]
Indeed I understand what you mean! It's not a big issue if the user re-click on delete again, but it's not very UX friendly not to display the warning again... Could be improved, but not top priority ^^
