### ISSUE TITLE
[FRONT] Z2M Discover tab must list only device discovered and with feature update

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#1655]
Devices already created in Discovered view are duplicate of Devices view.

With plenty of devices this is annoying and useless.

**Comment by atrovato** [comment]
Hi @VonOx, what do you mean with plenty? I'm thinking about filtering on front or back side.
If it takes too long to fetch list of devices, backend filter is better.

**Comment by VonOx** [comment]
All my devices :), this doesn't take so long to load.

![192 168 1 42_8012_dashboard_integration_device_zigbee2mqtt_discover](https://user-images.githubusercontent.com/1528694/207300641-159707c1-297d-4260-b206-374ee22584c0.png)
