### ISSUE TITLE
Scenaries : trigger doesn't work when OFF/0 value

### ISSUE THREAD

**Issue by PhilippeMA** [GladysAssistant/Gladys#1672]
I configured a MQTT fake device (switch) : 
![image](https://user-images.githubusercontent.com/25247304/207640856-99945ec4-3772-4994-b752-fe2c91bdd843.png)

In a scene, i use 2 triggers : 
* When device change value to "1"
* When device change value to "0"

Here, the settings : 
![image](https://user-images.githubusercontent.com/25247304/207641307-dc4c778a-e351-470d-8001-54063a25c961.png)

The trigger works fine when value pass from 0 to 1 but not work when value pass from 1 to 0.

**Comment by PhilippeMA** [comment]
Hello,

Ne voyant pas de retour à ce ticket, est-ce que c'est une mauvaise utilisation que je fais de Gladys ?

Merci pour votre aide.

**Comment by Pierre-Gilles** [comment]
Salut @PhilippeMA, le Github est beaucoup moins actif que le forum, on est seulement quelques un a y intervenir (la plupart des utilisateurs Gladys n'ont pas Github), et on s'en sert vraiment que pour tracker les bugs et développements en cours, on fait pas du support dessus par contre :)

J'ai testé ton soucis, et je n'arrive pas à le reproduire, le comportement marche bien chez moi. Cependant j'ai exactement la même configuration que toi, donc à voir ce qui ne va pas. 

Je te propose de basculer sur [le forum](https://community.gladysassistant.com/)
