### ISSUE TITLE
MQTT / Z2M containers should be started with --log-opt max-size=10m options

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1684]
https://community.gladysassistant.com/t/utilisation-du-disque-par-les-logs-mosquitto/7827

```
--log-driver json-file \
--log-opt max-size=10m \
```

**Comment by atrovato** [comment]
See https://github.com/GladysAssistant/Gladys/pull/1686

**Comment by Pierre-Gilles** [comment]
Fixed in https://github.com/GladysAssistant/Gladys/releases/tag/v4.16.0
