### ISSUE TITLE
Wrong SQL syntax in queries.getUserAtHomeAndNotSeenSince

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#169]
Hello,
There is an issue when multiple user in house in query **getUserAtHomeAndNotSeenSince** in **api/core/house/house.queries**

I think you should add line 56 **GROUP BY user.id** because with multiple users, the MAX(event.datetime) takes the max of any users, so when one user is at house and the other(s) have left, Gladys consider nobody's left home because the max return the user still in house.

**Comment by Pierre-Gilles** [comment]
Sorry for the (really late) reply, you're right! 

I'll correct that just after summer !
