### ISSUE TITLE
Philips Hue - Issue with state

### ISSUE THREAD

**Issue by kevin14389** [GladysAssistant/Gladys#1690]
I noticed on my dashboard that my Philips Hue lights retain the last state set directly from Gladys. 
For example, I put the light on red with Gladys. I change the color with the Android App Philips and I set the color to yellow. But on my Gladys dashboard, the red is still visible. The color is not correctly updating when I change de color with an external source. 
Same issue with  temperature and intensity I think (not sure at 100%, need to do some extra test). 

Working fine with the state ON or OFF (with a little delay).

**Comment by Pierre-Gilles** [comment]
Thanks for your feedback, I added some tags. If anyone here with Philips Hue could work on this?

**Comment by cicoub13** [comment]
Polling function is only managing Binary Feature (On/Off) here https://github.com/GladysAssistant/Gladys/blob/master/server/services/philips-hue/lib/light/light.poll.js#L15

**Comment by kevin14389** [comment]
Hello, 

Nobody to update and to fix this bug please ? :-)

**Comment by Pierre-Gilles** [comment]
Hey @cicoub13, I see that you made a commit on your repo, is there a PR to fix this? :)

**Comment by Pierre-Gilles** [comment]
Fixed in https://github.com/GladysAssistant/Gladys/pull/2071
