### ISSUE TITLE
Impossible to create an account

### ISSUE THREAD

**Issue by nimaen** [GladysAssistant/Gladys#17]
Hi, each time I try to create an account, I have the following error :

[{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid","model":"User","invalidAttributes":{"email":[{"rule":"email","message":"\"email\" validation rule failed for input: 'xxx.xxx@xxx.xx'"}]}}]

**Comment by Pierre-Gilles** [comment]
Your are not the only one with this strange bug, seems thats sails js validator isn't doing is job well.

A quick fix is to disable email verification ( in `api/models/User.js` disable line 37, remove `email : true` ),  but that's not the solution.

I'll try to find what's going out :)

**Comment by nimaen** [comment]
Hum right, i'll try to investigate using _node --debug_ :)
Thanks !

**Comment by Drillyus** [comment]
Hi , the error is that type should be 'email', so the correct model is:
email:{
        type:'email',
        required:true,
        unique:true
    }

**Comment by Pierre-Gilles** [comment]
Yep you are right, normally 

```
email: {
  type:'string', 
  email:true
}
```

 should work, but it seems that there is a bug with Anchor, the validator of sails.js ( https://github.com/balderdashy/sails/issues/3034 ), so I need to do it like you said, I'll change that :)

Thanks for the feedback !
