### ISSUE TITLE
"Go" instead of "GB" for the French version.

### ISSUE THREAD

**Issue by tlse-vins** [GladysAssistant/Gladys#1747]
**Describe the bug**
In Gladys when saving the DB there is GB, I know that GB (English) and Go (French) is the same thing but isn't it more meaningful for the French Go?

**To Reproduce**

1. Go to 'Paramètres'
2. Click on 'Sauvegardes'

**Expected behavior**
Replace GB by Go for the French version

**Screenshots**
![Capture d’écran save DB](https://user-images.githubusercontent.com/47563262/233588457-89bfc8ea-27ec-4877-8bf1-5b0c262f2ebf.jpg)

**Comment by Pierre-Gilles** [comment]
Done in https://github.com/GladysAssistant/Gladys/pull/1748
