### ISSUE TITLE
Zigbee2mqtt: Be able to select the USB key model to avoid crash

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1760]
On some models, Z2M crash when starting because it needs a custom config

We need to add a select box in Gladys so the user can select his USB key model

**Comment by atrovato** [comment]
I started it here https://github.com/atrovato/Gladys/pull/78

**Comment by Pierre-Gilles** [comment]
Very nice! Don't hesitate if you need help :)

**Comment by cicoub13** [comment]
I think this one can be closed thanks to @atrovato in #1769
