### ISSUE TITLE
Camera snapshots often display large band of pixels

### ISSUE THREAD

**Issue by bong101** [GladysAssistant/Gladys#1787]
**Describe the bug**
Probleme avec l'affichage de la camera dans un dashboard

**To Reproduce**
c'est aleatoire, mais je dirai que 50% des images sont comme celle-la
Aucun probleme avec vlc, par exemple

**Screenshots**
![ksnip_20230516-084654](https://github.com/GladysAssistant/Gladys/assets/16385819/e40eb190-3a8c-431c-ab06-4d7dcfff96dc)

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation on raspberry pi3

**Desktop (please complete the following information):**

- OS: [Linux Ubuntu 23.04]
- Browser [Firefox]

**Additional context**

**Comment by cailholm** [comment]
I've encountered the same problem. After searching, it appears that RTSP is acceded by default with UDP (which does not have error control). Just adding option " -rtsp_transport tcp" to the ffmpeg command line gives correct snapshots.

Example:

> ffmpeg -rtsp_transport tcp -i rtsp://192.168.0.72/stream2 -vframes 1 snapshot.jpg

(from https://stackoverflow.com/questions/34904548/how-to-grab-a-single-image-from-rtsp-stream-using-ffmpeg)

**Comment by Pierre-Gilles** [comment]
Thanks a lot @cailholm for your message, I've created a PR to add this setting to Gladys: 

https://github.com/GladysAssistant/Gladys/pull/2150

**Comment by cailholm** [comment]
Hi @Pierre-Gilles, I've just tested your correction but the current fix has not improved the snapshots. 
I've found that the "-rtsp_transport tcp" has to be placed **before** the -i argument, otherwise it is not effective...
So the test  in getImage.js would be :
  
>  // For rtsp protocol, add tcp transport to avoid green band of pixels)
> if (cameraUrlParam.value.includes('rtsp')) {
>           **args.unshift('-rtsp_transport', 'tcp');**
>     }

**Comment by cailholm** [comment]
With the last version 4.49.0 (Docker image), I have not any more pixels bands ... I don't understand why (upgrade of ffmpeg ?). So it seems that the code does not finally have to be changed. :)

**Comment by Pierre-Gilles** [comment]
@cailholm super weird! But at least if it works it's what matters :)

**Comment by cailholm** [comment]
I'm sorry, I spoke too soon. This is what I got this morning :
![image](https://github.com/user-attachments/assets/d46a2a07-434d-4deb-a2e7-9092d9dfb6fb)
I can make the pull request if you want.
