### ISSUE TITLE
On the dashboard, when moving the "devices" widget on top of the same widget, the content is not updated

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1817]
https://community.gladysassistant.com/t/bug-lors-du-deplacement-de-blocs-de-fonctionnalites/8222?u=pierre-gilles

**Comment by callemand** [comment]
PR : https://github.com/GladysAssistant/Gladys/pull/1822

**Comment by Pierre-Gilles** [comment]
Fixed in https://github.com/GladysAssistant/Gladys/pull/1838
