### ISSUE TITLE
Count des notifications 

### ISSUE THREAD

**Issue by ImChiip** [GladysAssistant/Gladys#183]
Bonjour , 
Le count des notifications a l'air de chier un peu dans la colle 

https://image.prntscr.com/image/av5qpHf4Sh_OWvEtfdDa7g.png

**Comment by Pierre-Gilles** [comment]
Hello! Il s'agit des notifications non-lues, c'est comme sur Facebook :) Donc le compte est bon!

Après on pourrait clarifier le message effectivement

**Comment by ImChiip** [comment]
Ah d'accord vu comme sa effectivement 
Je n'ai pas vu de boutton pour supprimé la notification ( celle de l'update de gladys) c'est voulu ?

**Comment by Pierre-Gilles** [comment]
C'est exactement comme ton onglet de notifications sur Facebook/twitter/LinkedIn, tu garde un historique de tes notifs!

**Comment by ImChiip** [comment]
J'adore supprimé mouhahaha 
Va falloir s'y faire :)
Merci pour toutes ses réponses
