### ISSUE TITLE
Installation de Gladys

### ISSUE THREAD

**Issue by Toadman13680** [GladysAssistant/Gladys#184]
Bonjour à tous, 
j'ai un problème lors de l'installation de Gladys sur mon Raspberry Pi 3...
Je commence par suivre les étapes sur ce lien : https://github.com/GladysProject/Gladys

Et j'ai des problèmes lors de la ligne 
npm install..

> [pi@maison ~/gladys]  npm install sails
> /
> > sails@0.12.13 preinstall /home/pi/gladys/node_modules/sails
> > node ./lib/preinstall_npmcheck.js
> 
> Sails.js Installation: Checking npm-version successful
> npm ERR! 404 Not Found
> npm ERR! 404
> npm ERR! 404 'sailshq/express' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it
> npm ERR! 404 It was specified as a dependency of 'sails'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, or http url, or git url.
> 
> npm ERR! System Linux 4.4.50-v7+
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "sails"
> npm ERR! cwd /home/pi/gladys
> npm ERR! node -v v0.10.29
> npm ERR! npm -v 1.4.21
> npm ERR! code E404
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/pi/gladys/npm-debug.log
> npm ERR! not ok code 0

Avez-vous déjà eu ce problème ?

Merci par avance.

Tony.

**Comment by Pierre-Gilles** [comment]
Ah, il faut que je test chez moi, je vais regarder ce soir!

En attendant, quel est ta version de Node ?

Pourquoi ne pas installer gladys directement avec l'image Raspbian toute prête ?

**Comment by Pierre-Gilles** [comment]
Sinon, si tu veux pas t'embêter, lance ça dans ton dossier `/home/pi` : 

```
curl -SLs https://raw.githubusercontent.com/GladysProject/gladys-update/master/update-gladys.sh | bash
```

C'est une version pré-buildée de Gladys. 
( attention, c'est buildé pour node v6 uniquement )

C'est le script d'update de Gladys en gros, il faut avoir quelques dépendances d'installées ( notamment pm2 )

**Comment by Toadman13680** [comment]
Pierre-Gilles,

Tout d'abord je tiens à te remercier pour ton travail que tu as fourni, il est énorme :)

En ce qui concerne ta première question, j'ai Raspbian installé de base sur mon Raspberry et j'ai domoticz et pas mal d'autres programmes qui tournent.. Donc c'est pour cela que j'ai préféré intégrer ton travail manuellement.

J'ai exécuté ta commande, cela m'a généré un fichier compressé puis ça a planté car il manque pm2 et gret. 
J'ai fait : 

> sudo npm install pm2
> sudo npm install gret

J'ai relancé ta commande 

Toujours problème de pm2 et gret introuvable...

....
....
```
./gladys/CHANGELOG.md

/home/pi/gladys/config/update.js:15
    updateScript: process.env.UPDATE_SCRIPT_PATH || `${__dirname}/../rpi-updat
                                                    ^
`include-all` attempted to `require(/home/pi/gladys/config/update.js)`, but an error occurred::
Details:SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/pi/gladys/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (native)
    at _recursivelyIncludeAll (/home/pi/gladys/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/home/pi/gladys/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/home/pi/gladys/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.aggregate (/home/pi/gladys/node_modules/include-all/index.js:101:10)
    at Array.loadOtherConfigFiles [as 0] (/home/pi/gladys/node_modules/sails/lib/hooks/moduleloader/index.js:247:22)
    at /home/pi/gladys/node_modules/sails/node_modules/async/lib/async.js:591:38
    at _arrayEach (/home/pi/gladys/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Object.async.auto (/home/pi/gladys/node_modules/sails/node_modules/async/lib/async.js:552:9)
    at Hook.loadUserConfig (/home/pi/gladys/node_modules/sails/lib/hooks/moduleloader/index.js:245:13)
    at Hook.wrapper [as loadUserConfig] (/home/pi/gladys/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Hook.loadModules (/home/pi/gladys/node_modules/sails/lib/hooks/userconfig/index.js:41:27)
    at Hook.wrapper [as loadModules] (/home/pi/gladys/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Array.async.auto.modules [as 0] (/home/pi/gladys/node_modules/sails/lib/hooks/index.js:79:27)
    at /home/pi/gladys/node_modules/sails/node_modules/async/lib/async.js:591:38
bash: ligne 46: grunt : commande introuvable
bash: ligne 49: pm2 : commande introuvable
```

**Comment by philz1** [comment]
Bonjour j'ai le même problème.

**Comment by Pierre-Gilles** [comment]
Hello @Toadman13680, visiblement au vu de ton erreur tu n'es pas en Node v6 comme j'ai dis! :) 

pour voir ta version de Node.js, tape: 

```
node -v
``` 

Ta version doit être >= 6.0.0. 

Pour mettre à jour en Node 6, fais : 

```
wget https://nodejs.org/dist/v6.11.1/node-v6.11.1-linux-armv6l.tar.xz
tar -xvf node-v6.11.1-linux-armv6l.tar.xz
cd node-v6.11.1-linux-armv6l
sudo cp -R * /usr/local/
```

Pour installer pm2 et grunt, fais:

```
sudo npm install -g pm2 grunt
```

Ensuite, inspire toi de ce script d'installation : 

https://github.com/GladysProject/Gladys/blob/master/rpi-install.sh

Regarde ligne par ligne ce que ce script fait, et installe ce dont tu as besoin :)

**Comment by Pierre-Gilles** [comment]
Par ailleurs, pour ce genre de problème, Github n'est pas l'endroit ! 

Les issues Github sont là pour reporter les bugs dans Gladys :) 

Pour le support sur l'installation, le mieux reste le forum Gladys => https://community.gladysproject.com/

**Comment by Toadman13680** [comment]
Pierre-Gilles,
J'étais en version 0.19 -_-
Là je viens de mettre à jour via tes lignes de commande et maintenant tout marche, je te remercie :)
