### ISSUE TITLE
Zigbee2mqtt: Add link to Zigbee2Mqtt instance in UI

### ISSUE THREAD

**Issue by cce66** [GladysAssistant/Gladys#1893]
[cce66](https://community.gladysassistant.com/u/cce66)
[10h](https://community.gladysassistant.com/t/zigbee2mqtt-capteur-desactive/7156/8?u=cce66)

oui c’est cela http://adresse IP:8080/#/
[@pierre-gilles](https://community.gladysassistant.com/u/pierre-gilles)
ce serait bien en terme d’ergonomie et de convivialité d’ajouter le lien http://adresse IP:8080/#/
comme l’a fait [@Lokkye](https://community.gladysassistant.com/u/lokkye) pour l’accès Node-Red (il y a des paramètres plus complets) car on se souvient pas forcement du comment y acceder surtout pendant l’été :partying_face: :wine_glass:

![image](https://github.com/GladysAssistant/Gladys/assets/87046877/dca98f8d-7aec-4df9-8797-5f23d25a3ff7)

**Comment by cicoub13** [comment]
@callemand Can you explain how you obtain the IP ? I watched into Gladys server side and found nothing.

**Comment by cce66** [comment]
http://adresse IP:8080/#/
http://127.0.0.1:8080/#/

**Comment by Pierre-Gilles** [comment]
@cicoub13 Here is it in the PR : https://github.com/GladysAssistant/Gladys/blob/a10436b10a62ba697dec05daf3b01ce0e884b53a/front/src/routes/integration/all/node-red/setup-page/SetupTab.jsx#L28
