### ISSUE TITLE
Bug in search functionality for MQTT integration

### ISSUE THREAD

**Issue by quentinlegay** [GladysAssistant/Gladys#1921]
No results for some features even though they are present in the drop-down list. Some results can only be found with the English value of the feature or category.

More infos here : https://community.gladysassistant.com/t/bug-dans-recherche-fonctionnalite-sur-l-integration-mqtt/8441

**Comment by Pierre-Gilles** [comment]
Investigated: https://community.gladysassistant.com/t/bug-dans-recherche-fonctionnalite-sur-l-integration-mqtt/8441/3?u=pierre-gilles
