### ISSUE TITLE
Plusieurs utilisateurs

### ISSUE THREAD

**Issue by pjap93** [GladysAssistant/Gladys#194]
bonsoir,
Est ce qu'il n'y aurai pas un bug lors de l'utilisation avec plusieurs utilisateurs ?

Lors de l'utilisation dans un scénario "va se coucher" défini avec des actions distinctes l'une de l'autre pour chaque utilisateur, alors toutes les actions sont activées quand un scénario est activé y compris celles définies pour les autres utilisateurs.

c'est un bug ou c'est un problème chez moi ??

Merci

**Comment by Pierre-Gilles** [comment]
Ah.. il faut que je regarde! Par curiosité, comment dis tu à Gladys que tu vas te coucher ? Textuellement ?

**Comment by pjap93** [comment]
salut,
J'envoie mes commandes en format GET depuis mon téléphone avec MacroDroid.

En fouillant un peu, j'ai trouvé le problème et la solution en même temps.
Le problème est aussi présent quand on paramètre le scénario "Réveil".

Le problème c'est que pour ces 2 scénarios on défini pas la Maison et l'Utilisateur comme pour le scénario Retour ou Départ.
Quand j'ai ajouter dans la table "launcherparam" les 2 paramètres pour les 2 modes, cela marche maintenant correctement.
 
Je vais essayer d'envoyer un PR si cette fois-ci Travis veut bien l'accepté.

A+

**Comment by pjap93** [comment]
Bonjour,
La correction est envoyé dans Gladys-data, ainsi que l’ajout de la fonction « Si Maison non vide » sur Gladys où j’ai eu un peu de difficulté à comprendre le fonctionnement avec Travis :-)

A+

**Comment by Pierre-Gilles** [comment]
Effectivement! Thx ! 

Je ne pourrais pas corriger ça maintenant (je pars en vacances ce soir!), mais je ferais ça à mon retour :)

**Comment by Lyreo** [comment]
Oui, je l'ai constaté aussi :)

**Comment by Pierre-Gilles** [comment]
Corrigé !
