### ISSUE TITLE
[SONOS] Add support Era serie (100 & 300)

### ISSUE THREAD

**Issue by Terdious** [GladysAssistant/Gladys#1994]
Following a nice Christmas present (1 Roam, 2 ERA 100 and 1 ERA 300) I was able to test Sonos in Gladys ... at the top.
Unfortunately, only Roam is currently working.

So I ask the possibility of adding the ERA range to Sonos integration.
Once Netatmo was released, I could see if I can take care of it ^^ But I put it there for the record ^^

They appear well, I can add them but the commands and info feedback does not work!
The stage action "Talking on an enclosure" does not work either, no worries on the side of the Roam

**Comment by Pierre-Gilles** [comment]
This is more an issue for the library we use, I'm not sure it makes sense to keep this issue in Gladys as we can't do anything about it :)
