### ISSUE TITLE
impossible to launch (impossible de le lancer)

### ISSUE THREAD

**Issue by nobodyjoh** [GladysAssistant/Gladys#2]
Bonjour,

petit problème pour moi, impossible de le faire tourner, le npm install n'installe jamais tout même si j'utilise le npm install -g node-gyp et que j'installe sudo apt-get install libasound2-dev, et j'ai installé à la main sails-util-mvcsloader qui ne s'installait pas via le package.json

Une idée?

Erreur ramené par le node app.js   

info: User hook policies loaded from /root/gladys2.0/api/hooks/example/policies.
info: User hook config loaded from /root/gladys2.0/api/hooks/example/config.
error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 30000)
    at tooLong [as _onTimeout] (/root/gladys2.0/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15) { [Error: The hook`orm`is taking too long to load.
Make sure it is triggering its`initialize()`callback, or else set`sails.config.orm._hookTimeout to a higher value (currently 30000)] code: 'E_HOOK_TIMEOUT' }
error: Grunt :: module.js:340
    throw err;
          ^
Error: Cannot find module 'grunt-cli/bin/grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/gladys2.0/node_modules/sails/lib/hooks/grunt/grunt-wrapper.js:10:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
info: User hook models loaded from /root/gladys2.0/api/hooks/example/lib/../models.
error: [ { [Error: ENOENT, lstat '/root/gladys2.0/api/hooks/example/assets']
    errno: 34,
    code: 'ENOENT',
    path: '/root/gladys2.0/api/hooks/example/assets' } ]
error: A hook (`example`) failed to load!

/root/gladys2.0/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /root/gladys2.0/node_modules/async/lib/async.js:30:31
    at process._tickDomainCallback (node.js:463:13)

**Comment by Pierre-Gilles** [comment]
I think the error is pretty explicit "Cannot find module 'grunt-cli/bin/grunt' ", have you tried a global install of "grunt-cli" ? ( `npm install -g grunt-cli` )

Otherwise, if this doesn't work, it might be that your computer isn't fast enough to create the database in the accorded time, you should create a `orm.js` file in the `config` directory with the following code : 

```
// config/orm.js
module.exports.orm = {
  _hookTimeout: 60000 // I used 60 seconds as my new timeout
};
```

( reference [here](http://stackoverflow.com/questions/28524926/the-hook-orm-taking-too-long-to-load) )
If it's the case, I will add this file to the project.

( I've answered in English because that's a little bit better to speak in English on GitHub, so that everyone can understand :) )

**Comment by nobodyjoh** [comment]
Ok yeah I hesitated to speak in English too but that's right it's better for a global understanding.

So i create orm.js file and re-execute npm install -g grunt-cli and i have the same problem. So i executed grunt on the racine. Order referred me was missing

```
>> Local Npm module "grunt-contrib-coffee" not found. Is it installed?
>> Local Npm module "grunt-contrib-less" not found. Is it installed?
>> Local Npm module "grunt-mocha-test" not found. Is it installed?
```

grunt-mocha-test isn't in the package.json, it was a mistake?

Therefore i installed 3 modules and order grunt works

However, i have already this error even if i have created the file orm.js

```
info: User hook policies loaded from /root/gladys2.0/api/hooks/example/policies.
info: User hook config loaded from /root/gladys2.0/api/hooks/example/config.
error: Error: The hook `views` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.views._hookTimeout to a higher value (currently 30000)
    at tooLong [as _onTimeout] (/root/gladys2.0/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15) { [Error: The hook `views` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.views._hookTimeout to a higher value (currently 30000)] code: 'E_HOOK_TIMEOUT' }
info: User hook models loaded from /root/gladys2.0/api/hooks/example/lib/../models.
error: [ { [Error: ENOENT, lstat '/root/gladys2.0/api/hooks/example/assets']
    errno: 34,
    code: 'ENOENT',
    path: '/root/gladys2.0/api/hooks/example/assets' } ]
error: A hook (`example`) failed to load!

/root/gladys2.0/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /root/gladys2.0/node_modules/async/lib/async.js:30:31
    at process._tickDomainCallback (node.js:463:13)
```

**Comment by Pierre-Gilles** [comment]
Try adding `hookTimeout: 60000` to the `config/env/development.js` file.

So that your development.js file looks like that : 

```
module.exports = {
  // add this line
  hookTimeout: 60000 
};
```

Something is maybe slower on your computer. Tell me if that work !

**Comment by nobodyjoh** [comment]
Yes my raspberry is in trouble ^^ but you test on raspberry too? or on a computer?

Same problem with the line added but i don't understand why i have already this error whereas we changed the config to 60000

```
Make sure it is triggering its `initialize()` callback, or else set `sails.config.views._hookTimeout 
to a higher value (currently 30000)
```

**Comment by Pierre-Gilles** [comment]
Ok, in the `config/views.js` file, add the line : 

`_hookTimeout: 60000`

I'm working on my Mac, that's faster :) But other people are working with a Raspberry Pi and they don't have the problem, strange. 
I'm currently bringing Gladys to my Rpi, I'll tell you if I have the problem too. If yes, I'll update Gladys in consequence.

**Comment by Pierre-Gilles** [comment]
Otherwise, thanks for grunt-mocha-test, it was not included in package.json, I just updated the file !

**Comment by nobodyjoh** [comment]
Otherwise i will install all modules on my mac and transfer to my raspberry, i think npm install didn't install correctly all modules.

I try to reinstall sails but i have no idea what's the problem on my raspberry maybe i have to format memory card

**Comment by Pierre-Gilles** [comment]
No no you need to install Gladys on the machine that'll run the software, because npm install compile directly the module. 

Your mac is based on a x64 architecture, and you Raspberry Pi a ARM architecture, that won't work.

**Comment by nobodyjoh** [comment]
Oh yeah i didn't think about that >.< , that's right.

Hum... i will try to start from scratch and install module line per line, i think my raspberry isn't powerful enough even if i think it changes nothing but i can try ^^

**Comment by Pierre-Gilles** [comment]
Otherwise I'm building a ready to go raspbian image, I'll release it during the week I think.

**Comment by nobodyjoh** [comment]
Yeah i saw that but i also use my raspberry for others things so i prefer to install gladys like this. After it depends if raspbian image is only for gladys or if we can do others things with it

**Comment by Pierre-Gilles** [comment]
It's just a basic raspbian image, where Gladys is installed. So you can do what you want !

**Comment by nobodyjoh** [comment]
ok if i don't succeed in install i will try with the raspbian image, thanks for your answers

**Comment by GladysAssistant** [comment]
I have the same problem as you on my Rpi B+, the raspberry is too slow to load Gladys in just 30 secondes the first time so I'm going to give a higher timeout, update coming soon :)

**Comment by nobodyjoh** [comment]
Ok right so i waiting your news :) 

PS : i use also a Rpi b+, maybe others person use rpi powerful

**Comment by Pierre-Gilles** [comment]
I'm doing some tests about the best timeout, 60 seconds is not enough too. I'm trying 90 seconds.

**Comment by Pierre-Gilles** [comment]
I've updated Gladys with a timeout of 240000, it works by me ! Just git pull and tell me if it works

**Comment by nobodyjoh** [comment]
It's really curious i already have in error timeout of 30000, I feel it does not take me config files, really curious...

Error 

```
info: User hook policies loaded from /root/gladys/api/hooks/example/policies.
info: User hook config loaded from /root/gladys/api/hooks/example/config.
error: Error: The hook `views` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.views._hookTimeout to a higher value (currently 30000)
    at tooLong [as _onTimeout] (/root/gladys/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15) { [Error: The hook `views` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.views._hookTimeout to a higher value (currently 30000)] code: 'E_HOOK_TIMEOUT' }
info: User hook models loaded from /root/gladys/api/hooks/example/lib/../models.

/root/gladys/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /root/gladys/node_modules/async/lib/async.js:30:31
    at process._tickDomainCallback (node.js:463:13)
```

My gladys folder is up to date

**Comment by Pierre-Gilles** [comment]
30 000 < 240 000 ... ;)

**Comment by nobodyjoh** [comment]
Yeah yeah i know but even if i change the timeout with different file with 240 000 value, 240000 doesn't appears ^^

**Comment by Pierre-Gilles** [comment]
in config/views.js file ?

**Comment by Pierre-Gilles** [comment]
To explain how sails works : 
`sails.config.views._hookTimeout` means that : 
sails looks at the `config` folder => `views` file => `_hookTimeout` properties.

**Comment by nobodyjoh** [comment]
Yeah it works, i forgot to change value on views.js it was still at 60000, damn it ^^
It's good i have another error but it's mysql and this time it's normal ^^ 
Thanks for your answers, i close the issue it's good for me :)

**Comment by Pierre-Gilles** [comment]
For the mysql error just git pull I made a correction, it was a stupid mistake in the code
