### ISSUE TITLE
Tag on scene feature: When all scenes of a tag are only disabled, the tag is deleted

### ISSUE THREAD

**Issue by Terdious** [GladysAssistant/Gladys#2000]
Related to the subject: [Add any other context about the problem here.](https://community.gladysassistant.com/t/suppression-des-tags-des-scenes-desactivees/8642)

**Describe the bug**
When all scenes of a tag are only disabled, the tag is deleted as if no scene contained this tag anymore even though it is just disabled

**To Reproduce**

- Go to scenes
- Create a “Test tag scene deactivated” scene
- Add a “Disabled Scenes” tag
- Save and return to the Scenes list menu
- Select the new tag "Deactivated scenes" to find the newly created scene
- Disable scene
- Refresh the page
- Search again for the “Disabled Scenes” tag => It no longer exists

**Expected behavior**
The tag should always exist when at least one scene, disabled or not, has this tag.

**Comment by Pierre-Gilles** [comment]
Hey @Terdious, it's not a bug, it's as the feature was designed!

**Comment by Terdious** [comment]
Hi @Pierre-Gilles sorry but no, what was defined is that if no more scenes contain the tag, then the tag is deleted.  Here I am talking about a scene which contains the tag but which is only deactivated.

See : https://community.gladysassistant.com/t/suppression-des-tags-des-scenes-desactivees/8642

**Comment by Pierre-Gilles** [comment]
Ah my bad indeed!
