### ISSUE TITLE
MQTT external broker option is not taken in account

### ISSUE THREAD

**Issue by cicoub13** [GladysAssistant/Gladys#2040]
**Describe the bug**
Button "Utiliser un broker dans un conteneur Docker." on MQTT Setup page is not taken in account.

When you click on the button, action `updateConfiguration`in **index.js** has an undefined variable `config`. So it's not taken in account and not saved into backend configuration.

![image](https://github.com/GladysAssistant/Gladys/assets/1773153/41af8416-a884-4302-9580-665b1adcd555)

https://github.com/GladysAssistant/Gladys/blob/master/front/src/routes/integration/all/mqtt/setup-page/index.js#L44

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation 4 with Gladys base image Docker

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox
- Version: 123.0.1 64 bits

**Additional context**
https://community.gladysassistant.com/t/gladys-et-broker-mqtt-externe/8741

**Comment by McFlyPartages** [comment]
Hy,

I add my config with thesame problem.

**Your Gladys installation (please complete the following information):**

* Proxmox with VM Debian 12 and Docker

**Desktop (please complete the following information):**

* OS: Ubuntu
* Browser: Firefox and Brave
* Version : Latest

**Comment by Pierre-Gilles** [comment]
I tested extensively without managing to reproduce :/ 

https://community.gladysassistant.com/t/gladys-et-broker-mqtt-externe/8741/28?u=pierre-gilles

**Comment by Pierre-Gilles** [comment]
Fixed in https://github.com/GladysAssistant/Gladys/pull/2046
