### ISSUE TITLE
No options on get device value

### ISSUE THREAD

**Issue by nataloko** [GladysAssistant/Gladys#2074]
**Describe the bug**
I have a Gladys installation with 15 devices, I can see their values and interact with them form the "Home" tab with no problem, but when I try to create a "Scene" both "Get device value" and "Set device value" show "No options"

**To Reproduce**

1. Go to Scenes tab
2. Create new scene
3. Click on 'Add action'
4. Select 'Get device value' type
5. Click 'Add action'
6. Click drop down menu
7. Shows no options 

**Expected behavior**
Show a list of installed devices and their "features".

**Screenshots**
![image](https://github.com/GladysAssistant/Gladys/assets/93059500/9fb27127-de35-414f-bd88-717c60a2d709)

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation: no
- Manual installation: Linux - docker

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version 125.0.3

**Comment by William-De71** [comment]
Have you put your devices in a room? If no, please add your devices in a room before.

**Comment by nataloko** [comment]
Ah! That was it!
Thank you very much :)
