### ISSUE TITLE
Z-index issue with shutter command button in scene action Control a device

### ISSUE THREAD

**Issue by William-De71** [GladysAssistant/Gladys#2098]
Z-index issue with shutter command button in scene action Control a device

![image](https://github.com/GladysAssistant/Gladys/assets/11477113/802e63e3-b893-43f2-8295-6a53dbc1afb8)

https://community.gladysassistant.com/t/gladys-assistant-4-42-1-volets-roulants-dans-les-scenes-correctifs/8961/4

**Comment by Pierre-Gilles** [comment]
Fixed in https://github.com/GladysAssistant/Gladys/pull/2100
