### ISSUE TITLE
Missing documentation page for LAN Manager integration

### ISSUE THREAD

**Issue by Sigri44** [GladysAssistant/Gladys#2111]
Hello,

Documentation page for LAN is missing :
https://gladysassistant.com/fr/docs/integrations/lan-manager

Have fun !

**Comment by Pierre-Gilles** [comment]
Thanks for the issue, indeed!

**Comment by Pierre-Gilles** [comment]
Fixed! 

Documentation is live: https://gladysassistant.com/docs/integrations/lan-manager/
