### ISSUE TITLE
Zigbee2mqtt: Add device undefined

### ISSUE THREAD

**Issue by barnsFromOz** [GladysAssistant/Gladys#2122]
I am trying to get a Zigbee device attached to Gladys. 
After adding a Sonoff USB 3 dongle (model E) into my RasPi3 Gladys Server, I followed Pierre-Gilles advice and disabled then re-enabled the service. Then it started looking for Zigbee devices. I re-enabled syncing (the docs say BT SIG Mesh, wifi 2.4Ghz bgn, Zigbee 3.0) and the message that appeared talked about Coordinator. And said: “Device not handled yet, please contact us to help us connect it to Gladys!” So I logged into GitHub, and here I am.

The device is called a  High Power Switch, Hub only req’d for Zigbee, Model #CS-SS-ZHPEU/US(PRO)… except it may not be the Pro, as the Pro incl. a Power Monitor… 
I hope this isnt hard work for someone! Anything else I need to provide? Will GitHub tell me if there is?
Thanks in advance, Cheers, Barney 

```
{
  "name": "Coordinator",
  "external_id": "zigbee2mqtt:Coordinator",
  "features": [],
  "should_poll": false,
  "service_id": "146434da-46c8-4620-a389-300a40a736e8"
}
```

**Comment by Pierre-Gilles** [comment]
Hi @barnsFromOz ! Thanks for creating this issue 🙏

What is this device exactly doing? How do you expect to control it in Gladys?

Can you find this device on this page: https://www.zigbee2mqtt.io/supported-devices/ ?

**Comment by jgcb00** [comment]
Hi,
I found out that the coordinator is just the Zigbee dongle, as it's part of the zigbee network, in new version of Zigbee2Mqtt, it's now a device that is display in Gladys but can't be added

**Comment by Pierre-Gilles** [comment]
@jgcb00 Ok, then I think there is no need to integrate this, it's not a real device. Can I close this issue?

**Comment by Pierre-Gilles** [comment]
I'm closing this issue :) Feel free to open any other issue if needed!
