### ISSUE TITLE
Scene : Variable injection doesn't work in HTTP request

### ISSUE THREAD

**Issue by jgcb00** [GladysAssistant/Gladys#2124]
**Describe the bug**
After getting back a value, when trying to inject it in the http request nothing is proposed

**To Reproduce**
In scene :
1.  get a value
2. try to inject in the body of the request with {{, nothing shows up

**Expected behavior**
A dropdown should appear and propose the different value retrieved 

**Your Gladys installation (please complete the following information):**
- Beelink S12
- Docker compose + dockge
- Gladys v4.45.1
- Retrieve a fake MQTT device

![image](https://github.com/user-attachments/assets/2c6d0b9f-4c80-49d7-9f86-e9645fda2a2b)

**Comment by Pierre-Gilles** [comment]
@jgcb00 You need to press "space" after pressing {{

**Comment by jgcb00** [comment]
Indeed my bad,
I still have a weird issue so two question, 
is it possible to cast value to an int ? I'm using temperature for a light and it doesn't behave as expected, but brightness and on/off do. 
Is there any way to log the http request easily ? To see what it's sending to debug ?

**Comment by Pierre-Gilles** [comment]
@jgcb00 no it's not possible to cast a value here. 

> Is there any way to log the http request easily ? To see what it's sending to debug ?

I recommend using tools like https://webhook.site/ to test your API calls. You'll see what you're sending :)

**Comment by Pierre-Gilles** [comment]
Closing this. Don't hesitate if you have any questions to join on our forums :) 

- International community: https://en-community.gladysassistant.com/
- French community: https://community.gladysassistant.com/
