### ISSUE TITLE
Zigbee2mqtt: Add device undefined

### ISSUE THREAD

**Issue by Manu85320** [GladysAssistant/Gladys#2154]
```
{
  "name": "Coordinator",
  "external_id": "zigbee2mqtt:Coordinator",
  "features": [],
  "should_poll": false,
  "service_id": "2dcd2303-1f27-4646-91e6-6ad10e5e0aba"
}
```

**Comment by Pierre-Gilles** [comment]
Hi @Manu85320, this is the coordinator (your USB stick), it's not useful in Gladys :) 

@cicoub13 I think we should hide the coordinator from the "New device" view, it was added recently in Zigbee2mqtt
