### ISSUE TITLE
Virtual Machine - Gladys 

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#22]
Bonjour,

j'ai reussi à m'installer gladys sur une machine virtuel (j'ai pas de raspberry sous la maiin)

je vais essayer de mettre la machine virtuel a dispô mais ou uploader 1 go ?

qu'elle capteur peut on utiliser avec une machine virtuelle sachant que le seul moyen et d'avoir quelque chose connecter sur le reseaux, en fait que je trouve comment trufer m maison de capteur.
et que je puisse connecter un haut parleur dans la maison pour lui envoyer des sons depuis gladys

Je découvre la domotique, et apparamment c'est pas facile mais c'est super interressant les scénarios décrit sur votre site son génial !!
faut que je trouve comment mettre en place ça et ajouter des modules j'ai pleins d'idée déja !!!

c'est vraiment un projet génial !!
merci

**Comment by Pierre-Gilles** [comment]
Tu pourrais la partager sur [Mega](https://mega.co.nz/) par exemple, c'est pratique pour le transfert de fichier lourd :)

Tu peux utiliser n'importe quoi qui est connecté sur le réseau du coup, type Ampoule Wi-Fi, etc... Tout ce qui est objet connecté Wi-Fi et qui a une API !

**Comment by ghost** [comment]
depuis ce matin j'essai d'uploader sur mega sans succés, ça ne fait que planter :/ 

Voici mon petit d'utilisation de la vm : 

1> Importation de la vm dans virtual box : 
![gladys_vm_01](https://cloud.githubusercontent.com/assets/301074/8334838/4f8ccb76-1a9a-11e5-82fd-2d9507ddc21b.jpg)

2> Démmarage de la vm 
![gladys_vm_02](https://cloud.githubusercontent.com/assets/301074/8334841/53f90cc4-1a9a-11e5-918b-612f37e4f2ac.jpg)

3> Connexion à la vm
![gladys_vm_3](https://cloud.githubusercontent.com/assets/301074/8334863/7cf57658-1a9a-11e5-9e18-0d33c42c80c7.jpg)

utilisateur : gladys
mot de passe : password 

4> Démmarage de Gladys 
une fois démmaré en ligne de commande : 
On récupére l'adresse ip local de sa machine : 

```
> ipconfig 
```

dans mon cas c'est 192.168.50.41

![galdys_vm_06](https://cloud.githubusercontent.com/assets/301074/8334983/26b55ca8-1a9b-11e5-84ef-1866fb3b07a9.jpg)

ensuite on démarre gladys : 

```
> cd gladys
> nvm use 0.10.39
> node app.js
```

![gladys_vm_04](https://cloud.githubusercontent.com/assets/301074/8334931/dd0789dc-1a9a-11e5-876f-685f18220366.jpg)

et gladys démmare : 
![gladys_vm_05](https://cloud.githubusercontent.com/assets/301074/8334957/f204d574-1a9a-11e5-9f39-99c74e73a22e.jpg)

5> Connexion à Gladys 

on se connecte avec l'adresse ip récupéré précédemment : 
![gladys_08](https://cloud.githubusercontent.com/assets/301074/8335053/8e2d61c8-1a9b-11e5-9125-b16596d72460.jpg)

et il y a plus qu'a faire joujou 

6> ATTENTION : 
Lors de la création du compte pour passer la date de naissance il faut qu'elle soit au format 'YYYY-MM-DD' 

amuser vous bien

**Comment by ghost** [comment]
Bonsoir,
Quel est le lien de download de la VM svp.
Merci.

**Comment by Pierre-Gilles** [comment]
Essai un autre système d'hébergement, il y en a plein :) 

Est ce que tu pourrais rajouter le lancement automatique de Gladys au démarrage ? ( avec [PM2](https://github.com/Unitech/pm2) )

**Comment by ghost** [comment]
l'upload est enfin terminé : 
https://mega.co.nz/#!CExDWD7a!whvry4kK8yL83-pY7X_W-FqbTTtzmX9d92pfK9H53W4

pour la version 2 je vais ajouter https et le lancement automatique c'est pas mal ça

faut aussi dans un premier temps que je me trouve un hautparleur qu'on peux connecter au réseaux pour l'utiliser avec Gladys !

**Comment by ghost** [comment]
Top. Ca fonctionne nikel, aussi la VM que le Raspberry Pi2.
Reste maintenant à connecté Gladys à mes IPX800 !

**Comment by ghost** [comment]
ok j'ai tester PM2 ça marche nikel.

faut que je ruploade ma vm 

ça veut dire que tu imoprt la vm dans virtual box, il faut trouver l'adresse ip, et aprés tu peux te connecter directement à gladys !

**Comment by Pierre-Gilles** [comment]
Je vais essayer de faire un Docker Gladys, ça serait plus facile à partager :)
 ( je ne sais pas si tu connais docker : https://www.docker.com/ )

**Comment by ManuInNZ** [comment]
Salut,

Du coup le docker tu as essayé ?

A+
Manu

**Comment by Pierre-Gilles** [comment]
Image Docker pour Gladys => http://gladysproject.com/fr/article/gladys-et-docker
