### ISSUE TITLE
Reboot button can be confusing

### ISSUE THREAD

**Issue by p6ril** [GladysAssistant/Gladys#220]
The reboot button in gladys UI can be a little confusing. First it says pm2 necessary which I assume concerns only people who installs gladys from scratch out of github, but not all the people using the standard image, then pressing the button doesn't do anything from the user standpoint. At least a small pop-in to acknowledge the reboot request (asking to wait for 30s) would be great.

**Comment by Pierre-Gilles** [comment]
You're right ! This is in my list for the next milestone :)

**Comment by Pierre-Gilles** [comment]
Added a modal telling the user Gladys is rebooting + health check regularly so that Gladys dashboard refresh automatically when Gladys is up ! ;)
