### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Legend23** [GladysAssistant/Gladys#224]
Bonjour, 

je ne suis nouveau sur le sujet, et j'ai donc tenter d'utiliser Gladys. 
J'ai alors suivi le tutoriel: télécharger l'image avec gladys pré-installé, utilisé etcher, etc etc.
J'allume mon RPI, je me connecter sur: http://192.168.1.xx et tout fonctionne bien. 

Le problème vient dès que j'installe un module exemple: hue ou encore weather. 
Je n'arrive plus à accéder à l'interface de gladys. 

![gladys_1](https://user-images.githubusercontent.com/3600281/30521293-a4d63ad0-9bbd-11e7-9ae3-a377326094fe.PNG)

Je fais alors la commande: `pm2 logs gladys`

Et j'ai cela en retour: 

![gladys_2](https://user-images.githubusercontent.com/3600281/30521339-59ec7060-9bbe-11e7-8b1f-486f22aa7bec.PNG)
![gladys_3](https://user-images.githubusercontent.com/3600281/30521341-5c5868fe-9bbe-11e7-9748-8655e85e26bf.PNG)

J'ai essayé de faire: `/home/pi/gladys/rpi-update.sh` car `/home/pi/gladys/node_modules/gladys/rpi-update.sh` n'existe pas. 

Mais toujours le même soucis.  
A part re-flasher la carte mémoire et installer manuellement (que je trouve complexe, vu mon niveau) , il y a t'il une solution ? 

Merci d'avance.

**Comment by Pierre-Gilles** [comment]
Hello !

Tu peux supprimer les modules installés en supprimant tous les dossiers dans le dossier: 

```
/home/pi/gladys/api/hooks
```

Chaque dossier dans le dossier hooks correspond à un module, tu peux supprimer tous les dossiers puis faire : 

```
pm2 restart gladys
```

A l'avenir, pose tes questions sur le forum => https://community.gladysproject.com/ plus que sur GitHub qui est dédié aux retours de bug propre à Gladys plus qu'au soucis d'installation de modules :)
