### ISSUE TITLE
Improve user card in map view with info like at home or not

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#228]
- at home ? Which home ?
- moving ? Last seen here ? How long has the user been here ?

**Comment by kalon33** [comment]
@Pierre-Gilles is this currently possible to set this at home/not at home state automatically? Maybe using a smartphone? How? I often forgot to say to Gladys (using Telegram) that I left or that I'm back... using phone bluetooth? An app to send location to Gladys?

**Comment by Pierre-Gilles** [comment]
Of course it is ! 

You can check my latest article about this (published 2 days ago!) => 
https://gladysproject.com/fr/article/detecter-presence-porte-cle-bluetooth

If you have question, don't hesitate to go on [Gladys Forum](https://community.gladysproject.com/), Github issues are more about reporting problems + todo list of scheduled improvements
