### ISSUE TITLE
Gladys won't start anymore

### ISSUE THREAD

**Issue by kalon33** [GladysAssistant/Gladys#232]
I just installed gladys-yeelight module from advanced interface, and now gladys won't start anymore (no webinterface). I only get this log:

```
0|app      | Bootstrap is taking unusually long to execute its callback (2000 milliseconds).
0|app      | Perhaps you forgot to call it?  The callback is the first argument of the function, `cb`.
```
Is this possible to fix this, or revert module install without resetting everything?

**Comment by C4rlit0** [comment]
Yes you can delete the gladys-yeelight folder in /home/pi/gladys/api/hooks

**Comment by kalon33** [comment]
Even if I installed it manually? 

----- Mail original -----

De: "C4rlit0" <notifications@github.com> 
À: "GladysProject/Gladys" <Gladys@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 26 Septembre 2017 08:16:10 
Objet: Re: [GladysProject/Gladys] Gladys won't start anymore (#232) 



Yes you can delete the gladys-yeelight folder in /home/pi/gladys/api/hooks

**Comment by C4rlit0** [comment]
Yes just find the hooks folder

**Comment by kalon33** [comment]
thanks, that solved my problem (even if yeelight module is not fixed)
