### ISSUE TITLE
When removing items from google calendars, these are still partially listed in Gladys calendar

### ISSUE THREAD

**Issue by kalon33** [GladysAssistant/Gladys#233]
When removing items from a google calendar, items are still "partially" listed in calendar box in Gladys.

By partially, I mean, for example, when clicking on a day in calendar:
02:00 - 02:00 : machin bidule chouette
09:30 - 16:30 :
02:00 - 02:00 :
02:00 - 02:00 : truc important
14:00 - 17:00 :

Some items are still listed, but with empty description (title). These are the ones I deleted.

**Comment by Pierre-Gilles** [comment]
> Some items are still listed, but with empty description (title). These are the ones I deleted.

Mmm I understand, this is related to gladys-google module here => https://github.com/GladysProject/gladys-google/blob/master/lib/calendar/calendar.syncCalendarEvents.js#L71

The deleted info is not propagated to Gladys

Thanks for the report!  :)

**Comment by Pierre-Gilles** [comment]
I've saved this issue in the gladys-google module here => https://github.com/GladysProject/gladys-google/issues/2
