### ISSUE TITLE
Add a module to retrieve electricity use from Linky (via Enedis API)

### ISSUE THREAD

**Issue by kalon33** [GladysAssistant/Gladys#234]
Would it be possible to implement a module to retrieve and graph electricity use based on Enedis API, like https://github.com/Asdepique777/jeedom_linky does? I think that enhancement would be useful to be able to create some scenarii to react to it by launching actions.

**Comment by Pierre-Gilles** [comment]
Yes of course ! There is already a module "Energie", something similar can be developed ! https://community.gladysproject.com/t/module-energie/631

**Comment by Pierre-Gilles** [comment]
I'm closing this issue as it's not related to Gladys core itself :)
