### ISSUE TITLE
Can't easily find via Github search

### ISSUE THREAD

**Issue by pfalcon** [GladysAssistant/Gladys#244]
You may be interested (or not) that your project can't be found on github, searching for "home automation", "smart home", or "smarthome".

**Comment by Pierre-Gilles** [comment]
Thanks for your feedback! I added the topic "home automation" + "smart home" + "smart" + "home" to Gladys so the repository is referenced in these request.

Could your confirm it's working on your side? it works on mine

**Comment by pfalcon** [comment]
It is: github search "home automation", sort by "most stars", Gladys is on the 1st page: https://github.com/search?o=desc&q=home+automation&s=stars&type=Repositories&utf8=%E2%9C%93 . Also added to https://github.com/pfalcon/awesome-smarthome .

Thanks!

**Comment by Pierre-Gilles** [comment]
Nice ! Thank you :)
