### ISSUE TITLE
New modules on website don't shown on my online version.

### ISSUE THREAD

**Issue by marius851000** [GladysAssistant/Gladys#245]
Hi, I'm testing GLadys ( I haven't any connectable object ). Some modules on the website don't shown on my version ( from SVN, version 3.7.2, lauched with node.js ( and not pm2 )).
My hosted version -
![image](https://user-images.githubusercontent.com/22586596/32454116-8a574950-c31e-11e7-8ca1-f28560e6cb73.png)
![image](https://user-images.githubusercontent.com/22586596/32454123-9030c0ae-c31e-11e7-9334-6dd2368f2b31.png)
website -
![image](https://user-images.githubusercontent.com/22586596/32454147-a4991b36-c31e-11e7-883b-d1129ff748c1.png)
for exemple, there are the download addon on the website, but not on my hosted version.

**Comment by Pierre-Gilles** [comment]
Hey!

This is "normal" (but not well explained maybe), the modules displayed in Gladys are the modules available on your current version of Gladys.

Other modules are old module that have not been adapted to new version of Gladys :)
