### ISSUE TITLE
Association compte google

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#25]
Hello,

je voulais associé mon compte mail avec gladys mais ça ne semble pas marché est ce normal : 

![parametres gladys - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/8337039/d91a9432-1aa8-11e5-815b-2fb31df64345.jpg)

une fois cliquer sur le bouton, nous avons le message d'erreur suivant : 

![error 401 oauth2 error 1 - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/8337043/e4a023f8-1aa8-11e5-856e-2fa2ef5d9dd8.jpg)

**Comment by VonOx** [comment]
As tu édité le fichier googleapi.js ?

**Comment by BenjaminBrahmi** [comment]
Bonjour, 

Pouvez-vous m'indiquer où se trouve ce fichier ? (Avec l'image raspbian) 

EDIT : au temps pour moi, j'avais mal lu (elle se situe dans /home/pi/gladys/config/)

@ychoucha réfère toi à cette partie ;) 
![capture](https://cloud.githubusercontent.com/assets/7962236/8391848/126c7300-1cd3-11e5-945b-9ccfeda89482.PNG)

**Comment by VonOx** [comment]
@ychoucha tu as réussi ?

**Comment by ghost** [comment]
ça a marché mais aprés validation du premier menu google j'ai l"erreur suivante : 

![erreur de chargement de la page - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/8396169/05937ebc-1d9b-11e5-814b-78ad408b4ceb.jpg)

et j'ai cette erreur dans la console : 

```
warn: sameNetworkPolicies : MachineService : getMyHouse : I don't know in which house I live :(
warn: sameNetworkPolicies : MachineService : getMyHouse : I don't know in which house I live :(
```

warn: sameNetworkPolicies : MachineService : getMyHouse : I don't know in which house I live :(
warn: sameNetworkPolicies : MachineService : getMyHouse : I don't know in which house I live :(

**Comment by Pierre-Gilles** [comment]
C'est normal, tu as mis "localhost" en URL ! Je ne l'ai pas indiqué c'est vrai, il faut mettre l'IP de la machine qui execute Gladys.

L'autre erreur n'a rien à voir, il faut que tu aille dans les paramètres de Gladys ( dans le dashboard ) et que tu définisse la maison ou est situé ton Raspberry Pi executant Gladys pour que Gladys puisse détecter quand tu es chez toi et que tu te connecte sur le même réseau.

**Comment by ghost** [comment]
google ne veux pas que je mette d'adresse ip : 

![identifiants - gladys - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/8396351/30f46416-1da2-11e5-93cc-9e17368cea5f.jpg)

**Comment by Pierre-Gilles** [comment]
Je viens d'avoir exactement le même retour sur le forum, c'est un problème. En fait normalement ce genre d'authentification sert sur un site, donc google accepte les noms de domaines, et localhost pour faire du dev. Il y a donc deux solutions : 

1) Tu te mets sur le navigateur du raspberry pi pour faire la connexion ( en gardant localhost dans ce cas là ). Comme ça la redirection fonctionnera !

2) Je fais un outils sur le site du projet comme ça vous pouvez utiliser gladysproject.com comme URL de redirections. Mais bon, ça serait pas pour tout de suite :p

**Comment by ghost** [comment]
ça veut dire qu'il faut que la machine soit sur internet.
c'est pas bon ça !

deplus je n'utilise pas de raspberry, mais une Virtual machine pour le moment
ce qui veut dire que je peux pas utiliser une machine local pour interferer avec mon compte google,
ça c'est pas cool

**Comment by Pierre-Gilles** [comment]
Nope ce n'est pas ça, j'ai du mal m'exprimer!

En fait juste pour l'étape de connexion à ton compte Google, il faut que la redirection se fasse sur localhost, ou un domaine, donc toi sur ta VM aucuns soucis en théorie, tu te mets sur le navigateur de ta VM et ça sera parfait :)

Et une fois la config faites c'est bon, la configuration sert à juste à Gladys à récupérer 2 tokens ( Oauth2 )pour pouvoir accéder à ton compte Google par le futur. Une fois que les tokens sont récupéré, tout va bien tu n'as plus besoin d'être sur ta VM tout fonctionne comme avant.

**Comment by ghost** [comment]
Bonjour,
J'ai le même problème sur mon raspberry. Par contre, j'ai un domaine.
J'ai renseigné les informations sur la console google avec le bon nom de domaine.
Lorsque je clique sur Connecter un compte, il conserve le localhost. 
Y a t il une modification d'un fichier dans Gladys pour la redirection de l'API
Merci pour votre aide.
F.
![screenshot](https://cloud.githubusercontent.com/assets/13037313/8832377/f4f7dc4e-30a8-11e5-9d89-4debb4bc28f9.png)

**Comment by VonOx** [comment]
Remplace localhost par ton domaine lorsqu'il fait la redirection j'ai le même problème, ça vient de chez Google je penses ou fait le depuis ton raspberry

**Comment by Pierre-Gilles** [comment]
Regarde le fichier "config/googleapis.js" !

**Comment by ghost** [comment]
Je suis sur le fichier, mais il n'y a pas de commande de redirection.
Dois-je la rajouter à la mano ?

**Comment by Pierre-Gilles** [comment]
Oups, effectivement non de tête je pensais ! Normalement tu change l'URL de redirection dans le dashboard Google

**Comment by ghost** [comment]
En effet, en modifiant dans la barre de raccourci web localhost par mon domaine, Google a reconnu et accepté la connexion.
Par contre ensuite, Gladys est revenu à la page de login. Lorsque je navigue sur Paramètre, Gladys n'a pas associé le compte GOOGLE.

**Comment by Pierre-Gilles** [comment]
En fait par défaut la synchronisation du compte n'est pas automatique, il faut créer une scénario : Toutes les 30 minutes => Synchroniser compte ( par exemple ).

**Comment by VonOx** [comment]
Je penses qu'il faut considérez ces fonctions de la V2 comme "Broken" et patientez pour la V3.

@paris-ci En base de données tu n'as rien ? Le token goole n'est pas du tout enregistré ? Quelque chose dans les logs ?
