### ISSUE TITLE
problème de gestion des Utilisateurs entre user-seen-at-home et back-at-home

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#262]
Salut,
En travaillant sur une fonction de purge des event, j'ai purgé trop d'events :)

Du coup, en relancant mon instance, n'ayant aucun d'évenement _back-at-home_ ou _left-home_, je suis donc considéré à juste titre comme _user-seen-at-home_

Sauf quand mon controle de présence sur détection de mouvement appel la fonction _house.isAtHome_ qui appelle elle meme la fonction _house.getUsers_, hors cette dernière s'appuie sur les évènements _back-at-home_ et _left-home_ et donc visiblement pas sur _user-seen-at-home_.

Ainsi, je suis considéré comme n'étant pas à la maison tant que je n'y serais vraiment pas afin de reprendre un état normal.

Si mon analyse est confirmée, ne faudrait-il pas intégrer l'event type _user-seen-at-home_ dans la fonction _house.getUsers_ ?

**Comment by Pierre-Gilles** [comment]
Mmmm on pourrait, après c'est plutôt ta fonction de purge qui devrait être remise en cause :p 

Un event "user-seen-at-home" déclenche nécessairement un event "back-at-home" si tu n'es pas à la maison normalement, donc ce cas n'arrive pas trop en général ^^

Mais bon ça pourrait être rajouté !

**Comment by Jean-PhilippeD** [comment]
Ben en fait j'ai fais une purge manuelle trop agressive. 
Coté fonction, c'est censé etre clean, je vais l'éprouver ces prochains jours.

Mais dans l'opération, j'ai perdu les dernies events left et back at home.

J'ai eu l'impression qu'en labsence de ces events, j'ai eu un user-seen-at-home et rien d'autre. 
Donc si j'ai bien vu, ca n'arrive que dans le cas d'un premier démarrage tant qu'il n'y a pas eu de détection du premier left-home, donc cas certe assez rare.

**Comment by Pierre-Gilles** [comment]
Effectivement c'est le cas!

Je vais ajouter l'event à la fonction pour éviter tout problème à l'avenir :)
