### ISSUE TITLE
Des données privées sont renvoyées en réponse à un appel au brain.classify

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#264]
Salut,

Lorsqu'on appel le brain par HTTP (via gladys-voice), ligne 52 du brain.classify

`return result`

contient le scope, et le scope contient notamment le hash du password du user. 

Je pense qu'il faudrait voir pour nettoyer le scope avant de répondre à la requete HTTP.

**Comment by Pierre-Gilles** [comment]
Bien vu ! C'est effectivement un bug à corriger, c'est noté !
