### ISSUE TITLE
changer les liens href en adresses relatives

### ISSUE THREAD

**Issue by kyuuk** [GladysAssistant/Gladys#272]
Ajouter le support de reverse proxy a Gladys en changeant les href des views par exemple :
sous Nginx si on proxy_pass les requetes de http://localhost/gladys vers localhost:8080(qui est l'adresse de gladys), tout les css et js de la page retournent une 404 Not Found, et /installation nous renvoi vers http://localhost/installation, non pas http://localhost/gladys/installation .

solution passer tous les liens dans le code des views en liens relatives, au lieu d'avoir 

> href="/installation"

 mettre 

> href="installation"

**Comment by Pierre-Gilles** [comment]
Mmm à réfléchir, je ne sais pas si c'est souhaitable, étant donné qu'ensuite si on fait des pages /installation/step-2 par exemple, on est bloqué avec les adresses relatives ! 

Pourquoi ne pas faire un sous nom de domaine plutôt sur ton reverse proxy  ? genre `gladys.domaine.com` ?

**Comment by kyuuk** [comment]
Oui c'est tout a fait possible,au pire je peux modifier les liens juste pour moi, mais j'ai mis ce commentaire a titre de suggestion (par exemple une case a cocher pour le support de reverse proxy avec un web-root du genre `/gladys`). 

Bonne continuation avec ce super projet ^^
