### ISSUE TITLE
Brain Depreciated, unable to install

### ISSUE THREAD

**Issue by scarecr0w12** [GladysAssistant/Gladys#295]
It seems the NPM Package "brain" has been removed from NPM causing installation to not be possible without manually installing the npm package.

**Comment by Pierre-Gilles** [comment]
Thanks for your feedback, I got the same problem. 

In fact we are not using directly the "brain" package, but "limdu" that uses "brain" as a dependency. 

I submitted an issue on the limdu repository to inform them =>

https://github.com/erelsgl/limdu/issues/57

**Comment by Pierre-Gilles** [comment]
I'm seriously considering switching to switch to [natural](https://github.com/NaturalNode/natural) library instead.

**Comment by scarecr0w12** [comment]
If i remember correctly BrainJS or something like that took over for the Brain package.
