### ISSUE TITLE
Box which displays house mode 

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#296]

**Comment by jmellano** [comment]
Bonjour @Pierre-Gilles, je profites de cette issue pour te remonter : 
- 1 bug à mon sens
- 1 proposition d'évolution de la box 'Changement de mode'

- Le bug est sur le select de la maison. Par défaut, la première valeur n'est pas sélectionnée (car le type est number et Angular ne semble pas reconnaitre exactement le type (https://stackoverflow.com/questions/12654631/why-does-angularjs-include-an-empty-option-in-select)
Du coup on obtient qqch comme ca : 
<img width="816" alt="capture d ecran 2018-07-25 a 17 19 41" src="https://user-images.githubusercontent.com/2357082/43210759-32b004be-9030-11e8-8df4-360e9a3411a3.png">

- Autre point, j'ai essayé cet aprem de faire un autre rendu. Mon but est de pouvoir depuis l'écran du raspberry changer le mode de la maison en 1 clic. 
Du coup j'obtiens quelque chose du style : 
<img width="817" alt="capture d ecran 2018-07-25 a 17 19 51" src="https://user-images.githubusercontent.com/2357082/43210841-70a74638-9030-11e8-9765-26fb4de55445.png">

Alors idéalement il faudrait une icône différente et propre à chaque état, mais la je veux bien une idée du comment faire. J'ai vu qu'on utilise font awesome et j'imaginais ajouter une classe type : `fa fa-{{mode.code}}` mais c'est pas du tout dans les standards de fontawesome... Est-ce qu'il y a un endroit où l'on peut surcharger les icones ?

**Comment by Pierre-Gilles** [comment]
Hello! 

L'idée est top, c'est vrai que ça serait beaucoup plus pratique! 

A mon sens, le mieux est de faire un cas par type de mode (en gardant un cas par défaut), c'est pas un soucis et comme ça on sait ce qu'on met par mode :) 

Seul truc c'est un peu gros là je trouve, et surtout le texte à côté de la grosse icône c'est pas super élégant, je verrais plus une icône contenant en même temps le texte + l'icône au dessus du texte, tu en penses quoi ?

**Comment by jmellano** [comment]
Ola,

merci pour le retour.
OK pour les icones et le texte (c'était bien mon idée au départ...mais moi et le design ca fait deux :) )
Si tu sais comment avoir de belles icones je suis preneur.

Sinon qu'est-ce que tu entends pas "un cas par type de mode" ? Une box par mode ? 

PS : j'suis en congés encore 2 semaine :) donc pas trop actif...

**Comment by jmellano** [comment]
Salut @Pierre-Gilles 
tout d'abord j'espère que tu es bien installé dans ta nouvelle vie à l'autre bout du monde 😍

Je ne sais pas quand tu liras ce message, mais je voulais juste te montrer où j'en suis.

Côté design, j'ai retravaillé un peu le look pour donner qqch du style : 
<img width="838" alt="capture d ecran 2018-08-21 a 10 28 43" src="https://user-images.githubusercontent.com/2357082/44390210-07eec500-a52d-11e8-9add-dd9f437d6faa.png">

On peut certainement l'améliorer mais au moins c'est plus propre et pour commencer je trouve ca pas si mal (nb : j'suis vraiment mauvais en design). Je t'ai laissé un cas par défaut (ici c'est la sieste). Comme ca si le mode est inconnu on a quand même qqch qui s'affiche d'homogène.

Ensuite j'aimerais poussée cette box dans gladys et là nous avons 2 options avant que je te fasse une PR.
1. Je met à jour le code de l'actuelle box (attention est-ce que cela va plaire à tout le monde, pas si sur)
2. Je propose une nouvelle box de changement maison.

La je te laisse décider selon ce que tu préfères.

Dernier point qui n'a pas trop de rapport, maintenant que j'ai un peu mieux compris comment marche l'archi du code, je vais m'essayer à un module. Je me documente et je te posterais un message pour avoir ton point de vue et des conseils si possible.

++

**Comment by Pierre-Gilles** [comment]
Hello! :) 

Désolé pour ma réponse lente, je viens de me plonger dans mes centaines de notifications Github pour faire du ménage et je viens de voir ton message!

l'idée est super bonne, mais je t'avoue que je suis pas fan du design :D Tu peux peut-être demander de l'aide sur le forum pour faire un design plus proche de ce qu'on a actuellement sur le reste de l'UI? :)
