### ISSUE TITLE
UI color picker for deviceType = 'color'

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#300]
File views/device/index.ejs
Add color picker if `!type.sensor && type.type == 'color'`
But which one ? 
Some samples: http://angularjs.bestjquery.com/demo/color-picker/

**Comment by Pierre-Gilles** [comment]
Can be nice yes ! 

Maybe this one => 

https://tovic.github.io/color-picker/

( Written in pure JS )

**Comment by atrovato** [comment]
Ok, I will try to do it.

I can see an existing colorpicker at /assets/img/bootstrap-colorpicker/
But it seems that it is not used.

**Comment by atrovato** [comment]
Last pull request : https://github.com/GladysProject/Gladys/pull/404
