### ISSUE TITLE
Scénarios : disable a scenario

### ISSUE THREAD

**Issue by AlexDesign-Fr** [GladysAssistant/Gladys#312]
This is not an issue, but a new feature that can be add.

It would be nice to have the ability to disable a scenario without deleting it.
May be this feature can be add in the Scénarios > Mes scénarios page in a new column like "Edit" and "Supprimer".
The benefits will be to avoid a scenario to be triggered by an event and not to loose the code you've write  in.

**Comment by Pierre-Gilles** [comment]
+1
