### ISSUE TITLE
Issue when box path is wrong in a module

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#327]
When creating a module with a wrong box.view path, if we don't verify it and we add the wrong box on the dashboard, then, the dashboard fails to load due to missing data in ejs dasboard view.
You need to remove the box in db to be able to load again the dashboard.

Moreover, there is an issue on Title translation for box adding by a module, like if the title is trying to be translate with 'box-YouTitle-title'.

**Comment by Pierre-Gilles** [comment]
>When creating a module with a wrong box.view path, if we don't verify it and we add the wrong box on the dashboard, then, the dashboard fails to load due to missing data in ejs dasboard view.

Good idea!

> Moreover, there is an issue on Title translation for box adding by a module, like if the title is trying to be translate with 'box-YouTitle-title'.

You're right, actually the box system is only designed for internal use in Gladys, not for module use! 
Didn't had the time at the moment to think about the behavior for modules :)
