### ISSUE TITLE
Notification that are too long are cut on the notification dropdown  

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#334]
Ref => https://community.gladysproject.com/t/need-your-feedback-developpement-features/1525/122

**Comment by Hamtar0** [comment]
On Firefox 59.0.2 (64 bits) Mac ;)

**Comment by Hamtar0** [comment]
C'est vraiment corrigé ? J'ai pas l'affichage du contenu "text" des notifications...
<img width="281" alt="capture d ecran 2018-05-18 a 22 19 50" src="https://user-images.githubusercontent.com/1239484/40256393-91c82970-5aea-11e8-9365-b2957eeb0938.png">

**Comment by Pierre-Gilles** [comment]
Ah! On s'est mal compris, j'affiche toujours que le title mais je coupe plus le title. Je re-ouvre l'issue

**Comment by Hamtar0** [comment]
Et une petite notif flottante serait trop top

**Comment by Pierre-Gilles** [comment]
Fixed in next release! 

<img width="433" alt="capture d ecran 2018-07-21 a 20 37 08" src="https://user-images.githubusercontent.com/7365207/43039086-0d2d9fec-8d26-11e8-9f32-4eadfd5d34af.png">
