### ISSUE TITLE
Undefined module service from script

### ISSUE THREAD

**Issue by lTimeLordl** [GladysAssistant/Gladys#34]
I can't access to a module service from a script. Is undefined. Security or bug ?
`warn: In script error ReferenceError: KodiService is not defined`

**Comment by Pierre-Gilles** [comment]
Security! For now just "native" services are loaded in scripts ( here : https://github.com/GladysProject/Gladys/blob/master/api/services/ScriptService.js#L56 ). 
But you are right, we should be able to inject modules scripts into Gladys. I'll think about it ! :)

**Comment by lTimeLordl** [comment]
Ok, thanks :)
