### ISSUE TITLE
Node init.js error

### ISSUE THREAD

**Issue by Bagou450** [GladysAssistant/Gladys#350]
Hello

my error is in the node init.js command and here is the error

pi@raspberrypi:~/gladys $ node init.js
info: Could not find module: ejs in path: /home/pi/gladys/node_modules
error: Bootstrap encountered an error: (see below)
[TypeError: expecting a function but got [object

Bonjour
mon erreur est dans la commande node init.js et voici l'erreur

pi@raspberrypi:~/gladys $ node init.js
info: Could not find module: ejs in path: /home/pi/gladys/node_modules
error: Bootstrap encountered an error: (see below)
[TypeError: expecting a function but got [object

**Comment by Pierre-Gilles** [comment]
Have you installed Gladys dependencies with NPM/Yarn ?

**Comment by Bagou450** [comment]
J ai juste réinstaller Gladys et ca marche
