### ISSUE TITLE
Modules hdmicec

### ISSUE THREAD

**Issue by Bagou450** [GladysAssistant/Gladys#352]
Bonjour comment configurer ce module pour ma télévision et coment l'utiliser  . Avec des script?

**Comment by Pierre-Gilles** [comment]
Hello, pour toute question lié à l'utilisation de Gladys, merci d'aller sur le forum :) Nous utilisons Github pour tracker les problèmes/features à développer !

Le forum => https://community.gladysproject.com/

Merci d'avance,
