### ISSUE TITLE
Lack of documentation...

### ISSUE THREAD

**Issue by nux17** [GladysAssistant/Gladys#36]
Hello,

I managed to burn Gladys Floppy image to my Raspberry's SD Card, but what now ?

Everything bootep up, but nothing shows up, I can't connect to the local http server or else...

Could you please expand the "Getting Started" section to go further?

Thanks.

**Comment by Pierre-Gilles** [comment]
Hello,

Did you follow the instructions of the installations pages ? ( http://gladysproject.com/en/installation )

Did you expand the partition to fit the SD card size ?
