### ISSUE TITLE
Change "réveil" to "Alarme" in Gladys left menu

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#360]
https://community.gladysproject.com/t/need-your-feedback-developpement-features/1525/171

**Comment by aschelch** [comment]
Merci pour le merge ! J'imagine que cette issue peut-être fermée ;)

**Comment by VonOx** [comment]
@aschelch Tu peux la fermer toi même normalement. 😉

**Comment by aschelch** [comment]
Hmm non je ne crois pas. Je peux juste commenter !
