### ISSUE TITLE
Name device don't support special caracter in Control devices

### ISSUE THREAD

**Issue by Hamtar0** [GladysAssistant/Gladys#367]
<img width="362" alt="capture d ecran 2018-06-10 a 10 58 00" src="https://user-images.githubusercontent.com/1239484/41200016-4db3cafe-6c9d-11e8-9e49-1f4855dbde02.png">

**Comment by VonOx** [comment]
While updating ?

**Comment by Hamtar0** [comment]
Ok now ;)
