### ISSUE TITLE
Adding particle (spark) phothon support

### ISSUE THREAD

**Issue by chrigui** [GladysAssistant/Gladys#37]
Hi, great project, 
Can you please let me know how or tips to add support for spark photon WiFi support?
This will open an endless possibilitiesbecause most devices today are WiFi and/or Bluetooth enabled.

Thanks

**Comment by Pierre-Gilles** [comment]
Hi,

Of course your spark photon can communicate with Gladys :) Gladys is a server with an API, that mean that you can simply make HTTP request to Gladys server to tell Gladys something.

For example, if you want to tell Gladys a motion has been detected with your spark photon ( If you have connected a motion sensor to your photon ), just make an HTTP call to the URL : 

http://IP_OF_YOUR_RASPBERRY:1337/lifeevent/create?eventtype=motion&token=YOUR_ACCESS_TOKEN 

( with access token created in configuration panel on Gladys dashboard )

Possibilities are endless with the API ! 

Don't hesitate if you have any questions about it,

**Comment by chrigui** [comment]
Hi Pierre,

thank you for the easy reply!! i will give it a try 
my planned project will be as follows:

a smart greenhouse controller with hydroponics management:
- Wifi relays/Actuators using the raspberry pi
  http://unipi.technology/

2 photon weather stations (one inside and one outside the greenhouse)
https://www.sparkfun.com/products/13630

Hydroponics control:
https://www.whiteboxes.ch/tentacle/
and https://www.sparkfun.com/products/13321 

my plan is to use Gladys as a central automation app that triggers everything based on readings using user defined Scenarios.

i hope this gives you a good idea on what i have in mind and the bad news is i no nothing about programming heh

**Comment by Pierre-Gilles** [comment]
Okay I see your ideas :) 

Just buy a few modules and tests, that's a good point to start programming ! Don't hesitate if you have more questions
