### ISSUE TITLE
Guest mode for device control

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#374]
Hello,
I want to use gladys from a remote device (via http)  as a house remote control.
But I don't want to log on.
So I propose a guest mode to control some devices, without authentication.
This page can be accessible from home page, or maybe replace it. It will display all guest available devices, as a device control dashboard.

What's your opinion ?

Thx

**Comment by Pierre-Gilles** [comment]
It's already possible to generate a remote access token in Gladys parameters, that you can pass in the URL to authenticate automatically on your remote device :) 

Generate a token, then call any route of the [API](https://documentation.gladysproject.com/apidoc/) with the token in parameters. Ex:
 
```
POST /devicestate?token=XXXXXXXXXX
```

Security is really important in Gladys, unauthenticated route is really unsafe and is not something we want :)

**Comment by atrovato** [comment]
You're right.
I close this topic.
