### ISSUE TITLE
Ask preparationTimeAfterWakeUp in minutes

### ISSUE THREAD

**Issue by welcoMattic** [GladysAssistant/Gladys#375]
As we are humans, we often prepare ourselves in ~30min to ~1 hour. So Gladys may asks us `preparationTimeAfterWakeUp` in minutes, and converts the value in seconds itself. It'll improve UX detail by detail ;)

**Comment by Pierre-Gilles** [comment]
You are completely right! 

I just reworked on that view that was a little bit ugly, and here is the new form (not pushed yet) =>

<img width="405" alt="capture d ecran 2018-07-21 a 17 19 56" src="https://user-images.githubusercontent.com/7365207/43037152-6386caec-8d0a-11e8-956c-9152676b71a1.png">

**Comment by Pierre-Gilles** [comment]
Pushed, will be in next gladys release!
