### ISSUE TITLE
When you have a long name part of it disapear

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#381]
Hi,

It seems when you use a long name  at the top left of the WebApp a part of it disappears behind the main settings. 😅

![capture d ecran 2018-07-22 a 11 48 19](https://user-images.githubusercontent.com/5327696/43044401-6e426a86-8da5-11e8-8c80-65e5d3fc6cc2.png)

**Comment by Pierre-Gilles** [comment]
@MathieuAndrade Do you have any CSS tips for that? I tried but didn't succeed, CSS is not my thing 😅

**Comment by MathieuAndrade** [comment]
Ahah 

This is not the best solution but it works ! 

> style="max-width: 60% ; text-overflow: ellipsis; white-space: nowrap; overflow: hidden"

![image](https://user-images.githubusercontent.com/26581253/43045679-3f041fea-8dbd-11e8-94bb-ba8bdd2bcc06.png)

**Comment by Pierre-Gilles** [comment]
Nope, it doesn't work on all screen! 

<img width="229" alt="capture d ecran 2018-07-22 a 14 55 33" src="https://user-images.githubusercontent.com/7365207/43045785-50c636b2-8dbf-11e8-9e3f-b220599fe4a7.png">

**Comment by MathieuAndrade** [comment]
This issue can closed ;)
