### ISSUE TITLE
Beta 3.9 : devices graphs

### ISSUE THREAD

**Issue by PhilippeMA** [GladysAssistant/Gladys#382]
Hello,

just installed beta 3.9 manually (git pull + yarn upgrade).

Everything seems good, all updates are presents but i think there's a regression on devices graphs.

The dropdown list does not list the good list (mostly with blank text).

Thank you for this amazing job :+1:

**Comment by Pierre-Gilles** [comment]
Nice feedback, it's indeed  a problem. I'm correcting it

**Comment by PhilippeMA** [comment]
Correctif testé de mon côté aussi et validé !
