### ISSUE TITLE
Beta 3.9 : password modification

### ISSUE THREAD

**Issue by PhilippeMA** [GladysAssistant/Gladys#383]
When trying to modify my password, nothing happened. I try to click the update button many times but that doesn't work.

- Update with git pull + yarn upgrade
- No log with "pm2 logs"
- Database migration is ok

**Comment by Pierre-Gilles** [comment]
Hey! 

You need to do `grunt buildProd` when upgrading Gladys manually!

**Comment by PhilippeMA** [comment]
Thank you Pierre-Gilles. Sorry for this defect...
