### ISSUE TITLE
When a module is failing to install at reboot, it fails to install others

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#390]
https://community.gladysproject.com/t/tutoriel-controler-sa-freebox-gladys-v3/1497/61

**Comment by vincentBesseau** [comment]
On module.init function, you return a Promise.resolve(module) during Promise.map(modules, function(module){.
https://github.com/GladysProject/Gladys/blob/0a21759e8853e1fc3f6c1adfd0e4445e9c66863a/api/core/module/module.init.js#L55
