### ISSUE TITLE
Device box should use an API call get deviceType by ID instead of GET devicestate 

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#393]
Correct here => https://github.com/GladysProject/Gladys/blob/master/assets/js/app/device/device-value.box.controller.js#L90

**Comment by MathieuAndrade** [comment]
Hey ! 

Why want to use deviceType by ID instead of GET devicestate ? 🤔

**Comment by Pierre-Gilles** [comment]
Because the query is way less CPU intensive + so we are consistent between each page. 

We now store in the DeviceType the lastValue of the deviceType. 

Asking for the last deviceState is a query on a big table which can be slow.
