### ISSUE TITLE
Impossible to download gladys-3.8.0-rev2.img.zip

### ISSUE THREAD

**Issue by F4HTB** [GladysAssistant/Gladys#394]
Hello
Hello, 

It seems not possible to download gladys-3.8.0-rev2.img.zip.

Indeed, after a few minutes, the download stops and it is impossible to restart it except by clicking again on the link.

No problem of internet connection since I'm at the same time.

**Comment by Pierre-Gilles** [comment]
The file is hosted on GitHub release, but seems you are not the only one to have issues!

I have the feeling that Github is throttling file downloads... 

Can you try directly from the release page ?

https://github.com/GladysProject/Gladys/releases/tag/v3.8.0

( click on gladys-3.8.0-rev2.img.zip, don't download an older version, rev1 has some issues :)  )

I'm looking for a good mirror provider that could copy our file from GitHub and provide some download stats, but I haven't found any good service yet...

**Comment by Pierre-Gilles** [comment]
I just setup a new Gladys mirror available here =>

https://mirror-fr-1.gladysproject.com/releases/gladys-3.8.0-rev2.img.zip

It should be faster and works well this time! ;)
