### ISSUE TITLE
Device state/type value not large enough

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#405]
Device Type/State values are MySQL float type, but it is limited to 7 digits.
For the color device type (from 0 to 16777215 / from #000000 to #FFFFFF), we need 8 available digits.
The **double** column type accepts 16 digits values.
So it can be great to update value/lastValue columns from **float** to **double**.

```
alter table devicestate modify column value double;
alter table devicetype modify column lastValue double;
```

Do you agree ?

**Comment by Pierre-Gilles** [comment]
Good idea! sure! Is it still the case?

**Comment by atrovato** [comment]
To be able to fully use the color picker feature, we need this.
As I didn't change the SQL scheme queries, it is still the case.

I didn't change the SQL to let you be aware of this point, but we need it.

**Comment by Hamtar0** [comment]
I confirm we NEED it ! :p
