### ISSUE TITLE
Modules infos are not available at install-setup 

### ISSUE THREAD

**Issue by Boimb** [GladysAssistant/Gladys#406]
When You install or setup a module, you're likely to create devices with service and protocol.
As far as you don't know how the module has been named (in expert mode atleast) you have to force user to specify a given slug.
Passing module params to install & setup function could avoid problems and have more reliable code no ?

Let me know if it's ok. I'll do the patch.

**Comment by Pierre-Gilles** [comment]
Great idea! 👏
