### ISSUE TITLE
Echec d'installation Gladys

### ISSUE THREAD

**Issue by iTsmie** [GladysAssistant/Gladys#47]
Bonjour, tout dabord je te félicite de mener ce projet avec autant de serieux.

Je voudrais installer Gladys sur un raspberry avec la dernière version de "Jessie". donc j'install le prérequis, et a l'étape du : "npm install" dans le dossier gladys un ou plusieurs monule ne s'install pas je ne comprend pas tout étant débutant j'ai fais plusieurs recherches sans trouvé... 

voici l’erreur redondante après plusieurs réinstallation de jessie, gladys .... 

/

> speaker@0.2.6 install /home/pi/gladys/node_modules/speaker
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/gladys/node_modules/speaker
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! speaker@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the speaker@0.2.6 install script.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/gladys
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
|

> lame@1.2.3 install /home/pi/gladys/node_modules/lame
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/gladys/node_modules/lame
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

> serialport@2.0.5 install /home/pi/gladys/node_modules/serialport
> node-pre-gyp install --fallback-to-build

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/gladys/npm-debug.log
npm ERR! not ok code 0

**Comment by Pierre-Gilles** [comment]
Salut ! Tu as un Raspberry Pi B/B+ ou 2 ? Si tu as un 2, tu as une image Raspbian toute faite qui fonctionne directement juste en clonant l'image, rien à installer ! http://gladysproject.com/fr/installation ( l'image a quelques soucis actuellement sur Raspberry Pi B/B+ )

**Comment by iTsmie** [comment]
Bonjour, j'ai le 2. j'ai vus votre image mais j'aurais voulu conservés quelques fonctionnalité du raspi pour d'autre utilisation. je vais tout de mëme tester l'image.

**Comment by iTsmie** [comment]
l'interface graphique est juste désactivé sur ton image ? qu'a tu de moins par rapport a la version classique ?

**Comment by Pierre-Gilles** [comment]
En fait l'image que j'ai fais pars de "Raspbian Jessie Lite" ( https://www.raspberrypi.org/downloads/raspbian/ ), il me semble que le bureau est désactivé (on ne peut se connecter qu'en ligne de commande), et de base il y a peu de packets installés !

**Comment by VonOx** [comment]
@iTsmie As tu testé la dernière image ?

**Comment by bmedy** [comment]
C'est le paquet node-speaker qui plante pendant l'install.

Tu peux resoudre le proble avec cette commande :
`sudo apt-get install libasound2-dev`

[Plus d'infos sur le github du projet](https://github.com/TooTallNate/node-speaker)
