### ISSUE TITLE
Fix system view UI

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#494]
![Docker](https://user-images.githubusercontent.com/7365207/60228499-71fe9600-98c5-11e9-90d4-7c91e18ebc5f.png)

**Comment by VonOx** [comment]
% :)

![DiskUsage](https://user-images.githubusercontent.com/1528694/60286805-93d13a80-9910-11e9-9a31-d0a9ea918a30.png)
