### ISSUE TITLE
Find a way to give unique name to devices with a number when a device already exist

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#511]
Ex:

"Motion Sensor 1"
"Motion Sensor 2"

**Comment by Pierre-Gilles** [comment]
https://community.gladysassistant.com/t/proposition-ajouter-un-nombre-aleatoire-a-4-chiffres-a-tous-les-selector-pour-eviter-les-collisions/6617

**Comment by atrovato** [comment]
Not stale.

**Comment by Pierre-Gilles** [comment]
Not stale, PR in progress here : https://github.com/GladysAssistant/Gladys/pull/1336
