### ISSUE TITLE
Problem with battery / battery-sensor category

### ISSUE THREAD

**Issue by damalgos** [GladysAssistant/Gladys#514]
When you use battery as a category, in some case it use 'battery' and some other 'battery-sensor'. Difference between front and server.

For exemple: 
https://github.com/GladysAssistant/Gladys/blob/d48fb2f3dcd3841bcb654624a57a23892bbf8e6d/front/src/components/boxs/device-in-room/device-features/SensorDeviceFeature.jsx#L9

And other one:
https://github.com/GladysAssistant/Gladys/blob/d48fb2f3dcd3841bcb654624a57a23892bbf8e6d/server/utils/constants.js#L204

Here you can see that on the server the constant is **battery** and on front it's **battery-sensor**.

**Comment by Pierre-Gilles** [comment]
Nice catch! :)

For now the box "device-in-room" is really work in progress, I was waiting to get more device compatible to better understand how everything is going to work.
