### ISSUE TITLE
Non Docker Install

### ISSUE THREAD

**Issue by yonghan** [GladysAssistant/Gladys#518]
Some people would prefer a non docker install on their Linux machine.

So I wonder if you guys can provide a quick tutorial on how we can download and install them without using Docker?

Thanks.

**Comment by Pierre-Gilles** [comment]
Hey!

You can follow developer instructions how to install Gladys manually without Docker here =>

https://documentation.gladysassistant.com/en/development#setup-env

**Comment by Pierre-Gilles** [comment]
Note that this type of installation is more useful for development purposes. I strongly recommend using Docker for production use.

**Comment by cloudstudio** [comment]
Hello @Pierre-Gilles I try to install Gladys with Docker, I try all 3.** versions, but allways get same error : 

Unhandled rejection Error: Could not connect to MySQL:

![Captura de pantalla 2019-08-20 a las 21 20 05](https://user-images.githubusercontent.com/3589377/63377397-57f6a680-c390-11e9-8a7f-0fa5b2c7b485.png)

Which version can I use, to try Gladys ? I prefer v3 to check all modules.

Thanks for you time !

**Comment by Hamtar0** [comment]
You have to follow this post : 
https://gladysassistant.com/fr/article/gladys-et-docker

But it could be a little tricky to configure all you want with v3 and Docker.

**Comment by cloudstudio** [comment]
And what is te best option ? I just want try Gladys with all funcionality 

Thanks

**Comment by Hamtar0** [comment]
I am not the good person to advice you on this subject.
Depend of what you've got at your house, if you have a raspberry pi or not, a Mac etc...

**Comment by Oelus** [comment]
Possible to install v4 on CentOS?

**Comment by Hamtar0** [comment]
If you can install Docker on CentOS, why not ?
V4 run on Docker.

**Comment by Pierre-Gilles** [comment]
Closing this, please use our community for support => https://community.gladysassistant.com/ :) 

GitHub issues are used for development purposes!
