### ISSUE TITLE
[DOCS] Inconsistence in docker run command

### ISSUE THREAD

**Issue by quentin-legraverend** [GladysAssistant/Gladys#520]
Hi there,

A little inconsistence in the [installation doc of Gladys 4](https://documentation.gladysassistant.com/fr/installation#raspberry-pi).

In this command:
```
docker run -d \
--privileged \
-p 80:1443 \
--network=host \
--name gladys \
-e NODE_ENV=production \
-e TZ=Europe/Paris \
-e SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /var/lib/gladysassistant:/var/lib/gladysassistant \
-v /dev:/dev \
gladysassistant/gladys:4.0.0-alpha-arm
```
you can't use the option `--network:host` in conjonction with port mapping (`-p`). Here is what docker will tell you in that case:
```
WARNING: Published ports are discarded when using host network mode
```

So, actually this docker run command will expose Gladys 4 on the host network on port 1443, which is (apparently) not the intended behaviour.

Personally, I have juste remove the `--network=host` option.

**Comment by Pierre-Gilles** [comment]
Hey! Thanks for the feedback, we had the same error, I think we'll simply change the exposed port in the Dockerfile to expose directly the 80 port. 

Keeping this issue as a todo.

**Comment by Pierre-Gilles** [comment]
Fixed in the docker image + in the doc :)
