### ISSUE TITLE
RTSP login fields

### ISSUE THREAD

**Issue by Hamtar0** [GladysAssistant/Gladys#538]
Fields for login instead of URL with variables must be better appropriate.

**Comment by atrovato** [comment]
@Pierre-Gilles for this topic, we may need to think about a generic username/password on a device, to not store it in device params array, and to not send it over rest API.
I will get the case for Tasmota HTTP devices, I may need to store credentials for each device.

**Comment by Pierre-Gilles** [comment]
@atrovato Rather than doing something "magic" based on the name, I think we should just add a attribute to the device_param table, like "secret": boolean, which would do what you described :) 

Good idea!

**Comment by atrovato** [comment]
@Pierre-Gilles I was thinking on a new DB table "t_credentials", which can be used by devices and services (ie: mqtt credentials).
Stored in base64 encoded, linked on item (device or service) unique id.

**Comment by Pierre-Gilles** [comment]
I don't think we need a new table, we already have those use-cases in Gladys.

- if it's linked to a device, it should be in the `t_device_param` table
- if it's linked to a service, it should be in the `t_variable` table

But I agree that we can modify those tables to handle secrets in a more secure way.

**Comment by atrovato** [comment]
Ok, I propose a separated PR for secret params.
For RTSP, username/password are not always in the url as `rtsp://{username}:{password}@url` but only this case will be managed (asap in another PR).

**Comment by Pierre-Gilles** [comment]
Great PR! 

Mmm just saw that this PR relies on the "secret params" PR... 

I'm not sure what's the next step then... 

Waiting for your input!
