### ISSUE TITLE
MQTT handle broker configuration error

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#540]
**Describe the bug**
On MQTT configuration page, when invalid broken information are set, an error is expected, but the message stay as "pending".

**Expected behavior**
A red message with "connection error" should appear.

**Additional context**
Gladys V4

**Comment by Pierre-Gilles** [comment]
Good feedback, I tried to put one but for now I didn't manage to make it work. The MQTT library isn't sending any event in case of wrong informations. 

Even when setting manually a timeout in the lib parameter, no "error" event is sent! If you have any idea why, let me know.

In case we don't find a solution, we can put a timeout on the frontend side separated from the library.. but that's not a great solution

**Comment by atrovato** [comment]
Issue already opened : https://github.com/mqttjs/MQTT.js/issues/984

**Comment by Pierre-Gilles** [comment]
Ok, I don't think they'll fix that soon so we can maybe put a timeout on our side.

**Comment by atrovato** [comment]
This PR may fix our need https://github.com/mqttjs/MQTT.js/pull/1003
