### ISSUE TITLE
Devices view in config service Xiaomi

### ISSUE THREAD

**Issue by Hamtar0** [GladysAssistant/Gladys#542]
When you add a device from Xiaomi in Gladys, it doesn't dissapear from the first list on detected devices.

**Comment by Hamtar0** [comment]
You can add the same fix on the hue config page ! :p

**Comment by Pierre-Gilles** [comment]
It should be done!

**Comment by Hamtar0** [comment]
Ok maybe a cache problem. Solved now ! Thx ! ;)
