### ISSUE TITLE
Better information to add Xiaomi Gateway in Xiaomi service

### ISSUE THREAD

**Issue by Hamtar0** [GladysAssistant/Gladys#547]
Impossible to connect SID of a gateway in Gladys with the official app Xiaomi to know wich gateway is...
Better way it's to put local IP of the gateway, this information is present on the official app.

**Comment by Hamtar0** [comment]
I think you can remove sid field of the gateway to keep the same box size between devices and gateways.

**Comment by Pierre-Gilles** [comment]
are you sure the sid is useless for the gateway?

**Comment by Hamtar0** [comment]
Right now, yes even to manage action devices.
In the future, don't know. You can always hide it.
