### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#549]
You hard wrote the documentation URL.
I may be useful to have a shared component, or a property for the base URL.

I saw this according to Xiaomi service, and the reference to the online user documentation, and I will need to do same in future services.

PS: and it will be better to open it in a new browser window/tab `<a target="_blank" .. />`.

**Comment by Pierre-Gilles** [comment]
Yes good points !

**Comment by atrovato** [comment]
See `DeviceConfigurationLink` component on PR #519
