### ISSUE TITLE
Articial Intelligence - Gladys with AI ?

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#55]
Hello there, 

can Gladys have an Articial Intelligence, can be learn and do itself like Watson from IBM :) 

Well do u think we can add it on Articial Intelligence for gladys ?

a way to learn itself

it will be cool :)

**Comment by Pierre-Gilles** [comment]
Did you read my last article ? :) I talk about machine learning in Gladys, it's currently in progress for Gladys 3.0 !

http://gladysproject.com/fr/article/gladys-3-features

**Comment by ghost** [comment]
Non je n'avais pas lu cette article !
Bon c'est cool,

je vais tester ça  :)
