### ISSUE TITLE
rfxcom

### ISSUE THREAD

**Issue by bilbao77** [GladysAssistant/Gladys#551]
Hello Jean-Philippe

I installed gladys on raspi with rfxcom antenna (RFXtrx433).
I install FHEM too.
I used some PIR sensor KERUI.

I receive correctly somme data from a weather station .

but for the PIR I receive an error :

ERROR: > < returned by the TRX_LIGHT ParseFn is invalid, notify the module maintainer

do you know what's going on ?

regards
Romain

**Comment by Pierre-Gilles** [comment]
Following my feedback (https://community.gladysassistant.com/t/alarme-avec-fhem-rfxcom/4936/4), closing this.
