### ISSUE TITLE
On/Off for a room bug

### ISSUE THREAD

**Issue by Hamtar0** [GladysAssistant/Gladys#567]
See the gif, the main "on/off" stay "on" when only one binary device change to off (and all other on off before)

![test](https://user-images.githubusercontent.com/1239484/67230085-e5ac4c00-f43c-11e9-8a23-b4fcd507e195.gif)

**Comment by Hamtar0** [comment]
And the general "on/off" keep his state "off" when only one device set on "on", or added one by one...

**Comment by Pierre-Gilles** [comment]
Thanks for the feedback! I thought I handled this case, but seems it's not working :p 

I'll check !
