### ISSUE TITLE
Module Météo reste bloquer sur le loader

### ISSUE THREAD

**Issue by FabienMoudurier** [GladysAssistant/Gladys#57]
Bonjour;
je suis nouveau sur Gladys, et après quelques difficultés pour l'installation.
Le module météo ne s'actualise pas.
J'ai un peux farfouiller et le problème chez moi vient de la lib "simpleweather v3.0.2", mais qui sont résolues en passant à la version 3.1.0.

2ème question: pourquoi avoir abandonné open weather?

3ème question: pourquoi passer par une lib qui prend pas en compte la position des logements ajoutés dans Gladys, mais uniquement la géolocalisation?

Merci

**Comment by Pierre-Gilles** [comment]
Bonjour,

Tout d'abord bienvenue dans le projet ! 

1) Je suis conscient du problème, je ne l'ai pas corrigé ici car je travaille à fond sur la v3 de Gladys, et je voulais quitter simpleWeather pour cette v3 du coup j'ai pas plus fouillé que ça comment corriger le problème. Après si la maj de simpleWeather 3.0.2 à 3.1 corrige le bug, je vais regarder ça en attendant pour la v2 :)

2) OpenWeather nécessite maintenant une clé d'API ( ce n'était pas le cas avant ) , du coup c'était contraignant de demander systématiquement aux utilisateurs de rentrer une clé en installant Gladys. Déjà qu'on doit le faire pour Google API, ça fait beaucoup sinon !

3) La lib ne prend pas en compte la géolocalisation, c'est moi qui dans le code client Gladys demande la localisation du navigateur et passe cette géoloc à la lib. C'est voulu, en fait je me suis que quand tu es sur le navigateur ( sur ton PC ou mobile ) tu veux la météo où tu es, plus que où est ta maison, non ? Après on peut faire plusieurs widgets, un pour la température où tu es, et un où est ta maison. Et pour la température où est la maison mieux vaut la valeur d'une sonde de température à mon avis.

J'espère que j'ai répondu à tes questions !

**Comment by FabienMoudurier** [comment]
Merci beaucoup pour tes réponses. Je me doutais un peu des réponses mais je préférais quand même les poser.
