### ISSUE TITLE
Feature name is mandatory

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#575]
According to device boxes, feature name can be `null` or `undefined`.
But according to `device_feature.js` model, it is mandatory.

I think it would be better to let it optional, and to keep the `SensorDeviceFeature` box solution: 
```
if (feature.name) {
  return feature.name;
} else {
  return device.name + ' - ' + feature.type;
}
```

What do you think about it ?

**Comment by Pierre-Gilles** [comment]
This device box is the device box of the gateway, which was done on Gladys 3 which supports null/undefined feature name.

In Gladys 4, I don't think we want null feature name. 

What's the use case?

**Comment by atrovato** [comment]
Some integrations discover devices over the network and creates related features. But features name is generated from device name, with ` -feature.type` concatened.

If the feature name is left empty, the UI can handle it, generating the same format ( with ` - feature.type` ) but can be catch by i18n.

**Comment by Pierre-Gilles** [comment]
Yes it's true that we can do better that how it's done right now, and work on i18n.

The question is always: will it be shown in UI, and if yes: where?

I don't think allowing null is a good idea. Putting a name is a way to make it clear, even on the developer side in the DB.

**Comment by Pierre-Gilles** [comment]
I think it's ok if all integrations are not doing the same thing. 

For example, a camera device-feature name will never be displayed!

**Comment by atrovato** [comment]
Ok I undestand, let see case by case.
