### ISSUE TITLE
Démo en ligne

### ISSUE THREAD

**Issue by adamotte** [GladysAssistant/Gladys#6]
Je pense que ca serait une vrai plus value pour aider au lancement de la 2.0 d'ajouter une section de démonstration au site [gladysproject.com](http://gladysproject.com) afin d'apprécier - sans être un développeur - cette nouvelle version. :+1:

**Comment by Pierre-Gilles** [comment]
Tout à fait cela pourrait être une idée, il faudrait créer une image statique de Gladys afin que tout le monde puisse tester. Après les interactions seront limités, mais c'est une idée :+1:
