### ISSUE TITLE
Mauvais format de date sur le Graphe d'un device

### ISSUE THREAD

**Issue by Jean-PhilippeD** [GladysAssistant/Gladys#60]
Hello,
Lorsqu'on est sur le graphe d'un device, et qu'une valeur vient s'ajouter dynamiquement, le format de date est pas le même que les autres valeurs :)
Par ailleurs, il y a un reste de console.log() qui traine ligne 119 du device.controller.js

**Comment by atrovato** [comment]
Bonjour,
après quelques investigations, cela vient du fait qu'il manque l'information "dateFormat" dans l'objet "state" émit par _deviceState.create.js_.
Lors de la récupération des valeurs, la requête SQL ajoute "dateFormat" avec le format '%d %b %Y %T' (voir _deviceState.queries.js_).
Je laisse désormais les experts juger de la meilleure solution pour ajouter la date formatées proprement.

**Comment by MathieuAndrade** [comment]
Salut ! 
J'ai corrigé ce problème qui partira dans dans ma prochaine PR 🙂
