### ISSUE TITLE
Slack service

### ISSUE THREAD

**Issue by callemand** [GladysAssistant/Gladys#603]
**Is your feature request related to a problem? Please describe.**
Add slack service to discuss with gladys like telegram

**Describe the solution you'd like**
Create slack service like telegram service into communication section
Use slack rtm-api : https://www.npmjs.com/package/@slack/rtm-api

**Additional context**
I have already made all the developement

**Comment by atrovato** [comment]
> I have already made all the developement

So, why not a pull request ?

**Comment by callemand** [comment]
I'm on it :)

**Comment by callemand** [comment]
https://github.com/GladysAssistant/Gladys/pull/604

**Comment by Pierre-Gilles** [comment]
Closing this as we don't use Github for feature requests (we use the forum for that: https://community.gladysassistant.com/) but only for bug tracking
