### ISSUE TITLE
Ampoule Philips Hue E27 White and color ambiance

### ISSUE THREAD

**Issue by tlse-vins** [GladysAssistant/Gladys#623]
[{"name":"lampe canapé","service_id":"fa3e4161-a56b-4d12-b43f-5caa515548ec","external_id":"philips-hue-light:ecb5fa247b6c:1","selector":"philips-hue-light:ecb5fa247b6c:1","should_poll":true,"model":"LCA001","poll_frequency":60000,"features":[],"not_handled":true,"raw_philips_hue_device":{"_rawData":{"state":{"on":true,"bri":254,"hue":41424,"sat":97,"effect":"none","xy":[0.2953,0.3169],"ct":153,"alert":"none","colormode":"xy","mode":"homeautomation","reachable":true},"swupdate":{"state":"noupdates","lastinstall":null},"type":"Extended color light","name":"lampe canapé","modelid":"LCA001","manufacturername":"Philips","productname":"Hue color lamp","capabilities":{"certified":true,"control":{"mindimlevel":200,"maxlumen":800,"colorgamuttype":"C","colorgamut":[[0.6915,0.3083],[0.17,0.7],[0.1532,0.0475]],"ct":{"min":153,"max":500}},"streaming":{"renderer":true,"proxy":true}},"config":{"archetype":"classicbulb","function":"mixed","direction":"omnidirectional","startup":{"mode":"safety","configured":true}},"uniqueid":"00:17:88:01:08:36:ee:db-0b","swversion":"1.53.3_r27175","swconfigid":"297C5CDD","productid":"Philips-LCA001-5-A19ECLv6"},"_id":1,"mappedColorGamut":"C"}},{"name":"plafonier","service_id":"fa3e4161-a56b-4d12-b43f-5caa515548ec","external_id":"philips-hue-light:ecb5fa247b6c:2","selector":"philips-hue-light:ecb5fa247b6c:2","should_poll":true,"model":"LCA001","poll_frequency":60000,"features":[],"not_handled":true,"raw_philips_hue_device":{"_rawData":{"state":{"on":false,"bri":107,"hue":42611,"sat":94,"effect":"none","xy":[0.2976,0.3054],"ct":153,"alert":"none","colormode":"xy","mode":"homeautomation","reachable":true},"swupdate":{"state":"noupdates","lastinstall":"2019-11-30T12:41:53"},"type":"Extended color light","name":"plafonier","modelid":"LCA001","manufacturername":"Philips","productname":"Hue color lamp","capabilities":{"certified":true,"control":{"mindimlevel":200,"maxlumen":800,"colorgamuttype":"C","colorgamut":[[0.6915,0.3083],[0.17,0.7],[0.1532,0.0475]],"ct":{"min":153,"max":500}},"streaming":{"renderer":true,"proxy":true}},"config":{"archetype":"classicbulb","function":"mixed","direction":"omnidirectional","startup":{"mode":"custom","configured":true,"customsettings":{"bri":185,"xy":[0.4946,0.3266]}}},"uniqueid":"00:17:88:01:08:36:de:6a-0b","swversion":"1.53.3_r27175","swconfigid":"297C5CDD","productid":"Philips-LCA001-5-A19ECLv6"},"_id":2,"mappedColorGamut":"C"}},{"name":"bandeau led","service_id":"fa3e4161-a56b-4d12-b43f-5caa515548ec","external_id":"philips-hue-light:ecb5fa247b6c:3","selector":"philips-hue-light:ecb5fa247b6c:3","should_poll":true,"model":"LST002","poll_frequency":60000,"features":[{"name":"bandeau led On/Off","read_only":false,"has_feedback":false,"external_id":"philips-hue-light:ecb5fa247b6c:3:binary","selector":"philips-hue-light:ecb5fa247b6c:3:binary","category":"light","type":"binary","min":0,"max":1},{"name":"bandeau led Color","read_only":false,"has_feedback":false,"external_id":"philips-hue-light:ecb5fa247b6c:3:color","selector":"philips-hue-light:ecb5fa247b6c:3:color","category":"light","type":"color","min":0,"max":0},{"name":"bandeau led Brightness","read_only":false,"has_feedback":false,"external_id":"philips-hue-light:ecb5fa247b6c:3:brightness","selector":"philips-hue-light:ecb5fa247b6c:3:brightness","category":"light","type":"brightness","min":0,"max":100},{"name":"bandeau led Temperature","read_only":false,"has_feedback":false,"external_id":"philips-hue-light:ecb5fa247b6c:3:temperature","selector":"philips-hue-light:ecb5fa247b6c:3:temperature","category":"light","type":"temperature","min":153,"max":500}]}]

**Comment by hotfix31** [comment]
"modelid":"LCA001"
