### ISSUE TITLE
ampoule phillips Hue GU10 - LWG004

### ISSUE THREAD

**Issue by tlse-vins** [GladysAssistant/Gladys#628]
_id\":8}},{\"name\":\"spot évier 1\",\"service_id\":\"fa3e4161-a56b-4d12-b43f-5caa515548ec\",\"external_id\":\"philips-hue-light:ecb5fa247b6c:9\",\"selector\":\"philips-hue-light:ecb5fa247b6c:9\",\"should_poll\":true,\"model\":\"LWG004\",\"poll_frequency\":60000,\"features\":[],\"not_handled\":true,\"raw_philips_hue_device\":{\"_rawData\":{\"state\":{\"on\":false,\"bri\":254,\"alert\":\"select\",\"mode\":\"homeautomation\",\"reachable\":true},\"swupdate\":{\"state\":\"noupdates\",\"lastinstall\":\"2019-12-08T10:01:06\"},\"type\":\"Dimmable light\",\"name\":\"spot évier 1\",\"modelid\":\"LWG004\",\"manufacturername\":\"Philips\",\"productname\":\"Hue white spot\",\"capabilities\":{\"certified\":true,\"control\":{\"mindimlevel\":2000,\"maxlumen\":400},\"streaming\":{\"renderer\":false,\"proxy\":false}},\"config\":{\"archetype\":\"spotbulb\",\"function\":\"functional\",\"direction\":\"downwards\",\"startup\":{\"mode\":\"safety\",\"configured\":true}},\"uniqueid\":\"00:17:88:01:08:3c:6e:b7-0b\",\"swversion\":\"1.55.7_r28193\",\"swconfigid\":\"A7C27E3B\",\"productid\":\"Philips-LWG004-1-GU10DLv2\"},\"_id\":9}}]","mode":"application/json"}}}

**Comment by hotfix31** [comment]
```json
{
    "name": "spot évier 1",
    "service_id": "fa3e4161-a56b-4d12-b43f-5caa515548ec",
    "external_id": "philips-hue-light:ecb5fa247b6c:9",
    "selector": "philips-hue-light:ecb5fa247b6c:9",
    "should_poll": true,
    "model": "LWG004",
    "poll_frequency": 60000,
    "features": [],
    "not_handled": true,
    "raw_philips_hue_device": {
        "_rawData": {
            "state": {
                "on": false,
                "bri": 254,
                "alert": "select",
                "mode": "homeautomation",
                "reachable": true
            },
            "swupdate": {
                "state": "noupdates",
                "lastinstall": "2019-12-08T10:01:06"
            },
            "type": "Dimmable light",
            "name": "spot évier 1",
            "modelid": "LWG004",
            "manufacturername": "Philips",
            "productname": "Hue white spot",
            "capabilities": {
                "certified": true,
                "control": {
                    "mindimlevel": 2000,
                    "maxlumen": 400
                },
                "streaming": {
                    "renderer": false,
                    "proxy": false
                }
            },
            "config": {
                "archetype": "spotbulb",
                "function": "functional",
                "direction": "downwards",
                "startup": {
                    "mode": "safety",
                    "configured": true
                }
            },
            "uniqueid": "00:17:88:01:08:3c:6e:b7-0b",
            "swversion": "1.55.7_r28193",
            "swconfigid": "A7C27E3B",
            "productid": "Philips-LWG004-1-GU10DLv2"
        },
        "_id": 9
    }
}
```
