### ISSUE TITLE
Translate Gladys 4 in French

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#634]

**Comment by atrovato** [comment]
Hi,
we may use [compare-json](https://www.npmjs.com/package/compare-json) to check if translate files are similar.

**Comment by atrovato** [comment]
I just check for more plugin, I found eslint-plugin-preact-i18n which looks fine.
I propose a PR #644 to check this. But for now, there is around 150 i18n errors.

**Comment by Pierre-Gilles** [comment]
Really nice! Thanks for finding this! We will merge this when translating in french.

**Comment by Terdious** [comment]
Hi,
@atrovato, I just installed your fork for the resumption of the texts which were in hard. I'm starting to look, so I could come back here to report what I find. I also intended to put my translation file in fr there (you will just have to replace the file in to test it. Is that okay with you, do you want me to modify the texts by remaining hard or do I only give you the links?
The first :
- https://github.com/atrovato/Gladys/blob/compare-translation-files/front/src/routes/signup/layout.jsx: lines 34, 46, 58, 70 and 82.

I continue this weekend.
Looking forward

**Comment by atrovato** [comment]
@Terdious it fine for me, send me the 'fr' file, I will test it.
Thank for the remaining hard coded texts, I will check another time :)

**Comment by atrovato** [comment]
Ok, I check again for all hard coded texts (added `--ext .jsx` to front `eslint`), and fixed around 150 errors. Now `en.json` translation file should be complete.

**Comment by Terdious** [comment]
Hi @atrovato 

[Fichier fr en .txt](https://github.com/GladysAssistant/Gladys/files/4271440/fr.txt)
[Fichier weather en .txt](https://github.com/GladysAssistant/Gladys/files/4271443/weather.fr.txt)
[Fichier communication en .txt](https://github.com/GladysAssistant/Gladys/files/4271444/communication.fr.txt)
[Fichier device en .txt](https://github.com/GladysAssistant/Gladys/files/4271445/device.fr.txt)

**Comment by atrovato** [comment]
Hi @Terdious , please find the result of FR analysis, missing keys

[cr_trad_fr.txt](https://github.com/GladysAssistant/Gladys/files/4271453/cr_trad_fr.txt)

**Comment by Terdious** [comment]
@atrovato 
Sorry, I was delayed !!
Attached the new file, on should not be too bad. I also put you on the Galdys community screenshots of the texts that I find in English.
[fr.txt](https://github.com/GladysAssistant/Gladys/files/4272276/fr.txt)
[en.txt](https://github.com/GladysAssistant/Gladys/files/4281565/en.txt)

**Comment by Pierre-Gilles** [comment]
Is PR #644 ready for merge?

Thanks for the great work !! :)
