### ISSUE TITLE
Setup Gladys 4 RC Distribution process

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#635]
- [x] Setup CircleCI to build Docker image on tag only, and push it on Docker hub on latest + :v4 tags (without `-beta`)
- [x] Build Raspbian image based on Docker image with tag without `-beta`
- [x] The Raspbian image should silently do security upgrade at night

**Comment by Pierre-Gilles** [comment]
@VonOx Image Raspbian built with all new parameters (expand filesystem, new docker run, unattended upgrade)

The command I used to start gladys is:

```
docker run -d \
--log-opt max-size=10m \
--restart=always \
--privileged \
--network=host \
--name gladys \
-e NODE_ENV=production \
-e SERVER_PORT=80 \
-e TZ=Europe/Paris \
-e SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /var/lib/gladysassistant:/var/lib/gladysassistant \
-v /dev:/dev \
gladysassistant/gladys:v4-arm
```

I didn't use the `gladysassistant/gladys:v4` without `-arm` because the manifest part is still an experimental feature and I don't want to enable experimental features on a prod environnement. 

You can download the image here: https://github.com/GladysAssistant/Gladys/releases/download/v4.0.0-beta.15/gladys-v4-rev1.img.zip

Let me know if you have feedbacks :)

**Comment by VonOx** [comment]
> I didn't use the `gladysassistant/gladys:v4` without `-arm` because the manifest part is still an experimental feature and I don't want to enable experimental features on a prod environnement.

Maybe I misunderstood but the command `docker manifest` is experimental , not the builded/tagged image

gladys:v4 = gladys:v4-arm , in 2 cases you are using manifest , this is not the tag that define arch but the annotate command.

https://github.com/GladysAssistant/Gladys/blob/master/.circleci/config.yml#L165

To illustrate i can easily use this command to annotate the manifest
`docker manifest annotate $DOCKERHUB_REPO:$CIRCLE_TAG $DOCKERHUB_REPO:$CIRCLE_TAG-amd64 --os linux --arch arm --variant v6;` 

amd64 tag for arm arch 

-----

In your example , with the gladysassistant/gladys:v4-arm tag , manifest is still checked because it exist ( via docker run )

**Comment by Pierre-Gilles** [comment]
Ok, let me explain. I did on my Raspberry Pi v1 (ARMv6) 

```
docker pull gladysassistant/gladys:v4
```

And it didn't work, it pulled the wrong image, not in the right architecture. 

I guess it's because it can't choose with the manifest and picked the amd64 one by default. 

Maybe I misunderstood what the manifest does?

**Comment by VonOx** [comment]
> it pulled the wrong image, not in the right architecture.

Can you `docker inspect` pulled image please ?

I will install your image for testing

**Comment by Pierre-Gilles** [comment]
Mmm sorry it's not running anymore :/

But I checked the sha-256 of the image started, and it was not the sha-256 of any image on Docker hub (couldn't find which image it was on Docker hub)

**Comment by VonOx** [comment]
Expand FS not working

For docker , what I've done:

Cleaning pulled image, you can see weird untagged image
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
gladysassistant/gladys   v4-arm              2536dcb55c96        41 hours ago        433MB
containrrr/watchtower    armhf-latest        84378f5d38aa        3 months ago        13.3MB
pi@gladys:~$ docker images prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
**untagged: gladysassistant/gladys:v4-arm
untagged: gladysassistant/gladys@sha256:9e0a334d785c59ac46da1d1150e1392814d76687d600b33299a0c9c2f8eb35e3**
deleted: sha256:2536dcb55c96153b4f6dbdbd4a8107aedb1748d9221cf6743ad273ab55821013
deleted: sha256:69291c13a9a3073258e1df57901047cfe0764525ee4f40929ae9559f7f7e62bd
deleted: sha256:4d25a0dc5f4b3bf9902952c097d9e0adf7436a4b39ad0ef4604ea3fe93bd0bae
deleted: sha256:4040886a0cff9a97c31cd8e3b10ee1f1b9c35ccc5dc3d09bf02de0111dffff82
deleted: sha256:915a5115396f901c004c9b0de9c5a90af4a01cc8ae4f2fa46665d548bf450d7b
deleted: sha256:1fd27c28221e013cf2af5790d85d5fc85186c89ac7372d013f4a85785029ed24
deleted: sha256:4db83f847b825e01d414bace60fb96ae7fc99876f759374b4b95b624e40fabd8
deleted: sha256:6d85148872aab2e84e9dd0bb12caf68dfe2579e4f6b3a1ad35f3224e5a2092a2
deleted: sha256:901e548699effef6b3b94610935951766cafb5896513a994a21cad2acf5b830d
deleted: sha256:0b2bfed008ce04b10e18c1114e62a5dcd3a1fc6dd4a362a0912e94e24e7ca12d
deleted: sha256:7635d463d59002b292f46607f7b46917eb9bb7cac41cc8d8156a32a272a6ce01
deleted: sha256:e5318f3e9ac2e50f55164454b4ddaf4b4a47648c7fae108947091a9e122bb102

Total reclaimed space: 432.9MB
```
Pull v4 image
```
pi@gladys:~$ docker pull gladysassistant/gladys:v4
v4: Pulling from gladysassistant/gladys
3cfb62949d9d: Pull complete
9f88341ca4dc: Pull complete
5765f8fb68cd: Pull complete
ed6b46590934: Pull complete
60424f6b4b2f: Pull complete
b6db33421039: Pull complete
616d9726bdd4: Pull complete
b1da51b26730: Pull complete
75a018144c70: Pull complete
7b2158ad2891: Pull complete
462d56daa45d:  Pull complete
```
Digest
```
pi@gladys:~$ docker images --digests
REPOSITORY               TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
gladysassistant/gladys   v4                  sha256:b37c86adbce1447124c588946c5b3d4d0b0dd284b1c7f196d9f622eb11e63e56   afc020f61782        42 hours ago        417MB
containrrr/watchtower    armhf-latest        sha256:d93d72542f241a8f3411b66f5c9d9ab5fd3386af48f0b156bcd400d3a62e9d33   84378f5d38aa        3 months ago        13.3MB
```

Dockerhub repo is buggy because latest image was createg 1 day ago ( not 42 hours )

Pull image by sha256
```
 docker pull gladysassistant/gladys@sha256:9e0a334d785c59ac46da1d1150e1392814d76687d600b33299a0c9c2f8eb35e3


REPOSITORY               TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
gladysassistant/gladys   <none>              sha256:9e0a334d785c59ac46da1d1150e1392814d76687d600b33299a0c9c2f8eb35e3   2536dcb55c96        42 hours ago        433MB
gladysassistant/gladys   latest              sha256:b37c86adbce1447124c588946c5b3d4d0b0dd284b1c7f196d9f622eb11e63e56   afc020f61782        42 hours ago        417MB
gladysassistant/gladys   v4                  sha256:b37c86adbce1447124c588946c5b3d4d0b0dd284b1c7f196d9f622eb11e63e56   afc020f61782        42 hours ago        417MB
containrrr/watchtower    armhf-latest        sha256:d93d72542f241a8f3411b66f5c9d9ab5fd3386af48f0b156bcd400d3a62e9d33   84378f5d38aa        3 months ago        13.3MB

```

Latest image is not pulled , I suggest to wait next build and then inspect

**Comment by VonOx** [comment]
Another system suggestion to reclaim space:

Deleting all man-page and doc
```
find "/usr/share/doc" -depth -type f ! -name copyright -print0 | xargs -0 sudo rm || true
find "/usr/share/doc" -empty -print0 | xargs -0 sudo rmdir || true
sudo rm -rf "/usr/share/man" "/usr/share/groff" "/usr/share/info" "/usr/share/lintian" "/usr/share/linda" "/var/cache/man"
```
Config apt to not install doc ( create /etc/dpkg/dpkg.cfg.d/01nodoc )
```
path-exclude=/usr/share/doc/*
path-include=/usr/share/doc/*/copyright
path-exclude=/usr/share/man/*
path-exclude=/usr/share/groff/*
path-exclude=/usr/share/info/*
path-exclude=/usr/share/lintian/*
path-exclude=/usr/share/linda/*
path-exclude=/usr/share/locale/*
path-include=/usr/share/locale/en*
path-include=/usr/share/locale/fr*
```

**Comment by Pierre-Gilles** [comment]
Ok, and except the unused docker images, everything was good in this raspbian image? 

About removing the doc, I'm not sure. Does it really save tons of space? 

I would prefer staying as close as possible to the original raspbian image.

**Comment by VonOx** [comment]
> Ok, and except the unused docker images, everything was good in this raspbian image?

> Expand FS not working


> About removing the doc, I'm not sure. Does it really save tons of space?

A few MB, could be worth to save bandwith.



> I would prefer staying as close as possible to the original raspbian image.

Like you want ;)

**Comment by Pierre-Gilles** [comment]
> Expand FS not working

About that, sorry I didn't understand at first that FS = file system. Please don't use acronyms, it makes communication harder^^

It doesn't work? fuck

I'm doing: 

```
sudo raspi-config --expand-rootfs
```

At start of the system. See `sudo nano /etc/rc.local`

**Comment by VonOx** [comment]
> About that, sorry I didn't understand at first that FS = file system. Please don't use acronyms, it makes communication harder^^

Sorry about that


> I'm doing:
> 
> ```
> sudo raspi-config --expand-rootfs
> ```
> 
> At start of the system. See `sudo nano /etc/rc.local`

Ok I understand what happen here.

1. No need to prepend sudo in rc.local because root user is running it.
2. When I have tested the image , I have never rebooted the pi , expand filesystem need reboot. So I never see any ouput about the expand. Checked `df -h` is wrong if pi is not rebooted.

I think better approach is using the same method as noobs installer ( it expand at first boot ).

You can use a script like this before making image. ( I will test tonight )

```sh
#!/bin/bash -e

wget https://github.com/RPi-Distro/pi-gen/blob/master/stage2/01-sys-tweaks/files/resize2fs_once -O resize2fs_once
sudo cp ./resize2fs_once /etc/init.d/resize2fs_once
sudo chmod 755 /etc/init.d/resize2fs_once

echo 'quiet init=/usr/lib/raspi-config/init_resize.sh' 1<> /boot/cmdline.txt >#((EOF - 1)) 
```

**Comment by Pierre-Gilles** [comment]
> I think better approach is using the same method as noobs installer ( it expand at first boot ).

Ok but this method doesn’t need a reboot ? 

> You can use a script like this before making image. ( I will test tonight )

Many thanks 🙏 I’m working on Gladys on Thursday + Friday I’ll adapt the image with your findings :)

**Comment by VonOx** [comment]
This method also need a reboot but the flow is different.

1. User flash image.
2. First time pi is booted, resizefs service is launched ( early boot)
3. The service resize filesystem, self delete and reboot.

No action required from user.

But like I said, I need to test the script. 

This is the approach used by rpi foundation in their image builder.

Maybe I can add some actions you did manually today like apt upgrade, update gladys container...

**Comment by Pierre-Gilles** [comment]
Amazing! I'll implement that in the image then.

**Comment by Pierre-Gilles** [comment]
Ok I'm working on it now, little changes to the script: 

```
#!/bin/bash -e

wget https://raw.githubusercontent.com/RPi-Distro/pi-gen/master/stage2/01-sys-tweaks/files/resize2fs_once -O resize2fs_once
sudo cp ./resize2fs_once /etc/init.d/resize2fs_once
sudo chmod 755 /etc/init.d/resize2fs_once
```

**Comment by Pierre-Gilles** [comment]
This tutorial is helpful: https://www.raspberrypi.org/forums/viewtopic.php?p=1117880#p1117880

**Comment by Pierre-Gilles** [comment]
Trying the new image...

<img width="912" alt="Screenshot 2020-09-10 at 13 42 20" src="https://user-images.githubusercontent.com/7365207/92724792-79477d80-f36b-11ea-945a-08d15e03a5e8.png">

**Comment by Pierre-Gilles** [comment]
Annnnnd it's working!! 

✅ script has been removed from /boot/cmdline.txt
✅ image is resized to the right size

<img width="1039" alt="Screenshot 2020-09-10 at 13 47 06" src="https://user-images.githubusercontent.com/7365207/92725242-228e7380-f36c-11ea-9e12-2676d78be1d5.png">

**Comment by Pierre-Gilles** [comment]
Here is the image: https://github.com/GladysAssistant/Gladys/releases/download/v4.0.0-beta.15/gladys-v4-rev2.img.zip

**Comment by VonOx** [comment]
Good to know 👌, I will try it asap

**Comment by Pierre-Gilles** [comment]
Thanks for your research, it helped me a lot! :)

**Comment by Pierre-Gilles** [comment]
By the way, for faster downloads I put the file on our in-house CDN :) 

https://cdn.elephantcdn.com/gh/gladysassistant/gladys/releases/download/v4.0.0-beta.15/gladys-v4-rev2.img.zip

Tell me if according to you the image is ok, and if yes I'll replace the link on the main website.

**Comment by VonOx** [comment]
Image is ok for now.

![image](https://user-images.githubusercontent.com/1528694/92753042-c89ca680-f389-11ea-8731-f823fb13fbe6.png)

ToDo:

* Regen ssh key
* Prompt for changing password at first login
* udev rules
* What else ?

**Comment by Pierre-Gilles** [comment]
> Regen ssh key

Can you give me more informations on what you want to do?

> Prompt for changing password at first login

Why not, but for most users, the password will never be changed. 

> udev rules

Wasn't it supposed to be in the Docker image? If it's in the raspbian image, it's not upgradable.

**Comment by VonOx** [comment]
### Regen sshkey

I'm talking about the host key. Today all raspberry using your image has the same hostkey

### udev rules
We can let docker container to manage this, but I need to find a way because services does'nt exist in a container. Container just run the CMD instruction.

https://github.com/GladysAssistant/Gladys/blob/master/docker/Dockerfile#L46

**Comment by Pierre-Gilles** [comment]
> I'm talking about the host key. Today all raspberry using your image has the same hostkey

Oh yes right. 

> We can let docker container to manage this, but I need to find a way because services does'nt exist in a container. Container just run the CMD instruction.

Ok let me know !

**Comment by VonOx** [comment]
In raspbian you just need to enable service to regen host keys ( I just discover this )

`sudo systemctl enable regenerate_ssh_host_keys`

I'Have tested in your img, service is self disable after regen

![image](https://user-images.githubusercontent.com/1528694/92898754-8a04fb80-f41e-11ea-9e4c-3c38b4832553.png)

Add this in your script ;)

**Comment by VonOx** [comment]
For udev stuff , balena use entry script to run udev daemon inside container.


https://github.com/balena-io-library/base-images/blob/97f1c88ecfb2a67eeee6c61dc840a52c046fe1a6/balena-base-images/aarch64/alpine/3.11/build/entry.sh#L37

**Comment by VonOx** [comment]
I have implemented balena script in our image with [rules ](https://raw.githubusercontent.com/VonOx/gladys-pi-gen/gladys/gladys/04-udev/files/99-gladys-tty.rules
)

Seems promising 
![image](https://user-images.githubusercontent.com/1528694/93323098-738ee380-f814-11ea-9501-0755651bc2ce.png)
![image](https://user-images.githubusercontent.com/1528694/93324079-b3a29600-f815-11ea-8e6b-e04573b3a531.png)

BUT: nodeserial is not listing symlink so udev rules is useless.

exemple: ACM0 is zwave dongle and ACM1 is custom CC2531 chip ( zigbee )
```
{
    manufacturer: '0658',
    serialNumber: undefined,
    pnpId: 'usb-0658_0200-if00',
    locationId: undefined,
    vendorId: '0658',
    productId: '0200',
    path: '/dev/ttyACM0'
  },
  {
    manufacturer: 'Texas Instruments',
    serialNumber: '__0X00124B0018E1E975',
    pnpId: 'usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E1E975-if00',
    locationId: undefined,
    vendorId: '0451',
    productId: '16a8',
    path: '/dev/ttyACM1'
  }
```

I think usb service must provide a way to reconnect to usb device with pnpID because path can change after a reboot. ( this way is equivalent to list /dev/serial/by-id )

**Comment by Pierre-Gilles** [comment]
Nice findings for udev rules!

**Comment by Pierre-Gilles** [comment]
@VonOx I'm closing this card as it's an old card. If you want you can create another more specific issue for the udev rules :)
