### ISSUE TITLE
🐳 Manage Docker manifest

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#640]

**Comment by atrovato** [comment]
Any up on this point?

**Comment by VonOx** [comment]
Yep PR #643 ( need rebase)

**Comment by Pierre-Gilles** [comment]
Mm it seems there is a little issues on master as we still use tag like "v4.0.0-beta-14"

We have `error parsing name for manifest list :v4.0.0-beta-14: invalid reference format`

See:

https://app.circleci.com/pipelines/github/GladysAssistant/Gladys/1205/workflows/b524d146-c600-431f-8c05-343d52391952/jobs/3508

Any idea @VonOx ?

I don't really know if we can keep beta tags or we need to migrate to the real v4.0.0 format :) (which means we'll have to do "v4.0.1" and more after)

Except that it works very well btw! :D Thanks again for your work

**Comment by VonOx** [comment]
Yeah you need to stop using beta in your tag/release , parsing only semver format ( vX.X.X ) but we can catch this error.

**Comment by Pierre-Gilles** [comment]
Ok. Is there any way to still use a -beta release while we are not ready for RC?

Which program is throwing this error? Docker? 

Maybe we need to switch to tags like: v4.0.0-beta.14 ?

<img width="895" alt="Screenshot 2020-09-03 at 14 36 24" src="https://user-images.githubusercontent.com/7365207/92115541-df278880-edf2-11ea-9c49-fecd2cf8a7cd.png">

**Comment by VonOx** [comment]
> Which program is throwing this error? Docker?

Just after docker login, so error is throw by docker manifest command
https://github.com/GladysAssistant/Gladys/blob/master/.circleci/config.yml#L26 Here version is extracted 

But error is here => https://github.com/GladysAssistant/Gladys/blob/master/.circleci/config.yml#L162

$CIRCLE_TAG-arch is not manifest compliant

Testing v4.0.0-beta.15 right now https://app.circleci.com/pipelines/github/VonOx/GladysIsolatedCI/20/workflows/e9fb42ea-9e5e-42f4-9226-633d6c2d843a 🤞

**Comment by VonOx** [comment]
> Ok. Is there any way to still use a -beta release while we are not ready for RC?

We need to manage this case ( if beta release -> special docker tag )

**Comment by Pierre-Gilles** [comment]
No not specially, here I just want to build on v4 on Docker, BUT with Github tags still in beta

GitHub tags are mostly "marketing", if I publish a v4.0.0 tag right now: the signal is that the v4 is out! I can't do that. That's why i need to continue making beta tags

But on Docker I want to build on v4, no more beta because I need to build the new Raspbian image which will have docker v4 image.

Does it makes sense to you? ^^

**Comment by Pierre-Gilles** [comment]
> Testing v4.0.0-beta.15 right now https://app.circleci.com/pipelines/github/VonOx/GladysIsolatedCI/20/workflows/e9fb42ea-9e5e-42f4-9226-633d6c2d843a 🤞

Lets see 🤞 Thanks for testing!

**Comment by VonOx** [comment]
> GitHub tags are mostly "marketing", if I publish a v4.0.0 tag right now: the signal is that the v4 is out! I can't do that. That's why i need to continue making beta tags
> 
> But on Docker I want to build on v4, no more beta because I need to build the new Raspbian image which will have docker v4 image.

Ok i see, weird but ok. :D

I can just remove "beta" from docker tag

**Comment by VonOx** [comment]
Build on circle just terminated

![image](https://user-images.githubusercontent.com/1528694/92126360-5dd6f280-ee00-11ea-8987-7ebef0c73ee6.png)

ok with  v4.0.0-beta.15 like tag
This is ok

**Comment by Pierre-Gilles** [comment]
Amazing ! Building this right now !

**Comment by Pierre-Gilles** [comment]
Not ok on my side :/ Did I do something wrong?

<img width="744" alt="Screenshot 2020-09-03 at 18 00 07" src="https://user-images.githubusercontent.com/7365207/92138931-54a15200-ee0f-11ea-9685-ae70e94a2c26.png">


https://app.circleci.com/pipelines/github/GladysAssistant/Gladys/1207/workflows/a9ee3e17-591f-4d84-b082-e1f45ec0ef85/jobs/3520

**Comment by VonOx** [comment]
Hmmm we are missing something , you have not the same output

Did you check env in circle

![image](https://user-images.githubusercontent.com/1528694/92139301-d7c2a800-ee0f-11ea-8a33-ea871fb6210c.png)

Image is builded and pushed , that's weird

**Comment by Pierre-Gilles** [comment]
My bad, DOCKERHUB_REPO was missing ! It's rebuilding now :)

**Comment by Pierre-Gilles** [comment]
Success! Wow! Congrats @VonOx 👏
<img width="1283" alt="Screenshot 2020-09-04 at 10 32 01" src="https://user-images.githubusercontent.com/7365207/92218767-e48bde00-ee99-11ea-9a30-90434a9a814f.png">
