### ISSUE TITLE
MQTT devices setValue

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#645]
Allow to publish MQTT message on device update (actuator).

https://community.gladysassistant.com/t/mqtt-comment-fonctionne-le-module-mqtt/5000/39

**Comment by Pierre-Gilles** [comment]
https://community.gladysassistant.com/t/reflexion-autour-de-lapi-mqtt/5219

**Comment by atrovato** [comment]
@Pierre-Gilles So we can consider it as closed ?

**Comment by Pierre-Gilles** [comment]
Yes, this is done!
