### ISSUE TITLE
What's the login and password?

### ISSUE THREAD

**Issue by Magnatolia** [GladysAssistant/Gladys#653]
I used Etcher to flash the Gladys 4 to a new SD card. It went through a heap of boot up actions and then asked me for a login and password? This is not mentioned anywhere.

So, what is the login and password for this?

**Comment by Magnatolia** [comment]
Anyone? I managed to use the default username and password for my raspberry PI and now I'm on the command line for pi@gladys, but no idea what to do next as that also isn't covered in the documentation.

Thanks!

**Comment by Magnatolia** [comment]
And my PI is not connected to the WIFI at this stage

**Comment by Pierre-Gilles** [comment]
The image is a default Raspbian image, so:

**login**: pi
**password**: raspberry

If you have any issues, please ask questions on [our forum](https://community.gladysassistant.com/) rather than GitHub Issues that we use for bug tracking and development !

**Comment by tails1154** [comment]
this does not work

**Comment by noahbleau** [comment]
> The image is a default Raspbian image, so:
> 
> **login**: pi
> **password**: raspberry

Worked successfully. (My keyboard was on AZERTY for no reason)
