### ISSUE TITLE
Bug "Devices" view of the "Integrations/Devices/MQTT"

### ISSUE THREAD

**Issue by Terdious** [GladysAssistant/Gladys#657]
**Describe the bug**
In the "Devices" view of the "MQTT" service, when there are more than 20 registered devices, only the first 20 (or the last 20 according to the "A-Z" or "Z-A" sorting method). At the beginning I therefore thought that the new devices were not created, but when we use the "search" menu, we find them well.

**Expected behavior**
The solution would be to either:
- have a listbox at the top and bottom of the page allowing you to choose the number of devices to display: 20/50/100 / all.
- have a selection of pages each displaying 20 devices.
- better still, being able to display the devices of an entire house and/or a particular room.

**Screenshots**
-Either : 
![image](https://user-images.githubusercontent.com/35010958/74413431-ac5e7880-4e3f-11ea-9ba3-59c509917f42.png)

- or : 
![image](https://user-images.githubusercontent.com/35010958/74413136-26423200-4e3f-11ea-860b-9f85f5941bf7.png)

- or better (AMHA), something of style with in addition the menu by number of display or by page : 
![image](https://user-images.githubusercontent.com/35010958/74415671-1711b300-4e44-11ea-903b-1029848eb9f7.png)

**Your Gladys installation (please complete the following information):**
- Raspberry Pi 4 Modèle B - SDCard Sandisk Extreme PLUS 64GB V30
- Installation gladys-4.0.0-beta-raspbian-buster.img

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Professionnel x64
- Chrome
- Version 80.0.3987.87 (Build officiel) (64 bits)

**Comment by atrovato** [comment]
This is not only for MQTT device list.
