### ISSUE TITLE
Dashboard devices in room motion "Nan years ago"

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#661]
<img width="424" alt="Screenshot 2020-02-21 at 18 25 08" src="https://user-images.githubusercontent.com/7365207/75056556-90aa4080-54d7-11ea-9ffe-2066a174a061.png">

**Comment by atrovato** [comment]
What about:
![image](https://user-images.githubusercontent.com/1839717/76702528-be476b80-66ca-11ea-87bc-9f7dfd8478ab.png)
