### ISSUE TITLE
Z-Wave: Improve the "Network" tab and remove the "vis" library

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#668]
The "Network" tab is not really useful right now... 

<img width="903" alt="Screenshot 2020-02-27 at 18 37 30" src="https://user-images.githubusercontent.com/7365207/75470007-440bad00-5990-11ea-829b-210c7fee3723.png">

It uses a really heavy library ("vis") which can be removed.

Let's see how we can improve the display of this tab.

The goal is to display the list of Z-Wave devices, and know how connected they are to the network. 

Maybe we can display a table, with a list of devices, and foreach device, we can display the number of neighbors, the list of neighbors + and if the device is connected enough.(Maybe some stats?)

**Comment by domosoftdev** [comment]
Bonjour 
Petite contribution pour prendre en main le code du projet. 
Voici ce que j'ai réalisé a ce jour. 
Vos avis ? 
![Zwave-Network](https://user-images.githubusercontent.com/5730930/101692264-3da67780-3a70-11eb-9500-9deaafb97317.PNG)

**Comment by VonOx** [comment]
L'idée du tableau est pas mal pour les petits réseaux, mais ceux en full zwave ça va être compliqué à lire :)
Existe t il des libs plus légère ? [vue-d3-network](https://codepen.io/emilio/pen/QOaQjP) par exemple ?

Inspirations:
Domoticz qui fait les deux
![](https://www.domoticz.com/wiki/images/d/d0/ZWaveNetworkInfo.jpg)
Ou le zigbee
![](http://www.rfwireless-world.com/images/zigbee_network.jpg)

**Comment by Pierre-Gilles** [comment]
@domosoftdev Merci pour ta contribution ! Je trouve ça vraiment pas mal dans l'idée. Le header du tableau en noir ça fait un peu agressif je trouve mais sinon c'est vraiment pas mal. Il faudrait tester avec des grosses installations :) 

@VonOx c'est pourtant ce que font pas mal de box domotique le tableau, et ça rend bien je trouve! A voir comment ça réagit avec beaucoup de périphérique effectivement.

**Comment by VonOx** [comment]
"Un bon croquis vaut mieux qu'un long discours"

Pour moi les deux ont leur place, le tableau pour les données "brutes" OK, mais c'est quand même plus pratique un graph/schéma interactif.

**Comment by Pierre-Gilles** [comment]
Quand le croquis est clair! 

Pour moi, le graph actuel est inutilisable, sur les grosses installations il est illisible et apporte plus un côté "impressionnant lors d'une démo mais inutile en réalité" à Gladys actuellement. 

Comme en plus la librairie vis est super lourde, j'ai envie de changer ça.

L'exemple du graph chez Domoticz est exactement ce que je trouve inutile ^^ On voit rien, personne ne se sert de ça. 

Juste pour centrer le but de cette page, pour moi l'intérêt est de voir facilement quelles noeuds z-wave sont isolés et pas assez connectés à d'autres dans le réseau. 

Je suis preneur de toute proposition pour rendre la page plus clair :)

**Comment by domosoftdev** [comment]
Hello
J'essaie de mettre un schéma en plus du tableau avec la lib proposée, mais
mon réseau Zwave n'est pas très fourni.
L'un de vous a un réseau avec plusieurs (dizaines) de nœuds ?
Idem pour le titre, j'ai repris une class de Bootstrap. Je regarde pour
change ca.
A+

**Comment by VonOx** [comment]
@Pierre-Gilles Je voulais juste illustrer le fait que Domoticz fournissez les deux , je te rejoins sur le fait que leur graph est "bizarre"

Le schema "mesh node" est bien plus pratique qu'un tableau ( ça reste personnel comme avis ) ,donc pour moi les deux ont leur place.

@domosoftdev le theme que Gladys utilise c'est tabler, regarde la page de démo ou leur doc si tu veux récupérer des modèles ou les class css => https://preview.tabler.io/tables.html

Je n'ai que 2 nodes donc ça va pas faire avancer le schmilblick

**Comment by Pierre-Gilles** [comment]
@VonOx je suis d'accord avec toi ! Dans l'idée si on trouve un beau graph qui représente bien le réseau, sans prendre trop de place dans le bundle JS je suis tout pour :)

**Comment by domosoftdev** [comment]
Bonsoir,
@VonOx, la librairy tabler s'appuie sur Bootstrap. [cf doc](https://preview.tabler.io/docs/index.html)
_

> Tabler is a UI kit that speeds up the development process and makes it easier than ever! Built on the latest version of Bootstrap, it helps you create templates based on fully customizable and ready-to-use UI components, which can be used by both simple websites and sophisticated systems.

_
Avez vous défini des 'class' pour les tableaux par défaut, ou c'est selon l'envie de la personne qui code  ? 
La class .table de **tabler** est assez pauvre en configuration.
Par contre la bibliothèque vue-d3-network n'a pas évoluée depuis 2 ans, avez vous défini des critères de sélection des bibliothèques ajoutées au projet ? 
Désolé de poser peut être de questions évidentes mais je n'ai pas trouvé la réponse sur la doc. 
A bientôt

**Comment by Pierre-Gilles** [comment]
@domosoftdev On utilise les styles Tabler dans Gladys :) On évite de faire des styles custom (sauf pour certaines features fancy, ce qui n'est pas le cas ici!), ça permet de garder une unité dans le projet.

Les classes tabler ne te conviennent pas? Je trouve qu'elles sont bien moi ! 

https://preview.tabler.io/docs/tables.html

Une seule remarque par rapport à l'usage des table HTML pour faire ce genre de design: attention au responsive. Souvent, les tables c'est pas terrible sur mobile, et la plupart de l'usage Gladys est sur mobile donc c'est très important. Dans Gladys 4 on a quasiment (voir pas) de table dans l'UI, donc à étudier et à tester sur plusieurs tailles de device.  

Si l'usage des table ne marche pas, on pourrait retirer l'onglet "network" de l'intégration et afficher les voisins Z-Wave tout simplement dans la vue "Configuration".

> Par contre la bibliothèque vue-d3-network n'a pas évoluée depuis 2 ans, avez vous défini des critères de sélection des bibliothèques ajoutées au projet ?

Déjà "vue-d3-network" rien que le nom je pense que c'est une librairie pour vuejs, ça nous intéresse pas ici :D 

Ensuite effectivement on fait attention aux libs qu'on choisit. Il n'y a pas de règles stricte, mais des libs plus mise à jour depuis 2 ans effectivement c'est pas ce qu'on veut. 

Aussi, toutes les nouvelles librairies frontend qui sont ajoutées, je les fais passer dans https://bundlephobia.com/ pour voir la taille que ça va ajouter au bundle. On évite les librairies géantes. La lib "vis" + "vis-network" c'est un peu une erreur de l'avoir ajoutée (de ma part), d'où cette issue github pour la retirer.

Après en soit, à part si tu trouve une lib fantastique et que tu me prouve que ça a un intérêt de faire de la data-viz du réseau Z-Wave (et que c'est propre), je serais plutôt pour passer à vue liste dans un premier temps et de retirer tout graphique.

**Comment by Pierre-Gilles** [comment]
Done in Gladys Assistant v4.5.
