### ISSUE TITLE
Display container uptime instead of "created" date in Docker container list

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#672]
<img width="445" alt="capture_d___e__cran_2020-02-29_a___15 25 08" src="https://user-images.githubusercontent.com/7365207/75657958-a7832c80-5c67-11ea-916b-34aa2c5da14b.png">

**Comment by guim31** [comment]
Why not display both ? 
The creation time helps me knowing if I'm on the latest release of Gladys.

Otherwise it would be interesting to get a message like "You're running Gladys 4.1.1"

**Comment by VonOx** [comment]
Uptime is more revelant because it can reflect some defect.
Created date is not really necessary. It is just "updated date".

Docker image tagging is on the pipe so you don't need creation date anymore.

**Comment by atrovato** [comment]
I'll wait for inspect implementation done with https://github.com/GladysAssistant/Gladys/issues/722 issue.

**Comment by atrovato** [comment]
Not done, but should we do?

**Comment by Pierre-Gilles** [comment]
Not sure. Creation date indicate when was the container last upgraded (if you use watchtower), so it's useful too.

Also, I'm not sure we want to display both (as we use a table in this component, it'll make the component super wide and break even more on some screens (it already break with long container names).

Also, super low priority IMO.

**Comment by Pierre-Gilles** [comment]
Edit: Deleted my previous message.

As you want honestly, I don't have any argument on this. 

Also, IMO super low priority.
