### ISSUE TITLE
Improve English translation/localization

### ISSUE THREAD

**Issue by Scott-Fischer** [GladysAssistant/Gladys#674]
I recently installed Gladys and went through a new user flow (super great/cool project by the way!) and noticed that the English localization could be cleaned up a little bit in terms of spelling/grammar/word choice.

As a native English speaker, I'd be more than happy to go through this (in fact I already started) and submit a PR with the improved copy.

**Comment by Pierre-Gilles** [comment]
Thanks for your message! Sure it'll help a lot :)
