### ISSUE TITLE
To investigate: DB migration should start when Gladys start

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#679]

**Comment by atrovato** [comment]
Found this https://db-migrate.readthedocs.io/en/latest/API/programable/

**Comment by Pierre-Gilles** [comment]
We don't use db-migrate, we use Sequelize Migrations! 

https://sequelize.org/v4/manual/tutorial/migrations.html

We need to implement umzug:

https://github.com/sequelize/umzug
