### ISSUE TITLE
Handle Xiaomi commands

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#689]
Be able to control xiaomi devices (switches, ...)

**Comment by bobdivx** [comment]
mes périphériques Xiaomi :

Gateway v2 serveur Chine

INTERRUPTEURS
- Switch simple sans neutre filaire
- Switch double sans neutre filaire
- Switch simple avec neutre filaire
- Switch simple sans fils

BOUTONS
- Bouton pression zigbee
- Bouton pression zigbee Aqara

PRISES
- Fiche zigbee on/off
- Fiche wifi on/off avec suivis de consommation

CAPTEURS
- D'ouverture
- De mouvements
- De température
- D'inondation
- D'incendie
 - Fuites de gaz

LUMINAIRES
 - Ampoule Yeelight
 - Bande led 
 - Bande led plus
 - Spot Xiaomi Phillips
 - Lampe de bureau
 - Suspension Meteor

AUTRES
 - Serrure Aqara zigbee
 - Sonnette avec caméra
 - Caméras
 - contrôleur infrarouge

**Comment by Pierre-Gilles** [comment]
Closing this as we now use GitHub only for bug tracking, feature requests should be handled on the forum! https://community.gladysassistant.com/
