### ISSUE TITLE
[New feature] Tooltip text MQTT

### ISSUE THREAD

**Issue by PhilippeMA** [GladysAssistant/Gladys#705]
**Is your feature request related to a problem? Please describe.**
La page d'accueil de Gladys liste toutes les informations et inputs souhaités par rapport à nos devices. J'ai monté un station méteo custom avec un esp32 qui envoie les infos par le protocole MQTT (température, concentration CO2 et humidité). Ces informations sont remontées par Gladys sur la page d'accueil (c'est top !). Cependant, il me manque une info... De quand date les données affichées sur la page.

**Describe the solution you'd like**
Ne pourrait-on pas afficher le timestamp en bulle d'info lorsqu'on passe la souris au dessus de la valeur ?

**Comment by bobdivx** [comment]
Bonjour, Pierre-Gilles à prévu d'intégrer la fonction [appareil hors ligne](https://github.com/GladysAssistant/Gladys/issues/681)
donc si Gladys ne reçois plus d'info de ta station météo alors tu sera notifié ;-)

**Comment by PhilippeMA** [comment]
Hello, effectivement je ne l'avais pas vu.

Je viens de voir également cette issue https://github.com/GladysAssistant/Gladys/issues/663 qui semble poser la même problématque.

Sur confirmation, je close cette issue.

**Comment by Pierre-Gilles** [comment]
J'ai ajouté ton feedback dans https://github.com/GladysAssistant/Gladys/issues/663, je ferme cette issue !
