### ISSUE TITLE
Add a CO2 sensor category with PPM unit

### ISSUE THREAD

**Issue by PhilippeMA** [GladysAssistant/Gladys#706]
En créant un device MQTT, j'ai la possibilité de définir les fonctions disponibles (température, lumière, capteur de mouvement...). Toutes les fonctions n'ont pas d'unité alors que ça me semble être important de les afficher. Pour la température, on peut bien préciser °C ou °F.

Pour mon besoin j'ai utilisé :
- Density : pas d'unité. L'ayant utilisé pour un capteur de CO2, j'aurais souhaité pouvoir choisir l'unité "PPM"
- Humidity : pas d'unité. Pour ce cas, je pense que "%" devrait être sélectionné par défaut

Serait-il possible d'ajouter ces informations ?

**Comment by Pierre-Gilles** [comment]
Hello! Bonne remarque, pour le capteur de CO2 c'est quelle marque/modèle?

**Comment by PhilippeMA** [comment]
> pour le capteur de CO2 c'est quelle marque/modèle?

Il s'agit d'un capteur MH-Z19B connecté à un ESP32.

**Comment by Pierre-Gilles** [comment]
Added!

**Comment by PhilippeMA** [comment]
Je confirme que ça fonctionne, merci !
