### ISSUE TITLE
Adding a local Gladys Plus option when enabling it

### ISSUE THREAD

**Issue by NoskaOff** [GladysAssistant/Gladys#710]
I could be nice to add the choice in production mode of using either the normal Gladys Plus or a local instance

**Comment by Pierre-Gilles** [comment]
You mean, when building the frontend, to build it in Gladys Plus mode ?

You can, by setting the environnement variable GATEWAY_MODE=true

Is it what you were looking for? :)

**Comment by NoskaOff** [comment]
I mean having the choice of using Gladys Plus (your instance) or the one that I'll be running myself at home for testing. Hope it makes sense :)

**Comment by Pierre-Gilles** [comment]
Sure, you can set the env variable GLADYS_GATEWAY_API_URL in both frontend and backend when building it, and put your own endpoint. 

But I don't see what the point of running your own Gladys Plus instance ^^

If you have the knowledge to run your own Gladys Plus instance, you have the knowledge to just expose your Raspberry Pi to the internet, which is the exact same if you want to access your Pi remotely :) 

But it's possible ! 😄 

Closing this as it's possible already.
