### ISSUE TITLE
Session name should be a clear user agent of the browser using the app, not "Device"

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#713]
Example:

- "Safari MacOS" 
- "Chrome Windows 10"
- "Chrome Android"

<img width="940" alt="Screenshot 2020-03-21 at 16 53 35" src="https://user-images.githubusercontent.com/7365207/77230459-9bb6c600-6b94-11ea-92d8-842d9911a861.png">

**Comment by atrovato** [comment]
What about:

![image](https://user-images.githubusercontent.com/1839717/82093481-7e692880-96fb-11ea-994d-1fec548f3738.png)

**Comment by Pierre-Gilles** [comment]
Love it! Exactly what I was thinking about 👍
