### ISSUE TITLE
Multiple dashboards and public dashboards

### ISSUE THREAD

**Issue by moqmar** [GladysAssistant/Gladys#723]
**Is your feature request related to a problem? Please describe.**
Two scenarios:
- I have many sensors for my AC and heating, and also lots of stuff to control in the Garage. I don't want this on my "Home" tab, but I still want a similar way to organize it.
- I want others to see how the weather is at my home, show a live stream of the landscape, and perform a single action.

**Describe the solution you'd like**
I want to be able to add additional dashboard tabs (which solves the first scenario), and individually control the access rights (public, link with a token, specific users, ...) to each of them (which solves the second scenario, but probably is a huge problem and more related to #374 and #637).

**Describe alternatives you've considered**
Multiple Gladys instances are probably a stupid idea, so I'm not sure how else to solve the problem with Gladys.

**Comment by Pierre-Gilles** [comment]
Hi ! 

100% agree, this is something on our roadmap :)

Gladys v4 was designed for this. The current dashboard you see in the homepage is the "main" dashboard, but we plan to add  the ability to create multiple dashboards.

If you want to help us develop this, don't hesitate, PR are welcomed. We can talk about the feature here before implementing.

**Comment by Pierre-Gilles** [comment]
We now have multiple dashboard since v4.5 ! :) 

For public dashboard, don't hesitate to create a feature request on the forum as we now use the forum for feature request (we use Github only for bug tracking)

https://community.gladysassistant.com/
