### ISSUE TITLE
Camera event history

### ISSUE THREAD

**Issue by moqmar** [GladysAssistant/Gladys#724]
**Is your feature request related to a problem? Please describe.**
I can see the current situation with the camera view, but not e.g. what happened yesterday (which is even more important IMO).

**Describe the solution you'd like**
If I click the camera image, I'd like a bigger live preview to show up, with a timeline slider underneath displaying the past events e.g. recorded by ZoneMinder (that would probably be the easiest way to implement it). I then want to click old events from that timeline to play them back.

**Describe alternatives you've considered**
An external ZoneMinder instance would solve this, but it would be awesome if everything's integrated into a single dashboard.

**Comment by Pierre-Gilles** [comment]
I didn't know about ZoneMinder! We have lots of things to learn from them on the camera side :) 

I would prefer that we develop what's missing in Gladys in-house, so we have everything in Gladys without needing an external dependency. 

Can you explain a little bit more which images we need to save? Imagine you have a refresh rate of 1 sec, and we save every image, it means we save 60 * 60 * 24 = 86k images per day, 2.5M images per month, that's a lot and probably unnecessary to keep all that history. 

Should it be only image when something happened (movement/change in lights?, if yes, on which basis should we evaluate that?)

You probably know more about ZoneMinder than me, so don't hesitate to explain how they do it in ZoneMinder :)

**Comment by moqmar** [comment]
Yeah, saving all images is not the best idea. ZoneMinder does pretty good movement detection on live video streams, with selectable zones of interest, and much more features. I think this is a bit out of scope for Gladys, hence I was suggesting an integration.

What would be a great easy alternative way to implement something like this is an FTP server - most of the standalone video cameras can detect movement (some also including zones) themselves, and upload a series of images to a specific FTP server. The files on that server could then easily be used in Gladys' UI to show past events triggered by the camera.

Maybe that would be a good starting point for the feature and its UI, and then ZoneMinder (probably hosted on a different server, it's really resource intensive) could be integrated later for people who want more features than that.

**Comment by Pierre-Gilles** [comment]
While I agree that it's not the goal to re-develop entirely ZoneMinder in Gladys, some features like motion detection can be nice to have in Gladys natively ! 

Could you help us develop this? :)

**Comment by moqmar** [comment]
I can implement the UI and the FTP server (not this week though), but I have experimented with motion detection & everything related to RTSP streams, and I hated it :laughing:

ONVIF would be another standard that might be worth supporting - it's basically a standardized way to get the RTSP stream URL of a camera (basically all of them are supported), but also supports controlling camera features like pan/tilt, and also can be used to catch motion events (and maybe start a recording in that case). I can have a look at how complex that would be too.

So, there are basically the possibilities to...
- use ONVIF to trigger recordings of the RTSP stream, control cameras and get the RTSP URL in the first place (Pull option)
- use FTP to receive images from cameras (Push option)
- integrate ZoneMinder, which is heavy on network traffic and computing resources, but offers a way better set of features than anything we could implement ourselves.
- provide motion detection on the stream ourselves, which has the same disadvantages of ZoneMinder, but I don't see any advantages here.

**Comment by Pierre-Gilles** [comment]
Thanks for your analysis! 

For a first "camera history" feature in Gladys, what I see:

- Subscribe to ONVIF "motion" events in Gladys
- When a motion event is fired, simply save the current camera image (Getting the camera image is already coded in Gladys)
- In the frontend, have the ability to see the history of the camera motion events, and see the image captured at that time.
- Garbage collect old images older than XX days (user can choose in UI).

I would put aside any third-party integration (FTP, ZoneMinder), this is something separate from this feature. 

What do you think of that?
