### ISSUE TITLE
Find a way to send camera websockets images only when user needs it in UI

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#728]
Right now, camera image are sent all the time in websocket, even if the user is watching the settings page... it should not be the case!

**Comment by atrovato** [comment]
Or/and maybe proxy/forward the RTSP flow ?

**Comment by Pierre-Gilles** [comment]
It's another development ^^ But we can discuss on the forum if you need that precise use-case. I'm not sure this is the priority right now, IMO :) 

Here it's more a general card about "websocket being sent only when subscribed too"

**Comment by atrovato** [comment]
Ok I understand, I propose a solution: un/subscribing to event type.
Please see https://github.com/GladysAssistant/Gladys/pull/739

**Comment by Pierre-Gilles** [comment]
It's exactly what I had in mind! Nice job!

**Comment by Pierre-Gilles** [comment]
I'll close the issue as it doesn't really add value, but keep the PR open!
