### ISSUE TITLE
TypeError: r.rooms is undefined

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#732]
For some reason camera box is added twice on my Dashboard.

![image](https://user-images.githubusercontent.com/1528694/78471592-ab0c4680-7732-11ea-917f-36db1cb97bcb.png)

So first one is working because device is associated, but second one no. That's ok.

Issue is I can't edit dashboard to delete second box because no room is associated.
`TypeError: r.rooms is undefined`

**Comment by Pierre-Gilles** [comment]
I'm trying to debug this...

For now, I'm not able to reproduce the bug, it works fine on my side, even with no camera selected. 

I don't think that the problem comes from this box, as this box has no link with "rooms". It might be coming from your other boxes, I see (on your copy paste in Slack) that you have other boxes : 

type "temperature-in-room"
room "chambre"
1 […]
0 {…}
type "devices-in-room"
room "salon"
1 {…}
type "devices-in-room"
room "chambre"

I'm investigating and will keep you posted....

**Comment by Pierre-Gilles** [comment]
Despite all my attempt, I'm not able to reproduce...

Can you give me more informations?

Please don't delete your Gladys instance, this bug is critical and needs to be solved!

**Comment by Pierre-Gilles** [comment]
Where is this line coming from? 

```
TypeError: r.rooms is undefined
```

Can you click on the error in the browser to see where it happened?

**Comment by VonOx** [comment]
Error come from console browser, I have deleted the dashboard from db. Not able to reproduce too.

But I have a backup of the db, I will check the json, we will see which box is the problem. 


Edit: The Dashboard ( this one is not editable )

```json
[
  [
    {
      "type": "weather",
      "house": "maison"
    },
    {
      "type": "user-presence"
    }
  ],
  [
    {
      "type": "devices-in-room",
      "room": "salon"
    }
  ],
  [
    {
      "type": "devices-in-room",
      "room": "cave"
    },
    {
      "type": "camera",
      "camera": "ender-3",
      "name": "Imprimante"
    },
    {
      "type": "camera"
    }
  ]
]
```

**Comment by PhilippeMA** [comment]
A similar problem here. The UI is not responding as expected (cf. gif)
![Peek 09-04-2020 13-38](https://user-images.githubusercontent.com/25247304/78891383-c4c9c880-7a67-11ea-8a79-f272e776b38f.gif)

**Comment by PhilippeMA** [comment]
To reproduce (not sure at 100%) : "sudo docker prune -a" or remove Docker and all the repositories (include gladys container). Then, reinstall Gladys as descripted on the website. Gladys may have used backup functionality ?

**Comment by VonOx** [comment]
I've send my db with broken Dashboard to  @pierre-gilles

**Comment by Pierre-Gilles** [comment]
Thanks @VonOx for your DB, it helped me fix it ! 

PR is building in https://github.com/GladysAssistant/Gladys/pull/738
