### ISSUE TITLE
Add a view to see how many device feature state are in DB and a manual way to purge them

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#742]

**Comment by atrovato** [comment]
Do you have any idea on this?

Add a view on settings? As technical view?
Add a tab between "chat" and "integration"?

**Comment by Pierre-Gilles** [comment]
Yes, I think it should be in "settings" => "System".

We should display the total size of the DB, then the size of the deviceState table, and several options to purge the state table, like:

Clean device history older than:

- 1 day
- 1 week
- 1 month
- 3 months

Something like that

It could be great to find again the parameters of the `/signup/preference` page so the user can modify it. 

about the state history=>

<img width="1306" alt="Screenshot 2020-04-20 at 09 53 42" src="https://user-images.githubusercontent.com/7365207/79729311-95308100-82ef-11ea-8cc3-d87ad2defcca.png">
