### ISSUE TITLE
ScheduledTrigger.jsx - DatePicker not ordered correctly

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#750]
![image](https://user-images.githubusercontent.com/1528694/79866853-b1aae700-83dd-11ea-9afb-2be5d31bae33.png)

**Comment by Pierre-Gilles** [comment]
One question, what's the issue in your screenshot?

**Comment by VonOx** [comment]
AM PM is confusing me ( So I'm the problem :D )
