### ISSUE TITLE
Renaming a room does not update a selector

### ISSUE THREAD

**Issue by link39** [GladysAssistant/Gladys#752]
**Describe the bug**
When you rename a room, the name is not change everywhere. As shown in the following screenshot, I renamed my room "Salon" to "Neo coolcam" and the original name appears in the network log 

**Screenshots**
![image](https://user-images.githubusercontent.com/2229692/80254614-cc9a8700-867b-11ea-9feb-1b0365994e86.png)

**Your Gladys installation (please complete the following information):**
- Windows 10
- Dev environnement

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser : Chrome
- Version : 80

**Comment by atrovato** [comment]
It's not the name, it's the selector. It doesn't change when you rename the room.

**Comment by link39** [comment]
It's confusing. No way to change the selector when you rename a room ?

**Comment by Pierre-Gilles** [comment]
We use the selector as a unique ID everywhere in Gladys, and being able to update it have lots of implication everywhere. 

**The idea behind the selector is:**

- An unique ID
- "human readable"
- Used internally in the code & URL, but not directly exposed to the end-user

Right now, It's not designed to be updatable. If you update it, expect your scenes, boxes, caches to do weird things ^^

Still, if we evaluate that it's a really big pain, we could evaluate how much development is needed to change this behaviour, but it'll not be that easy!

**Comment by Pierre-Gilles** [comment]
I think we are closing this for now. There are so many things to do that have a higher priorities :)
