### ISSUE TITLE
Zwave : No autorefresh setup page after scan complete

### ISSUE THREAD

**Issue by link39** [GladysAssistant/Gladys#753]
**Describe the bug**
Zwave : When you click on the "setup" tab, zwave service read your stick. An icon indicate the loading. But the loading rounds in circle. I had go to another tab and switch again to "setup" to show my zwave equipements.

**Expected behavior**
At the end of the reading stick ("scan complet" instruction in the log), I expect to have an auto-refresh showing me my devices.

**Screenshots**

**Your Gladys installation (please complete the following information):**

- Windows 10 
- Developement platform

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 80

**Additional context**

**Comment by Pierre-Gilles** [comment]
Seems to be working for me, I don't think it's related to Z-Wave but it's maybe more a question of websockets. Maybe websockets are disconnecting because the instance was restarting, and never reconnected (it should!). 

Closing this, if you experience the bug again you can reopen it :)
