### ISSUE TITLE
MQTT: Change feature select + more explicit feature name in select

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#758]
Features are not well explained, some are even in duplicate: 

<img width="1440" alt="Screenshot 2020-04-28 at 08 49 14" src="https://user-images.githubusercontent.com/7365207/80456044-2d9cb600-892d-11ea-8b2c-f98c8ecd7c16.png">

**Comment by atrovato** [comment]
May be linked to https://github.com/GladysAssistant/Gladys/pull/731
