### ISSUE TITLE
Seems there is some bugs on Firefox/Safari

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#761]
- user profile image not showing
- Settings:
- houses not showing
- sessions not showing
- Actually, almost no page shows up in firefox haha

**Comment by mitchellbernstein** [comment]
The issue also occurs on Chrome - specifically the cancel subscription.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/748263/80894321-8eb2e980-8c9f-11ea-9c24-200a57b48b95.png">

**Comment by VonOx** [comment]
I'm using Firefox everyday ( Both ESR end latest ) , and the problem doesn't occur. ( Windows & Linux )

Tested with chromium , no problem. Only new users are impacted ?

**Comment by Pierre-Gilles** [comment]
@mitchellbernstein Thanks for reporting, I'm not able to reproduce neither... 

I wonder if it's an issue with a chrome extension you have which can be blocking Stripe JS code (our payment analytics solution) Can you try again in Incognito Mode without extension?

**Comment by Pierre-Gilles** [comment]
@mitchellbernstein I'm not able to reproduce any of your problems 😄 

Everything works fine on Firefox on my side... 

Are you sure you don't have a weird browser extension which messed up with Gladys?

Closing this in the meantime as it's likely that's it's an issue on your side.
