### ISSUE TITLE
Provide way for dev to build local Docker env

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#763]
Due to repo configuration with CI for building docker images, devs cannot build directly changes for testing.

Today we need to create/set a dockerhub account and circleci account for automatic build ( overkill for testing )

TODO List

* Dev dockerfile / docker compose
* Documentation

**Comment by atrovato** [comment]
Is this linked to https://github.com/GladysAssistant/Gladys/issues/626 ?

**Comment by VonOx** [comment]
Yep duplicate, sorry

**Comment by VonOx** [comment]
Yep duplicate, sorry

**Comment by VonOx** [comment]
Yep duplicate, sorry
