### ISSUE TITLE
French translation issues

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#774]
https://community.gladysassistant.com/t/gladys-4-beta-est-desormais-disponible-en-langue-francaise/5357/5?u=alextrovato

Some misses in french translation file:

Gladys Plus - Prix : Ligne 56, 160
<a href=“https://gladysassistant.com/fr/pricing/”> Gladys Plus. ",

MQTT : Lignes 480, 498
<a href=“https://documentation.gladysassistant.com/fr/api#mqtt-api”> ici .",

Xiaomi : Ligne 528
<a href=“https://documentation.gladysassistant.com/fr/configuration#xiaomi-configuration”> ici .",

Application Authy : Ligne 1144, la page Apple a bien une page dédiée en FR, pas de soucis pour google play
<a href=“https://itunes.apple.com/fr/app/authy/id494168017?mt=8”>iOS

Autre chose, des espaces s’étaient glissés lignes 55 et 297, à remplacer par :
<a href =“https://community.gladysassistant.com”> Gladys community .",

**Comment by Terdious** [comment]
After testing on the http links, in fact there are some that are still written in hard:
- Gladys Plus abonnement : front\src\routes\settings\settings-gateway\GatewayPricing.jsx - 
Ligne 106 : `<a href="https://gladysassistant.com/pricing" class="btn btn-green btn-block">`

- Gladys Plus Mot de passe oublié : front\src\components\gateway\GatewayLoginForm.jsx
Ligne 5 : `const EXTERNAL_FORGOT_PASSWORD_LINK = 'https://plus.gladysassistant.com/forgot-password';`
Lignes 74 à 77 : `<a href={props.external_forgot_password ? XTERNAL_FORGOT_PASSWORD_LINK : '/forgot-password'} class="float-right small">`

**Comment by Terdious** [comment]
Files fr.json of folders front\src\config\i18n modified
[fr.txt](https://github.com/GladysAssistant/Gladys/files/4602873/fr.txt)

**Comment by atrovato** [comment]
> Gladys Plus Mot de passe oublié : front\src\components\gateway\GatewayLoginForm.jsx
Ligne 5 : const EXTERNAL_FORGOT_PASSWORD_LINK = 'https://plus.gladysassistant.com/forgot-password';
Lignes 74 à 77 : <a href={props.external_forgot_password ? XTERNAL_FORGOT_PASSWORD_LINK : '/forgot-password'} class="float-right small">

Pour cette URL ci, je ne sais pas s'il existe une version française. Si oui, quelle est l'URL ?

**Comment by Terdious** [comment]
@atrovato,
Je n'en ai aucune idée pour ma part. J ai fait plusieurs essais mais je n'ai pas fait mouche. Ce qui est marrant c'est que les variables en/fr existe visiblement, ou en tout cas, il y en a qui reprennent tous les texte de cette page. Je laisse @Pierre-Gilles te répondre, mais elle sera sûrement à créer.

**Comment by Terdious** [comment]
@atrovato, I'm sorry but I found other things ... 
In device / feature :
- Line 554 file fr.json : "addActionButton": "Ajouter une nouvelle action", replace with "Nouvelle action" or better - Edit Scene / Button New trigger,
- Line 559 file fr.json : "addNewTriggerButton": "Ajouter un nouveau déclencheur", replace with "Nouveau déclencheur" or better - Edit Scene / Button New action,
- Line 601 file fr.json : "get-value": "Chercher le dernier état", replace with "Récupérer le dernier état" or better - Edit Scene / New action drop down menu,
In scenes : 
- Line 942 file fr.json : "decimal": "Valeur température" replace with "Température" or better - Integration Devices / New feature drop down menu,
- Line 966 file fr.json : "decimal": "Valeur feeeumée détectée" replace with "Valeur de fumée détectée" or better (I'm sorry, my bad !! My touch was blocked ^^) - Integration Devices / New feature drop down menu.
In Profile : 
- Line 197 to 214 file profile.jsx of front/src/components/user : <div class="custom-file"> - Is it possible change Text Label of button "Browse" ? To edit the profile picture.

That's all for the moment ^^

**Comment by Pierre-Gilles** [comment]
> Pour cette URL ci, je ne sais pas s'il existe une version française.

Non, il n'y a pas de version française de cette URL, c'est une app donc l'app est traduite directement, pas de langue dans l'URL comme sur la documentation qui est un site statique

**Comment by Terdious** [comment]
> > Pour cette URL ci, je ne sais pas s'il existe une version française.
> 
> Non, il n'y a pas de version française de cette URL, c'est une app donc l'app est traduite directement, pas de langue dans l'URL comme sur la documentation qui est un site statique

Bonjour @Pierre-Gilles,
Lorsque l'on clique sur Mot de passe oublié, on se retrouve sur cette page : 
![image](https://user-images.githubusercontent.com/35010958/81670513-09ba9380-9448-11ea-9d24-644eb7c2bda2.png)
Comme tu le vois, la traduction n'est pas faite, tandis qu'effectivement, sur la documentation, la traduction est bien faite en fonction de la langue du navigateur.

**Comment by atrovato** [comment]
@Terdious it's ok for following items:

> Line 554 file fr.json : "addActionButton": "Ajouter une nouvelle action", replace with "Nouvelle action" or better - Edit Scene / Button New trigger,
Line 559 file fr.json : "addNewTriggerButton": "Ajouter un nouveau déclencheur", replace with "Nouveau déclencheur" or better - Edit Scene / Button New action,
Line 601 file fr.json : "get-value": "Chercher le dernier état", replace with "Récupérer le dernier état" or better - Edit Scene / New action drop down menu,
In scenes :
Line 942 file fr.json : "decimal": "Valeur température" replace with "Température" or better - Integration Devices / New feature drop down menu,
Line 966 file fr.json : "decimal": "Valeur feeeumée détectée" replace with "Valeur de fumée détectée" or better (I'm sorry, my bad !! My touch was blocked ^^) - Integration Devices / New feature drop down menu.
In Profile :
Line 197 to 214 file profile.jsx of front/src/components/user :
> - Is it possible change Text Label of button "Browse" ? To edit the profile picture.

**Comment by atrovato** [comment]
Also done for "forgot-password" page, now based on navigateur language if user not connected.

**Comment by Terdious** [comment]
Thank you very much !!
