### ISSUE TITLE
Display the git commit hash of the current version in "Settings" => "System"

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#777]
So the user knows which exact version he's running

**Comment by VonOx** [comment]
What do you think about that ?

![image](https://user-images.githubusercontent.com/1528694/87672428-3d30db80-c773-11ea-98b5-d4ea36957fb0.png)

**Comment by Pierre-Gilles** [comment]
Looks nice !

What about merging the "Operations" and "Informations" boxes together? It can be a "Version" box.

And put a more self-explanatory text, like "Git commit hash", and the hash should be a link to the git commit ! :)

**Comment by VonOx** [comment]
OK I agree, I will do that

**Comment by Pierre-Gilles** [comment]
Ok, not necessary at the end at we'll use a version in prod release + we are now using a version in beta as well

<img width="943" alt="Screenshot 2020-07-28 at 11 02 59" src="https://user-images.githubusercontent.com/7365207/88643384-ed7ed800-d0c1-11ea-91df-186b3c74552d.png">
