### ISSUE TITLE
Dashboard edit menu - add buttons Save/Cancel

### ISSUE THREAD

**Issue by Terdious** [GladysAssistant/Gladys#779]
In the "edit" window of the dashboard, once the scroll bar has appeared after placing a certain number of cards, it would be useful to have the "Save" and "Cancel" buttons at the bottom of the page.

**Comment by atrovato** [comment]
Hi, what do you think about something like a fixed bottom bar?

![dashboard-fixed-edit-bar](https://user-images.githubusercontent.com/1839717/81478545-81a57580-921e-11ea-92d4-b29e55726227.gif)

**Comment by Terdious** [comment]
For my part I find it perfect !!  I let @Pierre-Gilles validate ^^ 
Thank you very much @atrovato

**Comment by Pierre-Gilles** [comment]
> Hi, what do you think about something like a fixed bottom bar?

It's really nice, but what happened to your dashboard? Seems there is no card anymore? Is it a side effect or just a test?

**Comment by atrovato** [comment]
It is because of the the gif screenshot application. There is no changes on cards.

**Comment by Pierre-Gilles** [comment]
Ok ! I'll have a look at the PR, looks good to me :)
