### ISSUE TITLE
House : impossible to update informations

### ISSUE THREAD

**Issue by billonalex** [GladysAssistant/Gladys#792]
It is impossible to update a house which already exists.

<img width="897" alt="Bug maison Gladys" src="https://user-images.githubusercontent.com/1650562/81848114-e7626c00-9554-11ea-8d92-6e6927f17df9.PNG">

When the user want to add a room in a house, there is an error message which says that the house already exists. As if the user tried to create a new house with the same configuration.

**Comment by atrovato** [comment]
I can't reproduce it. I tried adding a room, deleting one, but no error.

Can you paste here what you see in browser console? If there is any error log.

**Comment by billonalex** [comment]
<img width="476" alt="POST Error" src="https://user-images.githubusercontent.com/1650562/81855530-c2bfc180-955f-11ea-9a63-fb5d92d052a2.PNG">

I have a 409 (Conflict) error.

**Comment by atrovato** [comment]
What did you do exactly?
Simply add a new room? No rename? No new house?

**Comment by billonalex** [comment]
I first tried to add a room. Impossible. This is the same for renaming my house.

However, I can add a house, but not delete it from the DB.

**Comment by Terdious** [comment]
Hi @billonalex,
Does this problem occur in dev or in prod?
I have encountered this problem many times in dev. The only way I could find to solve the problem was to go back through the creation of an account. I have never encountered this problem in production, suddenly I do not know if this solution will work.
cordially

**Comment by billonalex** [comment]
Hi @Terdious 

This problem occurs in dev. However, I have just tried to run my server in prod, the problem is still there.

Am I wrong if I launch in prod with "npm start -s prod" ? It's the first time I launch it in prod, and it seems ok for me. Or maybe should I also launch the front in prod ?

**Comment by Pierre-Gilles** [comment]
@billonalex Can you show here the content of your "house" + "room" tables? 

I'm not able to reproduce either

**Comment by billonalex** [comment]
Hello !

After some checks, it seems that the problem doesn't exist anymore for me too ^^

I don't see what did I do differently... But I can't reproduce the bug anymore ! So for me it's fixed 🙂
