### ISSUE TITLE
When exiting the dashboard, if the dashboard is in edition mode, ask "do you want to leave" 

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#795]

**Comment by atrovato** [comment]
Or maybe ask "do you want to leave?", as expect in the house edition page.

**Comment by Pierre-Gilles** [comment]
Good idea that's maybe better!

**Comment by atrovato** [comment]
Linked to #585 (on ask before component).
But that's not really easy to do with Preact.
If someone has any idea.

**Comment by Pierre-Gilles** [comment]
Indeed, just had a look and it's not that easy with preact-router...

Maybe thanks to the handleRoute function :

https://github.com/GladysAssistant/Gladys/blob/master/front/src/actions/main.js#L25

We could watch the `currentUrl` and if it changes, try to keep the currentUrl if the state is not saved + display a modal ?

**Comment by atrovato** [comment]
Should check on new preact version if "leave page" behavior is implemented.

**Comment by atrovato** [comment]
Not stale.

**Comment by atrovato** [comment]
Not stale.
I need to check preact upgrade to see if it is nativly managed for now.

**Comment by atrovato** [comment]
Still looking for solution...
