### ISSUE TITLE
Chat : Message not ordering correctly

### ISSUE THREAD

**Issue by link39** [GladysAssistant/Gladys#798]
**Describe the bug**
When I tell something in the chat, the Gladys replying appears before my answer. 

**To Reproduce**
Go to the chat and tell to Gladys to : "show me the camera image in te ...." or " What's the temperature in the ....3

**Expected behavior**
Replies should be after answers

**Screenshots**

![image](https://user-images.githubusercontent.com/2229692/81986995-25d15700-9639-11ea-93c1-f1f0fa081dae.png)

**Your Gladys installation (please complete the following information):**
Synology Docker

**Desktop (please complete the following information):**
Windows 10
Edge Chrominium

**Comment by atrovato** [comment]
Sorting is done on string instead of dates.

**Comment by Pierre-Gilles** [comment]
Nice catch @atrovato ! Thanks for the PR 🙂
