### ISSUE TITLE
On boot, Gladys Raspbian image should expand filesystem

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#834]

**Comment by VonOx** [comment]
Hi ,  I don't know if I must continue https://github.com/VonOx/gladys-pi-gen but the builder take care of this issue ( automatic expand )

To solve this issue you must edit cmdline.txt ( see https://github.com/VonOx/gladys-pi-gen/blob/gladys/stage2/01-sys-tweaks/00-patches/07-resize-init.diff )

**Comment by Pierre-Gilles** [comment]
I'm not 100% sure we are ready for this type of build right now. From a user point of view, building the image with rpi-pi-gen is not as good as what we have right now, because the container is not ready at start immediately. 

To expand the image automatically, I was thinking of adding a task at boot which automatically resize the image.

**Comment by Pierre-Gilles** [comment]
Done in the image I've built.
