### ISSUE TITLE
Scene: Add sunset and sunrise trigger

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#850]
As a user, I'm able to trigger a scene with the following triggers: 

- "When the sun rise, do XX"
- "When the sun set, do XX"
- "20 minutes before the sunset, do XX"
- "20 minutes after the sunset, do XX"

The XX minutes should be an offset variable which can be positive or negative, and stored in seconds in the trigger.

**Comment by Pierre-Gilles** [comment]
@VonOx thanks for your issue, I edited it so it's more clear

**Comment by callemand** [comment]
I have made a first MR who add only the trigger on sunset and sunrise but not the time offset 
https://github.com/GladysAssistant/Gladys/pull/1026

**Comment by Pierre-Gilles** [comment]
Thanks for your PR ! 🙏

By looking at the code, I saw that you used OpenWeather API. I'm not sure we want to rely on a third-party to calculate sunrise/sunset time, it could be calculated locally very easily, and it would probably be simpler in terms of code implementation :)  

There are great libraries to do that: 

- https://www.npmjs.com/package/sunrise-sunset-js
- https://github.com/mourner/suncalc
- And probably many mores :) 

Maybe you could investigate the full landscape of libraries and find the best/most used/the cleanest one ?

**Comment by callemand** [comment]
I have investigate on all npm library and for me the "best" is [suncalc](https://www.npmjs.com/package/suncalc). 
This library is mature, light and downloaded about 10.000 by week.
I have change the code with this library.

**Comment by Pierre-Gilles** [comment]
Great! Thanks for taking the time 🙏

**Comment by Pierre-Gilles** [comment]
I'm removing this issue as we developed the sunrise/sunset trigger.

For the offset part, it could be a feature request on the forum, I'm closing this as we don't use issues anymore for features.
