### ISSUE TITLE
Philips Hue: Add device LWA001

### ISSUE THREAD

**Issue by guillaumeLamanda** [GladysAssistant/Gladys#851]
Issue automatique d'intégration d'un lampe Philips Hue.  
Ce sont les ampoules du "Starter Kit" de Philips.  

Je peux contribuer à l'intégration, mais je ne vois nul part de fichier `CONTRIBUTING.md`. Ce serait vraiment bien d'en avoir un. 

Données de l'ampoule : 
```
{
  "name": "Hue white lamp 2",
  "service_id": "86b98c11-f85f-44e4-8f18-030576b3ee9d",
  "external_id": "philips-hue-light:ecb5fa23912a:2",
  "selector": "philips-hue-light:ecb5fa23912a:2",
  "should_poll": true,
  "model": "LWA001",
  "poll_frequency": 60000,
  "features": [],
  "not_handled": true,
  "raw_philips_hue_device": {
    "_rawData": {
      "state": {
        "on": true,
        "bri": 254,
        "alert": "select",
        "mode": "homeautomation",
        "reachable": true
      },
      "swupdate": {
        "state": "transferring",
        "lastinstall": null
      },
      "type": "Dimmable light",
      "name": "Hue white lamp 2",
      "modelid": "LWA001",
      "manufacturername": "Signify Netherlands B.V.",
      "productname": "Hue white lamp",
      "capabilities": {
        "certified": true,
        "control": {
          "mindimlevel": 5000,
          "maxlumen": 800
        },
        "streaming": {
          "renderer": false,
          "proxy": false
        }
      },
      "config": {
        "archetype": "classicbulb",
        "function": "functional",
        "direction": "omnidirectional",
        "startup": {
          "mode": "safety",
          "configured": true
        }
      },
      "uniqueid": "<macAddress>",
      "swversion": "1.53.3_r27175",
      "swconfigid": "D6781B83",
      "productid": "Philips-LWA001-1-A19DLv5"
    },
    "_id": 2
  }
}
```

**Comment by Pierre-Gilles** [comment]
Merci d’avoir ouvert cette issue ! 

> je ne vois nul part de fichier CONTRIBUTING.md. Ce serait vraiment bien d'en avoir un.

Il y a pourtant un [contributing.md](https://github.com/GladysAssistant/Gladys/blob/master/.github/CONTRIBUTING.md) assez visible 😅 

<img width="971" alt="Screenshot 2020-08-19 at 17 38 02" src="https://user-images.githubusercontent.com/7365207/90659437-f5efac00-e244-11ea-9528-7fdb56afc16b.png">

Si tu veux proposer une PR Philips Hue, tu peux t’inspirer d’une autre PR dédiée aux Philips Hue, comme par exemple celle-ci:

https://github.com/GladysAssistant/Gladys/pull/781

**Comment by guillaumeLamanda** [comment]
My bad, mettons ça sur le compte de la fatigue 😅

Je vais préparer un PR pour cette version des Philips Hue

**Comment by Pierre-Gilles** [comment]
Top! 

Autres petites ressources pratiques:

- [Setup a development environnement](https://gladysassistant.com/en/docs/api/setup-development-environnement)
- [Developing a service](https://gladysassistant.com/en/docs/api/developing-a-service)

N'hésite pas si tu as des questions à venir sur le forum => https://community.gladysassistant.com/
