### ISSUE TITLE
See if we can display last refresh of image on dashboard on hover

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#857]
On the dashboard, on a camera image, if I hover with my mouse, I can see the last refresh of the camera.

**Comment by Terdious** [comment]
Hey !!
On the netatmo PR #1015, we made a proposal on the box camera avec @thibautmery. The display of the last image taken is moved up to the right of its name.
![unknown-1](https://user-images.githubusercontent.com/35010958/106356597-26159d80-6301-11eb-91ec-d7f3c0fe8387.png)

**Comment by Pierre-Gilles** [comment]
Mmm I don't really like it ^^

I don't think we need the info all the time, why not on hover?

**Comment by VonOx** [comment]
> 
> 
> Mmm I don't really like it ^^
> 
> I don't think we need the info all the time, why not on hover?

PWA ?

**Comment by atrovato** [comment]
With a little clock icon, on click and/or hover ?

**Comment by Pierre-Gilles** [comment]
Why not just on hover/click on the image?

We discussed with @Terdious about why he wants that, and after going down to the real need, he wants that to be sure that his camera is not offline

So same debate as for the battery, no need to always display it, Gladys could just automatically send a message when the camera is offline!

**Comment by Terdious** [comment]
Hey @Pierre-Gilles, @VonOx, @atrovato, would this be fine?
![Gladys-Date-Camera](https://user-images.githubusercontent.com/35010958/107133169-97e37d80-68e5-11eb-9ecd-bdc509e47941.gif)
We can also do it in css to have a skin.

**Comment by atrovato** [comment]
As we plan to get a bigger view of the picture, not sure the onclick on it to get time is a good way.

**Comment by Terdious** [comment]
@atrovato, why a click?  there is no click here (when there is a click, there is a little wave that appears on the GIF).  It is a mouse crossing.  I just used "title" to display it.  You can see it in the code.

however, as @VonOx  told me, not sure if it works on phones (I'm trying to test today).  So he (@VonOx ) proposed to put the date inlaid in the image via the "overlay"
Ex @VonOx : 
![unknown-2](https://user-images.githubusercontent.com/35010958/107142198-6db5ae00-692d-11eb-83a0-48256a221492.png)

**Comment by VonOx** [comment]
Yeah for me there is no debat.

Message in case camera is disconnected/offline is usefull, but we need information of timestamp directly on dashboard without needing of a scene or click on image etc.

I'm thinking of multiple dashboard, one dedicated for "security view" of my house, I'dont want to hover each camera .

**Comment by Pierre-Gilles** [comment]
@Terdious I really like this! :) 

@VonOx Why do you need the time displayed ? I still don't understand why having an automation, or a red message on the box saying "camera connection was lost at HH:mm" only when the connection is not live, is not better than always displaying the time?

**Comment by VonOx** [comment]
Just because the purpose of camera is security. If for some reason message or alert or scene not working, nothing inform me that camera ( or Gladys ) is not working as expected.
All camera system I know have a timestamp. There is a lot of psychology behind this but I think this little overlay cost nothing.

If you think this is ugly or something, we can make it optional.

**Comment by Terdious** [comment]
> @Terdious I really like this! :)

Thank you @Pierre-Gilles !!
However that does not solve the problem of the telephone part?

I would do there as it will be decided of course, but despite everything, I remain of the same opinion as @VonOx  and of my basic idea. My cameras are there for security, and I would be very interested to have the date / time directly. It does not eat up more space at the window level and it is cleaner (whether for either of the proposals - embedded in the image or next to the name of the cam). After the idea of @VonOx to be able to make it configurable with a checkbox in the device is interesting I find

**Comment by atrovato** [comment]
Overlay is nice, love it too.

**Comment by Pierre-Gilles** [comment]
I think an overlay could be nice, if it's beautifully designed 🙂

I was against the current proposal mostly because it looked not that nice, and against the overlay proposal because it looked like a 1998 security cam. 

I really think the biggest point of people using Gladys is because it has a fresh and modern UI, light to use and not too bloated. 

So I'm ok for the overlay if : 

- Optional
- Beautifully designed
- with a well chosen & light font, not too big, not hiding the image too much. In the corner is best
- Handle well camera image in white tone (if during the day) and camera image in black tone (if during the night)

But it's really for the psychological effect, because we could achieve the same result with a red banner on top of the camera saying "camera out of sync"....

**Comment by Pierre-Gilles** [comment]
I still think this is a great idea, but it should be on the forum (feature request), not on Github, so it can be prioritized and discussed.

If anyone here want to see this feature, feel free to reopen a feature request on the forum :)
