### ISSUE TITLE
Documentation: Add MQTT tutorial

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#861]

**Comment by atrovato** [comment]
Isn't it done? https://gladysassistant.com/fr/docs/integrations/mqtt/

A simple remark on the tutorial, your wrote `pièce` with the accent in the device id:

> ID externe: mqtt:cuisine:capteur-temperature. Celui-ci ne doit pas avoir d'espace et doit commencer par mqtt:. Je vous recommande de garder une convention à travers votre installation Gladys, comme par exemple mqtt:pièce_de_la_maison:nom_du_peripherique.

I'm not sure MQTT handle it very well... maybe we should not show this as an example.

**Comment by Pierre-Gilles** [comment]
Yes, I forgot to remove the todo :) 

> I'm not sure MQTT handle it very well... maybe we should not show this as an example.

It was just an example, but you're right it's not a good example. I removed the accent.
