### ISSUE TITLE
Documentation: Add a rich Caldav tutorial in the docs

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#868]
See what has been done on OpenWeather and do the same with CalDav

FR: https://gladysassistant.com/fr/docs/integrations/openweather
EN: https://gladysassistant.com/en/docs/integrations/openweather

**Comment by Pierre-Gilles** [comment]
@bertrandda would you be able to help us on this? :)

**Comment by bertrandda** [comment]
Yes, I'll do it

**Comment by Pierre-Gilles** [comment]
Done in https://github.com/GladysAssistant/v4-website/pull/10
