### ISSUE TITLE
Documentation: Add more screenshots/explaination in the Philips Hue tutorial

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#869]
See what has been done on OpenWeather and do the same with Philips Hue:

FR: https://gladysassistant.com/fr/docs/integrations/openweather
EN: https://gladysassistant.com/en/docs/integrations/openweather

**Comment by Pierre-Gilles** [comment]
@hotfix31 @Terdious @guillaumeLamanda can someone help us with this? :)

**Comment by cicoub13** [comment]
Do we steel need screenshots and explanations about the Philips Hue documentation or the video is OK ?
Do we need the same video for 🇬🇧 ?

**Comment by Pierre-Gilles** [comment]
I think it'll be great to have a more rich text tutorial like it is for the camera tutorial for example (for SEO purpose mainly) with screenshots.

The video is not needed in EN :)
