### ISSUE TITLE
Documentation: Add a rich Telegram tutorial in the documentation

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#871]
See what has been done on OpenWeather and do the same with Telegram

FR: https://gladysassistant.com/fr/docs/integrations/openweather
EN: https://gladysassistant.com/en/docs/integrations/openweather

**Comment by Gaetanb76** [comment]
J'ai commencé la page de la doc.
Il me reste à insérer les images, ce que je ne sais pas faire, et à proposer une vue du résultats sur appareil mobile.
[https://github.com/GladysAssistant/v4-website/pull/9](https://github.com/GladysAssistant/v4-website/pull/9)
