### ISSUE TITLE
Documentation: Add more information to the "Tasmota/Sonoff" tutorial in the docs

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#872]
See what has been done on OpenWeather and do the same with Tasmota

FR: https://gladysassistant.com/fr/docs/integrations/openweather
EN: https://gladysassistant.com/en/docs/integrations/openweather

**Comment by Pierre-Gilles** [comment]
@atrovato would you be able to help us on this? :)

**Comment by atrovato** [comment]
With pleasure, ASAP :)

**Comment by atrovato** [comment]
@Pierre-Gilles should I do this in https://github.com/GladysAssistant/v4-website Git repo?

**Comment by Pierre-Gilles** [comment]
Yes ! The other repo is archived.

**Comment by atrovato** [comment]
PR here: https://github.com/GladysAssistant/v4-website/pull/11/files
