### ISSUE TITLE
As a user, I'd like to customize my Selector when creating my user

### ISSUE THREAD

**Issue by pebou** [GladysAssistant/Gladys#884]
**Is your feature request related to a problem? Please describe.**
When a user is created, its selector is based on its firstname and can't be modified

**Describe the solution you'd like**
Allow the user to edit the selector

**Comment by Pierre-Gilles** [comment]
Why do you want that? Where do you use the selector ?

**Comment by Pierre-Gilles** [comment]
Closing this as there was no answer.
