### ISSUE TITLE
In device in rooms box, sometimes relative time is in the future

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#887]
https://community.gladysassistant.com/t/dashboard-evolutions-bugs-etc/5150/23?u=pierre-gilles

There should be a frontend check to verify that the relative time shouldn't be in the future, and if yes, change a little bit the datetime passed.

**Comment by Pierre-Gilles** [comment]
There is a more recent issue for the same bug: https://github.com/GladysAssistant/Gladys/issues/1328

**Comment by LM1LC3N7** [comment]
Hello there, 

Here what I just discover:
![image](https://user-images.githubusercontent.com/14235706/190126829-ae89cfb0-5ccf-4c1c-a7de-31aeb2a30f5f.png)

It seems there is a similar bug.
