### ISSUE TITLE
Problème de creation de compte

### ISSUE THREAD

**Issue by jeammimi** [GladysAssistant/Gladys#9]
Bonjour, je n'arrive pas a créer un compte.
J'ai essayé plusieurs type de mail
test.test@gmail.com
test@test.fr
a chaque fois j'ai le message:
[{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid","model":"User","invalidAttributes":{"email":[{"rule":"email","message":"\"email\" validation rule failed for input: 'test.test@gmail.com'"}]}}]

Comme je n'y connais rien en node.js, je ne sais même pas ou trouver le fichier qui 
comporte cette vérification.

**Comment by Pierre-Gilles** [comment]
C'est le module de validation de sailsjs qui doit perdre la tête, c'est étrange tu es le seul à avoir ce problème au niveau des mails ! Surtout que chez moi la validation fonctionne très bien avec ce même mail. La validation se fait grâce à [Anchor](https://github.com/balderdashy/anchor), du framework sails.js. Le fichier incriminé est dans `api/models/User.js`.

**Comment by jeammimi** [comment]
Merci,
C'est surement pas la bonne façon de régler le problème, mias au cas ou,
juste en enlevant email:true, dans le fichier api/models/User.js
le problème disparait.
J'espère que ce ne sera pas un problème pour plus tard.

**Comment by Pierre-Gilles** [comment]
Effectivement ce n'est pas la bonne façon de faire, ça enlève la vérification sur le mail. ( du coup un user peut rentrer n'importe quoi ). 

Je garde ce problème dans un coin de ma tête, j'essaie de voir d'ou vient ce bug étrange.
