### ISSUE TITLE
Integration zwave non fonctionelle

### ISSUE THREAD

**Issue by RunGp** [GladysAssistant/Gladys#905]
Bonjour

**Describe the bug**
Sur mon installation zware : 
**Clé Zwave everspring capatible zwave et zwave plus**
![everspring](https://user-images.githubusercontent.com/11268887/96539587-7b76f300-12ac-11eb-8800-aa271e4d6652.jpg)

Peripherique Zwave 
1. **Hank HKZW-DWS0**1 - Détecteur d’ouverture de portes et fenêtres Z-Wave+ [https://www.domotique-store.fr/domotique/modules-domotiques/detecteurs-capteurs-mesure/ouverture-porte-fenetre/777-hank-hkzw-dws01-detecteur-d-ouverture-de-portes-et-fenetres-z-wave-alimente-par-piles-alcalines-aaa.html](url)
2. **AEOTEC Tri Sensors** [https://www.domotique-store.fr/domotique/modules-domotiques/detecteurs-capteurs-mesure/detecteurs-mouvements-domotique-sans-fil-alarme/997-aeotec-zwa005-trisensor-capteur-3-en-1-mouvement-temperature-et-luminosite-z-wave.html](url)

L'integration se passe bien mais les données ne remonte pas et difficile de faire des scenes avec...

**To Reproduce**
Aprés recherche j'observe que
Pour mes 2 appareils la fonctionalité motion ("capteur d'ouverture/ou de precense') ne remonte jamais rien
Que la temperature/luminosité/baterrie remonte 1 fois par h depuis le tri-sensors (trés insuffisant)

**Expected behavior**
Declancher une scene dés la reception d'une motion ouverture/precence
Pouvoir pull la luminosité/temperature toute les minutes

**Your Gladys installation **

Raspberry pi3 avec l'image officielle de gladys (beta 16)

**Desktop **

- OS: Arch Linux (rolling release)
- Browser : Firefox 82
- Version : 82

**Comment by tagcashdev** [comment]
Bonjour j'ai le même problème, je sais pas comment résoudre : 

**Équipements Z-Wave**
-Fibaro capteur de mouvement
-Fibaro Socket
-Aeotec Z-Stick Gen5

**Description du bug**
les données ne remonte pas toutes et il est difficile de faire des scenes, par exemple allumer lors de détection de mouvement.

![Screenshot_20210427_151258_com android chrome](https://user-images.githubusercontent.com/29637320/116250233-d4e54080-a76d-11eb-9f38-749364b0f57c.jpg)


**Mon installation Gladys**
Raspberry pi 400, installation avec docker hier...

**Comment by EchoPouet** [comment]
Bonjour, j'ai également des problèmes avec mes détecteurs d'ouverture de porte. Ils sont bien détectés et intégrés mais je n'ai pas de retours.

Les appareils sont:
- FIBARO DOOR/WINDOW SENSOR 2 (FGDW-002) -> doc https://manuals.fibaro.com/content/manuals/en/FGDW-002/FGDW-002-EN-T-v1.1.pdf
- Aeotec ZWA008 - Door/Window Sensor 7 -> doc https://help.aeotec.com/support/solutions/articles/6000218764-door-windows-sensor-7-user-guide
