### ISSUE TITLE
Add service management page

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#910]
Add a setting page to list and manage services: see status, able to stop / start services...

**Comment by atrovato** [comment]
@Pierre-Gilles I'm working on the service page (to start / stop if if needed).
So I'll need to add a new "service.started" event over websocket.
But to do this, I'll need (2 possiblities):
1. to handle the `gladys.event.emit(EVENTS.ACTION.TRIGGERED, action);` on service side, which implies to move following lines from scene.actions.js
```
  [ACTIONS.SERVICE.START]: async (self, action, scope) => self.stateManager.get('service', action.service).start(),
  [ACTIONS.SERVICE.STOP]: async (self, action, scope) => self.stateManager.get('service', action.service).stop(),
```

2. or to call (no wait) directly `serviceManager.start(service)` from controller.

Any preference? (do you need more information?)

**Comment by atrovato** [comment]
A simple preview

![image](https://user-images.githubusercontent.com/1839717/97736175-95e67300-1adb-11eb-9da8-9efa3590a3c7.png)

**Comment by Pierre-Gilles** [comment]
This looks really great! Nice job!
