### ISSUE TITLE
[MQTT] Luminosity control from dashboard

### ISSUE THREAD

**Issue by Omega-Phone** [GladysAssistant/Gladys#915]
**Is your feature request related to a problem? Please describe.**
Currently, from dashboard, only sensors values and on/off commands are supported for Mqtt service. It could be a nice feature to be able to send analogic values, such as luminosity and color, in order to control strip led or light bulb for instance.

**Describe the solution you'd like**
The solution should be presented as different sliders (for different parameters) providing values from a minima to a maxima and publishing those values to the mqtt broker.

**Additional context**
A special attention is required concerning the value format:

1. Luminosity:
    From UI-side, the most user-friendly representation seems to be a percentage (value from 0 to 100).

2. Color
    RGB representation is composed of three bytes (one for each color) with value from 0 to 255. But it isn't a very user-friendly way to represent it. An alternative is the HSV representation where the color (hue) is represented as a number (of degree) from 0 to 360. So it could be displayed as only one slider.

**Comment by Pierre-Gilles** [comment]
FYI, color control is done. I remove "color" from the title :)

**Comment by atrovato** [comment]
Related to https://github.com/GladysAssistant/Gladys/issues/1141

**Comment by Pierre-Gilles** [comment]
Luminosity control is already in Gladys, I think this can be closed
