### ISSUE TITLE
Dashboard box showcase

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#922]
That's a just a idea,
to avoid to overload demo dashboard with all kind of device box,
and to not create a specific dema device for each each,

what if we create an "hidden showcase page" to list all device category / type and display it's related dashboard box?

I think this can help us to find any missing.

**Comment by atrovato** [comment]
First preview.
2 columns: actionnable and read only devices.

![showcase](https://user-images.githubusercontent.com/1839717/102934976-7cdbbc00-44a5-11eb-87ab-9cda6af5218f.gif)

This will be enabled only on demo mode.

**Comment by Pierre-Gilles** [comment]
Mmm it's a little weird no? I think the demo mode should only be a real world example of Gladys, without changes!

**Comment by atrovato** [comment]
Ok, but I keep it anyway on a branch, it is usefull to check box easily.
