### ISSUE TITLE
Error run gladys with docker: SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by fraoustin** [GladysAssistant/Gladys#923]
**Describe the bug**
I run gladys by docker and i have a error

> 2020-11-08T11:52:26+0100 <error> index.js:14 (process.<anonymous>) unhandledRejection catched: Promise {
>   <rejected> ConnectionError [SequelizeConnectionError]: SQLITE_CANTOPEN: unable to open database file
>       at Database.<anonymous> (/src/server/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:66:63) {
>     parent: [Error: SQLITE_CANTOPEN: unable to open database file] {
>       errno: 14,
>       code: 'SQLITE_CANTOPEN'
>     },
>     original: [Error: SQLITE_CANTOPEN: unable to open database file] {
>       errno: 14,
>       code: 'SQLITE_CANTOPEN'
>     }
>   }
> }
> 

**To Reproduce**

Go to terminal

> docker run -d \
> --log-opt max-size=10m \
> --name gladys \
> -e NODE_ENV=production \
> -e SERVER_PORT=80 \
> -e TZ=Europe/Paris \
> -e SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db \
> -v /var/run/docker.sock:/var/run/docker.sock \
> gladysassistant/gladys:v4-amd64

I have a same error if i add volume /var/lib/gladysassistant

**Your Gladys installation (please complete the following information):**

- use docker on linux Debian

**Comment by fraoustin** [comment]
the problem is from  "-e SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db"

in the docker image, the path /var/lib/gladysassistant/ does not exist

In the documentation  https://gladysassistant.com/fr/docs/installation/docker/, i read the path /var/lib/gladysassistant/gladys-production.db

Without variable SQLITE_FILE_PATH, i found gladys-production.db in /src/server

If add in my command

> -e SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db \
> -v /var/lib/gladysassistant:/home/fraoustin/Downloads/gladysassistant/gladysassistant \

I have the same problem ...

**Comment by fraoustin** [comment]
I think that it is necessary to add in Dockerfile

> RUN mkdir /var/lib/gladysassistant/

**Comment by VonOx** [comment]
@fraoustin

Bind mount is `- v /host/path:/container/path`

You have inverted host path and container path

**Comment by fraoustin** [comment]
I am stupid ... excuse me
