### ISSUE TITLE
Philips Hue: Add device LCT003

### ISSUE THREAD

**Issue by Aure51800** [GladysAssistant/Gladys#924]
```
{
  "name": "Spot 1",
  "service_id": "86b98c11-f85f-44e4-8f18-030576b3ee9d",
  "external_id": "philips-hue-light:001788781f6f:1",
  "selector": "philips-hue-light:001788781f6f:1",
  "should_poll": true,
  "model": "LCT003",
  "poll_frequency": 60000,
  "features": [],
  "not_handled": true,
  "raw_philips_hue_device": {
    "_rawData": {
      "state": {
        "on": false,
        "bri": 16,
        "hue": 62343,
        "sat": 30,
        "effect": "none",
        "xy": [
          0.4048,
          0.3646
        ],
        "ct": 283,
        "alert": "none",
        "colormode": "xy",
        "mode": "homeautomation",
        "reachable": true
      },
      "swupdate": {
        "state": "noupdates",
        "lastinstall": "2020-06-13T17:34:02"
      },
      "type": "Extended color light",
      "name": "Spot 1",
      "modelid": "LCT003",
      "manufacturername": "Signify Netherlands B.V.",
      "productname": "Hue color spot",
      "capabilities": {
        "certified": true,
        "control": {
          "mindimlevel": 5000,
          "maxlumen": 250,
          "colorgamuttype": "B",
          "colorgamut": [
            [
              0.675,
              0.322
            ],
            [
              0.409,
              0.518
            ],
            [
              0.167,
              0.04
            ]
          ],
          "ct": {
            "min": 153,
            "max": 500
          }
        },
        "streaming": {
          "renderer": true,
          "proxy": true
        }
      },
      "config": {
        "archetype": "spotbulb",
        "function": "mixed",
        "direction": "downwards",
        "startup": {
          "mode": "safety",
          "configured": true
        }
      },
      "uniqueid": "00:17:88:01:02:5e:7b:e4-0b",
      "swversion": "5.130.1.30000"
    },
    "_id": 1,
    "mappedColorGamut": "B"
  }
}
```

**Comment by Aure51800** [comment]
Bonjour,
Je suis en passe de passer de Home Assistant vers Galdys, qui en plus d'être français me parait beaucoup plus simple d'utilisation.
J'ai actuellement un Fibaro HC2, un pont Hue et un pont Tradfri.
Je ne peux aller plus loin dans mon installation pour le moment, car la majorité de mes équipements non Z-Wave n'est pas supporté.
Le projet v4 est encore jeune, je vais donc le laisser tourner en parallèle avec mon HA, le temps que les équipements soient supporter par Gladys.
Bonne journée:

**Comment by Pierre-Gilles** [comment]
@Aure51800 : Merci pour ton retour ! 

Peux-tu nous donner plus d'informations sur tes périphériques Z-Wave sur le forum (https://community.gladysassistant.com/) pour que l'on puisse les intégrer à Gladys ? Tu peux créer un topic et nous donner tous les informations ? Merci d'avance.

Pour l'ampoule Philips Hue, c'est bon elle est intégrée, cela partira dans la prochaine mise à jour.

**Comment by Aure51800** [comment]
Bonjour,
Merci pour ta réponse rapide et ton efficacité de déploiement.
Je n'ai aucun problème pour la partie zwave, j'ai des motion sensor fibaro
ainsi que des smoke sensor.
Les équipements qu'il me manque actuellement sont des ampoules tradfri via
la gateway. Ainsi que des prises WiFi gère via tuya. Pour cette dernière,
intégration je vais mettre les mains dans le cambouis.
J'ai vu que c'était intégré sur la v3 pour tradfri, donc je pense que ce
n'est qu'une question de temps.
En tout cas je suis bluffé par ta rapidité de réponse, félicitation. Ça me
conforte dans ma migration.
Bonne soirée !

**Comment by Pierre-Gilles** [comment]
> Je n'ai aucun problème pour la partie zwave, j'ai des motion sensor fibaro
ainsi que des smoke sensor.

Ok tant mieux ! 

> Ainsi que des prises WiFi gère via tuya. Pour cette dernière, intégration je vais mettre les mains dans le cambouis.

Génial ! N'hésite pas à venir en parler sur le forum pour que la communauté sache que tu travaille la dessus :) On est preneur de toute PR qui permet d'ajouter des compatibilités, ça sera avec plaisir.

> En tout cas je suis bluffé par ta rapidité de réponse, félicitation. Ça me
conforte dans ma migration.

Merci du feedback, ça fait plaisir :) 

De manière générale, si tu as d'autres besoins / retours / idées / questions, le forum est le meilleur endroit pour ça : 

https://community.gladysassistant.com
