### ISSUE TITLE
Dashboard : Device value on 2 lines

### ISSUE THREAD

**Issue by Hamtar0** [GladysAssistant/Gladys#925]
I don't know why...
Browser : Opera GX on Mac OS
Same thing on Chrome, obviously (Opera based on Chrome)

<img width="374" alt="Capture d’écran 2020-11-08 à 14 28 44" src="https://user-images.githubusercontent.com/1239484/98466310-0f165200-21cf-11eb-80a9-019912de1cc2.png">

**Comment by atrovato** [comment]
This is due to `Xiaomi Duplex Wired Switch Neutral` very long name.
I can reproduce on my local env using same name.

**Comment by Hamtar0** [comment]
Strange... Only one line affected and in the middle... oO

**Comment by atrovato** [comment]
Number `6` looks larger than `5` 😄
