### ISSUE TITLE
Smart life integration

### ISSUE THREAD

**Issue by storm1er** [GladysAssistant/Gladys#929]
There's a lot of devices compatible with smart life and not with gladys yet. A smart life integration could be an excellent solution until each devices are directly compatible with it. (Amibot, novostella bulb, Shelly IoT, ...)

**Describe the solution you'd like**
By enabling the integration, we could select devices to add to gladys (and maybe how to use them if they are unknown by gladys if smart life include some devices descriptor)

**Comment by Pierre-Gilles** [comment]
Hey ! 

Can you post this feature in this topic on the forum :  https://community.gladysassistant.com/c/feature-requests/43 so people can vote for it and see who's interested ?

It's what we use to prioritize features with the community :)
