### ISSUE TITLE
MQTT : ESP Easy doesn't support more than 40 characters long topics in reception (Gladys -> ESPEasy)

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#933]
**Issue**

It seems that ESP Easy modules doesn't support more than 40 characters long MQTT topic to listen to (ESP Easy listening to MQTT message published by Gladys, for example to wait for a state change), which means they cannot work with current Gladys integration.

**To discuss**

Propose an optional way to publish to a custom topic name, stored in device params ? 

For example, in an optional input that we can show on each non-sensor device feature in the MQTT UI, we can add a "MQTT topic" fields

What do you think @atrovato ? 

I know that I pushed for fixed topic names, but here we have a strong limitation that prevent them for being used with Gladys Assistant v4. If you have any other idea I'm open :)

**Comment by atrovato** [comment]
40 chars long... wow it's a bit small... I will check for ESPEasy, we may add new service, as Tasmota.

**Comment by Pierre-Gilles** [comment]
why can't we just modify the MQTT service and add an optional custom topic ? (to be discussed, but this seems like an easy win that makes sense no?)

**Comment by atrovato** [comment]
I just read ESPEasy doc, not clear for me.
It looks loke MQTT is not enabled by default, but it need to have an built-in plugin...

**Comment by Pierre-Gilles** [comment]
> I just read ESPEasy doc, not clear for me.

What is not clear ?

**Comment by atrovato** [comment]
How to use "native" ESPEasy MQTT.

**Comment by Pierre-Gilles** [comment]
Same user is talking about this issue again: https://twitter.com/Monwifi_fr/status/1434805893150003206
