### ISSUE TITLE
Add a device category/type for rolling shutters

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#934]
**Functional specs**

It should be able to be open/close with different levels:

- 0%
- 25% if supported?
- 50% 
- 75% if supported?
- 100%

**To do**

- Imagine a design to simply move the shutters in the UI (Maybe a set of buttons?, or a slide?)
- See how we can supports different types of devices which supports only 2 states (on/off), only 3 states (0-50-100%), only 4 states (0-25-50-100%), only 5....
- How does it work for MQTT users?

@atrovato  any opinion on that for the MQTT part ? It was asked by a MQTT user

**Comment by atrovato** [comment]
Not sure to understand the question, but I think a int 0 - 100 a percent is doing it well.
Let me check on Tasmota service if I already defined it.

Dashboard display is another question.

**Comment by Pierre-Gilles** [comment]
I'm talking about user experience ! It doesn't solve the problem, how do you know on the UI side which percentage the device supports?

I had a feedback of a user which had shutters which only supports 0, 50 et 100%. 

So a slider doesn't work, it needs to be like 3 buttons [closed] [50%] [open]

But this is not generic, because as I said another users can have a rolling shutters with another configuration.

The question is how to make this easy to specify for the user

**Comment by Pierre-Gilles** [comment]
I'm thinking about it 😃

**Comment by Pierre-Gilles** [comment]
When thinking about it, it's maybe more a general question : how do we handle devices with specific functions ?

For example devices with multi-states button ? (0, 1, 2)

How do we define them in an "open" services like MQTT ?

**Comment by atrovato** [comment]
What about a [ up | stop | down ] swith?

**Comment by Pierre-Gilles** [comment]
It's not the question ! How do you know that the roller shutter supports up / stop / down ?

The question is : Right now in Gladys, we only handle a simple type in the UI : On/Off.

How do we handle multi-state types ? 
 
- How do we represent them in DB ? 
- How does the service tells Gladys "My device supports this, this and this". ?
- How do we handle service like MQTT where it's the user which defines the device ?

**Comment by atrovato** [comment]
I think we can have a look to other existing platforms to handle new device types

https://developers.google.com/assistant/smarthome/guides/shutter

https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html

For Google, shutter is a percent and a direction, so an integer 0 - 100 can do the job for us.
With a new device feature SHUTTER / OPEN (?).

So a simple setValue with int on this feature will do the job.
But UI is another topic.

**Comment by Pierre-Gilles** [comment]
Let's talk about it here : https://community.gladysassistant.com/t/gestion-des-volets-roulants/5693

**Comment by Pierre-Gilles** [comment]
Ok closing this as it's a feature request, and we were already talking about it on the forum.
