### ISSUE TITLE
Zigbee support

### ISSUE THREAD

**Issue by MagicFab** [GladysAssistant/Gladys#937]
I can't find any mention of Zigbee support (or lack thereof). I'd like to propose adding support for this protocol.

Although current integrations like Philips Hue and Xiaomi Home provide access to these brands Zigbee devices, they require third-party, non-free, privacy-invasive software that defeats Gladys purpose. 

This is to track existing or coming Zigbee support via USB radios such as : 

* Digi XStick2 (XU-Z11) - [link1](https://www.mouser.com/ProductDetail/XU-Z11?R=0virtualkey0virtualkeyXU-Z11), [link2](https://www.digikey.com/product-detail/en/digi-international/XU-Z11/602-1144-ND/2199598)
* [ConBee Zigbee USB stick](https://phoscon.de/en/conbee)
* [ConBee II Zigbee USB stick](https://phoscon.de/en/conbee2)

At least three other free open source software projects support Zigbee although I don't know if their source code (and licence) may be appropriate for integration into Gladys : 

* https://iot.mozilla.org/gateway/
* https://www.openhab.org/
* https://www.home-assistant.io/

**Comment by Pierre-Gilles** [comment]
We have a work in progress Zigbee2mqtt integration which will enable the use of USB dongles to control Zigbee devices :) 

The integration will use https://www.zigbee2mqtt.io/

if you speak french (seems you're from Canada?), we have a topic on the forum talking about it: https://community.gladysassistant.com/t/v4-integration-zigbee2mqtt/5009/113?u=pierre-gilles

**Comment by MagicFab** [comment]
Good to know, I can help to test with a Conbee 2 or [Nortek HUSBZB-1](https://www.nortekcontrol.com/products/2gig/husbzb-1-gocontrol-quickstick-combo/) once it's done.

**Comment by MagicFab** [comment]
I also noticed [a Feature requested with a vote](https://community.gladysassistant.com/t/integration-passerelle-zigbee-conbee-ii/5668it) in the forum.

**Comment by bulolo** [comment]
is there support zigbee yet?

**Comment by Pierre-Gilles** [comment]
There is a WIP development on this topic, but it's not in production yet.

**Comment by bulolo** [comment]
is there support zigbee yet? Is there a plan when to publish?

**Comment by Pierre-Gilles** [comment]
@bulolo We are in the final step of merging it, the PR is here: https://github.com/GladysAssistant/Gladys/pull/1098

You can see a working demo of the integration here: https://github.com/GladysAssistant/Gladys/pull/1098#issuecomment-806601362

**Comment by bulolo** [comment]
> @bulolo We are in the final step of merging it, the PR is here: https://github.com/GladysAssistant/Gladys/pull/1098
> 
> 
> 
> You can see a working demo of the integration here: https://github.com/GladysAssistant/Gladys/pull/1098#issuecomment-806601362

something mistake here

https://github.com/GladysAssistant/Gladys/pull/1098

**Comment by Pierre-Gilles** [comment]
@bulolo as @cicoub13 said, we don't support ser2net with remote adapter yet.

**Comment by Pierre-Gilles** [comment]
Zigbee2mqtt integration is now available in Gladys Assistant 4.2: 

https://gladysassistant.com/blog/gladys-assistant-4-2-is-here/
