### ISSUE TITLE
MQTT: UI bug when connecting external broker

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#943]
If you go to the MQTT Integration, then configure an external broker, then save, then leave and come back, you see this as it's was not configured : 

![5SZkOKSU](https://user-images.githubusercontent.com/7365207/98787876-bcc07580-2408-11eb-8ca7-a89fcb347ac3.jpg)

Source : 

![Screenshot 2020-11-11 at 10 26 48](https://user-images.githubusercontent.com/7365207/98787771-9569a880-2408-11eb-8f14-3f4521cb8970.png)

**Comment by atrovato** [comment]
I reproduce it easily. Should not be a lot of work.
On it.

**Comment by atrovato** [comment]
Ok, problème is that we store in a variable named `useEmbeddedBroker` a boolean, which is transformed to int and to string.
So we store `useEmbeddedBroker = false` but we retrieve `useEmbeddedBroker = "0"`.

So check should be on string value `useEmbeddedBroker === '1'` to check if embedded broker is used.
