### ISSUE TITLE
Unable to download from elephantcdn.

### ISSUE THREAD

**Issue by gammerboy** [GladysAssistant/Gladys#949]
First, are you sure that you found a Gladys bug?

If you are not sure, you can come discuss with us on [Gladys Community](http://community.gladysassistant.com/) 🙂

**Describe the bug**
Unable to download from the link provided in the guide(which uses elephantcdn), page gets timed out. Was not able to find the elephantcdn support page but then reporting here given it's from the same developer. Do apologies if this is the wrong place to post this report 

**To Reproduce**
Not sure. Trying to download from tamilnadu, India. Tried rebooting the modem to get new ip (dynamic ip), still not working.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22491935/99028684-6aad5a80-2596-11eb-82b8-f06b865c6710.png)

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation (if yes, which Raspberry Pi ?)
- Manual installation: [MacOS/Windows/Linux?]

**Desktop (please complete the following information):**

- OS: windows 10
- Browser - Brave 1.16.75, Firefox 83.0

**Additional context**

**Comment by Pierre-Gilles** [comment]
Hi ! 

Sorry for the slow response, we are quiet busy with the launch of Gladys Assistant 4. Servers are quiet busy as well :) 

Did it work at the end ?

If it doesn't work, could you run a nslookup of cdn.gladysassistant.com on your machine so you we could figure out at which server you are connected to. You should be connected to our Asia server. 

Also, you can download the file on GitHub as well: https://github.com/GladysAssistant/Gladys/releases/tag/v4.0.0

**Comment by gammerboy** [comment]
Hey and no issues about the slow reply tbh just saw about your cdn while looking into why amazon s3 was performing bad in a way. So just wanted to look into how elephantcdn was performing for me.

For cdn.gladysassistant.com
nslookup output:

> can't find cdn.gladysassistant.com: Non-existent domain

Using cloudflare as the dns provider.

As for cdn.elephantcdn.com:
Am still getting ERR_CONNECTION_TIMED_OUT.
nslookup output:

> Non-authoritative answer:
> Name:    elephantcdn-custom.3bc152.flexbalancer.net
> Address:  45.77.172.19
> Aliases:  cdn.elephantcdn.com

Ip details from iplookup:

> Continent: Asia.
>City: Singapore. 
> Choopa, LLC CHOOPA (NET-45-76-0-0-1) 45.76.0.0 - 45.77.255.255
> Vultr Holdings, LLC NET-45-77-172-0-23 (NET-45-77-172-0-1) 45.77.172.0 - 45.77.173.255

I'm not sure why but when downloading from github releases (github-production/amazon s3) the download speeds drop very low at times but work fast enough (about 2MB/s from what I've seen for now) at other times (well today after a while).

**Comment by Pierre-Gilles** [comment]
> I'm not sure why but when downloading from github releases (github-production/amazon s3) the download speeds drop very low at times but work fast enough (about 2MB/s from what I've seen for now) at other times (well today after a while).

Yes GitHub is very very slow in Asian country. 

> Continent: Asia.
City: Singapore.
Choopa, LLC CHOOPA (NET-45-76-0-0-1) 45.76.0.0 - 45.77.255.255
Vultr Holdings, LLC NET-45-77-172-0-23 (NET-45-77-172-0-1) 45.77.172.0 - 45.77.173.255

Ok, you're connected to the Singapore server as it should be :) 

Maybe your ISP in India is not well connected to Singapore... do you have good network speed in general? 

I tried downloading the file with a VPN through India, and I had very good speeds...

**Comment by gammerboy** [comment]
Hey, Just figured out that my router had this geoip blocking on for Singapore. Was not aware of the issue in the router as there was no alerts in the dashboard and dns was using also using a Singapore server (not sure how that works tho with how it blocks things).
Anyways, removing Singapore from the list fixed the problem and now am able to download from elephantcdn at about 6-7MB/s.
Just curious tho, is there a way to redirect traffic to another server if one is blocked on the clients side (or) is there a way to choose which server to use if required ?
Sorry for the trouble and Thank you for the help.

**Comment by Pierre-Gilles** [comment]
Not really, if client side you're blocking a range of IP we cannot detect this server-side. 

Closing this :)
