### ISSUE TITLE
Device.getByIdentifier

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#95]

**Comment by Florian56** [comment]
Plutôt : Device.getByIdentifierAndService :)

**Comment by Pierre-Gilles** [comment]
Exact :) Je verrais pour le nom

**Comment by Florian56** [comment]
J'ai vu autre chose.
Il faudrait pouvoir trouver un deviceType via :
- l'identifier du device
- et le service du device
- et l'identifier du deviceType.

Ceci pour créer un deviceState associé.

SELECT dt.id
FROM devicetype dt
INNER JOIN device d
    ON d.id = dt.device
WHERE d.identifier = ?
AND d.service = ?
AND dt.identifier = ?
