### ISSUE TITLE
Philips Hue auto-detect feature

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#952]
Instead of adding device by model,
is there any way to determine features with device raw data?

According to doc https://github.com/peter-murray/node-hue-api/blob/HEAD/docs/light.md
we might be able to be more generic.

**Comment by Pierre-Gilles** [comment]
Now that we have more data, maybe we could but I would be very careful with automated behaviour to avoid bugs like we had on the v3, or that we have with "open bar integrations" like Z-Wave...

**Comment by VonOx** [comment]
That's reminded me some Slack discussion @pierre-gilles 🙂

**Comment by Pierre-Gilles** [comment]
Yes but it's a little bit different. You were talking about automated import, he's talking about automated detection in the product :) 

With automated detection, we have the raw_data, with automated import, you don't have the raw_data!

**Comment by VonOx** [comment]
I've tested this ( based on type ) and its working

```js
      switch (philipsHueLight.type) {
        case 'Extended color light':
          lightsToReturn.push(getPhilipsHueColorTemperatureLight(philipsHueLight, serialNumber, this.serviceId));
          break;
        case 'Color light':
          lightsToReturn.push(getPhilipsHueColorLight(philipsHueLight, serialNumber, this.serviceId));
          break;
        case 'Dimmable light':
          lightsToReturn.push(getPhilipsHueWhiteLight(philipsHueLight, serialNumber, this.serviceId));
          break;
        case 'Color temperature light':
          lightsToReturn.push(getPhilipsHueWhiteTemperatureLight(philipsHueLight, serialNumber, this.serviceId));
          break;
        case 'On/Off plug-in unit':
          lightsToReturn.push(getPlugOnOff(philipsHueLight, serialNumber, this.serviceId));
          break;
```

**Comment by Pierre-Gilles** [comment]
Even for IKEA stuff? :)

**Comment by VonOx** [comment]
> 
> 
> Even for IKEA stuff? :)

Yes even Ikea / OSRAM etc have a type
https://github.com/GladysAssistant/Gladys/blob/master/server/test/services/philips-hue/lights.json#L938

**Comment by Pierre-Gilles** [comment]
@VonOx That''s nice! So if your run your code on the current list of Philips Hue device, it matches with the manual work we did (100% success rate?) ? If yes, we can definitely switch to this. But be careful to put a default case with the same behavior as we have today so people can report missing devices :)

**Comment by VonOx** [comment]
100% on my devices 😄 ( I think bridge/api take care to return a type )

We have ( in json test lights ) all the possible case. For me, implementing this is low risk.
Maybe one day hue api will return a new type, that day user will open a github issue with raw datas.

I will make a PR ( no modification on test side )

**Comment by VonOx** [comment]
> 
> 
> @VonOx That''s nice! So if your run your code on the current list of Philips Hue device, it matches with the manual work we did (100% success rate?) 

I think I've misunderstood , you mean service test ?

**Comment by Pierre-Gilles** [comment]
> I will make a PR ( no modification on test side )

Nice ! If it works with test data, I'm ok with that :) 

> I think I've misunderstood , you mean service test ?

Yes, data we have in tests, if it create the exact same results with current code and new automatic code, I'm ok !
