### ISSUE TITLE
Investigate if the NLP service can be more tolerant to spelling mistake in one word

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#958]
This is very low priority

https://community.gladysassistant.com/t/bugs-avec-la-discussion/5752/2

**Comment by VonOx** [comment]
https://github.com/axa-group/nlp.js/blob/master/docs/v4/similarity.md#spellcheck

**Comment by VonOx** [comment]
https://github.com/axa-group/nlp.js/blob/master/docs/v4/similarity.md#spellcheck

**Comment by Pierre-Gilles** [comment]
I wonder if we could include the spell check directly in the NLPManager

**Comment by Pierre-Gilles** [comment]
Seems it's better since we upgraded node-nlp! 

I'm closing this.
