### ISSUE TITLE
Z-Wave: Handle device "Unknown: id=0060 Unknown: type=0002, id=0003"

### ISSUE THREAD

**Issue by hugo99011** [GladysAssistant/Gladys#976]
```
{
  "manufacturer": "Unknown: id=0060",
  "manufacturerid": "0x0060",
  "product": "Unknown: type=0002, id=0003",
  "producttype": "0x0002",
  "productid": "0x0003",
  "classes": [
    "32",
    "48",
    "94",
    "113",
    "114",
    "115",
    "128",
    "132",
    "134"
  ]
}
```

**Comment by VonOx** [comment]
@hugo99011 

This device ?
https://products.z-wavealliance.org/products/1057

**Comment by hugo99011** [comment]
Hello @VonOx 

It's this one:
https://www.everspring.com/portfolio-item/sm810-doorwindow-contact-sensor/

**Comment by VonOx** [comment]
OpenZwave does'nt handle this device for now

https://github.com/OpenZWave/open-zwave/tree/master/config/everspring

**Comment by hugo99011** [comment]
Ok, thx for your answer 👍

**Comment by VonOx** [comment]
I will make a PR on openzwave library but this could take some times
