### ISSUE TITLE
Erreur d'installation de gladys sur un rpi docker hypriot

### ISSUE THREAD

**Issue by GSmurf** [GladysAssistant/Gladys#98]
Bonjour,

Voici ce que j'ai essayé de lancer pour faire fonctionner gladys sur un rpi sous hypriot (rpi docker) : 
mkdir -p /home/monUser/gladys/{mysql,hooks}

```
docker run --name gladys-mysql \
--restart=always \
-v /home/monUser/gladys/mysql:/var/lib/mysql \
-e MYSQL_ROOT_PASSWORD=monTest \
-e MYSQL_DATABASE=gladys \
-d mysql:latest
```

Initialiser Gladys

```
docker run --name gladys-node-init \
-v /home/monUser/gladys/hooks:/src/api/hooks \
-e NODE_ENV=development \
-e MYSQL_HOST=mysql \
-e MYSQL_PASSWORD=monTest \
-e MYSQL_PORT=3306 \
--link gladys-mysql:mysql \
gladysproject/gladys \
node init.js
```

Lancer Gladys

```
docker run --name gladys-node \
--restart=always \
-p 80:8080 \
-v /home/monUser/gladys/hooks:/src/api/hooks \
-e NODE_ENV=production \
-e MYSQL_HOST=mysql \
-e MYSQL_PASSWORD=monTest \
-e MYSQL_PORT=3306 \
--link gladys-mysql:mysql \
-d gladysproject/gladys
```

Mais voila l'erreur arrive ici : 

```
HypriotOS/armv7: monUser@monRpi in ~
$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                                  PORTS                                                               NAMES
d72bb7785b75        mysql:latest              "docker-entrypoint.sh"   6 seconds ago       Restarting (1) Less than a second ago   3306/tcp                                                            gladys-mysql

HypriotOS/armv7: monUser@monRpi in ~
$ docker run --name gladys-node-init \
> -v /home/monUser/gladys/hooks:/src/api/hooks \
> -e NODE_ENV=development \
> -e MYSQL_HOST=mysql \
> -e MYSQL_PASSWORD=monTest \
> -e MYSQL_PORT=3306 \
> --link gladys-mysql:mysql \
> gladysproject/gladys \
> node init.js
standard_init_linux.go:175: exec user process caused "exec format error"
```

**Comment by Pierre-Gilles** [comment]
C'est normal, l'image Docker n'est pas faite pour Raspberry Pi :) C'est un image basée sur l'image officielle Node.js, donc pour processeur x86/x64. Pas pour processeur ARM !

Si tu veux installer Gladys sur Raspberry Pi, tu as une image Raspbian toute prête ( mais sans Docker du coup )

Si tu veux installer Gladys via Docker sous Raspberry Pi, il va falloir faire ta propre image à partir d'une image Docker Node.js ARM ( ça peut être un projet sympa )

**Comment by GSmurf** [comment]
Je me doutais de ça mais je préfère avoir ta confirmation ! Ok dès que j'ai un peu de temps je travail à créer cette image ;)

Bonne continuation

**Comment by sylvaingiraud** [comment]
Salut, quelles sont les nouvelles du container docker de gladys sous armv7 ?
Ca m'interesse.

**Comment by Pierre-Gilles** [comment]
Je n'ai pas plus bossé dessus, après pour Raspberry Pi le plus simple reste l'image raspbian toute prête pour gladys :)
