### ISSUE TITLE
Upgrade to latest version of preact-cli + preact

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#982]
Right now we are using an old version of preact-cli, and this version has bugs. 

Let's upgrade to the latest version, with great care because it could break some things!

**Comment by VonOx** [comment]
From https://community.gladysassistant.com/t/fresh-development-installation/5785

**Comment by atrovato** [comment]
@Pierre-Gilles 
Isn't it already done?

**Comment by Pierre-Gilles** [comment]
Yes! Did it this summer 🔥
