### ISSUE TITLE
Erreur SQL getDeviceType

### ISSUE THREAD

**Issue by aschelch** [GladysAssistant/Gladys#99]
Bonjour, 

J'essaie de faire fonctionner ma prise Wemo. Mais quand j'essaie d'allumer/étendre ma prise, j'ai une erreur SQL.

```
Sending 500 ("Server Error") response: 
0|gladys   |  { [Error: ER_BAD_FIELD_ERROR: Unknown column 'dt.identifier' in 'field list']
0|gladys   |   cause: 
0|gladys   |    { [Error: ER_BAD_FIELD_ERROR: Unknown column 'dt.identifier' in 'field list']
0|gladys   |      code: 'ER_BAD_FIELD_ERROR',
0|gladys   |      errno: 1054,
0|gladys   |      sqlState: '42S22',
0|gladys   |      index: 0,
0|gladys   |      originalError: [Circular] },
0|gladys   |   isOperational: true,
0|gladys   |   code: 'ER_BAD_FIELD_ERROR',
0|gladys   |   errno: 1054,
0|gladys   |   sqlState: '42S22',
0|gladys   |   index: 0,
0|gladys   |   originalError: 
```

J'ai l'impression qu'il y a une erreur SQL sur la requête getDeviceType.
Je tente une petite correction et je fais une PR ;)

**Comment by aschelch** [comment]
PR lancé : https://github.com/GladysProject/Gladys/pull/100

**Comment by Pierre-Gilles** [comment]
Salut ! 

Alors non il ne s'agit pas d'une erreur, il y a bien un attribut identifier dans la table deviceType ( cf [la déclaration du model deviceType](https://github.com/GladysProject/Gladys/blob/master/api/models/DeviceType.js#L22) )

Si l'attribut n'existe pas dans ta table, il doit s'agir du fait que tu as dû mettre à jour Gladys manuellement sans relancer le script d'init ( `node init.js` à la racine de ton install Gladys ) qui s'occupe de créer/modifier les tables dans la DB. Tu peux le faire, tu verras l'attribut apparaitre :) 

**Petite remarque :** Dans Gladys, une très grande partie des fonctions sont couvertes par des tests unitaires ( Exemple du [dossier test du core](https://github.com/GladysProject/Gladys/tree/master/test/unit/api/core), et à chaque push sur n'importe quelle branche, ces tests sont lancés via notre service d'intégration continue Travis CI ! Une erreur aussi grosse dans le code du core aurait cassé le build, et ne serait sûrement pas passée en production ;) 

Du coup, pour les PR je fais comme tous les projets Open-Sources, une PR doit être entièrement couverte par des tests, pour assurer la stabilité de Gladys.

En tout cas merci d'avoir essayé de corriger (même si ce n'était pas un bug ici), c'est sympa de contribuer :)
