### ISSUE TITLE
Change watchtower configuration in next Raspbian build

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#991]
Docker started implementing rate-limit on image pull, and it affects Watchtower "attempt" to pull as well. ( https://github.com/containrrr/watchtower/issues/669 ) 

It means we need to change the frequency of the pull attempt on the Raspbian image.

I would suggest just changing the frequency to every 12 hours instead of every 5 minutes.

- It'll reduce the load on Gladys
- No need to try upgrading more than 2 times a day. 
- It'll spread the deploy of the new release on 12 hours, thus limiting spikes in errors in case we deploy a faulty upgrade. 
- At Gladys first boot, there is no risk the user experiences a downtime because watchtower upgrade his instance right now.

@VonOx FYI.

**Comment by cicoub13** [comment]
I can take this one (fix, docs and test) but I can't find the repo/code that builds the Raspbian image.

**Comment by Pierre-Gilles** [comment]
There is no repo, it's something completely manual! 

But given how critical it is, we are going to have a different approach. Right now, every service which tries to spin up a Docker container is broken because of the new rate limit....

As most people will never update their raspbian image (and it's normal, we don't want to promote this practice), we need to write a task in Gladys that will update the Watchtower configuration.

1. At Gladys boot, test if Gladys is using Docker
2. If yes, check if a watchtower container is runnning
3. If yes, check if the watchtower configuration needs to be updated
4. If yes, restart watchtower with the new configuration (stop old container, rm old container, start new container with new command line attributes)

@cicoub13 do you think you could help us in that? :)

**Comment by Pierre-Gilles** [comment]
Or maybe we don't need it, I just saw that on Watchtower GitHub repo (from yesterday): https://github.com/containrrr/watchtower/pull/674

As watchtower update itself, maybe it's already good :)

**Comment by Pierre-Gilles** [comment]
I still think that updating our watchtower configuration is good.

I'm thinking of updating the configuration to: 

```
docker run -d \
  --name watchtower \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  containrrr/watchtower:armhf-latest \
  --interval 86400 \
  --include-restarting \
  --cleanup
```

- Check only every 24 hours
- Include restarting container to avoid breaking all Gladys installation in case of faulty update

@VonOx what do you think?

**Comment by VonOx** [comment]
I prefer schedule ( cron argument) 

https://containrrr.dev/watchtower/arguments/#scheduling

With binding timezone

`-v /etc/timezone:/etc/timezone:ro`

I use this on my server with 10 running containers.

**Comment by cicoub13** [comment]
As I understand, the next release of WatchTower will include the change we want to do (default poll interval at 86400).
And WatchTower containers used in current Gladys installations will update itself.
So urgent issue will be solved as soon the release is done (+ waiting the 6 hours or rate limiting period).

If we still need a way to push new configuration, we can effectively study all options (in the forum ?)

⚠️  I don't see the `--include-restarting` in documentation

**Comment by VonOx** [comment]
Doc is not updated yet

**Comment by Pierre-Gilles** [comment]
>As I understand, the next release of WatchTower will include the change we want to do (default poll interval at 86400).

No, they will use a HEAD request instead of a GET request to avoid each "update request" to be counted in the rate-limit.

Right now, Watchtower is making a request every 5 minutes to check if there is an update available. Each request counts in Docker rate-limit for now, so in (100 * 5/number of containers) ( number of containers = 2 in Gladys raspbian image) = 250 minutes = 4h, the docker rate limit for the day is over.

> I prefer schedule ( cron argument)

I don't think a cron schedule is a good idea, because it means all instances will update at the same time (most users are in France right now so timezone doesn't change much) : 

1. It puts lots of stress on Docker infrastructure all at once. For now it's not a problem as we are not too many on the project + Docker infrastructure is solid, but if in the future we switch to a self-hosted Docker (Docker could close one day or become paid), we want that download happens smoothly during the day

2. If we push a faulty upgrade, if means we will know it only when all the instances upgrade, and it'll be "all or nothing". 

In distributed system like this, an interval is better because it means all instances will upgrade smoothly during the day (at mostly random) depending on when the instance was first started. If we discover in 1 hour that the upgrade is broken, we can rollback and have only 1/23 of the pool of instances broken. The longer the interval, the most progressive the interval is. 

It's a progressive rollout :)

**Comment by Pierre-Gilles** [comment]
Hello guys! I just built a new version of the Raspbian image, based on Gladys v4.0.4 + Watchtower latest version with the fixes + the --include-restarting flag.

If you could try it and tell me if everything seems good to you, it could be great! 

https://github.com/GladysAssistant/Gladys/releases/download/v4.0.4/gladys-4.0.4-rev4.img.zip

**Comment by cicoub13** [comment]
Tested on RPI 3A+
Everything is 👍 

Log from watchtower is OK (next poll in 24h)
`time="2021-01-14T14:58:56Z" level=info msg="Starting Watchtower and scheduling first run: 2021-01-15 14:58:56 +0000 UTC m=+86401.449579114"`

Just one thing, you didn't clear the bash history (so we see all commands done to prepare the image) ⚠️

**Comment by Pierre-Gilles** [comment]
> Just one thing, you didn't clear the bash history (so we see all commands done to prepare the image) ⚠️

Ah! Nothing critical in the command?

**Comment by cicoub13** [comment]
> Ah! Nothing critical in the command?

No password or private info 😉

**Comment by cicoub13** [comment]
Can we close this one ?

**Comment by Pierre-Gilles** [comment]
Yes !
