### ISSUE TITLE
MQTT: If the user started a MQTT container automatically with Gladys, be able to create a MQTT user from Gladys

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#992]
I cannot use the user given by gladys as credentials for another MQTT client (because 1 MQTT credentials = 1 client), so I need to create another Mosquitto user. 

https://community.gladysassistant.com/t/premiere-installation/5791/15

**Comment by R6n0** [comment]
The user given by gladys as credentials could be used for another MQTT client if the Gladys MQTT client ID was different than user name for connexion ('gladys').
As you said in your link, the solution could be to define a unique client ID for gladys instance ('gladys-assistant-main-instance').

Line 34
https://github.com/GladysAssistant/Gladys/blob/master/server/services/mqtt/lib/connect.js

**Comment by Pierre-Gilles** [comment]
Ok I'm closing this issue in favor of: 

https://github.com/GladysAssistant/Gladys/issues/997
